rundeck/rundeck

packaging/root/etc/rc.d/init.d/rundeckd
Made changes to display rundeckd when checking status of rundeckd daemon. Please, review.
```shell
java (pid  24682) is running...
```
__Fix:__
```shell
rundeckd (pid  24682) is running...
```
=> Fix rundeckd init script

RELEASE.md, docs/en/history/version-2.4.0.md, docs/en/plugins-user-guide/ssh-plugins.md
Hi,
The documentation and the release notes for Rundeck 2.4.0 use a wrong name for the two new ssh-agent variables. I noticed that ssh-agent forwarding did not work after upgrading to 2.4.0 and realized that the documentation was wrong.
=> Fix ssh-agent variable names in documentation

rundeck-launcher/rundeck-jetty-server/src/main/java/org/rundeck/jaas/pam/AbstractPamLoginModule.java
" +" matches "one or more whitespace".
Correctly it should be " *" which matches "zero or more whitespace"
=> JettyPamLoginModule: supplementalRoles split regex requires whitespace

rundeck-launcher/launcher/src/main/resources/templates/sbin/rundeckd.template
Made changes to redirect nohup output to server.log when starting/restarting rundeckd daemon using launcher startup script (also includes some variable cleanup)
```
[root@puru ~]# $RDECK_BASE/server/sbin/rundeckd start
Starting rundeckd: nohup: redirecting stderr to stdout
[OK]
```
__Fix:__
```
[root@puru ~]# $RDECK_BASE/server/sbin/rundeckd start
Starting rundeckd: [OK]
```
=> Launcher: fix "nohup: redirecting stderr to stdout" warning

core/src/main/java/com/dtolabs/rundeck/core/resources/format/ResourceYamlFormatParser.java
The currently specified MIME types "*/yaml", "*/x-yaml" are not generally found on any popular web server. See http://www.iana.org/assignments/media-types/media-types.xhtml . Consequentially, the MIME type returned for a YAML file hosted via a common web server is text/plain . This change shouldn't affect XML files served since they do have a globally accepted MIME type and will be served with that in the header.
Facing issues with being able to serve such a file off a shared service. Seeing...
```
ERROR ExceptionCatchingResourceModelSource: [ResourceModelSource: 1.url (URL Source), project: XYZ] 
com.dtolabs.rundeck.core.resources.ResourceModelSourceException: Error requesting URL Resource Model Source: http://f.q.d.n/xyz.yaml: Response content type is not supported: text/plain
Caused …
```
=> Add text/plain MIME type for YAML files

rundeck-launcher/rundeck-jetty-server/src/main/java/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java, rundeck-launcher/rundeck-jetty-server/src/test/java/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModuleTest.java
fixes #748 
caused by case-sensitivity bug in regexp pattern that failed for
ActiveDirectory but worked for openldap
=>  Fix LDAP nested groups for Active Directory

docs/en/administration/09-authentication.md, docs/en/administration/10-authorization.md, rundeckapp/grails-app/conf/Config.groovy, rundeckapp/grails-app/conf/rundeck/filters/AuthorizationFilters.groovy, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/src/groovy/org/rundeck/web/infosec/AuthorizationRoleSource.groovy, rundeckapp/src/groovy/org/rundeck/web/infosec/ContainerPrincipalRoleSource.groovy, rundeckapp/src/groovy/org/rundeck/web/infosec/ContainerRoleSource.groovy, rundeckapp/src/groovy/org/rundeck/web/infosec/PreauthenticatedAttributeRoleSource.groovy
Add ability to use pre-authenticated and authorized proxied requests, e.g. from Apache httpd.
* Requires disabling the container authentication mechanism (remove the `<auth-constraint>` from web.xml)
* Accepts the remote_user as username, and a list of roles defined in a request attribute, the name and delimiter can be configured.
=> Refactor authorization into components, add preauth attribute role

rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
Support for project-specific email template overrides.  For example, given a project, "TestProject" and a job "TestJob" a line in rundeck-config.properties of the form:
rundeck.mail.TestProject.TestJob.template.file
Will override the template for TestProject TestJob.  
Ideally, eventually this will make its way into the job definition.
=> Support project-specific email template overrides

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/views/execution/_execDetails.gsp, rundeckapp/grails-app/views/scheduledExecution/_edit.gsp, rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp, rundeckapp/test/unit/rundeck/controllers/ScheduledExecutionControllerTests.groovy
Nowadays when a user wants to run a predefined job all nodes are automatically selected. Thus the user only need to click on "Run Job Now" to run the job on all those nodes.
In our case we are running jobs on business critical machines and we want to force the user to explicitly select nodes before running the job.
This commit add an option in the job definition to disable this automatic selection of nodes:
This feature is also visible in the "Definition" tab:
When this feature is enable for a job, the user has to select node explicitly:
=> add a job option to disable the automatic selection of all nodes

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
In a clustered rundeck installation, the cluster member that isn't the assigned node for a job will display "never" for the next scheduled execution time.
This turns out to be because `trigger.getNextFireTime()` returns `null` if the trigger hasn't been added to a schedule (or more precisely, if the start time hasn't been set yet). Using `trigger.getFireTimeAfter(new Date())` will properly calculate the next execution.
=> Fix next execution time on non-scheduled cluster member

rundeckapp/grails-app/views/layouts/base.gsp
Rundeck does not work well with Compatibility Mode in Internet Explorer.
This tag is to force disable of Compatiblity Mode
=> Disable Compatiblity Mode in Internet Explorer: Set X-UA-Compatible

docs/en/api/rundeck-api.md, rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy, rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy, rundeckapp/test/unit/rundeck/controllers/ProjectControllerSpec.groovy, rundeckapp/test/unit/rundeck/controllers/ProjectControllerTest.groovy, rundeckapp/test/unit/rundeck/services/ArchiveOptionsSpec.groovy, test/api/include.sh, test/api/test-project-export-executions.sh
add `executionIds` parameter to the /project/export API:
* a list of execution IDs to include in the archive
If `executionIds` is specified, the archive only contains the execution definitions specified, an other archive contents, such as Jobs, ACLs, configuration, etc.
Future enhancement: more extensive selection of archive contents.
=> Enhance project archive API: select only a set of executions for output

core/src/main/java/com/dtolabs/rundeck/core/utils/ThreadBoundOutputStream.java, rundeckapp/grails-app/conf/BootStrap.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy, rundeckapp/grails-app/services/rundeck/services/LoggingService.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/app/internal/logging/LogEventBuffer.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/app/internal/logging/LogEventBufferManager.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/app/internal/logging/LogFlusher.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/app/internal/logging/ThreadBoundLogOutputStream.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/app/internal/workflow/BaseWorkflowExecutionListener.groovy, rundeckapp/test/unit/com/dtolabs/rundeck/app/internal/logging/LogEventBufferManagerSpec.groovy, rundeckapp/test/unit/com/dtolabs/rundeck/app/internal/logging/LogEventBufferSpec.groovy, rundeckapp/test/unit/com/dtolabs/rundeck/app/internal/logging/ThreadBoundLogOutputStreamSpec.groovy, rundeckapp/test/unit/rundeck/services/ExecutionUtilServiceTests.groovy
* does not flush all output when a flush() is sent
* flushes remaining output when child threads complete
=> fix issue 1368: log output newlines

rundeckapp/grails-app/conf/BuildConfig.groovy
Version 3.2.1 has a CVSS 10.0 vulnerability. That's the worst kind of
vulnerability that exists. By merely existing on the classpath, this
library causes the Java serialization parser for the entire JVM process
to go from being a state machine to a turing machine. A turing machine
with an exec() function!
https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2015-8103
https://commons.apache.org/proper/commons-collections/security-reports.html
http://foxglovesecurity.com/2015/11/06/what-do-weblogic-websphere-jboss-jenkins-opennms-and-your-application-have-in-common-this-vulnerability/
=> Upgrade Apache Commons Collections to v3.2.2

core/src/main/java/com/dtolabs/rundeck/core/common/IProjectNodes.java, core/src/main/java/com/dtolabs/rundeck/core/common/ProjectNodeSupport.java, core/src/main/java/com/dtolabs/rundeck/core/resources/CachingResourceModelSource.java, core/src/main/java/com/dtolabs/rundeck/core/resources/ExceptionCatchingResourceModelSource.java, core/src/main/java/com/dtolabs/rundeck/core/resources/SourceFactory.java, core/src/main/java/com/dtolabs/shared/resources/ResourceXMLGenerator.java, core/src/test/java/com/dtolabs/shared/resources/TestResourceXMLGenerator.java, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy, rundeckapp/grails-app/services/rundeck/services/NodeService.groovy, rundeckapp/grails-app/services/rundeck/services/nodes/CachedProjectNodes.groovy, rundeckapp/grails-app/views/menu/admin.gsp, rundeckapp/test/unit/rundeck/services/NodeServiceSpec.groovy
Asynch nodes cache new behavior:
* If a project nodes cache file exists, initial load of project nodes will preload using this file
* Otherwise initial load of project nodes is *asynchronous*, meaning you may see 0 nodes until they are loaded
* this makes UI responsive after creating/saving project, and at startup
* can force this to be synchronous using rundeck-config value: `rundeck.nodeService.nodeCache.firstLoadAsynch=false`
* "Why would I want to force it to be synchronous?" If you deploy Rundeck with predefined jobs (e.g. new cluster node pointing at existing DB), this will force Rundeck to load all nodes prior to any jobs being executed, and may prevent spuriously failing jobs due to "no matched nodes" 
* Anytime the asynch cache successfully loads project nodes, it will write …
=> fix #1744 first node load is synchronous

rundeck-launcher/rundeck-jetty-server/src/main/java/com/dtolabs/rundeck/RunServer.java
Added a new system property "rundeck.server.workDir" to specify a temporary directory for the Jetty web app context which can be configured to be outside of the installation tree.
When unset, a new directory "work" is created under the "rundeck.server.serverDir" directory.
When set, the embedded Jetty uses or creates the directory identified by the "rundeck.server.workDir" directory.
=> Place Jetty work directory outside of the installation tree

core/src/main/java/com/dtolabs/launcher/Setup.java, core/src/main/java/com/dtolabs/rundeck/core/common/UpdateUtils.java, core/src/main/java/com/dtolabs/rundeck/core/utils/FileUtils.java, core/src/test/java/com/dtolabs/rundeck/core/cli/jobs/TestJobsTool.java, core/src/test/java/com/dtolabs/rundeck/core/common/TestFrameworkProject.java, core/src/test/java/com/dtolabs/rundeck/core/execution/impl/local/LocalFileCopierTest.java, core/src/test/java/com/dtolabs/rundeck/core/execution/service/TestScriptPluginFileCopier.java, core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/TestScriptFileNodeStepExecutor.java, core/src/test/java/com/dtolabs/rundeck/core/plugins/BaseScriptPluginTest.java, core/src/test/java/com/dtolabs/rundeck/core/resources/TestDirectoryResourceModelSource.java, core/src/test/java/com/dtolabs/rundeck/core/resources/TestFileResourceModelSource.java, core/src/test/java/com/dtolabs/rundeck/core/tools/AbstractBaseTest.java, core/src/test/java/com/dtolabs/rundeck/core/utils/TestFileUtils.java, core/src/test/java/com/dtolabs/rundeck/core/utils/TestPropertyLookup.java, core/src/test/java/com/dtolabs/rundeck/core/utils/TestPropertyUtil.java, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/BaseGitPluginSpec.groovy, rundeckapp/test/unit/ProjectServiceTests.groovy, rundeckapp/test/unit/com/dtolabs/rundeck/app/internal/logging/RundeckLogFormatTest.groovy
- Fix #1702 by replacing `File.renameTo` with `Files.move`, which handles moving between different filesystems; use the JDK 7 `Files.copy` for copy operations.
- When creating temporary files, check the parent directory structure exists and create it if needed.
- Tidy up temporary files on exit to reduce clutter in `/tmp` after running tests.
=> Make moving/renaming of files more robust

rundeckapp/grails-app/assets/javascripts/application.js, rundeckapp/grails-app/assets/javascripts/util/markdeep.js, rundeckapp/grails-app/assets/stylesheets/markdeep.less, rundeckapp/grails-app/assets/stylesheets/rundeck.less, rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy, rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy, rundeckapp/grails-app/views/menu/_jobslist.gsp, rundeckapp/grails-app/views/menu/licenses.gsp, rundeckapp/grails-app/views/scheduledExecution/_description.gsp, rundeckapp/grails-app/views/scheduledExecution/_show.gsp, rundeckapp/grails-app/views/scheduledExecution/_showHead.gsp, rundeckapp/grails-app/views/scheduledExecution/show.gsp, rundeckapp/test/unit/rundeck/UtilityTagLibSpec.groovy
Feature: Allow additional markdown text in a Job's extended description, which will be rendered as a separate "Runbook" tab in the Job view page.
* Markdown after a `---` (hr) separator in the extended description is treated as the Runbook
* Any Runbook markdown text is rendered into a separate tab in the Job page, using [Markdeep](https://casual-effects.com/markdeep) which supports tables, ascii diagrams, and other advanced features.
Example job description text:
~~~ {.markdown}
The basic description
This is the extended description, rendered under a "More" link in the Job page.
---
This content is rendered in the "Runbook" tab in the Job page.
~~~
=> Extended job description rendered as a Runbook

core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionContext.java, core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionContextImpl.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/local/LocalNodeExecutor.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/impl/local/LocalNodeExecutorSpec.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/grails-app/services/rundeck/services/LoggingService.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/app/internal/logging/LogEventBuffer.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/app/internal/logging/LogEventBufferManager.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/app/internal/logging/ThreadBoundLogOutputStream.groovy, rundeckapp/test/unit/ExecutionServiceSpec.groovy, rundeckapp/test/unit/com/dtolabs/rundeck/app/internal/logging/LogEventBufferSpec.groovy, rundeckapp/test/unit/rundeck/services/FrameworkServiceSpec.groovy
project.remote.charset.default
framework.remote.charset.default
=> fix #1938 allow default encoding of command output to be specified

core/src/main/java/com/dtolabs/rundeck/core/plugins/JarPluginProviderLoader.java, core/src/test/java/com/dtolabs/rundeck/core/plugins/TestJarPluginProviderLoader.java
fix jar plugin loader to avoid contention
with overwriting the same file if multiple threads
attempt to load classes from the same jar:
* use unique string in cached file name
* only use one cached file/libset per loader
* clean up all cached files
=> fix #1898  avoid file writing contention

rundeckapp/grails-app/i18n/messages.properties
The current URL is 404. Here is the current page for building Quartz cron expressions.
=> Update Quartz scheduler reference page

rundeck-launcher/launcher/src/main/resources/templates/config/rundeck-config.properties.template, rundeckapp/authfilter/AuthFilterGrailsPlugin.groovy, rundeckapp/authfilter/application.properties, rundeckapp/authfilter/scripts/_Install.groovy, rundeckapp/authfilter/scripts/_Uninstall.groovy, rundeckapp/authfilter/scripts/_Upgrade.groovy, rundeckapp/grails-app/conf/BootStrap.groovy, rundeckapp/grails-app/conf/BuildConfig.groovy, rundeckapp/grails-app/conf/rundeck/filters/AuthorizationFilters.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy, rundeckapp/src/java/com/dtolabs/rundeck/server/filters/AuthFilter.java
Hi,
Thanks to the team for all of the work you’ve put into this project. 
Here is a contribution towards preauthenticating with a reverse proxy, works towards resolving #1229 - Feedback is appreciated.
We are currently using https://github.com/bitly/oauth2_proxy to auth with Github and send a remote user and roles (as defined by teams) along to Rundeck. I’ve written a Spring filter that intercepts the request object at the beginning of the filter chain and modifies it to be sent along. 
There are a number of manual configuration changes. Here are the steps we take for `rundeck-launcher`
* Set `rundeck.security.authorization.preauthenticated.enabled=true`
* Build the project
`$ ./gradlew clean build` 
* Run jar with install option on (default)
`$ java -jar …
=> Preauthentication filter

packaging/root/etc/rc.d/init.d/rundeckd, packaging/root/etc/rundeck/profile
Default init script for redhat can be improved:
It looks for configuration in /etc/rundeck/profile. But service configurations should be in /etc/sysconfig/$service instead in redhat.
The profile script was not optimum. It needed a lot of editing. Many useless export where used. This new one add a lot of variable that can be used in a sysconfig configuration. It also remove the system property rdeck.base because it's overridden in com.dtolabs.rundeck.RunServer:
if (null != basedir) {
System.setProperty("rdeck.base", basedir.getAbsolutePath());
}
and
if (args.length > 0) {
basedir = new File(args[0]);
} else {
throw new RuntimeException("Basedir argument required");
}
So the `-Drdeck.base=/var/lib/rundeck` as no effect.
=> More redhatcompliance init file, more easier to use profile file

rundeckapp/grails-app/assets/javascripts/menu/job-remote-options.js, rundeckapp/grails-app/assets/javascripts/menu/job-remote-optionsTest.js, rundeckapp/grails-app/assets/javascripts/menu/joboptions.js, rundeckapp/grails-app/views/framework/_jobOptionsKO.gsp, rundeckapp/grails-app/views/framework/_optionValuesSelectKO.gsp, rundeckapp/grails-app/views/scheduledExecution/_editOptions.gsp
fix two issues: 
1. If a job option has a URL, but no dependencies on other options, it won't reload correctly when the reload button is clicked
2. if a job option has a `.` in the name, remote url loading error messages won't be shown correctly
=> Fix #2024 can't reload remote job option value

.github/ISSUE_TEMPLATE.md, .gitignore, rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/utils/rundeck/codecs/AnsiColorCodec.groovy, rundeckapp/test/unit/rundeck/controllers/ExecutionControllerSpec.groovy
renderOutput was not sanitizing task logs correctly for an HTML view. If
an attacker controlled a node, they could send Javascript code in the
response, which would be executed in the user's browser upon viewing the
page.
=> Escape HTML characters in ExecutionController.renderOutput

rundeckapp/grails-app/services/rundeck/services/ReportService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/views/framework/_nodeFilterInputGroup.gsp, rundeckapp/grails-app/views/reports/_baseReport.gsp, rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp, rundeckapp/src/groovy/com/dtolabs/rundeck/app/support/ExecutionContext.groovy, rundeckapp/test/integration/ReportServiceTests.groovy
If you enter a default node filter you can set the "Editable filter" to false so no one can edit it on the run. I you leave the node filter field empty, any user can edit it on the run job screen regardless of the "Editable Filter" value. 
The new execution screen looks like this:
On the Activity screen, if you search by filter, you can use the name of the searched node, and it will assume "name: "
=> Feature - override node filter (GUI enhancement)

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/test/unit/ExecutionServiceSpec.groovy
=> fix: runAtTime does not support "Z" timezone indicator in iso8601 format

docs/en/administration/07-relational-database.md
Postgres support for Rundeck is currently undocumented.
This PR includes these steps to set up Rundeck with a Postgres DB:
* Creating Postgres database for Rundeck
* Creating Postgres user, granting privileges
* Configuring Rundeck to connect to this database
This resolves #1405.
=> Add documentation to configure Rundeck with PostgreSQL DB

docs/en/administration/12-gui-customization.md
After this commit (https://github.com/rundeck/rundeck/commit/0c8c89378eea3ce6cca5d90b3f89605546e4b094) docs do not reflect the default value.
I also updated the list of values with the valid ones found here: https://github.com/rundeck/rundeck/blob/0c8c89378eea3ce6cca5d90b3f89605546e4b094/rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy#L225
Thanks!!!
=> Update rundeck.gui.startpage description

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/test/unit/ExecutionServiceTests.groovy
=> Add executionType

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/test/unit/ExecutionServiceTests.groovy
Currently there's no way to differentiate whether a job was ran by a user
and a job ran by the scheduler by looking at the job context variables.
With this change, we'll have a job.executionType context variable that will
indicate what invoked the job.
Possible values of job.executionType:
adhoc = adhoc command
user = job initiated by a user
scheduled = job triggered by the scheduler
This is a first stab at this problem to get the ball rolling.
Please review for correctness and let me know if anything
else is needed.
Addresses issue https://github.com/rundeck/rundeck/issues/1811
Signed-off-by: Rene Fragoso ctrlrsf@gmail.com
=> Add job.executionType context variable

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Added two method, one overload listworkflows with a generic Hashmap  to populate the ScheduledExecutionQuery, the other helps find a ScheduledExecution with the uuid and the project without using the domain
=> ScheduledExecutionService generic methods to use on plugin

packaging/debroot/etc/init.d/rundeckd, packaging/debroot/etc/init/rundeckd.conf
For debian, the equivalent of /etc/sysconfig is /etc/default - see
https://www.debian.org/doc/manuals/debian-reference/ch03.en.html#_the_default_parameter_for_each_init_script
=> Fix default parameter location for debian packaging

docs/en/history/changelog.md
There was a typo in the docs, it was cleaned up in most places in #1093 but `changelog.md` was missed.
=> docs: fix ssh-agent settings typo in changelog

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Some messages would appear similar to:
>    Option [endDate, 2016-01-01 00:00:001, ^[0-9]{4}-[0-1][0-9]-[0-3][0-9] [0-2][0-9]:[0-5][0-9]:[0-5][0-9]$] value: {1} doesnt match regular expression: {2}
Instead of the expected:
>    Option endDate value: 2016-01-01 00:00:001 doesnt match regular expression: ^[0-9]{4}-[0-1][0-9]-[0-3][0-9] [0-2][0-9]:[0-5][0-9]:[0-5][0-9]$
Also, improve lookupMessage's usability.
=> Fix some i18n error messages

rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, test/api/test-execution-state.sh
Attempt to fix #2268 
@gschueler I wasn't sure if `parameterStates` was intended to be returned by this API call, the documentation at: http://rundeck.org/docs/api/index.html#execution-state doesn't reference it. If you think it should be returned, then I can rework this.
=> Remove parameter states from execution state API

packaging/debroot/DEBIAN/conffiles
Right now, everytime Rundeck is updated we lose all the changes made to the `apitoken.aclpolicy` file, which is a bit annoying.
=> Add apitoken.aclpolicy to Debian conffile

packaging/debroot/etc/rundeck/profile, packaging/root/etc/rundeck/profile
This allows the ability to avoid modifying `/etc/rundeck/profile` and put the override in the OS-specific location:
- Debian:  `/etc/default/rundeckd`
- RedHat:  `/etc/sysconfig/rundeckd`
=> Add RDECK_CONFIG_FILE environment variable

rundeckapp/grails-app/conf/RefererFilters.groovy
By default, preserve the actual state without CSRF filter, to activate the administrator need to add a property on _rundeck-config.properties_:
"rundeck.security.csrf"
It accepts the values: 
**_POST_**: recommended, only filter the POST methods, verifies Refer and url.
**_*_**: applies the filter to any type of request, including POST and GET, except the login screen wich need to be accesible without refer or with a redirect from another url (case of localhost resolved to hostname)
_**NONE**_: don't applies any filter.
Any other string or the absence of the property, resolves as NONE.
i.e.:
rundeck.security.csrf=POST
=> Prevent csrf attacks

rundeck-storage/rundeck-storage-filesys/src/main/java/org/rundeck/storage/data/file/DirectFilepathMapper.java
Let mkdirs() create directories only if they don't exist
(instead of testing first) to avoid any race condition.
fixes #2400
=> [fix] IllegalArgumentException at job start on storage dirs creation

core/src/main/java/com/dtolabs/rundeck/core/execution/ServiceThreadBase.java, core/src/main/java/com/dtolabs/rundeck/core/execution/WorkflowExecutionServiceThread.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/EngineWorkflowExecutor.java, plugins/job-state-plugin/build.gradle, plugins/job-state-plugin/src/main/java/org/rundeck/plugin/jobstate/JobStateWorkflowStep.java, plugins/job-state-plugin/src/test/groovy/org/rundeck/plugin/jobstate/JobStateWorkflowStepSpec.groovy, rundeckapp/grails-app/assets/stylesheets/rundeck.less, rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy, rundeckapp/test/unit/rundeck/services/ExecutionUtilServiceTests.groovy
* If Job State Conditional  causes Halt without a failure: log a warning level instead of error
* Log execution result status not as "failed" if flow control caused a halt that was not a failure
* Log execution result status as succeeded if flow control caused a halt that was a success
* fix #2116
=> Job State Conditional check logs warning if not a failure

core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschNodeExecutor.java
When trying to "Kill Job" remote commands via Jsch Node executor, the task aren't killed on the node because a openssh known [bug](https://bugzilla.mindrot.org/show_bug.cgi?id=1424).
Setting Allocate Pty `true` on jsch fixes this, killing the remote pty, and the process with it.
Remote commands get the SIG 0 but are terminated prematurely.
=> Kill remote ssh command tasks

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/test/unit/ExecutionServiceSpec.groovy
Adds the possibility to relate and option value with a key storage path for secure option, in order to select the key storage path depending on the option value selected, for example:
`keys/${option.enviroment}/password`
It only replaces option values, and in case the option doesn't exist or doesn't match a valid keystorage path, it just use a default empty value.
Fixes  #1822
Example of job using this feature:
```
- description: 'test for issue 1822 '
executionEnabled: true
group: issue
id: d32cb0d7-2c41-4456-8a7a-ca2ac7dcdbb2
loglevel: INFO
name: '1822'
nodeFilterEditable: false
options:
- description: develop,production,qa
enforced: true
name: environment
required: true
value: develop
values:
- develop
- production
- qa
- name: dbpassenv
secure: true
storagePath: …
```
=> Using option value in key storage path

docs/en/administration/03-configuration.md
On reading this page as part of making this change, I see that it links
to the project config docs where project.globals are mentioned and that
links to further documentation on project globals that fully explains
it.  But I looked at this top level a couple times and missed this
wording and the link.  I'm thinking this wording might have helped,
but perhaps this is more my problem than a docs problem.  :-)
=> Changing wording of project global variable override.

rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
Fix problem with S3 plugin, produced when the /tmp folder is located on a different file system.
https://github.com/rundeck-plugins/rundeck-s3-log-plugin/issues/6
=> Fix problem with S3 plugin

rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy, rundeckapp/grails-app/views/user/_user.gsp
Small fix for #2525
In the actual behavior if the user don't have tokens the template with the token list isn't rendered  causing a javascript error creating the first one. 
Removing the validation for tokens on start the headers appears with a empty list to be filled.
=> Adding the first api token

rundeckapp/grails-app/assets/javascripts/jobedit.js, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowController.groovy, rundeckapp/grails-app/domain/rundeck/JobExec.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/WorkflowService.groovy, rundeckapp/grails-app/views/execution/_wfItemView.gsp, rundeckapp/grails-app/views/execution/_wfitemEdit.gsp, rundeckapp/grails-app/views/scheduledExecution/create.gsp, rundeckapp/grails-app/views/scheduledExecution/edit.gsp, rundeckapp/src/java/com/dtolabs/rundeck/execution/ExecutionItemFactory.java, rundeckapp/src/java/com/dtolabs/rundeck/execution/JobRefCommand.java, rundeckapp/test/unit/com/dtolabs/rundeck/execution/ExecutionItemFactoryTest.groovy, rundeckapp/test/unit/rundeck/controllers/ScheduledExecutionControllerTests.groovy, rundeckapp/test/unit/rundeck/controllers/WorkflowControllerSpec.groovy, rundeckapp/test/unit/rundeck/controllers/WorkflowControllerTests.groovy, rundeckapp/test/unit/rundeck/services/ExecutionUtilServiceTests.groovy, rundeckapp/test/unit/rundeck/services/ScheduledExServiceTests.groovy, rundeckapp/test/unit/rundeck/services/ScheduledExecutionServiceSpec.groovy
Added capability to use Job Reference step referencing another project.
The current behavior is maintained leaving the field empty ensuring backward compatibility.
New create/edit GUI:
Autocomplete of allowed projects:
If the user has no permission to see another project will not be displayed on autocomplete.
Choose A Job... button will show the entered project jobs if the field is completed. On empty field, continue to show current project jobs.
If the project field is filled with an unauthorized project or a non existent one this error will be displayed:
New text string representation on screen of Job reference from another project:
See #561
=> Job Reference on another Project

rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowController.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/views/execution/_wfitemEdit.gsp, rundeckapp/grails-app/views/scheduledExecution/create.gsp, rundeckapp/grails-app/views/scheduledExecution/edit.gsp
UI fixes for #2519 
- The project selector now is a select instead of autocomplete. (User now can't select a bad project name)
- Corrected job show/execution page in the UI steps section.
=> Job Reference on another Project (Fixes)

plugins/job-state-plugin/src/main/java/org/rundeck/plugin/jobstate/JobStateWorkflowStep.java, plugins/job-state-plugin/src/test/groovy/org/rundeck/plugin/jobstate/JobStateWorkflowStepSpec.groovy
Add *Job Project* property to the  Job State Plugin to search projects outside the actual project.
Actual jobs maintains his functionality and any job created with project empty use the actual project as usual.
Works with UUID and job name.
Similar to #2519 enhancement.
=> External Job State Conditional plugin.

rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/taglib/rundeck/AuthTagLib.groovy, rundeckapp/grails-app/views/execution/show.gsp, rundeckapp/grails-app/views/menu/_copyModal.gsp, rundeckapp/grails-app/views/menu/jobs.gsp, rundeckapp/grails-app/views/scheduledExecution/_jobActionButtonMenuContent.gsp, rundeckapp/grails-app/views/scheduledExecution/show.gsp, rundeckapp/test/unit/rundeck/controllers/ScheduledExecutionControllerTests.groovy
GUI enhancement to allow copy a job to another project, only if the user is authorized to create in the other project, uses the same copy method only overwriting the project for the selected one
**New item in dropdown menu "Duplicate this job to other Project":**
**Popup asking to choose the project in the autocomplete list:**
**If the user can't create in any other project, the user don't get the option on the menu:** 
**This is how it looks if the user can create in other project but only can read on the actual:**
**If the user tries to duplicate to a project he can't see:**
**If the user tries to duplicate to a project he can see but cant create:**
=> Copy job to another project

core/src/main/java/com/dtolabs/rundeck/core/Constants.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschNodeExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschScpFileCopier.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/NodeSSHConnectionInfo.java, core/src/main/java/com/dtolabs/rundeck/core/tasks/net/ExtSSHExec.java, core/src/main/java/com/dtolabs/rundeck/core/tasks/net/ExtScp.java, core/src/main/java/com/dtolabs/rundeck/core/tasks/net/SSHTaskBuilder.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/impl/jsch/NodeSSHConnectionInfoSpec.groovy, core/src/test/java/com/dtolabs/rundeck/core/tasks/net/TestSSHTaskBuilder.java, docs/en/administration/03-configuration.md, docs/en/plugins-user-guide/ssh-plugins.md
define separate connection and command timeout configs for SSH plugins
=> Fix #2547 deprecate framework.ssh.timeout

rundeckapp/grails-app/conf/BuildConfig.groovy
postgresql is very very very old (PostgreSQL 9.1). It's not compatible with postgresql 9.6, update to a postgresql 9.6 version with JDK 8 support.
See https://jdbc.postgresql.org/download.html
=> Update postgresql connector to 42.0.0

rundeckapp/build.gradle, testbuild.groovy
Included dependency for [rundeck-ansible-plugin](https://github.com/Batix/rundeck-ansible-plugin/releases/tag/2.0.2)
=> Include Batix/rundeck-ansible-plugin

rundeckapp/grails-app/domain/rundeck/Execution.groovy
Remove Join from  Execution table with LogFileStorageRequest to increase query  performances
=> Remove Join from  Execution table with LogFileStorageRequest

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/test/unit/rundeck/services/ScheduledExecutionServiceSpec.groovy
Fix #2677 
Add validation for `scheduleEnabled` and `executionEnabled` on a job when a scheduledExecution is scheduled on a different serverNode.
And a unit test to check the right behavior.
=> Next scheduled execution for cluster

core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionReference.java, core/src/main/java/com/dtolabs/rundeck/core/jobs/JobService.java, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/grails-app/services/rundeck/services/JobStateService.groovy, rundeckapp/grails-app/services/rundeck/services/execution/ExecutionReferenceImpl.groovy, rundeckapp/grails-app/services/rundeck/services/jobs/AuthorizingJobService.groovy, rundeckapp/grails-app/services/rundeck/services/jobs/ResolvedAuthJobService.groovy, rundeckapp/test/unit/rundeck/services/JobStateServiceSpec.groovy
Expose in the JobService methods for bulk delete executions and query to retrieve executions using same parameters as `rd executions bulkdelete`
`deleteBulkExecutionIds` accepts a list of ids and return a map with the result.
`queryExecutions` accepts a map with the search parameters and return a map with the executions as ExecutionReference.
=> Expose delete executions for plugins

docs/en/administration/12-gui-customization.md, rundeckapp/grails-app/views/user/login.gsp
Add a "footer" message below the login form.
It will be controlled by the attribute `rundeck.gui.login.footerMessageHtml` on rundeck.config.properties
=> Add "footer" message on login page.

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy, rundeckapp/test/unit/rundeck/services/ExecutionUtilServiceTests.groovy
Fix #2718 
When the jobRef item has null project, the parent project is used instead.
Test case:
ProjectA - job1  -> *runs command*
ProjectA - job2 -> *ref job1*
ProjectB - job3 -> *ref ProjectA/job2*
=> Fix nested Job Reference

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/test/unit/ExecutionServiceSpec.groovy
When user has a local timezone set to IST (+05:30) job is scheduled at wrong time. This is because ISO 8601 date format was not specified with long timezone format. Browsers (Chrome, Firefox and Safari) are sending runAtTime parameter with long TZ format:
```
------WebKitFormBoundaryxAWvOTSB4R0rNhMN
Content-Disposition: form-data; name="runAtTime"
2017-08-30T20:47:00+05:30
```
Fixed also test case 'should scheduleAdHocJob with alternative ISO 8601 date' where assertion was always true. 
Additional observation: when building and testing - local timezone should be set to GMT.
=> Improve ISO 8601 date handling with timezone when scheduling ad-hoc job

docs/en/developer/05-notification-plugins.md, docs/en/manpages/man5/job-v20.md, docs/en/manpages/man5/job-yaml-v12.md, docs/en/plugins-user-guide/configuring.md, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/views/scheduledExecution/_editNotificationsForm.gsp, rundeckapp/test/integration/rundeck/quartzjobs/ExecutionJobTest.groovy, rundeckapp/test/unit/ExecutionServiceTests.groovy, rundeckapp/test/unit/rundeck/services/ScheduledExecutionServiceSpec.groovy
Add a new trigger for job's notifications `onavgduration`.
When an execution takes more time that his *Average Duration* this notification is triggered, as long as got at least 1 execution to take the average duration and his *Average Duration* is greater than 0.
Any Notification plugin can be used in this new trigger
Here is a minimal example of groovy notification plugin included on the documentation:
**MinimalNotificationPlugin.groovy**:
~~~~~ {.java}
import com.dtolabs.rundeck.plugins.notification.NotificationPlugin;
rundeckPlugin(NotificationPlugin){
onstart { 
println("job start: data ${execution}")
true
}
onfailure {
println("failure: data ${execution}")
true
}
onsuccess {
println("success: data ${execution}")
true
}
onavgduration{
println("exceeded average duration: data …
=> Job Notification for jobs exceeding average duration

rundeckapp/src/groovy/com/dtolabs/rundeck/server/plugins/logging/SimpleDataFilterPlugin.groovy, rundeckapp/test/unit/com/dtolabs/rundeck/server/plugins/logging/SimpleDataFilterPluginSpec.groovy
Update to `Key Value Data` plugin to support a named pattern int he case the regex only had one group to capture.
=> Named pattern log filter

build.gradle, rundeckapp/build.gradle
I'm sure I'm doing this horribly wrong in gradle as I'm a total n00b.
Right now I can't build rundeck in windows without something like this patch.
Generally speaking I can't run unit-tests at all (they fail miserably).
But this way, I can at least run:
```
gradlew.bat build -x test
```
And get something done...
=> Allow building (without tests for now) in Windows

docs/en/manual/04-jobs.md, rundeckapp/grails-app/assets/javascripts/jobedit.js, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
This commit adds threadcount as a job context variable, so scripts and
commands called by rundeck can use the threadcount of a job.
For example, if you are running a job that involves taking some nodes in a
cluster offline, the threadcount vs. the total number of nodes in the
cluster could be used by called scripts to check that enough capacity
will be left.
=> Add threadcount as a job context variable

core/src/main/java/com/dtolabs/rundeck/core/authorization/providers/YamlParsePolicy.java
On syntax exception it encapsulate the code, from this:
```
Error parsing the policy document: Cannot create property=for for JavaBean=Policy{context=null, description='Admin project level access control. Applies to resources within a specific project.', for=null, by=null, id='null'}; Cannot create property=eqauals for JavaBean=Rule{}; Unable to find property 'eqauals' on class: com.dtolabs.rundeck.core.authorization.providers.yaml.model.ACLPolicyDoc$TypeRule
```
to this:
=> Simple syntax error messages on ACL

core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschNodeExecutor.java
Change the JSCH authentication error message ( "Incorrect Password")  to a more generic message:  "Could not authenticate".
=> Change the JSCH authentication error message

rundeckapp/grails-app/domain/rundeck/Option.groovy, rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy, rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
Lazy fetch for `ScheduledExecution.options` and `Option.values` and fix for the quartz load scheduleExecution including the options on the return object.
Resulting in approx 25% less on the job list page loading time.
=> Improvement on load jobs page

docs/en/manual/04-jobs.md, rundeckapp/grails-app/assets/javascripts/jobedit.js, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/test/unit/ExecutionServiceTests.groovy
We have a situation where we need to do the following:
1) have a common deployment job that takes a number of parameters and can deploy any application
2) have individual jobs that reference the common job with the parameters filled in for that specific application
3) have a series of steps performed on each server before the deployment
4) have the deployment happen sequentially
5) only have a single job reference in each of the "individual" jobs (for ease of maintenance and to ensure governance/compliance)
6) have node filters work normally
It looks something like this in reality:
```
Node 1
--- Run puppet
Node 2
--- Run puppet
Node 1
--- Drain load balancer
--- Deploy application
--- Undrain load balancer
Node 2
--- Drain load balancer
--- Deploy application
--- Undrain load balancer …
```
=> Add: Job filter as a context variable

rundeckapp/src/groovy/com/dtolabs/rundeck/app/support/PluginResourceReq.groovy, rundeckapp/test/unit/com/dtolabs/rundeck/app/support/PluginResourceReqSpec.groovy
Allow _: chars in provider names, remove . from service name validation
=> Fix #3001 plugin icons for providers with `:` char

packaging/Makefile
Change the .deb naming convention to a standard one to avoid potential problems. More details in issue
Fixes https://github.com/rundeck/rundeck/issues/2777
=> Use debian standard naming convention for .deb files

docs/en/developer/05-notification-plugins.md, docs/en/manpages/man5/job-v20.md, docs/en/manpages/man5/job-yaml-v12.md, docs/en/plugins-user-guide/configuring.md, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/views/scheduledExecution/_editNotificationsForm.gsp, rundeckapp/test/unit/ScheduledExecutionServiceTests.groovy, rundeckapp/test/unit/rundeck/services/ScheduledExecutionServiceSpec.groovy
This addresses issue #1067 by adding a new notification trigger
alongside the existing succeeded, failed, started, and average
duration exceeded notifications.
The new notification is triggered when a job that's configured to
retry on failure fails with retries still remaining. Jobs without
retries enabled never get the new notification.
The "failed" notification is now only sent on the last attempt.
=> Separate notifications for retryable failures

docs/en/administration/01-installation.md, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/services/rundeck/services/ReportService.groovy
Fix #3074 #3078 #3079
Will work out of the box in Oracle using default isolation level, on MSSQL the administrator must add this configuration on `rundeck-config.properties` to reduce the isolation level to READ_UNCOMMITTED if this is not set, the default isolation level can increase the deadlocks number.
```
rundeck.min.isolation.level=UNCOMMITTED
```
=> Low isolation level as property

rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy, rundeckapp/grails-app/views/execution/_execDetails.gsp, rundeckapp/grails-app/views/scheduledExecution/_editNotificationsTriggerForm.gsp, rundeckapp/test/unit/JobsXMLCodecTests.groovy, rundeckapp/test/unit/JobsYAMLCodecTests.groovy, rundeckapp/test/unit/rundeck/quartzjobs/ExecutionJobSpec.groovy
Adding a threshold on a per job basis to trigger on the avg duration plus some overrun allowance.
For example:
* avgduration 20% 
* avgduration +5m
* avgduration  5m
New inputs for notification form:
* percentage
* time delta
* absolute time
https://github.com/rundeck/rundeck/issues/3064
=> Average notification duration enhancement

core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmExportPlugin.java, core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmImportPlugin.java, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy, rundeckapp/grails-app/services/rundeck/services/ScmService.groovy, rundeckapp/test/unit/rundeck/controllers/MenuControllerSpec.groovy, rundeckapp/test/unit/rundeck/services/ScmServiceSpec.groovy
See #1622 
Removed member unique config. Now, on cluster mode, the configuration its saved on the `scm` folder, not in the `scm/nodeUuid` folder. This require configure again the scm plugins on cluster environments.
If a job is imported or from one node, other nodes got the same information.
=> Scm cluster config

rundeckapp/grails-app/services/rundeck/services/workflow/StateMapping.groovy, rundeckapp/test/unit/rundeck/services/WorkflowServiceSpec.groovy
Fix #1481
In some cases, the referenced jobs don't appear on the report at the start, only when the job is complete.
This specifically happens when the referenced job run on the same node as one of the parent jobs and in another node.
Prior to this PR.
At start:
Running:
At the end:
Now:
At start:
Running:
At the end:
=> Incomplete report at start on jobref

docs/en/manual/04-jobs.md, rundeckapp/grails-app/assets/javascripts/jobedit.js
Fix #1811 
Added ${job.executionType} to context variables documentation and to autocomplete.
=> ${job.executionType} to context variables documentation

rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
fix for "Matched Nodes list is not (Auto) Refreshed in Job" https://github.com/rundeck/rundeck/issues/3075
=> Fix: Matched Nodes list is not (Auto) Refreshed in Jobs

rundeckapp/grails-app/domain/rundeck/JobFileRecord.groovy
serverNodeUUID field works as a normal String field, no need to be a text field, causing the #3125 problem on Oracle.
This fixes the problem for future implementations over Oracle, current versions of the table need to migrate the CLOB field to Varchar2
=> serverNodeUUID field to varchar 

rundeckapp/src/groovy/com/dtolabs/rundeck/server/plugins/storage/KeyStorageLayer.groovy, rundeckapp/test/unit/com/dtolabs/rundeck/server/plugins/storage/KeyStorageLayerSpec.groovy
If a provider plugin is used that does not return all the metadata set in the create/update, then public/private/password entries will not show up correctly in the key storage API/GUI
=> Fix: key storage data type not set automatically with Vault plugin

rundeckapp/grails-app/assets/javascripts/executionControl.js, rundeckapp/grails-app/assets/javascripts/executionStateKO.js, rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/views/common/_js.gsp, rundeckapp/grails-app/views/execution/show.gsp, rundeckapp/test/unit/rundeck/controllers/ExecutionControllerTests.groovy, rundeckapp/web-app/js/executionState.js
Fix #3155 
Kill execution wrapped on try catch block, in case a database error is thrown, the job is forced to be killed, and later.
If was killed on the job execution page, ~~the next `ajaxExecState` will try to mark the execution as incomplete.~~ the kill button is replaced with a **Mark as Incomplete** button if you're still on the same execution page.
=> Force to kill execution on database problem

rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy, rundeckapp/test/unit/rundeck/services/ExecutionUtilServiceTests.groovy
Fix #3189
When a job that references another as an error handler is referenced and run on another project, the referenced job project is used to search the handler job.
=> FIX #3189: Referenced job error handlers

core/src/test/java/com/dtolabs/rundeck/core/tools/AbstractBaseTest.java
Fix some test issues where test fail with `rdeck_base directory does not exist`
Due to spock groovy tests running before Junit java tests in some cases
=> Fix issues with test ordering

rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/test/unit/rundeck/controllers/FrameworkControllerSpec.groovy, rundeckapp/test/unit/rundeck/controllers/FrameworkControllerTest.groovy
This changes the ACL requirement to edit project/resource configurations from `admin` to `configure`
=> Fix #3012 admin access required to modify project config/nodes in gui

rundeckapp/grails-app/assets/javascripts/menu/project-model.js, rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/grails-app/views/common/_topbar.gsp, rundeckapp/grails-app/views/framework/_editProjectForm.gsp, rundeckapp/grails-app/views/framework/_projectSelect.gsp, rundeckapp/grails-app/views/framework/adhoc.gsp, rundeckapp/grails-app/views/framework/nodes.gsp, rundeckapp/grails-app/views/menu/_projectHomeKO.gsp, rundeckapp/grails-app/views/menu/home.gsp, rundeckapp/grails-app/views/menu/jobs.gsp, rundeckapp/grails-app/views/menu/projectAcls.gsp, rundeckapp/grails-app/views/menu/projectHome.gsp, rundeckapp/grails-app/views/reports/index.gsp, rundeckapp/grails-app/views/scm/diff.gsp, rundeckapp/grails-app/views/scm/index.gsp, rundeckapp/grails-app/views/scm/performAction.gsp, rundeckapp/grails-app/views/scm/setup.gsp, rundeckapp/test/unit/rundeck/controllers/FrameworkControllerTest.groovy, rundeckapp/test/unit/rundeck/controllers/MenuControllerSpec.groovy
Free-form labels for projects.
New property `project.label` in the project configuration:
This label is going to be rendered on the GUI instead of the project name in the project list page:
Old:
New:
In the project home page:
In the project selector on the menu:
On the API can be read using the `project.label` value:
`/api/21/project/<project>/config/project.label`
=> Project free form label

docs/en/manual/04-jobs.md, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
Disable JSON check for remote options using the project variable called project.jobs.disableRemoteOptionJsonCheck
For: https://github.com/rundeck/rundeck/issues/2922
=> Disable JSON check for remote options

core/src/main/java/com/dtolabs/rundeck/core/resources/FileResourceModelSource.java, core/src/test/java/com/dtolabs/rundeck/core/resources/TestFileResourceModelSource.java
Fix #3246 
Now creates the resources file even without `Include Server Node` selected.
=> Create empty resources file

rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
Now the project table it's only updated if the project exists on the project list page, not on the import project code to avoid an NPE when the storage=db it's disabled.
=> fix #3289 on import project without db storage

rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/views/execution/show.gsp, rundeckapp/grails-app/views/scheduledExecution/_edit.gsp, rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp, rundeckapp/test/unit/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Features #1144 and #1107 implemented.
For 1107:
If you enter the URL using the fragment `#output` you start on the `Log Output` tab.
For 1144:
On the job edit page you get a new option to select the default tab:
Also you can edit on the `Prepare and Run` page the default tab to be used for this execution.
=> Follow execution enhancements

rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
Edit node resources on error redirect to missing page `editProjectResourceFile`, corrected to `editProjectNodeSourceFile`.
Fix #3317
=> Fix wrong redirect on node edit with errors

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/domain/rundeck/JobExec.groovy, rundeckapp/grails-app/domain/rundeck/ReferencedExecution.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/test/unit/rundeck/controllers/ScheduledExecutionControllerSpec.groovy, rundeckapp/test/unit/rundeck/controllers/ScheduledExecutionControllerTests.groovy
Fix #3340 
Caused by a query with many `or`, the query has moved to `ReferencedExecution` to avoid multiple or on `JobExec`.
Fix #3346 
Force delete ReferencedExecution on delete of a job and executions.
=> Fix postgresql problems on JobReference

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
Job definition download should only contain desired format contents.
=> Fix for #3366. 

docs/en/api/rundeck-api.md, rundeckapp/grails-app/conf/UrlMappings.groovy, rundeckapp/grails-app/conf/rundeck/filters/ApiRequestFilters.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/test/unit/rundeck/controllers/ScheduledExecutionControllerSpec.groovy, test/api/include.sh, test/api/test-v23-project-sources-json.sh, test/api/test-v23-project-sources-xml.sh
An endpoint for the API to retry a job's execution on failed nodes.
The new endpoint is: 
`POST /api/23/job/[ID]/retry/[EXECID]`
Optional parameters. 
All of this parameters are going to be populated with the execution values unless they are included in the call:
* `argString`: argument string to pass to the job, of the form: `-opt value -opt2 value ...`.
* `loglevel`: argument specifying the log level to use, one of: 'DEBUG','VERBOSE','INFO','WARN','ERROR'
* `asUser`: specifies a username identifying the user who ran the job. Requires `runAs` permission.
* `option.OPTNAME`: Option value for an option named `OPTNAME`. If any `option.OPTNAME` parameters are specified, the `argString` value is ignored.
* `failedNodes` : `false` to run on the same nodes as the original execution, `true`or …
=> API: Run job based on execution (retryExecId)

docs/en/plugins-user-guide/git-plugins.md
List was't being correctly displayed here: http://rundeck.org/docs/plugins-user-guide/git-plugins.html#job-source-files-configuration
A blank line before the start of the list should solve it.
=> fixed list not being correctly rendered

rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
Using temp `scheduledExecution` object when the job is copied and still not in the database.
Fix #3421 
Fix #3384
=> Fix missing job options on duplicated job 

core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionServiceImpl.java, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Resolves #2092 
Add capability to use ${job.x} and ${node.x} on Storage Path options.
=> Enhancement: Using variable in Storage path job options

core/src/main/java/com/dtolabs/rundeck/core/properties/CoreConfigurationPropertiesLoader.java, rundeckapp/grails-app/init/rundeckapp/Application.groovy, rundeckapp/grails-app/init/rundeckapp/init/DefaultRundeckConfigPropertyLoader.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java
Allows a user to write a custom property loader for rundeck-config.properties.
Adds the rundeck.security.ldap.bindPassword property that can be specified in the rundeck-config.properties file so that it can be loaded in the same way as the other properties in rundeck-config.properties.
=> Addresses issue #2062 

rundeckapp/grails-app/init/rundeckapp/init/FileUtils.java
Method was ripped from 2.11 branch and moved to a separate class, but should've been marked static.
=> Fix #3434. Method should be static.

rundeckapp/grails-app/domain/rundeck/JobExec.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/JobExecSpec.groovy
Fix #3429
Job definition now it's exported correctly:
```
sequence:
commands:
- jobref:
group: ''
importOptions: true
name: test2
```
=> ImportOptions to jobref in job definition

.travis.yml, travis-helpers.sh
This PR aims to cleanup the Travis build log output for easier viewing as well as gaining timing insight into the individual commands.
* Breaks the large `command && command` script up into multiple script lines
* Utilizes `set -o errexit` to preserve fail fast behavior
* Adds code folding and timing to each script via a new bash helper function(exported from **travis-helpers.bash**)
* Overrides the install command as `assemble` is a dependency of the build target
=> Build output improvements.

.gitignore, .travis.yml, travis-helpers.sh
This PR introduces an initial Travis CI stages **"spike"**.  It introduces a few new concepts:
* Travis CI stages to bundle jobs that can be run in **parallel**
* Scripts re-bundled into a build stage, followed by a test stage with parallel jobs
* Artifact syncing to s3 for sharing outputs between stages
* Knocks a further **10+ minutes** off the existing build process
* Further increases build output readability by grouping outputs under jobs in the Travis UI
* Opens up s3 and other aws services to the build process
* Building base docker containers and pushing them to dockerhub for reuse in downstream stages
* Speeding up the API test suite(possibly use a different runner from roundup that support parallel execution and a junit results formatter)
* Gradle caching(some info out there on …
=> Implement Travis stages.

.travis.yml
This PR introduces a `fork` stage that consolidates all the tests into one stage/job. This is essentially the *slow* path.
Encrypted envars are not available to forks, so we are not able to pass artifacts between stages and jobs. In the future we can discuss running a subset of stages/tests on PRs coming through on forks. For instance, if we were using Sauce Labs we wouldn't want to expose credentials to forks and may skip the selenium tests or run them locally. As well, Travis is supposedly releasing artifact support this summer...
=> Add stage for forks.

gradle.properties, rundeckapp/gradle.properties, rundeckapp/metricsweb/gradle.properties
=> Grails3: Cleanup gradle/grails props with version numbers

core/src/main/java/com/dtolabs/rundeck/core/cli/acl/AclTool.java, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/grails-app/taglib/rundeck/AuthTagLib.groovy, rundeckapp/src/test/groovy/FrameworkServiceTests.groovy
Closes #1812
* Adds the capability to use job's UUID instead of name, group:
```
context:
project: '.*' # all projects
for:
job:
- equals:
uuid: baad57ad-1e0b-4452-b1e3-0cbcd10a7bec
allow: [view,run]
- equals:
uuid: b8ed7b5b-cac9-44eb-a543-e62423bdac3f
allow: [view,run,runAs]
```
works in the same way as using
```
context:
project: '.*' # all projects
for:
job:
- equals:
nane: exampleJobA
allow: [view,run]
- equals:
name: exampleJobB
allow: [view,run,runAs]
```
* Adds the option `-I --jobUuid <uuid>` to use instead of job's name on rd-cli tool.
* Adds the Uuid field to the project Resources Attributes By Type to be used on rundeckpro gui acl editor
=> ACL for uuid

rundeckapp/grails-app/conf/logback.groovy
Fix startup WARN level logs that are just noise.
Set loglevel to ERROR for specific loggers.
=> fix #3478 reduce startup logging noise

rundeckapp/grails-app/conf/application.groovy
Fix #3476
Default max size for file upload. The grails 3 max by default is 128kb, but exported projects can be greater than that.
The new default max size is 25MB but can be overrided on the `rundeck-config.properties` file with the file size in bytes:
```
grails.controllers.upload.maxFileSize=26214400
grails.controllers.upload.maxRequestSize=26214400
```
=> Set a max file size of 25mb configurable

rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp
Use `values` instead of the empty array `inputValues` for freeSelect on scm plugin
Fix #3483
=> Preserve values on freeSelect.

.travis.yml, gradle/java.gradle, scripts/delete-bintray-package.sh, scripts/deploy-deb-snapshots.sh, scripts/deploy-maven-snapshots.sh, scripts/deploy-rpm-snapshots.sh, scripts/publish-deb-to-bintray.sh, scripts/publish-jar-to-bintray.sh, scripts/publish-rpm-to-bintray.sh, scripts/replace-filename-token.sh, travis-helpers.sh
This PR introduces a `release` stage to the Travis build. The stage will run on a daily Travis cron to build and publish snapshot artifacts from master. It can also be triggered manually through the Travis UI by setting `RUNDECK_RELEASE=true`.
**Change synopsis:**
* Vendors external script dependencies used for publishing to Bintray
* Consolidates Jenkins steps into top level scripts for portability
* Removes findbugs, a deprecated Gradle plugin which was silently failing builds on the Jenkins server
* Consistency improvements in script naming and calling convention
This work will serve as a first step to cutting beta and GA releases from Travis CI as well.
=> Travis snapshots

rundeckapp/build.gradle
This PR adds the latest JDK8 compatible JDBC drivers for supported databases to the run-time dependencies in `rundeckapp/build.gradle`. This will cause Spring Boot to bundle them in the repackaged `war` file.
* Postgresql
* SQL Server
* MariaDB
The `ojdbc8` driver is hosted on Oracles own Maven repository which requires registration and authentication. Adding this to the deps like the others will require anyone building the application to jump through these hoops. I'm still looking for the best way to handle this:
* Add a class path via the spring boot config(incidentally we could probably do this with all drivers, but it's more friendly IMHO to bundle the drivers for supported databases)
* Go ahead and add the repository and dep info; require developers to export environment variables …
=> fix #3505 Bundle jdbc drivers.

.travis.yml, scripts/travis-helpers.sh, test/docker/common.sh, test/docker/dockers/rundeck/Dockerfile, test/docker/test-api.sh
* Utilizes base Ubuntu image from testdeck(pre-installs most dependencies like jdk)
* Refactors rdtest Dockerfile to reduce layers and image size
* Pushes/pulls rdtest to/from DockerHub and uses it as a cache candidate
=> Build test images from dockerhub base.

rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy, rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionJobTest.groovy
Fix #3484
Get the options values from the executions if the timeout of the `scheduleExecution` starts with `${`.
=> Usage of option values for timeout

rundeckapp/grails-app/controllers/rundeck/interceptors/ControllerBaseInterceptor.groovy
Fix #3544
Add executionMode page to allowed UI plugin pages.
=> Allow ui plugin loading on executionMode page

rundeckapp/build.gradle
Fix #3554 
Re-enable less files to be built by the asset-pipeline.
=> Fix missing ansi colorization css

rundeckapp/grails-app/views/common/_topbar.gsp
Fix "ConcurrentModificationException" thrown in logs sometimes.
Use a copy of the session object in the view because the view sorts the list.
Difficult to reproduce, but I've seen the exception occur, possibly when creating a new project while having another browser window open.  The user session has a list of project names, so two browser tabs might both access the session variable, and the projectSelect template sorts the variable directly which could cause concurrent modification.
=> Fix potential concurrent modification exception

rundeckapp/grails-app/assets/javascripts/jobedit.js, rundeckapp/grails-app/views/execution/_execDetailsWorkflow.gsp, rundeckapp/grails-app/views/execution/_wflistContent.gsp, rundeckapp/grails-app/views/scheduledExecution/_detailsOptions.gsp, rundeckapp/grails-app/views/scheduledExecution/_edit.gsp, rundeckapp/grails-app/views/scheduledExecution/_optlistContent.gsp
Fix #3556 
replace prototype dragdrop with html5 drag and drop
Prototype dragdrop could work, it broke due to scrollable content instead of page scroll (i think). If you drag and drop without scrolling the page down at all, the drop targets work correctly, however any scrolling means that the targets no longer work.
`Position.includeScrollOffsets` may just need to be set to true, but i'd rather ditch prototype instead of trying to fix it.
=> Fix #3556 wf/opt drag and drop not working

rundeckapp/grails-app/views/execution/show.gsp
Fix #3536
Floating bar over log output and "Scroll to Top" button.
=> rd3 Job Execution Show Page floating header

rundeckapp/grails-app/views/common/_sidebar.gsp
Fix #3585 
Don't force the contextual page info into the sidebar project link from the home page (project list)
=> Fix #3585 sidebar project links from home list work

build.gradle, core/build.gradle, core/src/main/java/com/dtolabs/rundeck/core/VersionConstants.java, rundeckapp/build.gradle, rundeckapp/grails-app/views/menu/welcome.gsp
display build info on welcome page
Adds git info to metadata for core and app, displays it on the secondary welcome page.
Uses git-build-info and buildconfig gradle plugins to include git info in both a java BuildConfig class in core, and in the grails metadata file.
=> Add git info to core and rundeck app metadata

.travis.yml, scripts/travis-helpers.sh
* Stores artifacts in a new, more predictable S3 path scheme
* Stores tagged build artifacts in a singular location(discovery for other projects)
* Passes tag information to downstream Travis builds
* Cleanup and comments
=> Refactor to make coordinating tagged releases with pro easier.

rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java
Performance bugfix/enhancement
getUserRoles ldap search currently fetches ALL attributes which is a waste of bandwidth resources and woefully slow on large ldap groups when it only needs to parse roleNameAttribute.
This 2 line fix makes ldap role search 1000x faster.
Returning Selected Attributes from https://docs.oracle.com/javase/jndi/tutorial/basics/directory/filter.html
=> getUserRoles ldap search attributes filter

rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/views/scheduledExecution/_edit.gsp, rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
fixes #3612
Definition removed from Default tab selector.
HTML added creating a link to `/project/<project>/execution/renderOutput/<id>?ansicolor=on&loglevels=on&convertContent=on`
Since the log is in `waiting` state, a new param is added `reload`, that causes the HTML view to reload every 5 seconds until the execution is complete.
=> Add html otuput to tab selector

.travis.yml, scripts/travis-helpers.sh
Assume master build is good for snapshot purposes based on full testing in PR builds.
This should tighten the snapshot feedback loop significantly.
=> Trigger downstream snapshot builds immediately after build.

core/build.gradle, packaging/rundeck.spec, rundeck-storage/build.gradle, rundeckapp/grails-app/conf/BuildConfig.groovy
Fix: testbuild.groovy failing due to jackson-databind version
=> Update jackson-databind to 2.8.11.2

core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkProjectConfig.java, core/src/main/java/com/dtolabs/rundeck/core/common/ProjectNodeSupport.java, core/src/main/java/com/dtolabs/rundeck/core/resources/LocalResourceModelSource.java, core/src/main/java/com/dtolabs/rundeck/core/resources/LocalResourceModelSourceFactory.java, core/src/main/java/com/dtolabs/rundeck/core/resources/ResourceModelSourceService.java, core/src/test/java/com/dtolabs/rundeck/core/common/TestFrameworkProject.java, rundeckapp/grails-app/assets/javascripts/resourceModelConfig.js, rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy, rundeckapp/grails-app/views/framework/editProjectNodeSources.gsp, rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
* fix #3185 - use new `local` provider as default node source provider for new projects 
* applies to db-storage and file-storage
* Upgrade issue: new projects using file-based config storage will not have a `file` nodes provider set by default
* fix some tangential issues: 
* ACE text area not loading on Project configuration editor page for code/multi-line properties of resource model sources
* 500 page error on Edit Project Configuration page if some expected config properties were not set
Add a default resource model provider implementation that generates the local node, but does not require a file to be used.
=> Fix default node source for new projects with db storage

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
For large projects with many jobs in many groups, if pagination is turned on the query needs to order by groupPath so the output results make more sense to a user.
=> Add order by groupPath so that UI grouping makes sense in pagination mode

core/src/main/java/com/dtolabs/rundeck/core/common/ProjectNodeSupport.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/local/LocalNodeExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/CloseableProvider.java, core/src/main/java/com/dtolabs/rundeck/core/resources/ResourceModelSourceService.java, core/src/test/groovy/com/dtolabs/rundeck/core/common/ProjectNodeSupportSpec.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/grails-app/services/rundeck/services/NodeService.groovy, rundeckapp/grails-app/services/rundeck/services/PluginService.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy, rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerTest.groovy, rundeckapp/src/test/groovy/rundeck/services/NodeServiceSpec.groovy
Use the PluginService methods to load ResourceModelSourceFactory plugins:
* allows loading spring-based bean plugins
* requires replacing use of the framework.getResourceModelSourceService() to directly load plugins
We have to pass the original ResourceModelSourceService to the PluginService, so it can load packaged plugin files as before, since the ResourceModelSourceService loads the plugins slightly differently than most other plugin types.  Otherwise we could have let the PluginService create a generic plugin loader service for the ResourceModelSourceFactory plugin types.  The problem is that the default no-arg constructor expected by the generic loader won't work with ResourceModelSourceFactory type, as they allow a single-arg Framework argument constructor.
=> Use the PluginService methods to load ResourceModelSourceFactory plugins

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/FileUploadService.groovy, rundeckapp/grails-app/services/rundeck/services/NodeService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy, rundeckapp/src/test/groovy/ExecutionServiceTests.groovy, rundeckapp/src/test/groovy/rundeck/services/NodeServiceSpec.groovy
Fix #2598 
Pass the options of type `file` to the context of the referenced job and skip the validations on the new context.
=> file options on referenced jobs

test/docker/docker-compose-api-mysql.yaml
Update mysql-api test to remove warnings about index key sizes.
* upgrade to mysql 5.7, fixes errors like:
> 2018-07-08 00:25:11,810 [main] ERROR hbm2ddl.SchemaUpdate - HHH000388: Unsuccessful: create index EXEC_REPORT_IDX_0 on base_report (ctx_project, date_completed, jc_exec_id, jc_job_id)
2018-07-08 00:25:11,812 [main] ERROR hbm2ddl.SchemaUpdate - Specified key was too long; max key length is 767 bytes
* add `useSSL=false` to jdbc string to quell errors about not using SSL.
TODO:
=> Update to mysql 5.7, quell ssl startup warning

rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/views/execution/_wfItemView.gsp
Fix #3694
Adds message `(Job not found)` on definition tab for wrong referenced jobs.
=> Job not found message on definition tab

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
Fix Error message: ORA-01795 in `menu/home` with Oracle database over 1000 projects.
#3650 For release `3.0.0`
Rebase from #3651
=> Fix Error message: ORA-01795 (rd3)

rundeckapp/grails-app/conf/application.yml, rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy, rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy, rundeckapp/metricsweb/src/main/groovy/metricsweb/MetricswebGrailsPlugin.groovy, rundeckapp/metricsweb/src/main/groovy/org/grails/plugins/metricsweb/DisablingAdminServlet.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ApiControllerSpec.groovy, test/api/include.sh, test/api/test-metrics.sh
paths: /api/25/metrics  - list of metric hrefs
/api/25/metrics/{metrics,ping,threads,healthcheck} - endpoints
configuration, the servlets must be enabled for each endpoint, plus
api must be enabled for each endpoint
rundeck.web.metrics.servlets.$endpoint.enabled=true
rundeck.api.metrics.$endpoint.enabled=true
TODO:
=> Add metrics to API, update to APIv25

plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/config/Export.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginFactorySpec.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy, test/api/test-scm-git-plugin-inputs.sh
Add new configuration options to create a new branch on the `git-export` SCM plugin.
If the branch doesn't exist on the remote repo, it will create a new one with the `branch` name. It will be based on the `base branch`.
If the `base branch` doesn't exist on remote, it will throw an error:
=> Create new branch on git-export

rundeckapp/grails-app/conf/application.yml, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/init/rundeckapp/init/servlet/JettyServletContainerCustomizer.groovy
Restore security config settings from rundeck 2.x for embedded jetty:
* set httpOnly cookies
* disable session ID in url params
ref:  previous coded jetty embed configuration in RunServer: https://github.com/rundeck/rundeck/blob/v2.11.5/rundeck-launcher/rundeck-jetty-server/src/main/java/com/dtolabs/rundeck/RunServer.java#L118-L123
=> Restore embedded jetty security settings

rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy, test/docker/dockers/rundeck/scripts/start_rundeck.sh
System property `rundeck.bootstrap.build.info=true` will report build information at startup.
=> Optional sys prop displays build info on startup

rundeckapp/grails-app/conf/logback.groovy
This increases the log level to `DEBUG` on select auth related loggers. Without this, and currently, JAAS configuration and module errors are not visible in the logs by default.
Some of the logging that is sent to `DEBUG` is probably more suitable for the error `ERROR` or `WARN` level, however this does not address that.
**Auth/JAAS Logging**
Sets related jaas packages to `DEBUG` so that config and run-time errors are visible in the log output.
**Logback `WARN` level**
Increases default logback log level to `WARN`, which is for potential problems, or "harmful situations" according to log4j.
=> Set logging to output jaas config issues.

rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy, rundeckapp/grails-app/views/common/_mainbar.gsp, rundeckapp/grails-app/views/user/loggedout.gsp, rundeckapp/grails-app/views/user/login.gsp
User configurable logos now served with links that contain the context.
Copy jars from WEB-INF/lib if app is deployed as a war and the classloader can't find the tool jars.
=> Fix various container deployment issues

scripts/helpers.sh
Update to use the newly defined repos for public consumption of pre-release builds:
* `dev-*` master snapshots
* `testing-*` tagged releases(alpha,beta,rc)
=> Use newly defined repo names.

rundeckapp/grails-app/services/rundeck/services/ApiService.groovy
see #3767 
The token is used on the next method after the creation, on Postgres without flushing the save, the token is not yet on the database, causing a `null` message.
=> Problem saving api token on postgres

grails-persistlocale/build.gradle, rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy
JBoss Wildfly uses a customized classloader, so the normal methods for extracting jars will fail.
=> Fix #3787 deployment on jboss wildfly 13.

core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/state/WorkflowExecutionStateListenerAdapter.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepExecutionItem.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/state/WorkflowExecutionStateListenerAdapterSpec.groovy, rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStateImplSpec.groovy
Fix #3791 
* fix incorrect test for node step items.  Job references were incorrectly treated as node steps in all cases, and final state was not correctly updated when they were non-node-steps.
=> Fix incorrect workflow state when non-node-step jobrefs complete

rundeckapp/grails-app/domain/rundeck/Storage.groovy, test/docker/docker-compose-api-mysql.yaml, test/docker/dockers/rundeck/scripts/start_rundeck.sh
Fix #3785 
Remove the index on the dir field
Add check in mysql API tests to fail if startup log contains mysql exceptions
=> Remove index for storage dir field to prevent mysql warning

rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ApiControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ProjectControllerTest.groovy, test/api/include.sh
fix #3827 
Project description from project configuration file and adds the label on new API version v26
Using API version >=26 adds the project `label` to the API call  `/api/26/projects` 
```
[
{
"name":"...",
"description":"...",
"url":"...",
"label":"..."
}
]
```
Doc documentation PR: rundeck/docs#72
=> Project description on project list api call

rundeckapp/grails-app/assets/javascripts/executionStateKO.js, rundeckapp/grails-app/assets/javascripts/util/testing.js, rundeckapp/grails-app/assets/javascripts/workflow.js, rundeckapp/grails-app/assets/javascripts/workflow.test.js
Fix #3828 
Properly escape `/` char in node names when loading workflow step details in a workflow with node-step job references.
Docker plugin was generating node names like `/word_word` breaking output loading in some cases when viewing execution output.
=> Fix #3828 node names with / break GUI output loading

.gitignore, build.gradle, core/build.gradle, rundeck-storage/build.gradle, rundeckapp/build.gradle
Uploads existing artifacts directly from their location in the artifacts directory.
Gradle seems to remove the project build directories when `bintrayUpload` is run if the project has never been built.
=> Bintray debug

rundeckapp/grails-app/services/rundeck/services/DbStorageService.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Mysql use `ConcurrencyFailureException`  instead of `OptimisticLockingFailureException` in the same expected lock exception.
`org.springframework.dao.ConcurrencyFailureException` is the parent class of `org.springframework.dao.OptimisticLockingFailureException` so its no risk for other databases that use the current Exception without problems (tested so far on Postgres, h2, mssql and Oracle).
=> fix jobs failing over lock exception on mysql

rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/src/main/groovy/org/rundeck/security/RundeckJaasAuthorityGranter.groovy
This is a fix for a bug getting the roles from LDAP.
1)  By default, rundeck3 use the role prefix `ROLE_` which can break the use of LDAP on 2.x
2) Also, rundeck3 add the username as a role.
1) Replacing the default role prefix with an empty value.
That value can be modified using the parameter `rundeck.security.jaasRolePrefix=` on `rundeck-config.properties`
I tried using  `rundeck.security.jaasRolePrefix=` on  `rundeck-config.properties` to pass an empty value, but that is not posible using  `rundeck-config.properties` (maybe using the groovy format)
The use of `ROLE_` as prefix can produce this kind of errors
This can fix this issue: …
=> LDAP authentication fixing

rundeckapp/grails-spa/src/pages/project-dashboard/App.vue, rundeckapp/grails-spa/src/pages/project-dashboard/components/activity.vue
Fix #3888 
Links from project home page to Activity use `rdBase` as base URL.
=> Fix #3888 activity links should be relative to app base url

rundeckapp/grails-app/assets/javascripts/menu/home.js, rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy, rundeckapp/grails-app/views/common/_mainbar.gsp, rundeckapp/grails-app/views/menu/home.gsp
=> display icon for project schedule/exec disabled state in header

rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
Fix #3914 
import statement glob was masking correct class. (revert code cleanup import optimization)
add a test for affected action
=> Fix #3914 NodeFilter class was shadowed by glob import

rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
Add a test for saveProjectNodeSources
~~~
groovy.lang.MissingPropertyException: No such property: FrameworkProject for class: rundeck.controllers.FrameworkController
at grails.artefact.gsp.TagLibraryInvoker$Trait$Helper.propertyMissing(TagLibraryInvoker.groovy:121)
at rundeck.controllers.FrameworkController.saveProjectNodeSources(FrameworkController.groovy:1394)
~~~
caused by https://github.com/rundeck/rundeck/commit/7d055f5f11b55cf3fe51ee82991ea9d7b5c6f182
=> Add spec unit test for saveProjectNodeSources

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy, rundeckapp/grails-app/controllers/rundeck/interceptors/ControllerBaseInterceptor.groovy, rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp, rundeckapp/grails-app/views/menu/userSummary.gsp, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy, rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/UserControllerSpec.groovy, test/api/include.sh
New Page listed in the System menu only to users with admin privileges:
This page list the users (in the table `rduser`) and some info about them:
* Login username
* Profile information (first name, last name, email)
* Creation and modification date
* Last time the user runs a job
* Number of tokens
=> Users summary page

rundeckapp/grails-app/services/rundeck/services/ConfigStorageService.groovy, rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy, rundeckapp/src/test/groovy/rundeck/services/ConfigStorageServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
Fix #3960 
Only occurs when using `file` provider for config storage backend.
=> Fix config storage tree errors using file provider

grails-persistlocale/src/main/groovy/grails/persistlocale/PersistlocaleGrailsPlugin.groovy, rundeckapp/build.gradle, rundeckapp/src/integration-test/groovy/rundeck/grails_plugins/PersistLocaleIntegrationSpec.groovy
Fix #3860 
persist locale plugin was not loading after i18n plugin, so `localeResolver` bean was not correctly overriding default session resolver.
=> Fix locale not persisting via cookie correctly

rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/domain/rundeck/ReferencedExecution.groovy, rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy, rundeckapp/grails-app/views/scheduledExecution/_renderJobStats.gsp
* Optimization execution count query, creating new indexes and removing legacy execution status `true`.
* Disabled count missing log storage. This query takes a lot of time on databases with over 1 million records on `log_file_storage_request` and `execution`. It can be enabled using `framework.storage.missing=true` on `framework.properties`. This is not used in the current code so it could be removed completely on future releases.
=> Query optimization 2.11

rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/BaseNodeFilters.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ExecutionContext.groovy
Recent versions of Gorm change the way dirty checks work on domain class superclasses. You either need to use setter methods or annotate the super class with @DirtyCheck.
https://github.com/grails/grails-data-mapping/issues/1097
=> Add @DirtyCheck annotation to ScheduledExecution superclasses

rundeckapp/grails-app/views/common/_sidebar.gsp, rundeckapp/grails-app/views/layouts/base.gsp
Sets the ui_token in base.gsp, saves the status of the sidebar (open/closed) when user triggers the open/close sidebar event.
=> #4029 - sets ui_token, uses token to save sidebar status

rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java
Fix: user LDAP credentials potentially exposed in server log.
Don't log user credentials.
User credentials may be exposed in the rundeck server log in these conditions:
* using JettyCachingLdapLoginModule or JettyCombinedLdapLoginModule
* using `forceBindingLogin="false"` in the jaas.conf
If user credentials in the LDAP server are stored unencrypted, then the server log may print them in plainttext.
Workarounds:
* use `forceBindingLogin="true"` in jaas conf for the JettyCachingLdapLoginModule
=> Fix: LDAP user credentials should not be exposed

core/src/main/java/com/dtolabs/rundeck/core/plugins/ScriptPluginProviderLoader.java
This PR makes the script loader compare versions like the jar loader to detect if plugins support resources.
=> Fix script icons not loading for plugin format version 2 script plugins

core/src/main/java/com/dtolabs/rundeck/core/init/CustomWebAppInitializer.java, rundeckapp/grails-app/init/rundeckapp/init/servlet/JettyServletContainerCustomizer.groovy, rundeckapp/src/test/groovy/rundeckapp/init/servlet/JettyConfigPropsInitParameterConfigurationTest.groovy
Some customers used the ability to configure the web.xml in Rundeck 2.x to enhance their installation. This PR provides a way for customers to customize the WebAppContext in Rundeck 3.x.
To use this feature follow these steps:
(These steps apply to Rundeck 3.0.7 or later)
1. Create a java project that has the dependencies: org.rundeck:rundeck-core:3.0.7+ and org.eclipse.jetty:jetty-webapp:9.4.11.v20180605
2. Create a class that implements the `com.dtolabs.rundeck.core.init.CustomWebAppInitializer` interface
3. Put your logic that customizes the Jetty `WebAppContext` object in the `customizeWebAppContext` method. The object being supplied to this method has the type: `org.eclipse.jetty.webapp.WebAppContext` 
4. Add a file called `com.dtolabs.rundeck.core.init.CustomWebAppInitializer` in …
=> Allows custom libraries to configure Jetty WebAppContext

rundeck-storage/rundeck-storage-api/src/main/java/org/rundeck/storage/api/PathUtil.java, rundeck-storage/rundeck-storage-conf/src/main/java/org/rundeck/storage/conf/TreeStack.java, rundeck-storage/rundeck-storage-conf/src/test/groovy/org/rundeck/storage/conf/TreeStackSpecification.groovy, rundeck-storage/rundeck-storage-data/src/main/java/org/rundeck/storage/data/MemoryTree.java, rundeck-storage/rundeck-storage-data/src/test/groovy/org/rundeck/storage/data/MemoryTreeSpecification.groovy
Fix #4094 
Fix several problems related to configuration and behavior when multiple storage layers are defined.
* Key storage user interface problems due to backend issues
* Multiple folders with the same name shown
* Reading/writing key values was not storing in correct path
Example configuration:
~~~
rundeck.storage.provider.1.type=db
rundeck.storage.provider.1.path=/
#rundeck.storage.provider.1.path=/keys
rundeck.storage.provider.2.type=file
rundeck.storage.provider.2.path=/keys/extra
rundeck.storage.provider.2.config.baseDir=/tmp/rd-store-keys-extra
~~~
The behavior should be:
* anything stored under /keys/extra should read/write from filesystem
* anything …
=> Fix: problems with multiple key storage backend definitions

core/src/main/java/com/dtolabs/rundeck/core/rules/NumericCondition.java, core/src/main/java/com/dtolabs/rundeck/core/rules/NumericEqualsCondition.java, core/src/main/java/com/dtolabs/rundeck/core/rules/NumericGreaterThanCondition.java, core/src/main/java/com/dtolabs/rundeck/core/rules/NumericLessThanCondition.java, core/src/main/java/com/dtolabs/rundeck/core/rules/Rules.java, core/src/test/groovy/com/dtolabs/rundeck/core/rules/RulesSpec.groovy
Support for basic numeric integer and float Condition for ruleset.
Less than, Greater than and Equals using only the number portion.
=> Basic numeric rules condition

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
It fixes issue https://github.com/rundeck/rundeck/issues/4107
It was produced for a not-necessary code added on https://github.com/rundeck/rundeck/pull/4071, which was added to get the default options values from child jobs (using job reference). That feature already existed on the code.
I added a test for the case that the default value is a secure option with a default value (issue #4107).
=> Fixing issue #4107, NPE running job reference jobs with secure option with default values

build.gradle, docker/build.gradle, plugins/build.gradle, rundeckapp/build.gradle, rundeckapp/grails-spa/build.gradle
the rundeckapp/grails-spa build was including extraneous files (jars) in the assets dir
Update node based gradle build for grails-spa to use gradle base plugin, define archives, and update the rundeck app grails build to only copy the correct assets.
=> fix: grails-spa build, don't include extraneous assets

docker/official/README.md, docker/official/remco/templates/rundeck-config.properties
In order to use the official container image with an oauth2 proxy
Or any other authentication layer, we need to add this environment
variables to the rundeck-config.properties template, since the
entrypoint of the image overwrites the rundeck-config.properties if
mounted. Also that's for adopting a better practice.
fixes  #4142
=> Add env variables for preauthenticated mode

rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowController.groovy, rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp
1. fixing a bug when a workflow step was editing (didn't reach the dynamicProperties method)
2. if the dynamicProperties is map, display the values of the map as labels.
=> Dynamic Properties enhancement

docker/official/remco/templates/jaas-loginmodule.conf
for non-docker configuration document https://rundeck.org/docs/administration/security/authenticating-users.html#login-module-configuration , there's`roleUsernameMemberAttribute="memberUid"` in `Login module configuration`, but not found in docker. it's needed to map LDAP group to rundeck roles.
fix the Misspelled words of `module`
=> add env for LDAP auth in docker  and fix Misspelled words 

rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy
Fix error on Execution show page, if an invalid "maxlines" parameter is sent, possibly due to misconfiguration.
Use grails parameter map conversion
=> Fix execution show page error when invalid parameter was set

rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
For notification plugins, fix the issue when the plugin properties are defined at project or framework level. 
For https://github.com/rundeck/rundeck/issues/3459
=> Notification Plugin required properties not allowing project/framework defaults

rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
Rundeck issue rundeck/rundeck#3961 shows an out of date execution status being sent to Notification plugins.  I believe that this is due to the call to `Execution.get(e.id)` which refreshes the execution state from the database, however I think the end state of the execution hasn't yet been committed to the database, so the previous running state is fetched.
This passes all tests , and in my local testing addresses the issue - although I can't be sure why this was originally added.
=> Remove refresh of Execution state from database on Notification rundeck/rundeck#3961

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/server/plugins/storage/KeyStorageTree.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/server/plugins/storage/KeyStorageTreeImpl.groovy, rundeckapp/test/unit/ExecutionServiceSpec.groovy
Add validation to check if a key exists when is called from a secure option on a job. This avoids that a transaction exception be generated, and the job fails
=> Add validation to check if a key exists on secure options

rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/PluginControllerSpec.groovy
Fix: 500 error for pluginDetail ajax request is plugin is not found
=> Fix: 500 error for pluginDetail if plugin not found

.github/mergeable.yml, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/StepPluginAdapter.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapter.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/DynamicProperties.java, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
1) Fix an error when a script workflow step/node step plugin was added/edited on a job
2) Returning a map of objects on DynamicProperties interface (allows passing list or maps to the views)
=> Fixes for dynamic properties

rundeckapp/src/main/groovy/org/rundeck/jaas/jetty/JettyAuthPropertyFileLoginModule.java, rundeckapp/src/main/groovy/org/rundeck/jaas/jetty/ReloadablePropertyFileLoginModule.java, rundeckapp/src/test/groovy/org/rundeck/jaas/jetty/JettyAuthPropertyFileLoginModuleTest.groovy
Jetty PropertyUserStore has a hot reload flag, but the default Jetty property file login module doesn't set it. This PR adds a module that sets the flag when the module is initialized.
=> Fix #3452 and #3987 by adding a login module that can hot reload realm.properties

rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy, rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
Adds internal events when a project is deleted, to allow acting upon project deletion.
=> Enable internal events for project delete

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
Adding a config setting that prevents the first run message from being hidden so it remains visible.
If this setting is adding on rundeck-config, then the first run message is not hidden:
```
rundeck.startup.alwaysFirstRun=true
```
=> Disable toggle off of first run message

core/src/main/java/com/dtolabs/rundeck/core/cli/acl/AclTool.java, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/scm/ScmJobImporter.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/authorization/AuthConstants.java, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Implements #4058 
A user with `scm_update` job permission can import SCM changes over a particular job.
A user with `update` permission still can edit or import scm changes normally.
acl example:
```
context:
project: '.*'
for:
job:
-allow: [read,view,kill,scm_update]
```
=> scm_update acl special permission

docker/official/remco/templates/jaas-loginmodule.conf
This fixes #4203
Env Variables in the remco template were referenced with camelcase keys which doesn't work. They have to be lowercase. Without this fix the default value for `getv` is always used.
=> Fix camelcase keys in remco template for docker image

core/src/main/java/com/dtolabs/rundeck/core/plugins/JarPluginProviderLoader.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginMetadataValidator.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginValidation.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/ScriptPluginProviderLoader.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/ScriptPluginScanner.java, core/src/test/groovy/com/dtolabs/rundeck/core/plugins/PluginValidationSpec.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/plugins/ScriptPluginProviderLoaderTest.groovy, core/src/test/java/com/dtolabs/rundeck/core/plugins/TestJarPluginProviderLoader.java
Fix issue: ERROR log output at startup when an incompatible (target host or rundeck version) plugin is loaded using plugin version 2.0
Use INFO log level only for incompatible plugins (this level is hidden by default)
** note**
User can increase log level for plugin loading in log4j.properties:
log4j.logger.com.dtolabs.rundeck.core.plugins=INFO
=> Reduce log level of ERROR message for incompatible plugins

rundeckapp/grails-app/views/layouts/base.gsp
Adds the language param to the window._rundeck object to allow for JS localization of languages - i18n
=> adds language to window._rundeck

rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy, version.properties
The documentation URL's are being generated with the version date however the docs are setup under the short version.
Split the app version on `-` and take the first portion when generating the doc URL.
=> Strip date from doc url

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
For issue https://github.com/rundeck/rundeck/issues/4239
- Pass option references on job reference to loadSecureOptionStorageDefaults 
- New test for the use case
=> Fix: option references in key storage defaults in job reference options

rundeckapp/grails-app/views/menu/_workflowsFull.gsp
Fix #4290 
Remove `name` attribute from `actionSubmit` tag causing annoying WARN message.
=> Fix #4290 fix grails warning log message about name attribute

core/build.gradle, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/RemoteScriptNodeStepPluginAdapter.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/ScriptBasedRemoteScriptNodeStepPlugin.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/AbstractDescribableScriptPlugin.java, core/src/main/java/com/dtolabs/rundeck/plugins/step/RemoteScriptNodeStepPlugin.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/RemoteScriptNodeStepPluginAdapterSpec.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/ScriptBasedRemoteScriptNodeStepPluginSpec.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/plugins/AbstractDescribableScriptPluginSpec.groovy, core/src/test/java/com/dtolabs/rundeck/core/execution/service/TestScriptPluginFileCopier.java
Fixing an issue produced when a remote script plugin is used along with a node executor/file copier script plugin. Remote script plugin's config variables were overwritten by the node executor script plugin.
The workaround is changing context variable names for step script plugin and node executor/file copier plugin, in order to avoid the overwrite:
* step plugin will use **RD_NODESTEP_XXX** 
* node executor will use **RD_NODEEXECUTOR_XXX**
* file copier will use **RD_FILECOPIER_XXXX**
Old names variables (RD_CONFIG_XX)  will be maintained in order to not break old plugins.
=> Changing context variable names for step script 

rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Add crontab string to notification's job context as `job.schedule`. 
If the job is not scheduled, the value is an empty string.
fix #4305
=> job.schedule info on notification plugin context

rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy
Add ajax endpoint to validate plugin configs
=> Add ajax endpoint for plugin validation

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
new transaction for jos statistics, disable jobref stats using framework.properties rundeck.disable.ref.stats=true
Fix #4302 deadlock and allow disabling jobref stats 
Use `rundeck.disable.ref.stats=true` in framework.properties to disable
=> Fix #4302 deadlock and allow disabling jobref stats 

rundeckapp/grails-app/controllers/rundeck/interceptors/ControllerBaseInterceptor.groovy
an enhancement
Add a flag in order to load UI plugins on all pages (skip the while list)
A long term solution is removing the while list 
It will be enabled it using:
```
rundeck.ui.plugin.enableAllPages=true
```
=> Add new flag to enable UI plugins on all pages

packaging/common/etc/rundeck/profile
Https connections fail with `sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target` with this environment variable set. Once commented or removed they work fine. Removing this setting does not impact the Rundeck SSL configuration.
=> Remove environment variable that hijacks jvm ssl settings

grails-securityheaders/build.gradle, grails-securityheaders/gradle.properties, grails-securityheaders/grails-app/conf/application.yml, grails-securityheaders/grails-app/conf/logback.groovy, grails-securityheaders/grails-app/controllers/grails/securityheaders/UrlMappings.groovy, grails-securityheaders/grails-app/init/grails/securityheaders/Application.groovy, grails-securityheaders/grails-app/init/grails/securityheaders/BootStrap.groovy, grails-securityheaders/grails-app/views/error.gsp, grails-securityheaders/grails-app/views/index.gsp, grails-securityheaders/grails-app/views/layouts/main.gsp, grails-securityheaders/grails-app/views/notFound.gsp, grails-securityheaders/src/main/groovy/grails/securityheaders/GrailsSecurityheadersGrailsPlugin.groovy, grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/CSPSecurityHeaderProvider.groovy, grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/CustomSecurityHeaderProvider.groovy, grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/RundeckSecurityHeadersFilter.groovy, grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/SecurityHeader.groovy, grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/SecurityHeaderImpl.groovy, grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/SecurityHeaderProvider.groovy, grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/XCTOSecurityHeaderProvider.groovy, grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/XFOSecurityHeaderProvider.groovy, grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/XXSSPSecurityHeaderProvider.groovy, grails-securityheaders/src/test/groovy/org/rundeck/grails/plugins/securityheaders/CSPSecurityHeaderProviderSpec.groovy, grails-securityheaders/src/test/groovy/org/rundeck/grails/plugins/securityheaders/RundeckSecurityHeadersFilterSpec.groovy, rundeckapp/build.gradle, rundeckapp/grails-app/conf/application.yml, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, settings.gradle
Adds some default HTTP security headers to the application.
Default set of enabled security headers, and allows configuration of all headers.
* `X-Content-Type-Options: nosniff`
* `X-XSS-protection: 1`
* `X-Frame-Options: deny`
* `Content-Security-Policy` header with a default policy (and `X-Content-Security-Policy`, `X-WebKit-CSP`)
* Optional custom headers, if security policy differs or there are new requirements.
Improves web-app security against common attacks.
Modifies the src URL for the first-run external image loaded to use https://media.rundeck.org and allows access in the CSP.
The default configuration values are shown below.
~~~ .properties …
=> Add common web-app security headers

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
Fix #4179 
Handle thread interruption in job reference execution to properly abort the child job
Job ref thread was continuing until completion even if parent job was killed.
=> Fix #4179 kill job reference thread when parent is killed

docker/official/remco/templates/rundeck-config-storage.properties, docker/official/test/remco/test.yml
Makes it possible to change project storage type in the Docker container through the template system.
fixes #4445
=> Docker - Fix key for project storage type

core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/EngineWorkflowExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/NodeFirstWorkflowExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/rules/StateLogger.java, core/src/main/java/com/dtolabs/rundeck/core/rules/WorkflowEngine.java, core/src/main/java/com/dtolabs/rundeck/core/rules/Workflows.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/EngineWorkflowExecutorSpec.groovy
Fix #3443 
Avoid a race condition, and ensure EngineWorkflowExecutor is thread safe
=> Fix race condition/workflow state bug

core/src/main/java/com/dtolabs/rundeck/core/execution/dispatch/OrchestratorNodeDispatcher.java, core/src/main/java/com/dtolabs/rundeck/core/execution/dispatch/OrchestratorNodeProcessor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/NodeFirstWorkflowExecutor.java
Minor cleanup:
* orchestrator node dispatcher should capture and log any errors during node dispatch
* reduced debug verbosity
=> Cleanup: orchestrator node processor logging

rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy, rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy, rundeckapp/src/test/groovy/ProjectServiceTests.groovy, rundeckapp/src/test/groovy/rundeck/services/ExecutionUtilServiceTests.groovy
fix #4414 
Adds the full job in the current state to the execution XML exported. So, if you go through the files in alphabetical order you can get a list of job's definition to recreate them.
=> Job detail in execution xml for log storage

rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/grails-app/views/execution/mailNotification/status.gsp
This is a bug using mssql database, described here: https://github.com/rundeck/rundeck/issues/4458
For now we will disable the jobStats on the email notification view.
Move the queries outside the view, but they are blocked anyway
Rundeck using MSSQL as external database, and running a simple job with a email notification using the default view template.
=> Disable JobStats because it produces a deadlock on mssql.

core/src/main/java/org/rundeck/core/projects/ProjectConfigurable.java, rundeckapp/grails-app/services/rundeck/controllers/MenuService.groovy, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/grails-app/services/rundeck/services/NodeService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
rename to ProjectConfigurable
Move the project configurable interface to core for use by other modules
=> Refactor: move project configurable interface to core

core/src/main/java/com/dtolabs/rundeck/core/authorization/Authorization.java, core/src/main/java/com/dtolabs/rundeck/core/authorization/MultiAuthorization.java, core/src/main/java/com/dtolabs/rundeck/core/authorization/RuleEvaluator.java, core/src/test/groovy/com/dtolabs/rundeck/core/authorization/RuleEvaluatorSpec.groovy
Configurable audit.log granularity:
`warn` log level on unauthorized validations. 
To log only the unauthorized validations you can edit the log4.properties file and modify the line:
`log4j.logger.com.dtolabs.rundeck.core.authorization=info, audit`
to 
`log4j.logger.com.dtolabs.rundeck.core.authorization=warn, audit`
Log on multi evaluation (system and project validation) the log is moved upper level to log on warn level only if any validation is unauthorized.
Fix #4435
=> Improvement for audit.log file size

rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
Enhancement: https://github.com/rundeck/rundeck/issues/4443
Adding an empty string to ${logoutput.data} context variable when that variable is set on the template, and the flag attachLogInline is false.
For issue https://github.com/rundeck/rundeck/issues/4443
=> Notification email template with log output: use blank when not included

rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/WorkflowControllerSpec.groovy, test/api/test-jobs-import-jobref-renamed.sh, test/selenium/__image_snapshots__/create-test-ts-job-has-not-visually-regressed-1-snap.png, test/selenium/docker-compose.yml, test/selenium/docker-local-compose.yml, test/selenium/package.json
Job reference step using UUID and job name pointing to a job that doesn't exist won't fail it will only remove the `UUID` component and leave just the `jobname` reference.
Fix #4451 and 4471
=> removed UUID validation of jobRef

rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy, rundeckapp/grails-app/domain/rundeck/ScheduledExecutionStats.groovy, rundeckapp/grails-app/services/rundeck/services/ApiService.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/views/execution/show.gsp, rundeckapp/grails-app/views/menu/_runningExecutions.gsp, rundeckapp/grails-app/views/scheduledExecution/_show.gsp, rundeckapp/grails-app/views/scheduledExecution/_showStats.gsp, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerTests.groovy, rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy, test/api/include.sh, test/api/test-job-run-without-deadlock.sh, test/docker/dockers/rundeck/scripts/start_rundeck.sh
New domain table `ScheduledExecutionStats` to use instead of `ScheduledExecution` on statistics.
The objective of this change is to reduce the direct use of the `ScheduledExecution` table at updating or consulting the average time statistics.
Reduces the appearance of deadlocks by updating the statistics in the referenced jobs.
Docker test included to detect the appearance of deadlocks on parallel usage of the table:
`test/api/test-job-run-without-deadlock.sh`
New jobs will be created with a field on the `ScheduledExecutionStats` table and existing fields will be migrated in usage or retrieve of the data.
=> New scheduled execution stats table 

rundeckapp/grails-app/conf/application.yml
The introduction of CSP headers in #4405 has caused a situation where loading images, among other things, from different sources requires updating the header configs. For users with custom images in their README and MOTD markdowns, as well as our Tour functionality, this has resulted in *surprising* behavior. 
I have allowed images to be loaded from any source by default. This is a low risk default and will prevent surprises and constant updating of defaults on new releases..
I considered disabling CSP headers by default to revert all behavior. The downside to this is that `form-action: self` is a very good default as it effectively breaks …
=> Allow loading images from any source

rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy, rundeckapp/src/test/groovy/rundeck/services/PluginApiServiceSpec.groovy
Fix: string rendering constant enums should be converted to strings
=> Fix: ajax plugin rendering option response values

core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/PluginAdapterUtility.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/PropertyUtil.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/Validator.java, core/src/test/groovy/com/dtolabs/rundeck/core/plugins/configuration/PluginAdapterUtilitySpec.groovy
Updates behavior of Options plugin property type
* allow List,Set,String[] input values
* only enforce allowed values if not null
This enables a `List<String>` property option which doesn't have a predefined allowed values set, so any values can be used.
=> Update Options property type behavior

rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
Fix #4497 appending to output stream fails on Tomcat 7 without compile static annotation.
=> Fix #4497 appending to output stream fails on Tomcat 7 

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
Fix stacktrace on menu controller caused by typo. Made call more efficient.
=> Fix stacktrace on menu controller caused by typo. 

rundeckapp/grails-app/views/execution/_showFragment.gsp
Links for downloading job logs now set the target attribute so they don't
replace the main window when clicked, allowing for smoother user experience.
=> Links for downloading job logs now set the target attribute

core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/WorkflowExecutionService.java, core/src/main/java/com/dtolabs/rundeck/plugins/CorePluginProviderServices.java, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/grails-app/services/rundeck/services/PluginService.groovy
Update plugin infrastructure to return plugin information correctly to UIPluginService.
=> Fixes spurious plugin not found messages

.travis.yml, rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ControllerBase.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/StorageController.groovy, rundeckapp/grails-app/services/rundeck/services/ApiService.groovy, test/docker/dockers/tomcat/Dockerfile, test/docker/test-api-tomcat.sh, test/run-docker-tomcat-tests.sh
Adds tomcat 7 API tests and updates Rundeck to achieve passing results.
=> Add tomcat 7 tests

docker/official/README.md, docker/official/remco/resources.d/rundeck-config-mail.properties.toml, docker/official/remco/templates/rundeck-config-mail.properties, docker/official/test/remco/test.yml
Fixes #4539 
Enhancement to add basic SMTP/Email settings into the Docker config templates.
I had considered placing the keys under `/rundeck/grails/mail`. After a lot of back-and-forth with myself I opted to drop `grails` from that path and hide it as an implementation detail.
=> Add basic smtp/email settings to stock Docker config

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
This changes allow context access ${job.user.email}, i.e. the email address of the user profile can be passed into the workflow step.
=> Make email of user profile accessible on context #4212

rundeckapp/grails-app/controllers/rundeck/interceptors/ControllerBaseInterceptor.groovy
- Enabling ui plugins on all pages by default
- fixing an issue that produces the following pages were not considerate for loading UI plugins:  Key Storage , Log Storage , Password Utility , User Summary
by default, all pages loads UI plugins
=> Enabling ui plugins on all pages by default

rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
A wrong merge on 'imports' on FrameworkController caused an error because there are two classes with the same name (NodeFilter). A java class (core) and another groovy class (rundeckapp). This allowed the project to be compiled but obviously caused a bug
=> Fixing errors caused by a wrong merge

rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/logging/RenderDatatypeFilterPlugin.groovy
enhancement
Adding a flag on the Render Formatted Data filter to display the table with table-striped style
(zebra-striping to any table row)
passing extra CSS metadata to the HTMLTableViewConverter Plugin 
=> Adding a flag on the Render Formatted Data filter to add table-striped style

README.md
`rundeck-launcher.jar` no longer exists, so update the README to indicate we can launch directly from the `.war` file now.
=> Update README for spring boot launch

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Fixes #4459 
This builds off the work @jtobard completed in #4641.
During testing against MySQL with low `wait_timeout` I was still getting errors about the underlying connection being dead after the job finishes. This was strange as I could not see a running transaction in `show engine innodb status`.
**MySQL**
```
SET GLOBAL wait_timeout=15
```
**Rundeck**
```
dataSource.properties.validationInterval=5000
dataSource.properties.testOnBorrow=true
dataSource.properties.testWhileIdle=true
dataSource.properties.testOnReturn=true
dataSource.properties.timeBetweenEvictionRunsMillis=5000
```
Running `show full processlist` would display something like the following:
```
mysql> show full processlist;
+-----+---------+------------------+---------+---------+------+----------+----------------------- …
```
=> Stop holding DB connections during job execution

rundeckapp/grails-app/assets/javascripts/optionEditKO.js, rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
Fixes #3136 by switching to knockout event handlers to control the visibility of the regex field.
=> Switch edit regex field visibility to knockout handler

rundeckapp/grails-app/views/framework/_jobOptionsKO.gsp
Fixes #3951 
I'm pretty sure that we always want to display the label onscreen instead of `name`. `label` falls back to `name` anyway if unset.
=> Display label instead of name for remote options

rundeckapp/grails-app/views/framework/_nodesEmbedKO.gsp
Popover needed to be assigned a container - in this case the body element - in order to handle proper z-index over other elements.
=> Adds data-container = body to popover handler

rundeckapp/grails-app/views/common/_sidebar.gsp, rundeckapp/grails-app/views/layouts/base.gsp
Adds config check to disable Community News. Link persists. If user clicks on Community News, new tab is opened and page navigates to rundeck.com/community-updates
=> Adds check for disabled flag for Community News

rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, test/api/test-job-long-run.sh, test/docker/dockers/rundeck/scripts/start_rundeck.sh
Fixes #4677
Moves entity access into explicit transactions to prevent a hibernate session/connection from being opened and going stale during the command execution.
=> Avoid holding db connection during job runs

docker/official/Dockerfile, docker/ubuntu-base/Dockerfile
Fixes #4402
* Adds [tini](https://github.com/krallin/tini) to the entrypoint to serve as pid 1
* Update [remco](https://github.com/HeavyHorst/remco) to latest release
=> Implement tini as pid 1 to reap processes

core/src/main/java/com/dtolabs/rundeck/core/plugins/JarPluginProviderLoader.java
Add sane defaults for java plugins that do not provide name or version information in their metadata.
=> Default java plugin metadata

core/src/main/java/com/dtolabs/rundeck/core/plugins/JarPluginProviderLoader.java
For java plugins that don't set a plugin name in the manifest attributes, fallback to generate the id off of the plugin class names attribute which is less likely to change than the jar file name.
=> Update the way a plugin id is generated for java plugins.

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
fixing issue https://github.com/rundeck/rundeck/issues/4639
When failed set of nodes are not part original filter (for example when the original filter is overwritten), the failed nodes will be merged with the original node list filter result.
=> Retry Failed Nodes doesn't bring in failed nodes if Change the Target Nodes option was used

rundeckapp/grails-spa/src/pages/project-nodes-config/ProjectNodeSourcesConfig.vue, rundeckapp/grails-spa/src/pages/project-nodes-config/ProjectPluginConfig.vue, rundeckapp/grails-spa/src/pages/project-nodes-config/WriteableProjectNodeSources.vue
Fixes client js error if multiple POST requests made using different Vue components
=> Use shared UI client to maintain synchronizer tokens

plugins/flow-control-plugin/build.gradle, plugins/flow-control-plugin/src/main/java/org/rundeck/plugin/flowcontrol/FlowControlWorkflowStep.java, plugins/flow-control-plugin/src/test/groovy/org/rundeck/plugin/flowcontrol/FlowControlWorkflowStepSpec.groovy
`FlowControl.java` interface defines the Halt method:
`public void Halt(boolean success);`
Currently `FlowControlWorkflowStep` plugin passes `fail` boolean instead of success, to fix this the plugin should call `Halt(!fail)`.
Unit test added to ensure the correct use of `halt` and `fail` properties.
=> Flow Control fail flag right behavior

rundeckapp/grails-app/services/rundeck/services/ScmService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
ScmService `removePluginConfiguration` doesn't overwrite the same file that erases immediately.
fix #4623
=> Fix problem deleting SCM configured project.

docker/official/remco/templates/rundeck-config.properties
Setting server.session.timeout for the docker image doesn't work, because it's not included in the remco template. This PR resolves that.
=> Add server.session.timeout to docker remco template

rundeckapp/build.gradle
New version of python winrm plugin
https://github.com/rundeck-plugins/py-winrm-plugin/releases/tag/2.0.1
- better debug log
- fix for https://github.com/rundeck-plugins/py-winrm-plugin/issues/24
- compatibility for python3
- compatibility to use the plugin on a windows box
- new flag to disable TLS1.2 protocol (to connect to windows 2008 servers)
=> new version of python winrm plugin

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Fix for https://github.com/rundeck/rundeck/issues/4699
Adding the exclude filter when the execution and the execution context are created.
The exclude filter was just considered when the nodes are selected on the Run Now page.
=> Fix: job exclude filter doesn't work for scheduled jobs

docker/official/README.md
Adds information and a reference to the Docker Zoo related to extending the configuration of the stock Docker images.
=> Add docker configuration extension information

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/views/framework/_jobOptionsKO.gsp
Fixes #4622. Multi-valued option now works with option values plugins.
=> Fixes #4622. Multi-valued option now works with option values plugins.

rundeckapp/grails-spa/src/components/community-news-notification/App.vue
"results is not defined"
Fix JS console error:
Uncaught (in promise) ReferenceError: results is not defined
at App.vue:36
=> Fix js console error

rundeckapp/grails-spa/package-lock.json, rundeckapp/grails-spa/package.json, rundeckapp/grails-spa/src/pages/repository/App.vue, rundeckapp/grails-spa/src/pages/repository/PluginCard.vue, rundeckapp/grails-spa/src/pages/repository/Repository.vue, rundeckapp/grails-spa/src/pages/repository/main.js
* Adds the search feature to Repos. Current sensitivity set to .2 (0 to 1, 1 being least sensitive) as requested. Searches only "display" or "name" properties.
* Adds "docsLink" link to plugin card footer for Private Repos. "docsLink" must be present as a property for the private repo->plugin in order for this to display.
=> Working Search, DocsLink for Private Repos

rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy, rundeckapp/src/test/groovy/ProjectServiceTests.groovy, rundeckapp/src/test/groovy/rundeck/services/ExecutionUtilServiceTests.groovy
flag renamed to `rundeck.execution.logs.fileStorage.generateExecutionXml`. 
Execution file changed to `{id}.execution.xml`.
fix #4744
=> Rename flag for execution xml for log storage

core/src/main/java/com/dtolabs/rundeck/core/resources/FileResourceModelSource.java
Update description for `format` property of File node source plugin, to clarify that the file extension will be used if the format is not specified.
=> File node source: clarify use of file extension for format

rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
Fix #4786 
handle null return value
=> Fix #4786 page error for missing plugin

rundeckapp/grails-app/assets/javascripts/application.js, rundeckapp/grails-app/assets/javascripts/ko/handler-bootstrapPopover.js, rundeckapp/grails-app/views/framework/_nodeDetailsSimpleKO.gsp, rundeckapp/grails-app/views/framework/_nodesEmbedKO.gsp
* add knockout dom disposal callback
* constrain popup viewport to main-panel
* add mousedown handler to close popup for event outside of popup
* create unique id for interactive elements in referenced html content when copied to popup
Fix #4703
=> Fix #4703 node detail popup cannot be dismissed

.travis.yml, scripts/travis-build.sh, scripts/travis-helpers.sh
Disables rpm and deb building/publishing in favor of the `packaging-core` project build.
=> Use packaging project for deb and rpm builds

docker/official/Dockerfile
This simplifies downstream builds; they do not need to create and adjust the permissions on this folder before copying plugins in.
=> Create libext dir in base Docker image

core/src/main/resources/com/dtolabs/launcher/setup/templates/server-log4j.properties.template, docker/official/remco/templates/log4j.properties, grails-persistlocale/grails-app/conf/logback.groovy, grails-securityheaders/grails-app/conf/logback.groovy, packaging/common/etc/rundeck/log4j.properties, rundeckapp/grails-app/conf/logback.groovy, rundeckapp/metricsweb/grails-app/conf/logback.groovy, rundeckapp/repository/grails-app/conf/logback.groovy, rundeckapp/src/main/resources/config-defaults.properties, rundeckapp/templates/config/log4j.properties.template
Purpose of this PR is to open a discussion about log formatting consistency.
For stream processing of log output that is not structured(json, xml, etc) it is handy to have a consistently formatted logging prefix to help with routing and parsing. Typical docker/container based deployments may send all logging output to stdout to be picked up and sent through a log processing system(fluentd, cloud watch logs, etc). This is a little bit different than writing, reading, and parsing separate log files where extra context can then be added. Structured logging would be preferred.
These changes propose a common prefix of:  
`[<ISO8601>] <logger.name> <level>`
Level and name could be swapped, however it appears some output currently does not include the level. We could add it.
Here is the PR …
=> Consistent logging prefix.

core/src/main/java/com/dtolabs/rundeck/core/authorization/AclRule.java, core/src/main/java/com/dtolabs/rundeck/core/authorization/AclRuleBuilder.java, core/src/main/java/com/dtolabs/rundeck/core/authorization/AclRuleImpl.java, core/src/main/java/com/dtolabs/rundeck/core/authorization/RuleEvaluator.java, core/src/main/java/com/dtolabs/rundeck/core/authorization/providers/Policy.java, core/src/main/java/com/dtolabs/rundeck/core/authorization/providers/YamlParsePolicy.java, core/src/main/java/com/dtolabs/rundeck/core/authorization/providers/yaml/model/ACLPolicyDoc.java, core/src/main/java/com/dtolabs/rundeck/core/authorization/providers/yaml/model/YamlPolicyDocConstructor.java, core/src/test/groovy/com/dtolabs/rundeck/core/authorization/RuleEvaluatorSpec.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/authorization/providers/YamlProviderSpec.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
A new ACL policy that applies to all users who are not in the specified group or username (including regular expression).
The new syntax replaces `by:` for `notBy:`
As an example:
```
notBy:
username: dev
description: run-job
for:
job:
- allow:
- run
equals:
name: cleanTempFolders
context:
project: example
```
Everyone that is not the user `dev` can run a job called `cleanTempFolders` in the project `example`
fix #3810
=> Enhance ACL policies to enable access rules that apply to users not in a group or not by username.

rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
Fix #4765. Add ability to require a role in order for user to log in.
=> Fix #4765. Add ability to require a role in order for user to log in.

docker/official/README.md, docker/official/remco/templates/rundeck-config.properties
Fixes #4774
Adds the ability to set the context path through the environment variable `RUNDECK_SERVER_CONTEXTPATH`.
=> [Docker] Add template option for setting contextPath

rundeckapp/grails-app/i18n/messages_pt_BR.properties
The Welcome Page is not showing correctly when using Brazilian Portuguese locale.
Apparently something messed with markdown formatting (I also adjusted spaces and identation to match english locale).
This is how the Welcome Page currently looks while using Brazilian Portuguese locale:
=> Adjusting Welcome Page for PT_BR locale

core/src/main/java/com/dtolabs/rundeck/core/data/SharedDataContextUtils.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/StepPluginAdapter.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapter.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/PluginAdapterUtility.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/Property.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/PropertyBase.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/PropertyUtil.java, core/src/main/java/com/dtolabs/rundeck/plugins/descriptions/ReplaceDataVariablesWithBlanks.java, core/src/main/java/com/dtolabs/rundeck/plugins/util/PropertyBuilder.java, core/src/test/groovy/com/dtolabs/rundeck/core/dispatcher/SharedDataContextUtilsSpec.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapterSpec.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/plugins/configuration/PluginAdapterUtilitySpec.groovy, core/src/test/java/com/dtolabs/rundeck/plugins/util/PropertyBuilderTest.java, rundeckapp/src/test/groovy/rundeck/services/UserServiceSpec.groovy
Allow node step and workflow step java plugins to disable the substitution of a blank string if the variable is not found in the context.
This lets step plugins allow user scripts to contain bash array specifiers and other script structures that use the '${}' control characters to specify variables.
=> Allow control of property variable blank substitution

rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy, rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
A fix for Fixing https://github.com/rundeck/rundeck/issues/4895.
Passing the right context values to the average notification
=> Average notification didnt pass the execution context

docker/official/README.md, docker/official/remco/templates/rundeck-config.properties
This PR makes it possible to set the value of rundeck.api.tokens.duration.max in rundeck-config.properties for the official docker image
Also I added a hint in the readme about the availability of configuration variables.
=> Docker add rundeck.api.tokens.duration.max to remco template

rundeckapp/grails-app/assets/javascripts/executionControl.js, rundeckapp/grails-app/assets/javascripts/menu/jobs.js, rundeckapp/grails-app/assets/javascripts/scheduledExecution/jobRunFormOptionsKO.js, rundeckapp/grails-app/assets/scss/custom/jobs.scss, rundeckapp/grails-app/assets/scss/custom/text.scss, rundeckapp/grails-app/assets/scss/paper/_variables.scss, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_ja.properties, rundeckapp/grails-app/i18n/messages_pt_BR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/views/common/_expander.gsp, rundeckapp/grails-app/views/menu/_groupTree.gsp, rundeckapp/grails-app/views/menu/_jobslist.gsp, rundeckapp/grails-app/views/menu/_workflowsFull.gsp, rundeckapp/grails-app/views/scheduledExecution/_edit.gsp, rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp, rundeckapp/grails-app/views/scheduledExecution/_execOptionsFormButtons.gsp
=> UI updates 3.1: Part H

rundeckapp/grails-spa/build.gradle
Replace https://github.com/rundeck/rundeck/pull/3978
Node can be installed by gradle by using the `-Pnode.install` property:
./gradlew -Pnode.install=9.2.0 build
If that property is not used, an existing node install is used
=> Fix: rundeck build without existing nodejs install

rundeckapp/grails-app/assets/javascripts/menu/job-remote-options.js
Fix: js error loading remote option values
(prototype js was removed)
=> Fix: js error when loading remote option values

docker/official/README.md, docker/official/lib/entry.sh
Fixes #4904 
Adds two environment variables for controlling environment variable unsets:
* `RUNDECK_ENVARS_UNSETALL` Defaults to `true` and unsets all envars starting with `RUNDECK_` before starting Rundeck.
* `RUNDECK_ENVARS_UNSETS` Can be used to explicitly unset environment variables before starting Rundeck.
=> [Docker] unset envars before starting Rundeck

rundeckapp/grails-app/services/rundeck/services/UserService.groovy, rundeckapp/src/test/groovy/rundeck/services/UserServiceSpec.groovy
Fix issue where a mis-configured user group source plugin would emit an NPE.
(cherry picked from commit 16b74bed50fa6db9d95eacc25ca3fdd5e1af9f8f)
=> Fix issue where a mis-configured user group source plugin would emit an NPE.

rundeckapp/grails-app/assets/javascripts/framework/editProject.js, rundeckapp/grails-app/assets/javascripts/jobEditPage_bundle.js, rundeckapp/grails-app/assets/javascripts/plugins/pluginMetadata.js, rundeckapp/grails-app/assets/javascripts/workflowStepEditorKO.js, rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_ja.properties, rundeckapp/grails-app/i18n/messages_pt_BR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/views/framework/_createProjectForm.gsp, rundeckapp/grails-app/views/framework/_editProjectForm.gsp, rundeckapp/grails-app/views/framework/_editProjectFormTabs.gsp, rundeckapp/grails-app/views/framework/editProject.gsp, rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerTest.groovy
Refactor project config/create form to use tabs instead of a long form
Replace the default Node Executor/File Copier selection UI so it doesn't use radio buttons
=> 3.1: UI: project config form tabs

rundeckapp/grails-app/views/layouts/base.gsp
=> [3.0.x backport] fix: js console error 404 "manifest.js" #4873

rundeckapp/grails-app/conf/BuildConfig.groovy
2.11: upgrade commons-fileupload to 1.3.3
=> [2.11.x] Update commons-fileupload dep to 1.3.3

rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
Instead of logging full stacktrace, just log the error message if a job is already running when the scheduler tries to execute it
=> fix: don't log full stacktrace for "already being executed" conflict

rundeckapp/grails-app/views/scheduledExecution/_editOptions.gsp, rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
fix regression caused by 163dfac03c3eff77240a6c3128e0446fd7dae1c2
=> Fix: run job with no options causes error

rundeckapp/grails-app/views/framework/_editProjectForm.gsp
=> fix #4958 file copier form always show defaults

rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
problem: Project config page shows an error with an empty list if Default Node Executor/File Copier plugin validation fails.
=> Fix empty error when node exec validation fails

rundeckapp/grails-app/assets/javascripts/menu/home.js
Fix #4149 
Update jquery Waypoint usage to set correct scroll context
=> Fix home page project ui not loading #4149

rundeckapp/src/test/groovy/org/rundeck/jaas/jetty/ReloadablePropertyFileLoginModuleSpec.groovy
The removed test wasn't highly valuable, and was not very reliable.
=> Remove unreliable test on ReloadablePropertyFileLoginModule.

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/utils/OptionsUtil.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Changes to load options from remote URL to validate and fail when a parent job passes a non-allowed value to job
=> Changes to fix #4847 - Option enforced with allowed values from remote url was not validating

rundeckapp/grails-app/views/scheduledExecution/_jobActionButton.gsp, rundeckapp/grails-app/views/scheduledExecution/_uploadForm.gsp
=> Fix: job delete "delete all executions" checkbox, and some form control labels don't work

rundeckapp/grails-app/views/framework/projectNodeSources.gsp, rundeckapp/grails-spa/src/pages/project-nodes-config/ProjectNodeSourcesConfig.vue, rundeckapp/grails-spa/src/pages/project-nodes-config/ProjectPluginConfig.vue, rundeckapp/grails-spa/src/pages/project-nodes-config/main.js
Adds a Cancel button to the PluginConfig UI in Project Nodes Config.
=> Adds "Cancel" button to UI

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceIntegrationSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Currently, the takeover endpoint allows specifying only one job id or leave it empty for every job.
With this enhancement, using API v31 or greater you can specify multiple job ids using the same endpoint.
ENDPOINT: `/api/31/scheduler/takeover`
application/json 
``` 
{
"server": {
"all": true
},
"jobs":[
{
"id": "15f66e9e-4034-4eb4-9fb7-4d4a739f691b"
},
{
"id": "e4b6fdeb-85dd-4080-b723-1571ca3e1097"
}
]
}
```
application/xml
```
<takeoverSchedule>
<server all="true"/>
<job id="15f66e9e-4034-4eb4-9fb7-4d4a739f691b"/>
<job id="e4b6fdeb-85dd-4080-b723-1571ca3e1097"/>
</takeoverSchedule>
```
fix #4725
=> Add multiple jobs ids to scheduler/takeover endpoint

rundeckapp/grails-app/assets/javascripts/jobedit.js, rundeckapp/grails-app/assets/javascripts/scheduledExecution/jobEditorKO.js, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_ja.properties, rundeckapp/grails-app/i18n/messages_pt_BR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/views/execution/_wfitemEdit.gsp, rundeckapp/grails-app/views/scheduledExecution/_createForm.gsp, rundeckapp/grails-app/views/scheduledExecution/_edit.gsp, rundeckapp/grails-app/views/scheduledExecution/_editForm.gsp, rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp, rundeckapp/grails-app/views/scheduledExecution/_tabsEdit.gsp
Fixes #5000 
When a job Option or workflow Step edit panel is open and the create/save button is clicked, this adds a warning indicator the the Workflow tab, adds warning text by the form submit button, and highlights the unsaved job Option or workflow Step section inside the workflow tab.
=> Fix #5000 highlight workflow editor unsaved changes issues

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/views/menu/systemConfig.gsp
If the data source is configured using JNDI show that information instead of a default h2 URL.
fix #5010
Screenshot:
=> JNDI info in the configuration page #5010

core/src/main/java/com/dtolabs/rundeck/core/rules/StateWorkflowSystem.java, core/src/main/java/com/dtolabs/rundeck/core/rules/WorkflowEngine.java, core/src/main/java/com/dtolabs/rundeck/core/rules/WorkflowEngineOperationsProcessor.java, core/src/main/java/com/dtolabs/rundeck/core/rules/WorkflowSystemEventHandler.java, core/src/test/groovy/com/dtolabs/rundeck/core/rules/WorkflowEngineOperationsProcessorSpec.groovy
Fixes #5023
prevent race condition around checking if no more changes to wf engine state are available
=> Fix #5023 race condition bug in wf engine

rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerTests.groovy
Issue: https://github.com/rundeckpro/rundeckpro/issues/606
This PR creates a new API endpoing ``/api/V/system/executions/status`` which returns the current
execution mode using the same response format as ``/api/V/system/executions/active`` and ``/api/V/system/executions/passive``.
Additionally, the endpoint will respond with a HTTP status of ``503 - Service Unavailable`` when the current status is **passive**.
=> Execution mode status API with failing code when status is passive.

docker/official/remco/templates/rundeck-config.properties
Required for proper Oracle backend support, as https://docs.rundeck.com/docs/administration/configuration/database/oracle.html
=> Add validationQuery parameter

rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy, rundeckapp/src/test/groovy/JobsXMLCodecTests.groovy
Fixes issue with #4959 where dayofmonth is not null, it is `?`, but it sets dayofweek to also be `?`.
It simply looks if dayofmonth is set to `?`. If it is, then it goes to the next if.
=> Added test and extra if conditional to fix #4959

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
fix #4985 
For those strange cases in which you need to check when a job should have run.
This is a new parameter for the endpoint:
```
GET /api/31/job/[ID]/forecast
```
Adding the parameter `past=true` will return an inverse forecast, that is, considering the current scheduler, when it should have run.
This forecast is only referential, since it will not take into account if the job could have been disabled or not yet been created.
A couple of people in the community channels requested this functionality as a nice to have for administration purpose.
=> Small improvement to the API forecast

core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschNodeExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschScpFileCopier.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/NodeSSHConnectionInfo.java, core/src/main/java/com/dtolabs/rundeck/core/tasks/net/BindAddressSocketFactory.java, core/src/main/java/com/dtolabs/rundeck/core/tasks/net/ExtSSHExec.java, core/src/main/java/com/dtolabs/rundeck/core/tasks/net/ExtScp.java, core/src/main/java/com/dtolabs/rundeck/core/tasks/net/SSHTaskBuilder.java, core/src/test/groovy/com/dtolabs/rundeck/core/tasks/net/SSHTaskBuilderSpec.groovy, core/src/test/java/com/dtolabs/rundeck/core/tasks/net/TestSSHTaskBuilder.java
enhancement: adding bind address to jsch plugin 
for https://github.com/rundeck/rundeck/issues/4932
Adding a socket factory with the bind address. The variable is added to the plugin settings
=> adding bind address to jsch

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Bug:
reverting changes to allow schedule jobs to respect the remote policy execution if exists
https://github.com/rundeck/rundeck/pull/4799
Jobs scheduled can be removed from quartz, so the scheduled job won't be executed on any cluster member
the severNodeUUID cannot be changed, it just can be done when the job is saved.
=> reverting changes to allow schedule jobs to respect the remote policy

docker/official/remco/templates/jaas-loginmodule.conf, docker/official/remco/templates/rundeck-config.properties
enhancement: exposing sync Rundeck profile from LDAP user attributes for official docker image.
Adding the following environment variables:
* RUNDECK_JAAS_LDAP_USERLASTNAMEATTRIBUTE
* RUNDECK_JAAS_LDAP_USERFIRSTNAMEATTRIBUTE
* RUNDECK_JAAS_LDAP_USEREMAILATTRIBUTE
* RUNDECK_SECURITY_SYNCLDAPUSER
Example:
=> Sync Rundeck profile from LDAP user attributes for official docker image

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/test/unit/ExecutionServiceSpec.groovy
=> [Backport 4071] Fix Multi-value option delimiter variable not available within a Job Reference

docker/official/lib/entry.sh, docker/official/remco/resources.d/artifact-repositories-private.yaml.toml, docker/official/remco/resources.d/rundeck-config-plugin-repository.properties.toml, docker/official/remco/templates/artifact-repositories-private.yaml, docker/official/remco/templates/rundeck-config-plugin-repository.properties
enhancement:
adding custom templates for plugin repository feature. it will expose using env variable the option to define an external or local plugin repository (for example using the s3 like storage)
new remco templates to add data to artifact-repositories.yaml and rundeck-config.properties based on env variables.
Example of new variables
```
version: '3'
services:
rundeck1:
hostname: rundeck1
image: ${RUNDECK_IMAGE:-rundeck/rundeck:local}
links:
- minio
tty: true
environment:
RUNDECK_GRAILS_URL: http://localhost:4444
RUNDECK_FEATURE_REPOSITORY_ENABLE: "true"
RUNDECK_FEATURE_REPOSITORY_SYNCONBOOTSTRAP: "true"
RUNDECK_REPOSITORY_ARTIFACTS_PROVIDER_1_NAME: …
```
=> oficial docke image: adding custom templates for repository feature.

rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/PluginControllerSpec.groovy
Remove unused project param in plugin validation method so plugins can be validated outside a project context.
This change will allow the pluginConfig component in ui-trellis to be used outside of project contexts.
=> Remove unused project param in plugin validation method 

rundeckapp/grails-app/domain/rundeck/Workflow.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionTest.groovy, rundeckapp/src/test/groovy/rundeck/ScheduledExecutionTest.groovy
Inserting the relationship attribute "belongsTo" for workflow class, so that the workflow record is deleted when an execution is deleted
Records in Workflow, workflow_step and workflow_workflow_step do not get cleaned up when executions are deleted causing orphaned records to remain in the tables
inserting the relationship attribute "belongsTo" on Workflow class, so that the workflow record is deleted when an execution is deleted
=> Fixes #1654 to make cleanup on records in Workflow, workflow_step and workflow_workflow_step when executions are deleted

core/src/main/java/com/dtolabs/rundeck/core/schedule/JobScheduleManager.java, rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionsCleanUp.groovy, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/grails-app/services/rundeck/services/JobSchedulerService.groovy, rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionsCleanUpTest.groovy, rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionsCleanUpSpec.groovy
Enhancement:
On a cluster environment where the serverNodeUUID of the cluster members normally changed (on docker o kubernetes env), the execution cleanup process doesn't work as expected. The main reason is each cluster member will try to remove its own executions (filtering by serverNodeUUID).
1.- A new method to get the list of dead members is added. Each active node will have a different list of dead members in order to not get the same list of executions to delete.
2.- if that list is not empty, then the execution query will search for those uuids (plus the uuid of the server).
3.- the list of dead member can include the "null" option. In this case, it will remove execution with the …
=> Execution cleanup on a cluster

rundeckapp/grails-app/assets/javascripts/user/profile.js, rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/taglib/rundeck/BootstrapTagLib.groovy, rundeckapp/grails-app/views/common/_js.gsp, rundeckapp/grails-app/views/user/_token.gsp, rundeckapp/grails-app/views/user/_tokenList.gsp, rundeckapp/grails-app/views/user/_user.gsp, rundeckapp/grails-app/views/user/profile.gsp
This PR adds pagination to the token section of the user profile page, in order to support a high amount of tokens.
The main changes on this PR are:
- Added a gsp-based pagination which will appear when the amount of tokens exceeds 50.
- Page limit can be configured using the rundeck.gui.user.profile.paginatetoken.max.per.page key.
- Depending on the paging conditions and amount of tokens, tokens will be added/deleted either via ajax or by reloading the page.
- Added a new pagination taglib in order to support gsp pagination using bootstrap markup.
For further details see https://github.com/rundeck/rundeck/pull/4990
Fixes issue https://github.com/rundeck/rundeck/issues/4831
=> Backport PR #4990 - Adds pagination of tokens on user profile

rundeckapp/build.gradle, testbuild.groovy
fixes rundeckpro/rundeckpro#607 
When a node have the osFamily attribute with value "Windows", the job with an inline script step dispatch a .bat file even though this node needs to run a .sh file (using cygwin)
This plugin (https://github.com/rundeck-plugins/attribute-match-node-enhancer) can be used to solve this issue (https://github.com/rundeckpro/rundeckpro/issues/607) from support that causes the osFamily attribute do define the file extension to be dispatched to a node 
I considered to use the advanced settings on script step the override the file extension default, however, this is not a friendly solution when it comes to several jobs …
=> Adding attribute-match-node-enhancer plugin to the rundeck oss core

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/views/menu/jobs.gsp, rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Change the ajax call to `scmjobs` endpoint. Pass the data through the body of the ajax call instead of the URL to prevent 'URI is too large' problem.
fix #4998
=> Change in the async call for SCM gui #4998

rundeckapp/grails-app/conf/spring/resources.groovy
EnhancedNodeService bean was not being loaded then the node enhancement was not processed.
Backport PR #5005
=> Backport PR #5005 - EnhancedNodeService bean was not loaded

docker/official/README.md, docker/official/remco/resources.d/rundeck-config-quartz.properties.toml, docker/official/remco/templates/rundeck-config-quartz.properties
Hi :wave: 
It is an enhancement in the official docker image by supporting the quartz thread count configuration parameter through an environment variable.
Added in remco templates the possibility to set `RUNDECK_QUARTZ_THREADPOOL_THREADCOUNT` in `rundeck-config.properties` to override the default limit of 10 threads.
N/A.
This will allow users to extends the thread count easily if they are running rundeck inside container and/or in Kubernetes.
=> Support quartz.threadPool.threadCount parameter in Docker image

rundeckapp/grails-app/views/framework/_editProjectForm.gsp
If the chosen file copier had no config properties, the plugin name wasn't being sent to the server with the expected form property name which caused the save to fail.
=> Fix #5080 by sending the chosen file copier plugin type even if it has no config properties.

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Timeout in referenced job was working using a constant value, now it works too if you set as option and fill that option when the parent job calls the job.
Fix #5046
=> Referenced Job resolve variables on timeout field #5046

core/src/main/java/com/dtolabs/rundeck/core/schedule/JobScheduleManager.java, rundeckapp/grails-app/services/rundeck/services/JobSchedulerService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Enhancement:
* on cluster environment, the job scheduled should respect the remote execution policies (if it is enabled).
* When the job is created, it will be checked if the job will be scheduled on another cluster member or locally. 
* When a job is updated, that was already considered. But, it was added a flag to avoid registering on the local quartz when the job is owned by another node.
* for takeover API, it will be forced to run locally
A new method was added to JobScheduleManager (scheduleRemoteJob) which will check if the remote policies are available on cluster env (and it will send the takeover message if it is enabled)
**Additional …
=> on cluster environment , the job scheduled should respect the remote exec policies

plugins/jasypt-encryption-plugin/build.gradle, plugins/object-store-plugin/build.gradle
remove some transitive dependencies from embedded plugin libs, as updated versions are already available in the app libs
=> Updating transitive dependencies used in plugins

rundeckapp/grails-app/views/menu/home.gsp
Fixed: If no projects exists, the home page still shows a white card box with nothing in it.
=> Fix: empty project list shows white box on home page

core/src/main/java/com/dtolabs/rundeck/core/rules/WorkflowEngineOperationsProcessor.java, plugins/upvar-plugin/src/main/java/org/rundeck/plugin/vars/ExportVarWorkflowStep.java, plugins/upvar-plugin/src/test/groovy/org/rundeck/plugins/vars/ExportVarWorkflowStepSpec.groovy, rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Notification Service now uses modified global context instead of the original allowing it to read new variables created during workflow.
And export variable workflow plugin creates the variable directly on global  `ContextView`.
Example workflow using notification plugin (Splunk notification plugin):
fix #5061
=> Allow notification to use workflow exported variables #5061

core/src/main/java/com/dtolabs/rundeck/plugins/ServiceTypes.java
The ServiceLoader class is not thread safe, so the behavior can be non-deterministic if multiple threads try to access the method. 
The reported issue is not regularly reproducible, but I have seen the error enough to try to address it with this sync lock.
=> Attempt to fix #4286 by putting a sync lock around the service loader.

core/build.gradle, gradle.properties, plugins/object-store-plugin/build.gradle, rundeckapp/build.gradle, testbuild.groovy
This PR updates rundeck dependencies to address many vulnerabilities reported on CVEs. Updates include both new versions of plugins with revised dependencies and updated versions for libraries with known vulnerabilities.
Libraries updated and CVEs addressed:
Library | New Version | CVE
-- | -- | --
adapter-rxjava | 2.6.1 | CVE-2018-1000844
asset-pipeline-grails | 2.14.10 | CVE-2018-1000817
aws-java-sdk | 1.11.616 | CVE-2013-4366
bouncycastle | 1.62 | CVE-2018-1000613
commons-beanutils | 1.9.4 | CVE-2019-10086
commons-collections | 3.2.2 | CVE-2017-15708
dom4j | 2.1.1 | CVE-2018-1000632
gorm | 6.1.11 | CVE-2017-7536
hibernate | 5.1.17 | CVE-2017-7536
jackson-databind | 2.9.9.3 | CVE-2019-14439     CVE-2019-14379
jackson-jq | 0.0.10 | CVE-2019-14439     CVE-2019-14379
jetty | …
=> Update versions for plugins and libraries with reported vulnerabilities.

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
Fixes #5149
This moves the average duration notification into the same transaction/session as the success/failure notification. This will ensure the session for the proxy object is still active when accessed in the notification service.
=> Fix proxy initialization exception for avg duration notifications

rundeckapp/grails-app/assets/javascripts/executionStateKO.js
Fixes #5157
The issue can occur if there are duplicate steps in the state log. KO can't handle duplicate keys. It won't complain out right about them, but `undefined`s will appear in the observable array causing errors in mapping and other parts of the code.
This fix addresses the issue in the front end. After data is loaded the steps are de-duped on `stepctx` before being passed through to get mapped and summarized.
I considered de-duplicating the data in the backend however this information is actually present in the state file. It's unclear to me at this point if it serves a purpose to have multiple entries for the same `stepctx` in the …
=> Dedupe setps on stepctx

rundeckapp/grails-app/views/layouts/base.gsp, rundeckapp/grails-spa/build/webpack.base.conf.js, rundeckapp/grails-spa/package.json, rundeckapp/grails-spa/src/components/central/main.ts, rundeckapp/grails-spa/src/components/community-news-notification/main.js, rundeckapp/grails-spa/src/components/tour/main.js, rundeckapp/grails-spa/src/components/version-notification/main.js, rundeckapp/grails-spa/src/pages/community-news/main.js, rundeckapp/grails-spa/src/pages/project-activity/main.js, rundeckapp/grails-spa/src/pages/project-dashboard/main.js, rundeckapp/grails-spa/src/pages/repository/main.js, rundeckapp/grails-spa/src/pages/webhooks/main.js, rundeckapp/grails-spa/src/types.d.ts
* Loads development `Vue` when in development environment
* Externalizes `Vue` in build so anything requiring `Vue` gets the global `Vue`
* Configures `VueMoment` once so errors do not prevent loading
* Ensures every `new Vue({})` instance receives an `i18n` to prevent errors and expose internationalization support to Webhooks and plugin components
=> Externalize Vue

rundeckapp/grails-spa/src/pages/webhooks/views/WebhooksView.vue
This ensures that when `getHooks` is called the selected plugin will be updated. Otherwise the selected plugin, used for save, will become disconnected from the `curhook`.
=> Ensure selected plugin matches curhook

rundeckapp/grails-app/assets/scss/custom/jobs.scss
Answers and Fixes #5044
Improves the readability of options, stacking them one over the other, and implements word-breakage.
=> Improves readability of options in job executions, answers #5044

rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy, rundeckapp/grails-spa/src/pages/repository/components/ConfigureFrameworkString.vue, rundeckapp/grails-spa/src/pages/repository/views/PluginConfigurationView.vue
In app plugin configuration display now correctly uses project and framework mapping for plugin
properties configured with mappings. Fixes #5244.
=> Fix in app plugin configuration display 

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Options that have an option values plugin should not be run through the remote values validation.
This PR reduces the code duplication in the remote options validator, and excludes options that specify an option validator plugin.
=> Fix #5248. Option validator error

rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
=> Darkens the list delimiter input to differentiate between inline label

rundeckapp/grails-app/assets/javascripts/executionStateKO.js
This pull request correct the time zone offset display on the node status summary at the execution detail page.
Fixes: https://github.com/rundeck/rundeck/issues/5125
=> Fix #5125. Correct timezone offset on execution node status.

rundeckapp/grails-spa/src/pages/webhooks/views/WebhooksView.vue
When a new webhook is saved there is no current hook selected from the list so don't try to match.
=> Fix VUE UI issue on webhook page

rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy, rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy, rundeckapp/grails-app/domain/rundeck/AuthToken.groovy, rundeckapp/src/test/groovy/rundeck/controllers/UserControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
Handle null like AuthTokenType.USER.
Tested upgrade from pre 3.1.1 version to 3.1.1 snapshot and worked with no errors reported.
=> Fix #5261. Do not set not null constraint on AuthToken type. 

rundeckapp/grails-app/views/user/login.gsp
To satisfy Qualys Vulnerability scanning.
Even though it isn't best practice, because best practice is to use password managers to autocomplete the login fields.
However, it won't be honored by the browsers (for the above reason https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields), so users won't get affected.
So this change is only good to silence a vulnerability scanner, it doesn't actually close a vulnerability.
Closes #5205
=> Turn off autocomplete on password field

core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkProject.java, core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkProjectConfig.java, core/src/main/java/com/dtolabs/rundeck/core/common/IRundeckProject.java, core/src/main/java/com/dtolabs/rundeck/core/common/IRundeckProjectConfig.java, rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy, rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/projects/RundeckProject.java, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/projects/RundeckProjectConfig.java, rundeckapp/src/test/groovy/rundeck/controllers/ProjectControllerTest.groovy, rundeckapp/src/test/groovy/rundeck/services/NodeServiceSpec.groovy
fix #5099
on `GET /api/33/projects` endpoint adds `created` field.
This data is extracted from the property file if using `projectsStorageType` `file` or the creation date on the DB if using `projectsStorageType` `db`
XML:
```
<project url='http://wintermute:4440/api/33/project/bugbear'>
<name>bugbear</name>
<description>Test from issues and enhancement requests</description>
<created>Mon Sep 09 10:45:38 CLST 2019</created>
<label>Bugbear</label>
</project>
```
JSON:
```
{
"url": "http://wintermute:4440/api/33/project/bugbear",
"name": "bugbear",
"description": "Test from issues and enhancement requests",
"label": "Bugbear",
"created": "2019-09-09T13:45:38Z"
},
```
=> Add creation date to project list on api

rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/grails-app/views/execution/mailNotification/_newStatus.gsp, rundeckapp/grails-app/views/execution/mailNotification/_oldStatus.gsp, rundeckapp/src/main/groovy/org/rundeck/app/AppConstants.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Fix #5140 by making sure mail notification renderer checks the allow unsanitized property when rendering the mail.
=> Fix: Job mail notifications respect allow unsanitized property

rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/logging/RundeckLogFormat.groovy
Improves the performance of log format line parsing.
`parseLine` and the other methods have been annotated with `CompileStatic` and modified to compile.
This about doubles the performance on my system with a `5mb` test file:
* ~30s -> 15s in dev mode
* ~10s -> 5s in production mode
=> Improve execution log parsing speed with CompileStatic

rundeckapp/grails-app/assets/scss/custom/jobs.scss, rundeckapp/grails-app/assets/scss/custom/workflow-editor.scss, rundeckapp/grails-app/views/execution/_execArgString.gsp, rundeckapp/grails-app/views/execution/show.gsp, rundeckapp/grails-spa/src/components/activity/activityList.vue
activity list: don't wrap, allow horizontal overflow scroll
exec page: show values on separate blocks, max height to scroll on y axis
Update display of argstrings values in activity list and execution page, ref #5044 #5105
=> cleanup argstring display in activity list and exec page

core/src/main/java/com/dtolabs/rundeck/core/resources/ScriptResourceModelSource.java
Backporting for issue: #5147 Allow quotes in the middle of arguments to be interpreted as a single argument
(cherry picked from commit 38345bb5e37d41746f32ada2f238919a029aab02)
=> Backporting for issue: #5147

rundeckapp/grails-spa/src/pages/repository/views/PluginConfigurationView.vue, rundeckapp/grails-spa/src/pages/repository/views/PluginRepositoryView.vue
Fixes #5287 
Add "title" to search keys so that keywords in plugin titles will contribute to results.
=> Consider plugin title in search

rundeckapp/grails-app/assets/javascripts/application.js
If some characters are typed after @option. and then an item is selected from the autocomplete dropdown menu, @option. is inserted again at the beginning and an extra "@" is added at the end
This solution changes the regular expression to consider "." as a valid character on prefix input text when perform auto completions.
Initially, I was trying to custom the "getCompletions" function from auto completion tool library.
=> Fix #5083 - Fixing the regex expression to consider "." character when perform auto completions

rundeckapp/grails-app/services/rundeck/services/JobEventsService.groovy, rundeckapp/grails-app/services/rundeck/services/ScmService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
Fix #5301 
* prevents multiple listeners for the same project+integration plugin
from accumulating after repeated scm status queries
* same when scm plugins are re-enabled or re-configured
=> Fix #5301 fix initProject, and clean old listeners

rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowController.groovy, rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp, rundeckapp/src/test/groovy/rundeck/controllers/WorkflowControllerTests.groovy
Java plugins with a property that came from @SelectValues with multOption=true did not send their values to the server correctly. The server wasn't handling the value type correctly. That is now fixed too.
=> Fix issue with plugin select value with multiOption

.mergify.yml
add mergify.io rule file for automatic backport prs
=> Add mergify.yml with backport rules

rundeckapp/grails-app/assets/javascripts/executionControl.js, rundeckapp/grails-app/assets/javascripts/util/compactMapList.js, rundeckapp/grails-app/conf/application.yml
This improves the interactivity of the page while loading the execution log.
To reduce the amount of time JS is blocking the UI(scrolling primarily) the table rows are being added in chunks. Prior there was an implicit chunking due to the `500` max line limit fetched from the server at one time, however this chunk size proved to feel quite laggy in my testing.
This change decouples the DOM update batching from the data fetching. Until there are over **20k** lines of output the batch size will be 50. Around **20k** the reflow starts to take up a much larger portion of the update time and is constant for the input size. At this point the batch size is raised back to `500` to prevent a much …
=> Improve interactivity of page when loading execution log

rundeckapp/webhooks/grails-app/domain/webhooks/Webhook.groovy
Fixes #5326
SQL Server uses a bit for boolean values and will not accept "true" as a default for the column. Hibernate seems to not translate the default, string or boolean, to a 1 or 0 in the DDL statement.
Remove the database default value and rely on the default value in the domain object..
- Creating a custom dialect(yuck)
- Creating custom per-database create statements(double yuck)
I'm not aware of any great hibernate provided solutions for this that would be applicable across all supported databases.
=> Fix invalid default value error on startup against SQL Server

rundeckapp/grails-app/assets/javascripts/application.js
Fixes #5119 
Fixes a regression introduced in https://github.com/rundeck/rundeck/commit/0ffc45327e8947918a56ff18110ed34a694dd86b .
Prototype's `down` does not have a precise equivalent in JQuery; it returns the first descendant where as `find` returns all the matching descendants. Adding `first` approximates `down` all though it may be less performant..
=> Fix job group expansion applying to all levels

rundeckapp/grails-app/init/rundeckapp/cli/CommandLineSetup.groovy, rundeckapp/src/test/groovy/rundeckapp/cli/CommandLineSetupTest.groovy
Password encryptors with properties that have a displayType=PASSWORD now read the password without echoing it back to the command line.
=>  Enhance cli password encryption utility

rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowNodeStateImpl.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStateImpl.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStepState.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStepStateImpl.groovy, rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStateImplSpec.groovy, rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStateImplTest.groovy, rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/internal/workflow/MutableWorkflowStepStateImplTest.groovy
Fix potential race conditions/concurrency issues found in the workflow state management code
* use ConcurrentHashMap, put/computeIfAbsent
Unreproduced issue: large workflow with lots of concurrency can appear to having missing steps in the Node summary view, the state.json appears to miss some of the status info for some steps/nodes. the log reflects the steps as having correctly executed, but they are not shown in the Node step listing. Code review suggests potential race conditions due to unsafe concurrency.
=> Concurrency improvements for workflow state

rundeckapp/grails-app/views/scheduledExecution/_show.gsp
Fix missing import from #5362 on `rundeckapp/grails-app/views/scheduledExecution/_show.gsp`
=> Fix missing import 5375

rundeckapp/src/test/groovy/rundeck/services/NodeServiceSpec.groovy
Adds a framework.var.dir to the test so the temp dir that is generated is not in the rundeckapp dir.
=> Cleanup test dir in NodeServiceSpec test

rundeckapp/grails-app/views/execution/_wfAddStep.gsp
* only include necessary fields
* use existing json load mechanism
Fix #5385 
Reduce serialized data to only necessary content.
Reduces raw page size :
~~~
955361 Oct 15 12:03 new.html
1909893 Oct 15 12:14 old.html
~~~
=> Fix step search page content fixes #5385

rundeckapp/grails-app/assets/javascripts/executionControl.js, rundeckapp/grails-app/assets/javascripts/util/compactMapList.js, rundeckapp/grails-app/conf/application.yml
Reverts #5254
This introduced a regression with the loading bar not going away after the execution has finished when viewing the log output.
After spending some time going through the code the exact cause wasn't presenting itself quick enough :) There is a much, much quicker log output viewer in the works that should make this change obsolete shortly so reverting is probably a better use of time.
=> Revert "Improve interactivity of page when loading execution log"

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/integration-test/groovy/rundeck/services/ExecutionServiceIntegrationSpec.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Fixes #5314 
Fix
`loadOptionsRemoteValues` can return three(?) different shapes for results:
- `List(Collection)<String>` for `['foo','bar']`
- `List<JSONObject>` for `[{"name": "foo", "value": "bar"}]`
- `List<LinkedHashMap>` for `{"foo":"bar"}`
Changing to `instanceof Map` will match both JSONObject and the Groovy map.
**Additional**
I believe at some point the remote option loading could afford to be refactored out into a utility class. Breaking the logic out across multiple methods and ensuring a uniform(typed?) return schema regardless of the supported input JSON shape could help with test-ability and maintainability.
=> Fix error on remote opts with enforced values for simple JSON object

rundeckapp/grails-spa/src/components/activity/activityList.vue
Run later executions or `scheduled` shouldn't be selectable to `bulk delete`
=> fix selectable run later executions on bulk delete 5373

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
Use a Future to get the AbortResult and return it. The actual fix for this bug is on the enterprise side. This change enhances the reply handling.
=> Wait for AbortResult from event bus reply. Fixes #4916.

rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy
Fixes #5358. If there are no log entries in the log then "No output" will be written to the output stream to avoid triggering a grails error.
=> Fix error when attempting to download text log

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
fix #4842
In this particular case: https://github.com/rundeck/rundeck/issues/4842#issuecomment-535131898
If the option is not mandatory and  the remote list is only values not complex json objects, the clause throws a `groovy.lang.MissingMethodException`.
=> fix #4842 default selected validation fails if the object is not a map

rundeckapp/repository/build.gradle
Bump repository version to update dependencies and fix an issue when accessing the official repo manifest fails.
=> Fixes #5121. Bump repository version.

rundeckapp/grails-app/assets/javascripts/executionControl.js
Fixes #4047 
Scrolling log output doesn't work in 3.x as the scrolling element is no longer the `window.documentElement`, but div `#main-panel`.
Scroll the `#main-panel` element instead.
I suspect a more wholesome approach would be to initialise the `exectuionControl` with an element that represents the scrolling element, passed in from the page. It doesn't feel totally right that it 'knows' about the page structure in this sense.
I'm also not 100% sure that `document.querySelector` is best here. I know that `jQuery` is used elsewhere in the app and there is some Vue around, but this works in the one browser i tested it on.
PR is "RFC" because …
=> [RFC] Fix scrolling to bottom in log output

rundeckapp/grails-app/assets/scss/custom/execution-output-table.scss
Fixes a wordbreak bug in the log output of a job. Fixes #5320
Please test with the included job definition - renamed as .txt, change to .dtd
[very_long_line copy.txt](https://github.com/rundeck/rundeck/files/3740733/very_long_line.copy.txt)
=> Fixes #5320 - adds a wordbreak to the contents of a table column

rundeckapp/grails-app/assets/javascripts/executionStateKO.js, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy, rundeckapp/grails-spa/package.json, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy, test/api/include.sh
* Adds `job/[ID]/workflow` endpoint to public API for retrieving a job's workflow tree
This is preparatory work for moving more functionality out into components in the `grails-spa` project. Specifically it is being utilized by the new execution output viewer component.
**Docs PR**
rundeck/docs#338
=> Add API endpoint for getting job workflow tree

core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/PluginAdapterUtility.java, core/src/test/java/com/dtolabs/rundeck/core/plugins/configuration/PluginAdapterUtilityTest.java, rundeckapp/src/integration-test/groovy/rundeck/services/PluginApiServiceIntegrationSpec.groovy
Allow all plugin properties to use groupName and grouping rendering options.
Also fixes the name of a service in the Plugin api integration test.
=> Allow all plugin properties to use groupName and grouping rendering options.

rundeckapp/grails-app/assets/javascripts/filterStepPluginsKO.js, rundeckapp/grails-app/assets/javascripts/filterStepPluginsKOTest.js, rundeckapp/grails-app/views/common/_stepPluginsfilterStringHelp.gsp, rundeckapp/grails-app/views/execution/_wfAddStep.gsp, rundeckapp/grails-app/views/framework/_stepPluginFilterInputGroup.gsp
Update search behavior for step plugin selector in Job Edit page.
Previous behavior only searched the Title, and required syntax like `description=query` to search the description or plugin name (identifier).
This change makes the field search the title, name, and description by default.
Old behavior: (1 result for `inline`)
New behavior: (3 results for `inline`)
**Future enhancements**
* The `description` that is searched is currently the default value from the plugin itself, and does not correctly use any i18n in the user's locale.
=> Enhancement: step search improvement

rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ApiControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/UserControllerSpec.groovy
Fixes two places that were outputting webhook tokens with user type API tokens.
=> Prune Webhook token output from unexpected places

core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionContext.java, core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionContextImpl.java, core/src/main/java/com/dtolabs/rundeck/core/jobs/ExecutionLifecycleStatusImpl.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/StringRenderingConstants.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/ExecutionContextImplSpec.groovy, rundeckapp/grails-app/assets/javascripts/application.js, rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp, rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
Some fixes for lifecycle plugins:
* UI: CODE rendering option in job edit page not loading for exec lifecycle plugins
* Add utility implementation of expected return type for execution lifecycle plugins
* fix: `useSingleComponentOfType` method not working correctly
=> Lifecycle plugin updates

rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
ACE editor setup call is already being done in the jobedit.js. This seems to have the effect of adding it twice.
=> Fix duplicate ACE editors being added on job edit page.

rundeckapp/grails-app/views/user/_token.gsp
User token table, when a user has many roles, does not wrap the text therein, obsecuring the delete button off the viewport. This fix adds an inline "word-break" to the containing span and removes "ellipsis" class that is both unnecessary and incorrect.
=> Table word wrap issue, fixes #5384

rundeckapp/grails-app/services/rundeck/services/JobStateService.groovy, rundeckapp/src/test/groovy/rundeck/services/JobStateServiceSpec.groovy
fix: run job via JobService passing extra execution metadata doesn't correctly store the metadata to the execution
Job resume feature not working
=> Fix: run job with extra metadata doesn't work

rundeckapp/grails-app/views/menu/storage.gsp
Fixes: "Don't overwrite" checkbox on key storage popup.
=> Fix #5480 by moving the location of the input element.

rundeckapp/grails-app/conf/application.groovy
Enables the `executionLifecyclePlugin` feature by default
=> enable executionLifecyclePlugin by default

rundeckapp/grails-app/services/rundeck/services/ExecutionLifecyclePluginService.groovy
Inverted boolean check caused the plugin listing to be bypassed when feature is enabled.
=> Fix #5488. Wrong boolean check for execution lifecycle feature

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Bug
for issue https://github.com/rundeck/rundeck/issues/5481
rebuilding PR https://github.com/rundeck/rundeck/pull/5145 that was overwritten
If a scheduled job (with cluster mode enabled) is modified without changing the scheduled or the name/group, the deleteJob method (that removes the job from the quartz) shouldn't be called.
described on PR  https://github.com/rundeck/rundeck/issues/5481
=> Job rescheduling issue

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Skip the previous validation only if the default field contains a variable (`${`).
If the default value is invalid, the job fails with the correct message:
Fix #5397
=> Allow to run jobs using variables with keystorage and required yes

rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Modified `${execution.succeededNodeList}`  on notifications based on real node list not on the target node list.
Uses the `workflowService` to obtain the list of nodes and add only the nodes that really run the job, in case the workflow executor execute only in a portion of the nodes, as example, the random subset Orchestrator.
Fix #5517
=> variable execution.succeededNodeList to observe real node execution on notification

core/src/main/java/com/dtolabs/rundeck/core/execution/service/ScriptPluginNodeExecutor.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/service/ScriptPluginNodeExecutorSpec.groovy
Enhancement:
Adding the private context data to script node executor plugins
for https://github.com/rundeck/rundeck/issues/4425
Passing the private data context to the environment variables added when the node executor script is ran on rundeck server
The variable available on the script node execution plugin will be called: `RD_PRIVATE_<option.name>`
=> Adding the private context data to script node executor plugins

rundeckapp/grails-app/views/common/_footer.gsp
So that we don't have to constantly update the copyright each time the year changes, setting the copyright year to use local Java getYear.
=> Adds automagic copyright date

rundeckapp/grails-app/views/common/_footer.gsp
Reduces the size of the "Unsupported Software" notice in the footer from 1EM to .7EM.
=> Reduces text size

rundeckapp/grails-spa/src/pages/webhooks/views/WebhooksView.vue, rundeckapp/webhooks/grails-app/services/webhooks/WebhookService.groovy, rundeckapp/webhooks/src/test/groovy/webhooks/WebhookServiceSpec.groovy
Fix save and validation problems with webhooks
=> Webhook validation fixes

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_ja.properties, rundeckapp/grails-app/i18n/messages_pt_BR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/views/execution/_execDetails.gsp, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerTests.groovy
List plugins for the Job in the job detail, such as ExecutionLifecycle plugins
=> Job detail: show plugins

rundeckapp/grails-spa/src/pages/webhooks/views/WebhooksView.vue
When switching between event plugin types on the config page, the selected plugin object was not maintaining a reference to the same object, so the config wasn't always being saved properly in the cases of custom config components.
=> Fixes webhook config for plugins with a custom config component.

rundeckapp/grails-app/assets/scss/paper/_alerts.scss
Fixes rundeckpro/rundeckpro#816
Added a `z-index` to the alert class in `app.css`.
=> Ensure alert is above other elements

rundeckapp/src/main/groovy/org/rundeck/security/RundeckJaasAuthenticationProvider.groovy
Update to the text checked for suppression when the Jetty Jaas module generates a spurious NPE on logout.
=> Suppress NPE generated by Jetty JAAS logout module

rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy, rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
When a webhook post is received the authtoken can contain a hash + webhook name. This commit cleans the token in that scenario.
=> Handle webhook post with auth token containing hash

rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy, rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy, rundeckapp/webhooks/grails-app/controllers/webhooks/WebhookController.groovy, rundeckapp/webhooks/src/test/groovy/webhooks/WebhookControllerSpec.groovy, rundeckapp/webhooks/src/test/groovy/webhooks/WebhookSpec.groovy
Fix possible issue with posting to a webhook endpoint with the hash and webhook name appended to the auth token used by the webhook.
This PR moves the auth token cleaning code and does an additional cleanup step in the post method of the webhook controller.
=> Fix potential webhook authtoken issue

rundeckapp/build.gradle
plugin bug fix:
https://github.com/rundeck-plugins/py-winrm-plugin/issues/39
=> new version pywinrm plugin 2.0.5

docker/official/remco/templates/jaas-loginmodule.conf
When nestedgroups are setup in Docker using environment variables, a single character case typo will produce invalid configuration file preventing Rundeck to start.
With this fix, Remco will set the right value in the configuration file and Rundeck will start normally.
Fixes https://github.com/rundeck/rundeck/issues/5474
=> Fix typo in remco template (nestedGroups)

rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy, rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
Bug fix:
On cluster mode, if a cluster member modifies any node enhancer plugin, the other cluster members cannot refresh the plugin list defined on the EnhancedNodeService.
for issue https://github.com/rundeckpro/rundeckpro/issues/823
The workaround is to call the `refreshProjectNodes` when a change on the project settings is detected on ProjectManagerService
add a guava cache on EnhancedNodeService
=> call refresh-nodes when the project settings are refresh

rundeckapp/grails-app/views/framework/_jobOptionsKO.gsp
bugfix:
fixing Option Value plugin is not using the name attribute (issue https://github.com/rundeck/rundeck/issues/5539) 
it is not necessary to assign the `valuesFromPlugin` to the KO `values` attributes, because KO checks later if the valuesFromPlugin is set ( using `hasPluginValues` method)
=> fixing Option Value plugin is not using the name attribute

rundeckapp/grails-app/assets/javascripts/momentutil.js
Fix #5553 
Relative duration formatting was skipping Month and Year 
Moment.js has a relative duration format function, but needs either custom locale data or separate utility library such as https://github.com/jsmreese/moment-duration-format to use a custom format.
the Moment.js duration formatting could be used as-is, but is more verbose " 22 days" vs "22d". 
I opted to correct the internal code instead of alter the formatting completely or adding a new dependency.
=> Fix #5553 duration more than 1 month should show correctly

core/src/main/java/com/dtolabs/rundeck/core/nodes/ProjectNodeService.java, rundeckapp/grails-app/services/rundeck/services/NodeService.groovy, rundeckapp/src/main/groovy/org/rundeck/app/services/EnhancedNodeService.groovy, rundeckapp/src/main/groovy/org/rundeck/app/services/ProjectNodesEnhancer.groovy, rundeckapp/src/test/groovy/org/rundeck/app/services/EnhancedNodeServiceSpec.groovy, rundeckapp/src/test/groovy/org/rundeck/app/services/ProjectNodesEnhancerSpec.groovy
enhancement: skipping node executor plugins to avoid loops
=> skipping node executor plugins to avoid loops

rundeckapp/grails-spa/src/components/activity/activityList.vue
fixes #5133 
Customers requested to back old way to show duration time when jobs spend seconds to end. Today the activity view is displaying the words "a few seconds" but needs to be shown the amount of seconds
The activityList.vue was changed to set the relative time threshold so 'moment' lib will not change the seconds value to the text "a few seconds".
=> Fixes #5133 - Change duration jobs info displayed on activity view to show seconds time and not a text saying "a few seconds"

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Abort referenced execution before it has time to start if the execution has been aborted. 
Now the aborted job reference step works in job references that run as a workflow step.
=> Fix unexpected behavior when killing a job that includes Job Reference of workflow type. 5478

core/src/main/java/com/dtolabs/rundeck/core/data/SharedDataContextUtils.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/common/DefaultFileCopierUtil.java, core/src/main/java/com/dtolabs/rundeck/core/execution/script/ScriptfileUtils.java, core/src/test/groovy/com/dtolabs/rundeck/core/dispatcher/SharedDataContextUtilsSpec.groovy, core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/TestScriptFileNodeStepExecutor.java
Add bom char to destination file if all of these conditions are true:
* the target node is `windows`
* the encryption is `utf-8` 
* the special property `file-add-bom` is present on the target node.
fix #4291
Pending documentation PR
=> Add bom char to destination file of the script #4291

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/domain/rundeck/JobExec.groovy, rundeckapp/test/unit/rundeck/JobExecSpec.groovy
Back port of #3442 
Not urgent, just nice to have in a future 2.11.x release.
Had to make this back port by hand instead of cherry picking commits because the test has changed between 3.0.0 and 2.11.x
Also found a missing comma inside a SCM method call from a previous back port. Its inside an Ajax call so it doesn't stop the flow of the SCM actions.
=> [2.11 backport] ImportOptions to jobref in job definition

docker/official/README.md
Corrects a typo in README.md file: "default" word : defualt -> default
=> Corrects a typo in documentation file

rundeckapp/grails-app/assets/scss/custom/labels.scss, rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
Fix #5117 that request to return tags filter to select target nodes
Tags filter to select target nodes for jobs executions was removed from the GUI
Get back the tags filter to select target nodes.
=> Fixes #5117 - getting back the tags to select target nodes for jobs execution

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/QueueQuery.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ScheduledExecutionQuery.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Fix #5001 
A customer requested to change dashboard behaviour so jobs that will run later should be shown as scheduled and not as running
The query was adapted to filter jobs with date start setted to a date future
=> Fix #5001 - Adapting query so dashboard can show one time scheduled job (run job later) as scheduled and not as running job

rundeckapp/grails-spa/src/pages/repository/components/ProviderCard.vue, rundeckapp/grails-spa/src/pages/repository/components/ProviderCardRow.vue
fixes #5624 
Installed "BuiltIn" Plugins were displaying the "uninstall" button.
Adds v-if statement to the grid and table, checking if a "provider" (read: plugin) is NOT a builtin, otherwise, don't show the Uninstall button.
=> Adds v-if checking for if provider/plugin is builtin

.mergify.yml
change mergify config so that master based prs are not labeled with 3.3.x anymore
=> mergify config: auto-label for master prs changed to 3.2.x

rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
Fixes #5679
Creating a new Project and enabling Execution History Clean leaving 'cron expression' field empty to use default values causes an on-screen error
All properties uses a default value when fields on UI is empty. This was not just for the 'Cron' field but now it was fixed
=> Defining a default value for crontabString prop when field is empty. 

rundeckapp/grails-app/domain/rundeck/User.groovy, rundeckapp/src/test/groovy/rundeck/UserTests.groovy
Fix #5188 and #5684 by allowing valid unicode characters in first and last name fields.
=> Allow valid unicode characters in user first and last name fields

plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
fix #5675 
Fix a random condition on git SCM plugin on windows, `.pack` files aren't released until the garbage collector runs and those files cant be deleted immediately.
If the error is just ignored and logged that file is released later and causes no problem with the configuration.
=> scm git plugin: close repo and delete using recursive flag on cleanup

rundeckapp/build.gradle
enhancement:
* passing authentication password from Secure Remote Option on a job
* passing authentication passphrase from Secure Remote Option on a job
* Using dynamic username (eg: `username=${job.username}` ) 
Using the new private context variable `RD_PRIVATE_XX` for script plugins
Related requests:
https://github.com/rundeck-plugins/openssh-node-execution/issues/12
https://github.com/rundeck-plugins/openssh-node-execution/issues/11
=> upgrade openssh plugin 

rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
bugfix:
fix for issue https://github.com/rundeck/rundeck/issues/5674
Replacing execution context variables (like `${execution.id}`) doesn't work on notification plugin config attributes. Job, options and globals variables can be replaced.
add execution context variables to the process that performs the replacement
=> expanding execution variables on notification plugin config

core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionService.java, core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionServiceImpl.java, core/src/main/java/com/dtolabs/rundeck/core/execution/NodeExecutorUtils.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschNodeExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/service/NodeExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/tasks/net/SSHTaskBuilder.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/NodeExecutorUtilsSpec.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/tasks/net/SSHTaskBuilderSpec.groovy
Enhancement:
You can now inyect RD_ variables as part of the ssh commands, so no modification to the ssh configuration on the client side is needed
- This can be enabled/setup at node level making it able to run with different sintaxis depending on the node config.
EG:
1.-Linux node
ssh-variable-export-pattern="export {key}='{value}'"
2.-Windows node
ssh-variable-export-pattern="set {key}='{value}'"
- Custom separator can also be set with the following node attribute:
ssh-variable-export-separator
EG:
1.-ssh-variable-export-separator=";"
2.-ssh-variable-export-separator="\n"
- Node attributes can now be excluded from the export, using the following node attribute:
ssh-variable-export-exclude-nodes="true"
- Example job to print the environment variables …
=> ssh export rd variables

core/src/main/java/org/rundeck/app/components/jobs/BaseQueryInput.java, core/src/main/java/org/rundeck/app/components/jobs/JobQuery.java, core/src/main/java/org/rundeck/app/components/jobs/JobQueryInput.java, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/views/menu/_workflowsFull.gsp, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/BaseQuery.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ScheduledExecutionQuery.groovy, rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Add JobQuery type for extending job queries
Some refactoring of the job query methods to allow a spring bean to contribute to UI and query.
**usage**
1. define a bean that implements `JobQuery`
2. return a `List<Property>` from `getQueryProperties`
3. implement the `extendCriteria` method
* This method will be called when the job query is invoked, the "params" contains the web query params
3. If the params contains an input property defined in the queryProperties, modify the query using the delegate (Criteria)
=> Job query internal extension

rundeckapp/grails-spa/src/components/activity/activityFilter.vue
Calls Search() before popping the "Save Search" modal. This allows for the filter to be applied before opening the save modal which resolves an issues we experienced where the saving of a filter (giving it a name) didn't actually save the filter itself, just the name.
Updates the vue file to standard linting - e.g. double, not single quotes, space at the end of self-closing elements before the trailing slash.
Edits for Activity Filter Modal Search begin on line 333.
=> fixes #5692 - Activity Filter Doesn't Save in Search Modal

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Add other options values when remoteurl is validated before run.
=> Fix for problem validating remote url options using other options values. 5733

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Fixes #5735 
Fixes rundeckpro/rundeckpro#873
Mistakenly, was inserted a code which made a query for each execution of a job. It caused a n+1 issue and that strongly impacted performance
Was changed the code so instead of a query for each execution, now should run only one query for the executions.
=> Fixing a n+1 issue removing a code that accessed the list of executions and was making a query for each one. 

rundeckapp/grails-app/views/menu/_projectDeleteForm.gsp
Fix #5753 and https://github.com/rundeckpro/rundeckpro/issues/872
No message is displayed on GUI when deleting a project returns an error
Was added a div to show an error alert if any error message exists
=> Fix #5753 - An error message needs to be shown on GUI when deleting the project returns an error

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Bug Fix:
On Jobs Page, when you disable the project scheduled and you have the cluster mode enabled, the job status scheduled message is wrong (it is shown the next time instead show the scheduled is disabled)
https://github.com/rundeck/rundeck/issues/5763
if the project scheduled or project executions are disabled, return null to the nextExecutionTime (in order to show the correct status on job page)
=> fixing wrong job scheduled status message

build.gradle, rundeckapp/build.gradle
This change updates the artifact IDs and publishing paths of published projects to take into account the `rundeckapp` project name change.
=> Fix artifact id and publishing path

rundeckapp/grails-app/views/scheduledExecution/_editNotificationsForm.gsp
Fix #5721 by setting the form name to the correct value for the avg duration url.
=> Fix #5721 by setting the form name to the correct value for the avg duration url.

rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy, rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy
Fixes #5784 and fixes https://github.com/rundeckpro/rundeckpro/issues/882
This bug was inserted after changing the plugins registry map to use type of plugin as prefix of name on key. 
The type as prefix on key map should be used only on registry map. When listPlugins method is called, this method returns a list of a specific type, so it does not needed to use the type as prefix.
=> Fix regression in plugin service causing plugin names to return prefixed with type

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Fixes #5809 by not executing a criteria query when the "in" criteria will be an empty list.
=> Fixes #5809 by not executing a criteria query when the "in" criteria will be an empty list.

rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/views/framework/_projectConfigurableForm.gsp
<enhancement>
for grails-plugin Disable/Enable execution after X hours
https://github.com/robertopaez/execution-mode-later-plugin
The plugin add the option to enable/disable executions/schedule after X hours.
This PR add some small changes to the edit project form in order to inject the  `execution mode later` form with more control on css modifications.
Without the PR
With the PR
=> adding some small changes to the edit project form for UI plugin

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
bugfix: for issue https://github.com/rundeck/rundeck/issues/5725
When an Execution is saved (that is dispatched to nodes), the Succeeded Node List is not saved as expected, in the case that exists an incomplete node list.
Using the `requestStateSummary` method from `workflowService` that returns the correct status of the nodes after the execution finished. Then, with this status, we can get the correct list of succeeded nodes and saved on the execution table.
change the implementation of FailedNodesListener, but that just can get the partial status of a node execution.
=> saving the correct list of Succeeded Node

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
fix #5794 
if the user has no `create` or `scm_crete` permission the `scheduledExecution` is null so it is added to the validation.
=> fix Nullpointer exception on api call

rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
Bug fix:
import /common/messages template if the job doesn't have options. It fixed a bug using a job lifecycle plugin ( errors messages are not shown when the job doesn't have options)
check if the job doesn't have options, import the `common/message` template
just move the import to the parent view, but it could be safer not to modify the job options view.
for issue https://github.com/rundeck/rundeck/issues/5776
=> Joblifecycle plus job without options doesn't show error messages

.circleci/config.yml, build.gradle, core/build.gradle, rundeckapp/grails-spa/build.gradle, rundeckapp/grails-spa/config/index.js
* Solve dependency issue when using parallel Gradle builds
* Restores build caching in CircleCI builds
* Improves chances `grails-spa` will be pulled from cache
=> Fix build parallel bug and improve build cacheability

.circleci/config.yml, grails-persistlocale/build.gradle, grails-persistlocale/gradle.properties, grails-securityheaders/build.gradle, grails-securityheaders/gradle.properties, rundeckapp/build.gradle, rundeckapp/metricsweb/build.gradle, rundeckapp/metricsweb/gradle.properties, rundeckapp/repository/build.gradle, rundeckapp/repository/gradle.properties, rundeckapp/webhooks/build.gradle, scripts/travis-helpers.sh
Switches dynamic addition of plugins into the build to a form that works correctly during development. Without this the plugins would randomly, but more often than not, be "broken" during development causing errors resolving `gsp` view names..
This _magic incantation_ could have something to do with the Gradle AST transformations, or the way the closures are constructed in the Grails plugin. I did not end up locating the specific issue in the source code.
=> Fix Grails plugins in development mode

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceIntegrationSpec.groovy
Fixes #2668 by preventing an endless loop when locking exceptions are encountered during schedule takeover.
=> Fixes #2668 by preventing an endless loop 

core/src/main/java/org/rundeck/app/components/project/BuiltinExportComponents.java, core/src/main/java/org/rundeck/app/components/project/BuiltinImportComponents.java, core/src/main/java/org/rundeck/core/projects/ProjectDataExporter.java, core/src/main/java/org/rundeck/core/projects/ProjectDataImporter.java, rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy, rundeckapp/src/main/groovy/org/rundeck/util/Toposort.groovy, rundeckapp/src/test/groovy/org/rundeck/util/ToposortSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
Updates ProjectComponent to allow ordering declarations
* ProjectDataExporter
* `exportMustRunBefore` list of component or builtin names to run before
* `importMustRunAfter` list of component or builtin names to run after
* builtin names: `jobs`,`executions`,`config` (readmes, acls and scm config are combined within `config`)
* ProjectDataImporter
* `importMustRunBefore` list of component or builtin names to run before
* `importMustRunAfter` list of component or builtin names to run after
* builtin names:  `jobs`, `executions`, `config`,`readme`, `acl`, `scm`
Apply topological sort on before/after dependencies for components.  In case of cyclic dependency, revert to original (component …
=> project component ordering changes

build.gradle, build.yaml, rundeckapp/build.gradle
Exports the output of `bootWar` through a custom configuration.
=> Allow build output to be consume from other projects

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Do not try to delete Orchestrator if Executions are linked to it.
Copy Orchestrator when job is executed so that correct historical data is maintained.
=> Fix orchestrator issue

build.yaml
Updates AWS plugins to latest which include `aws-java-sdk-sts`. This should hopefully allow the default credential provider chain to resolve web identity roles(IAM for service accounts).
=> Update AWS plugins

rundeckapp/grails-app/views/scheduledExecution/delete.gsp
Job Delete form "All executions" checkbox doesn't work.
1. Upload a job via the job upload form
2. Choose "delete job" from action menu for uploaded job while in the Upload page
3. The "Delete all executions" checkbox doesn't work
Fix input label.
=> Fix: delete all executions checkbox doesn't work in job delete form from upload page

rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy, rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
Fix #5901 and https://github.com/rundeckpro/rundeckpro/issues/886
the "live log" between the cluster members was not refreshed; it can be seen when the job is finished.
at some point, the list of listeners is empty and an exception is thrown and log processing is interrupted. This changes is to avoid the process to be interrupted.
=> Verirfying list of listeners to avoid an exception thrown before handle result

rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ProjectControllerSpec.groovy, test/api/include.sh
API response for Archive import was not including any errors produced by webhook import.
* Add error messages to API responses from project data importers failures, when API version is greater than 34
* Update API version to 35
=> Update API archive import error response

rundeckapp/grails-app/views/scheduledExecution/_show.gsp
Fix layout of job action menu on job show page when there is a long name or description.
before:
after:
=> Fix: job actions menu position for long descriptions

rundeckapp/grails-app/views/scheduledExecution/_editNotificationsTriggerForm.gsp, rundeckapp/src/test/groovy/rundeck/controllers/ProjectControllerSpec.groovy
fix #5911
This was caused by the line break and tabulation inside the `<textarea>` tag
This happens only on notifications that has a length of more than 100 characters.
In that case, the input type in the GUI changes to a text area and adds empty spaces and line break characters.  If the job is saved without removing the empty spaces is saved with the new characters every time.
Fix validated by @runwaldo see original issue: rundeckpro/rundeckpro#931
=> Remove tabulation and line break from the content of text area

docker/official/README.md, docker/official/remco/templates/grails-config.properties
This ensures that if the user chooses a limit above 200MiB, it will still
work.
Bugfix: This relates to the instructions in https://github.com/rundeck/rundeck/pull/3477 (and used by the container), which only change 2 of the 3 places where the filesize is checked, making sizes over 200MB not work.
Also set the fileUploadService's tempfile maxsize to the chosen limit.
None.
Not applicable.
=> Docker: Also change the max filesize in fileUploadService

core/src/main/java/org/rundeck/app/components/jobs/JobQuery.java, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/jobs/JobQueryService.groovy, rundeckapp/grails-app/views/menu/jobs.gsp
Enhancement: job query components can now show the search parameters in jobs list
Currently: When an implementation of job query is used, the aditional parameters used by the implentation are not shown in the jobs list page.
Proposed: extendCriteria method can now return a map with the values to be shown in the jobs list page
=> job query enhancement

rundeckapp/grails-app/assets/scss/custom/modals.scss
Adds a media query that sets the modal backdrop to `display:none` for viewports smaller than 992px.
Turns this: 
Into this:
=> Adds media query to backdrop

rundeckapp/grails-app/views/menu/_editAclFile.gsp
Fixes #5928 - Updating ACL doc links in app
These links were busted:
=> Fixes #5928 - Updating ACL doc links in app

core/src/main/java/com/dtolabs/rundeck/core/schedule/JobScheduleManager.java, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/JobSchedulerService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/JobSchedulerServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Bug fix. The use of `REQUIRES_NEW` to create executions has impacted existing code paths that were in the same unit of work. This has caused a number of scheduling issues to pop up related to transaction handling.
Jobs added to the Quartz scheduler through the existing code-path have their triggers placed into a `PENDING` trigger group, which is _paused_.
The `QuartzScheduleManager` subscribes to Grails GORM events in order to "activate" the job in the Quartz schedule after the transaction creating the `Execution` commits. This happens by rescheduling the job with a trigger set to the appropriate 
A clear and concise description of any …
=> Fix job scheduling transaction errors

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Fix #5933 
handle input param values for workflow details when there is not a workflow object in session
=> Fix #5933 wf strategy change saved without changing workflow contents

rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Fix #5945
Options variables on subject of an email notifications was not replaced by values passed by parent job.
The shared data context was not getting the base map with some context like options and global variables causing the option attributes not to be replaced in the subject of the email notification
=> Fix #5945 - Shared data context was not considering the base map with options attributes

rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy, rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy
Adds support on RundeckPluginRegistry to specify a PluginResourceLoader for plugins registered as beans from add-ons, enabling support for embedding ui-plugins into a grails addon.
This way, a grails plugin can inject a regular plugin (including UI plugins using the java interface) using a FactoryBean, and additionaly provide an implementation for the PluginResourceLoader to use with that plugin.
Example of UI plugin adapter loading resources from standard jar resources:
```
package com.rundeck.plugins.jobtags
import com.dtolabs.rundeck.core.plugins.Plugin
import com.dtolabs.rundeck.core.plugins.PluginException
import com.dtolabs.rundeck.core.plugins.PluginResourceLoader
import com.dtolabs.rundeck.plugins.ServiceNameConstants
import …
```
=> Support for loading plugin resources from addons

rundeckapp/grails-app/views/menu/jobs.gsp, rundeckapp/grails-app/views/scheduledExecution/_execOptionsFormButtons.gsp, rundeckapp/grails-app/views/scheduledExecution/show.gsp
Fix #5894 
* show spinner to indicate execution is starting
* hide buttons, and prevent double click with state variable
=> Fix #5894 prevent double click on run job button

rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy, rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy, rundeckapp/src/test/groovy/ProjectServiceTests.groovy, rundeckapp/src/test/groovy/rundeck/services/ExecutionUtilServiceTests.groovy
Fix #5943 
Temporary files are being created when deleting executions. This becomes an issue especially when the "Executions History Cleaner" feature is enabled and removes many files frequently.
The file path for the xml file created when execution finish should be determined from logFileStorageService.getFileForExecutionFiletype
The creation of the file at the end of the execution was also updated to obtain the file path in the same way instead of being constructed
=> Fix #5943 - Avoiding creating temporary files when deleting executions

rundeckapp/grails-app/assets/javascripts/menu/jobs.js, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/views/menu/_jobslist.gsp, rundeckapp/grails-app/views/menu/_workflowsFull.gsp, rundeckapp/grails-app/views/menu/jobs.gsp, rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Enhancement to improve the load time of the job list page using SCM.
`scmExportActions` and `scmImportActions` are no longer used on` jobsFragment` method if is called from the GUI (parameter `_gui_min_scm=true`).
Now on the job page the actions section looks like this:
Until the ajax call of scm return with the info (that info was already on that call, we were just using the one from the method to load that menu as son as the page load):
As usual this only affect if the SCM plugin is enabled.
fix #5967
=> Remove remaining SCM calls prior to job list on GUI

rundeckapp/grails-app/domain/rundeck/LogFileStorageRequest.groovy, rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy, rundeckapp/src/integration-test/groovy/rundeck/ExecutionIntegrationSpec.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
Fix #5081 
Add unique constraint for LogFileStorageService.execution
=> Fix #5081 log file storage request should be unique for execution

rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy, rundeckapp/grails-app/domain/rundeck/ScheduledExecutionStats.groovy, rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
Fixes #5963
Disable optimistic concurrency control on the job stats domain object. This will allow a "last writer" wins scenario but should reduce/remove update contention. If we don't necessarily care about the update order this may be a viable solution.
Solutions outlined in #5963 
https://gorm.grails.org/latest/hibernate/manual/#locking
https://gorm.grails.org/latest/hibernate/manual/#ormdsl
=> Use pessimistic locking on job stats update

rundeckapp/grails-app/services/rundeck/services/JobSchedulerService.groovy
The trigger could be gone already and is more likely under heavy activity. This would cause an `NPE` during the cleanup task.
`storeDurably()` is extraneous and shouldn't have made it in during the cluster fix. It could cause Jobs to stay in the scheduler after the triggers are removed if they are not otherwise explicitly removed.
=> Scheduler - Handle null trigger and do not store durably

rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy
Remove unnecessary warning log output in plugin loader checking
=> Plugin resource loader: remove unnecessary WARN log

rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/views/user/login.gsp, rundeckapp/src/main/groovy/rundeck/services/audit/AuditEventsService.groovy, rundeckapp/src/test/groovy/rundeck/services/audit/AuditEventsServiceSpec.groovy
Disallows submitting the login form with an empty username.
Login toggles a spinner to replace the login button so multiple form submissions cannot be attempted.
=> Fix #5938 error when logging in with empty credentials.

core/src/main/java/com/dtolabs/rundeck/core/resources/format/json/ResourceJsonFormatParser.java, core/src/test/groovy/com/dtolabs/rundeck/core/resources/format/json/ResourceJsonFormatParserSpec.groovy
fix #5988 
Some resources files were being generated with 'null' values on tag list causing an error when this files was parsed
Now 'null' values on tag list is handled to avoid errors on parser
Originally it was thought that the error could be related to the file size.
=> fix #5988 - Handling tags with null values on parser of node resource files in json format

rundeckapp/grails-app/domain/rundeck/JobExec.groovy, rundeckapp/src/test/groovy/rundeck/JobExecSpec.groovy
fix #6001 
When a job with referenced jobs is exported on Rundeck 2.x and imported on Rundeck 3.2.x, the option "Search job by" have the value 'uuid' marked instead of 'name'. The file exported have only the name of referenced jobs
If there is a name of referenced job and there is not uuid, the property useName should  be true even the useName property is null
=> Fix #6001 - useName property of referenced jobs should be true when it is null and there is name but there is not uuid on map

core/src/main/java/com/dtolabs/rundeck/core/common/ProjectNodeSupport.java, core/src/main/java/com/dtolabs/rundeck/core/resources/BaseFileResourceModelSource.java, core/src/main/java/com/dtolabs/rundeck/core/resources/FileResourceModelSource.java, core/src/main/java/com/dtolabs/rundeck/core/resources/ResourceModelSourceFactory.java, core/src/main/java/com/dtolabs/rundeck/core/resources/ResourceModelSourceService.java, core/src/main/java/com/dtolabs/rundeck/core/resources/format/ResourceFormats.java, core/src/main/java/com/dtolabs/rundeck/core/storage/StorageTreeFactory.java, core/src/main/java/com/dtolabs/rundeck/core/storage/StorageUtil.java, core/src/main/java/com/dtolabs/rundeck/core/storage/projects/ProjectStorageTree.java, core/src/main/java/com/dtolabs/rundeck/core/storage/projects/ProjectStorageTreeImpl.java, core/src/main/java/org/rundeck/app/spi/Services.java, core/src/test/groovy/com/dtolabs/rundeck/core/common/ProjectNodeSupportSpec.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/storage/StorageUtilSpec.groovy, core/src/test/java/com/dtolabs/rundeck/core/resources/TestFileResourceModelSource.java, rundeck-storage/rundeck-storage-conf/src/main/java/org/rundeck/storage/conf/PrefixPathTree.java, rundeck-storage/rundeck-storage-conf/src/main/java/org/rundeck/storage/conf/SubPathTree.java, rundeck-storage/rundeck-storage-conf/src/main/java/org/rundeck/storage/conf/TreeBuilder.java, rundeck-storage/rundeck-storage-conf/src/test/groovy/org/rundeck/storage/conf/PrefixPathTreeSpec.groovy, rundeck-storage/rundeck-storage-data/src/main/java/org/rundeck/storage/data/DataUtil.java, rundeck-storage/rundeck-storage-data/src/test/groovy/org/rundeck/storage/data/DataUtilSpec.groovy, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/services/rundeck/services/ConfigStorageService.groovy, rundeckapp/grails-app/services/rundeck/services/NodeService.groovy, rundeckapp/grails-app/services/rundeck/services/PluginService.groovy, rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy, rundeckapp/src/main/groovy/org/rundeck/app/authorization/RundeckAuthorizedServicesProvider.groovy, rundeckapp/src/test/groovy/org/rundeck/app/authorization/RundeckAuthorizedServicesProviderSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/NodeServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
* Adds SPI interfaces: ProjectStorageTree, and ResourceFormats
* ResourceFormats added to base services
* extends ResourceModelSourceFactory with a new default method `createResourceModelSource(Services,Properties)` allowing factory to receive Services instance
* Node service creates model sources with appropriate ProjectStorageTree spi instance and passes in Services
=> project storage SPI

docker/official/lib/entry.sh
It is both :) 
OpenShift Container Platform runs containers using an arbitrarily assigned user ID, this means the rundeck process will be started with an UID not equal to the rundeck user defined in the passwd. This leads to problems, for example using ssh.
Simple add a new rundeck passwd entry with the correct UID during the start of the container. 
Of course the /etc/passwd needs write permissions for the group (->'RUN chmod g=u /etc/passwd' has to be added to the Dockerfile as well)
Morge background information:
https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html#openshift-container-platform-specific-guidelines
=> Docker - Set uid in passwd for OpenShift support

rundeckapp/grails-app/services/rundeck/services/JobSchedulerService.groovy
This generally happens in dev mode when a misconfiguration causes the startup to fail after bootstrap. Jobs with a schedule were trying to be scheduled on a quart scheduler that was shutdown which causes massive stacktrace dumps.
=> Prevent attempt to schedule jobs on a quartz scheduler that is shutdown.

docker/ubuntu-base/Dockerfile
Make /etc/passwd groupwriteable thus that at starttime of the container the Rundeck user entry can be adjusted. 
That is important for the arbitrary user ID support on OpenShift (see #5440 )
=> Docker - Make /etc/passwd group writable

rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/logging/SimpleDataFilterPlugin.groovy, rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/logging/SimpleDataFilterPluginSpec.groovy
Bugfix for:
* https://github.com/rundeck/rundeck/issues/2729
* https://github.com/rundeck/rundeck/issues/5603
Add a new config value to replace any not allowed character on the key, the default value is `\s|\$|\{|\}|\\`
Also, adding a new  default pattern  for key/value capturing (to avoid capturing spaces)
=> adding an invalid key pattern to avoid characters like space on the key.

rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
When the browser is polling for logging updates on an active job,
tailExecutionOutput can be called many times in succession. Each
call leaks a file descriptor until the garbage collector cleans up
the underlying FileInputStream.
This can be easily verified by writing a long running noisy job,
trying to watch the logs in the browser, then monitoring the list
of open files using something like lsof or, on linux,
/proc/$rundeckPid/fd/.
=> Bugfix: close logread in tailExecutionOutput

rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_ja.properties, rundeckapp/grails-app/i18n/messages_pt_BR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/views/framework/projectNodeSources.gsp
* Removes "legacy" Node Config UI, which was disabled by default and only remained as a hedge against issues in the current (vue) UI.
* update current UI to clean up some styles
Style fix: current incorrect nested `card` style:
Cleaned up:
=> Remove legacy node config UI

rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy, rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy, rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
removes duplicate LogFileStorageRequest entries at bootstrap time
ref https://github.com/rundeck/rundeck/issues/5081
Find and remove any duplicate entries at startup.  Rundeck 3.2.5 and earlier had no unique constraint preventing duplicate LogFileStorageRequest entries from being created, which can occur in some conditions. Rundeck 3.2.6 added a constraint, which should prevent further duplicates from being created. However existing duplicates can still be a problem in a DB without manual removal.
This introduces a cleanup process at startup which can remove duplicates.
=> Clean up duplicate LogFileStorageRequest entries at startup

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
fix #5670
Leave `asUser` empty if not set on retry job from API.
=> fix asUser on retry job

rundeckapp/grails-app/domain/rundeck/Workflow.groovy, rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy, rundeckapp/grails-app/services/rundeck/services/ConfigStorageService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/WorkflowService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/WorkflowServiceSpec.groovy
fix https://github.com/rundeckpro/rundeckpro/issues/973
When importing a job definition, the ruleset description was lost
When handling the data map of the strategy plugin an error caused the map to become inconsistent and thus it was not possible to interpret it when loading the job.
=> Fixing the job import process where the ruleset strategy was not saved correctly

.circleci/config.yml, rundeckapp/grails-spa/package-lock.json, rundeckapp/grails-spa/package.json, rundeckapp/grails-spa/src/types.d.ts
Fix #5979 
adds markdown support for extended plugin property descriptions for Node Enhancer section
=> Fix #5979 update ui-trellis to support markdown extended property descriptions

rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
Fixes #6023
Grails GORM appears to have a bug where `Query.lock(boolean lock)` ignore `false` values. Passing in true or false always results in the `PESSIMISTIC_WRITE` lock mode being set.
This resolves the issue by leaving the argmap key out completely if locking isn't requested. A bug has been filed with GORM:
https://github.com/grails/grails-data-mapping/issues/1345
=> Fix execution stats lockmode

rundeckapp/grails-spa/src/components/execution-log/logViewer.vue
This should resolve the broken modal backdrop issue on the `execution/show` page.
=> Remove translate3d scroll fix

test/selenium/src/__tests__/selenium/visual-regression/create.test.ts
Fix selenium test issue:  expect().resolves returns promise, need to await
In case of timeout, the promise failure is not indicating the correct test
=> Fix: need to await expect resolves, bump timeouts

rundeck-storage/rundeck-storage-filesys/src/main/java/org/rundeck/storage/data/file/FileTree.java, rundeck-storage/rundeck-storage-filesys/src/main/java/org/rundeck/storage/data/file/FileTreeUtil.java, rundeck-storage/rundeck-storage-filesys/src/test/groovy/org/rundeck/storage/data/file/FileTreeSpecification.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/storage/FileStoragePlugin.groovy
Setting `0600` permissions for file system storage key content files
for issue https://github.com/rundeck/rundeck/issues/3017
using nio libraries to set the key file content permissions
=> FileSystem Key Storage permissions 

rundeckapp/grails-app/assets/scss/paper/_sidebar-and-main-panel.scss
* seems logo height was previously explicitly 75px, but is now 60px due to 5px padding + 50px a link
incorrect height on sidebar-wrapper shows as a 15px bar in Safari, although I don't see it in Chrome or Firefox
=> fix: incorrect height for sidebar wrapper

rundeckapp/build.gradle
Removes the spring boot session storage default change by dev-tools causing jetty to complain about being unable to serialize/store sessions.
Spring loaded is reportedly still the fastest reload option: https://github.com/grails/grails-core/pull/11441 .
Also increase the `bootRun` max heap. This seems to improve devmode perf particularly on first page loads and first asset access.
=> Use spring loaded instead of dev tools

core/src/main/java/com/dtolabs/rundeck/core/rules/WorkflowEngineOperationsProcessor.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/EngineWorkflowExecutorSpec.groovy
Fix https://github.com/rundeckpro/rundeckpro/issues/980
When a node with an incorrect configuration was loaded during a job execution, an exception was thrown and the execution was stuck in a loop
A "finally" clause has been added to ensure that execution will continue even if an exception is thrown in a log event call
=> Fix an issue that caused job execution to get stuck inside a loop when an exception was thrown from a log event call

core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/DescribableServiceUtil.java, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy, rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy
Fix https://github.com/rundeckpro/rundeckpro/issues/924
The first time the Job edit screen is loaded, it takes a long time to load. In some environments, it took more than 1 minute to open
These changes allow you to find a description of the plugin without having to load all plugins of a given type. Before, all plugins were loaded for each search for a description
I couldn't find the reason why this case is more critical in Windows environments
=> Avoiding loading all plugins whenever a method needs to search for a plugin description

docker/build.gradle, docker/official/Dockerfile, docker/official/README.md, docker/official/lib/entry.sh, docker/official/lib/includes/100_defaults.sh, docker/ubuntu-base/Dockerfile
Closes #6032 
* Updates base image to use Ubuntu 18.04 LTS
* Upgrades to OpenJDK 11
* Replaces deprecated JVM RAM properties with `MaxRAMPercenatage` and defaults it to 75%
=> Docker - Update to Ubuntu 18.04 and OpenJDK 11

rundeckapp/build.gradle
Fixes warning messages at startup from Java 11:
WARNING: Illegal reflective access by org.codehaus.groovy.vmplugin.v7.Java7$1 (jar:file:/Users/greg/rdinstall/rdcore/rundeck-3.3.0-7501.war!/WEB-INF/lib/groovy-2.5.6.jar!/) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
Add `Add-Opens` manifest entry to open selected modules/packages which quells the illegal reflective access warnings when running as `java -jar`
Can also be added to JVM options: `--add-opens=java.managment/com.sun.jmx.mbeanserver=ALL-UNNAMED ...` if not using `java -jar` to run the war.
Groovy 2.5 uses "illegal" reflective access …
=> Fix java 11 illegal reflective access warnings

rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/framework/ConfigFrameworkPropertyLookupFactory.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/framework/FrameworkPropertyLookupFactory.groovy, rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/internal/framework/ConfigFrameworkPropertyLookupFactorySpec.groovy
Add the setting `rundeck.loadFrameworkPropertiesFromRundeckConfig=true` to your rundeck-config.properties file.
Put your framework properties settings in rundeck-config.properties with a `fwk` prefix.
Ex. 
`fwk.framework.server.name=my-server`
`fwk.rundeck.server.uuid=a4a4af69-74d6-4319-bzb1-16eec8c742d3`
=> Ability to load framework properties from the app config sources.

rundeckapp/grails-spa/build.gradle, rundeckapp/grails-spa/packages/ui-trellis/build.gradle, rundeckapp/grails-spa/packages/ui-trellis/package.json, rundeckapp/grails-spa/packages/ui/package-lock.json, rundeckapp/grails-spa/packages/ui/package.json
Newer versions of NPM do not stomp on the `package-lock.json` file unless there is a version range conflict between it and `package.json`. Using npm install will re-use the `node_modules` directory along with the webpack cache loader dir `node_modules/.cache` for faster re-builds.
=> Build - Use npm install for development

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/jobs/JobQueryService.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
Fix https://github.com/rundeckpro/rundeckpro/issues/1019
Some changes affected the query that returns info to Dashboard page where the running jobs counter was showing zero jobs even if there are jobs running and, in addition, the schedules that was created by run job later option is not showing too.
The criteria to query jobs was fixed to get jobs running even the status of the execution is null and fixed `JobQueryService` to consider jobs executed with `run job later` option as scheduled job.
If the addon enterprise-schedules is enabled the jobs scheduled by `run job later` will not be shown on dashboard: https://github.com/rundeckpro/rundeckpro/issues/1036
=> Fix issue/1019 where running jobs is aways zero even if there are jobs running.

plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/PullAction.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy
fix #6078
Add default result when no pull action is needed in `git-import` plugin.
This is targeted to 3.2.9 and 3.3.0 leaving as draft meanwhile 3.2.8 is on testing phase.
=> Add default result for git-import pull action

rundeckapp/templates/config/log4j2.properties.template
Fix for log4j2 template where the classLength number was literally added to the message rather than limiting the class precision.
=> Fix for log4j2 template 

build.yaml
Enhancement:
upgrade py-winrm-plugin to 2.0.7
- passing env variables from rundeck to windows
- fix kerberos requirement warning message
=> upgrade py-winrm-plugin to 2.0.7

core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschNodeExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/tasks/net/ExtSSHExec.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/impl/jsch/JschNodeExecutorSpec.groovy, test/docker/dockers/hostnode/Dockerfile, test/docker/dockers/hostnode/scripts/createnode.sh
fix #4137
Jsch library has a problem with infinite timeout on channel connection, it has a hardcoded retry of 20000ms.
The solution is to use a number different to 0 on the timeout, but that has the collateral impact to throw an error previously ignored from Jsch: If the remote server is not configured to accept environment variables throws an exception.
The solution proposed is to make Environment variables optional, so you enable only if you are sure you already configured that on the server:
https://docs.rundeck.com/docs/administration/projects/node-execution/ssh.html#passing-environment-variables-through-remote-command
Another collateral effect of this change is connections with high latency that doesn't pass the variable environment has a better time on the execution of the step …
=> Accept Environment variables optional for jsch executor. fix #4137

test/testdeck/src/ClusterManager.ts, test/testdeck/src/DockerCompose.ts, test/testdeck/src/commands/cluster_commands/LogsCommand.ts
* Uses `stop` to shutdown the cluster after tests are run so logs are still available
* Adds a basic command to print the cluster logs
=> Build - Add command for printing cluster logs

rundeckapp/grails-app/conf/application.groovy
Enables the `/h2-console` in development mode
=> Enable h2 console in dev mode

rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy
Fixes #6151.
This directory is referred to in our Oracle setup docs.
=> Add creation of rd_base/server/lib directory

rundeckapp/webhooks/grails-app/services/webhooks/WebhookService.groovy
Rundeck running on postgres requires the webhook save to flush in order to save the webhook.
=> Webhook save must flush the session

docker/official/remco/templates/log4j2.properties, rundeckapp/templates/config/log4j2.properties.template
Quell a spring bean warning log message that is common for grails applications on startup. The grails guys don't appear to be in a hurry to fix it, so this log4j entry bumps the threshold to error for that particular class.
=> Quell a common grails/spring bean warning

rundeckapp/grails-app/conf/application.yml
sets default project storage to use DB which is consistent with the default configuration templates.
=> Set project storage to use db by default

core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkProjectConfig.java, core/src/test/groovy/com/dtolabs/rundeck/core/common/FrameworkProjectConfigSpec.groovy
Fix #6158 
fix storage method to set project.name after merging properties
=> Fix #6158 should not set incorrect project.name

docker/official/lib/entry.sh
Fixes #6167
Move `passwd` to a temp file under `/tmp`, process it, and then overwrite the original with it.
Cleanup the temp file afterwards.
#6163 would work however in an effort to keep everything tidy and not have duplicate entries, this solution was based off the RedHat Jupyter notebooks blog: https://www.openshift.com/blog/jupyter-on-openshift-part-6-running-as-an-assigned-user-id .
**Additional Context**
```
rundeck@a62ccb92d499:~$ cat /etc/passwd
...
rundeck:x:1234:0:rundeck user:/home/rundeck:/bin/bash
rundeck@a62ccb92d499:~$ whoami
rundeck
rundeck@a62ccb92d499:~$ echo $HOME
/home/rundeck
```
=> Docker - Process passwd update through /tmp for random uid

docker/official/remco/templates/jaas-loginmodule.conf
optional bindPassword environment variable for jass-loginmodule.
If you try to use the enterprise password encryption this value must be empty.
https://docs.rundeck.com/docs/administration/configuration/encryptable-properties.html#rundeck-enterprise-config-property-encryption
Enable the attribute  if the variable is set
=> Docker - Optional bindPassword variable for jass-loginmodule

core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionContextImpl.java, core/src/main/java/com/dtolabs/rundeck/core/execution/dispatch/OrchestratorNodeDispatcher.java, core/src/main/java/com/dtolabs/rundeck/core/execution/dispatch/ParallelNodeDispatcher.java, core/src/main/java/com/dtolabs/rundeck/core/execution/dispatch/SequentialNodeDispatcher.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/StepExecutionContext.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/ExecutionContextImplSpec.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/execution/dispatch/OrchestratorNodeDispatcherSpec.groovy, core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/TestBaseWorkflowStrategy.java, core/src/test/java/com/dtolabs/rundeck/core/tools/AbstractBaseTest.java, core/src/test/resources/com/dtolabs/rundeck/core/common/test-nodes5.xml
Fix https://github.com/rundeckpro/rundeckpro/issues/1020
When a step fail, the node where this step failed is stored in a list but, when the error handler is executed, it's executed on all nodes
the execution should consider the filtered node by selector so that error handler will be executed only on node where the step failed
=> Fix issue 1020 - Error handler on failed steps should be executed only in failed nodes

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerTests.groovy
Fix https://github.com/rundeck/rundeck/issues/5730
The criteria to query metrics have a sqlProjection that is not compatible with some databases and was returning an error 500 when this API was called
This changes is a workaround to calculate the metrics loading the data on memory avoiding using native sql on criteria. It will be executed only for databases that not support the original criteria with sqlProjection
First, I tried to change the native SQL on criteria that could be supported by any type of database but it was not possible since H2 and MySql has different behaviours on this scenario. After I tried to create a native sql to test the …
=> fix issue 5730: It's a workaround to allow calc metrics when database does not support sql contained within the criteria.

rundeckapp/grails-app/views/menu/jobs.gsp
Fixes issue when using enterprise paged job list then reverting back to grouped job list and trying to advance a page.
=> Fix for rundeckpro/969 job list paging

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/JobSchedulesService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Cleans up unnecessary modifications to domain object field ScheduledExecution.nextExecution, reduce possibility of optimistic locking failures when doing other modifications to jobs and when handling cluster reschedules.
=> cleanup: unnecessary domain model field changes removed

rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
Refreshing the domain object before saving seems to fix many of the log file storage save issues
=> Fix for LogFileStorage save issue

docker/official/lib/entry.sh
BUG: When starting the container with a different UID as 1000 (e.g. in OpenShift), the HOME environment variable is set to /.
This can lead to problems, e.g. Ansible is using ~/.ansible/tmp as local temorary directory.
simply declare it
=> Docker - Environment Variable $HOME not set

plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/BaseGitPluginSpec.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginFactorySpec.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitUtilSpec.groovy
some spurious CI test errors seem to be due to race conditions around cleaning up temp dirs for git tests, this attempts to ignore those errors
=> Attempt to fix spurious testing errors in git plugin in some test cleanup phases

core/src/main/java/com/dtolabs/rundeck/core/schedule/SchedulesManager.java, rundeckapp/grails-app/services/rundeck/services/JobSchedulesService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceIntegrationSpec.groovy
* query was not correctly selecting jobs
Fix: schedule takeover results in 0 jobs when it should match
=> Fix: schedule takeover results in 0 jobs when it should match

rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy
Fix #4085 
When log file is empty (e.g. race condition where API client reads output before any is produced), the `percentLoaded` value could return `NaN`
=> Fix #4085 empty log file causes NaN in percentLoaded value

docker/official/lib/entry.sh, docker/official/remco/templates/framework.properties, docker/official/remco/templates/jaas-loginmodule.conf, docker/official/remco/templates/log4j2.properties, docker/official/remco/templates/rundeck-config.properties
These changes make it easier to reuse the configuration templating and entry in different contexts(ie Tomcat).
=> Docker - Allow Remco templates to target different rundeck base dirs

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Significant performance enhancement for job takeover with large job/execution sets.
The current code is doing a session flush inside a loop for every job and execution that is being taken over. This session flush can take up to 2s per domain object being saved. For takeovers that deal with 100s of jobs, the takeover time can be very long. 
This change flushes the session once after all of the jobs and executions have been claimed. The session flush is necessary because a subsequent query in the reschedule code needs up to date job/execution information to schedule jobs correctly.
=> Performance enhancement for job takeover process

rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy
Fixes #6227 by converting the file path to a URI before setting the log4j2 system property. This is required on a Windows OS.
=>  Fix URI parse message on Windows for log4j2 config file

test/api/test-job-flip-scheduleEnabled-bulk.sh
This appears to mitigate cluster scheduling interfering with the bulk toggle work.
=> Test - Allow time for scheduling

rundeckapp/grails-spa/packages/ui-trellis/.storybook/main.js, rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/execution.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logEntryFlex.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue
Resolves some Safari related issues with layout:
* Content area no longer overflows when option is deselected
* Gutter ellipsis overflow fixed
* Non-content items no longer copied to clipboard
* Fixed sticky controls : https://bugs.webkit.org/show_bug.cgi?id=175029
=> Output Viewer Safari style fixes

docker/official/remco/templates/jaas-loginmodule.conf
Add / at the begining of rundeck/jaas/file/required. Without "/", the env variable is not taken in consideration
=> Docker - Add / on rundeck/jaas/file/required

rundeckapp/grails-app/assets/javascripts/executionStateKO.js, rundeckapp/grails-app/assets/javascripts/framework/adhoc.js
The conditional chaining operator is not supported by FireFox ESR(68) and other older browser versions. This code is not down-leveled.
Fixes #6232
Fixes #6230
=> Fix log viewer and adhoc command page in FireFox ESR(68)

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
fixes #6069
Fix a problem in API call
```
GET /api/14/project/[PROJECT]/executions/running
```
Entering asterisk instead of the project name generates an 500 error.
**solution implemented**
When the asterisk comes as a parameter the list of projects will be searched and those without permission will be filtered.
=> Fixes API call using asterisk #6069

rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy, rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
Fix #6239 
Converting from project storage type FS to DB now imports all config resources
Using WAR deployment in rundeck 3.2 and earlier, the default for the `rundeck.projectsStorageType` was `file` not `db` based on internal app default, whereas other install types (deb,rpm,docker) use `db` by default.
On upgrade from 3.2.x to 3.3.0, a war install using the default config value would convert from file to db, however project level ACLs were not getting converted.
**mitigation**
If you upgrade to Rundeck 3.3.0 using a war install, and did not set `rundeck.projectsStorageType` explicitly in your config file, any filesystem-stored projects would be converted to DB …
=> fix #6239 acls not imported during fs conversion upgrading from 3.2 to 3.3

rundeckapp/build.gradle, rundeckapp/templates/config/log4j2.properties.template
Set logging of interceptors to info.
Set logging of grails.util.Environment to error to avoid unhelpful warning messages.
Add more module opens for JDK 11.
=> Reduce console messages in standalone war launch

rundeck-storage/rundeck-storage-filesys/src/main/java/org/rundeck/storage/data/file/FileTree.java
Fixes #6214 startup error on Windows.
=> Ignore the unsupported exception thrown when posix file permissions are set

rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/BuilderUtil.groovy, rundeckapp/src/main/groovy/org/rundeck/app/components/JobYAMLFormat.groovy, rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/support/BuilderUtilSpec.groovy, rundeckapp/src/test/groovy/org/rundeck/app/components/JobYAMLFormatSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/audit/AuditEventsServiceSpec.groovy
Allows a user to direct the yaml exporter to trim lines before exporting in order to get a nice literal text dump of their code blocks.
The user who reported their job exporting in an unexpected format #5723 was apparently depending on the older snakeyaml lib behavior which was more lax about string space representation. The newer snakeyaml lib tries to be more accurate in its string spacing representation and defaults to the YAML double quote representation which provides the most accurate rendering of complex multiline output.
Stripping all trailing spaces on all lines seems to allow the YAML exporter to use the literal representation more deterministically.
Default for the trim spaces is off.
New Rundeck config:
`rundeck.job.export.yaml.trimSpaces=true`
=> Enhance YAML multiline export functionality

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
fixes: https://github.com/rundeck/rundeck/issues/6275
Fix a problem when to execute a job using "Remote URL options" and "Enforcing from allowed values". 
**solution implemented**
Send the "authContext" in the "ExecutionService.addRemoteOptionSelected" method as a parameter because the OptionsUtil.expandUrl method requires the variable usename of the job 
and thus don't incorrectly call the OptionsUtil.getHttpSessionInstance () method.
=> Fixes when to execute a job using "Remote URL options" #6275

plugins/object-store-plugin/build.gradle, plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/ObjectStorePlugin.groovy
The minio java client must be configured with the correct region in order to connect to non default AWS regions. This PR allows the region to be passed to the object store plugin.
=> Add ability to configure object storage plugin with a region

rundeckapp/build.gradle, rundeckapp/grails-app/conf/application.groovy
Replace ehcacheV2 dependency by using hibernate-jcache+ehcache3.
Reason: ehcache 2.10.6 includes embedded jackson-databind 2.9.6
Note: spring-security-core declares dependency on ehcache 2.10.6, which I excluded here.  This might be a problem
=> replace ehcache2 with jcache/ehcache3

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, docker/official/remco/templates/rundeck-config.properties, rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
Only apply data fixes using primary server if set.
If the Rundeck server is not configured in a cluster the fixes will be applied.
If no server is set as primary, all servers will attempt to run the fixes.
=> Allow a rundeck server to be set as primary. 

rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy
If the java tmp dir specified does not exist, try to create it on startup.
=> Fix non existant tmp dir issue

rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logBuilder.ts, rundeckapp/grails-spa/packages/ui-trellis/src/stores/ExecutionOutput.ts
Fixes #6292
Fixes rundeckpro/rundeckpro#1150
This fixes execution output not rendering in the "node view". More likely to occur with job reference steps.
The KO code uses a _cleaned_(stripped of parameters like node) step context when creating an `RDNodeStep`. The execution output store was grouping on the raw `stepctx` causing a lookup failure if it contained encoded parameters.
This change groups the output entries by the cleaned `stepctx` so the lookups will always be successful.
N/A
=> Fix node view output not rendering

rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue
Fixes #6306 
Safari fixes this cycle broke the scroller reference used for following and jumping to lines. This restores the scroller on the proper element and passes the "log" element through to the builder.
N/A
N/A
=> Fix scroller reference

build.gradle, core/build.gradle, gradle.properties, rundeckapp/build.gradle
Update okhttp, and spring security dependencies with CVEs reported by OWASP.
Prevent OWASP from scanning npm files to avoid redundant security reports.
=> OWASP dependency updates

rundeckapp/grails-app/services/rundeck/services/JobEventsService.groovy
Removes the @Transactional from JobEventsService to avoid triggering "Active Connection is required" error when withNewSession is used on a @Transactional method
Might be hitting this bug: https://github.com/grails/grails-data-mapping/issues/1234
Fixes #6310
=> Remove the @Transactional from JobEventsService

build.gradle, docker/build.gradle
Adds the following labels to the built docker image:
* `com.rundeck.version` => The Rundeck version the image was built against
* `com.rundeck.commit` => The project commit the image was built from
=> Docker - Add version and commit labels to docker image

plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy
Fix: #6349 
when serializing multiple jobs in the same dir at the same time a race
condition around the parent dir creation can cause a failure
this synchronizes creation of parent dirs
=> Fix #6349: failure to serialize jobs for git due to mkdirs

test/testdeck/src/test/selenium.ts, test/testdeck/src/util/Error.ts
Proxies calls to the Selenium driver methods and wraps them with extra error information.
In the case that a promise rejection was not handled(`await` was forgotten) the stack from the original call will be preserved in the resulting unhandled error.
In the case of `await` raising the error in the Jest test, Jest will still print the correct source lines.
Workaround for seleniumhq/selenium#7626
**Error raised in Jest test**
**Unhandled Error**
=> Enhance stack traces for selenium webdriver errors

core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmExportPlugin.java, core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmImportPlugin.java, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy, rundeckapp/grails-app/services/rundeck/services/JobEventsService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ScmService.groovy, rundeckapp/grails-app/services/rundeck/services/StoredJobChangeEvent.groovy
Fix several issues with SCM/git serialization.
=> SCM and Git plugin fixes

rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
replace real executor with mock to prevent race condition for test result
fix a flaky test
=> Fix: flaky test race condition in LogFileStorageServiceSpec

rundeckapp/grails-spa/README.md, rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue, rundeckapp/grails-spa/packages/ui-trellis/src/stores/ExecutionOutput.ts, rundeckapp/grails-spa/packages/ui/src/pages/execution-show/nodeView.ts
Fixes rundeckpro/rundeckpro#1172
Resolves infinite loading spinner when viewing an execution output node's step if there is not output for it.
The KO code needs to be updated after all output has been consumed regardless if there was any output for the step. This updates the KO code and displays a message in the viewer if there was no output loaded.
=> Display message when no log output is available

rundeckapp/grails-spa/packages/ui/src/components/tour/main.js, rundeckapp/grails-spa/packages/ui/vue.config.js
Fixes rundeckpro/rundeckpro#1200
The public path was not set correctly to load assets referenced from source files. This also needs to be set dynamically in the entry in order to account for non-bare base url paths(ie running in tomcat under `/rundeck`).
It may be cleaner to have a single webpack runtime file loaded and then set the public path once in `central/main`. This is a big runtime change to be made so close to release though.
=> Set webpack public path dynamically

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
Fixes an error caused by using the context of the parent job to evaluate if the child job can be read, this caused the child jobs ACL not be included.
An `Authcontext` is added using the user, roles, and child project to evaluate that condition.
Fix #3157
=> Fix read validation of a job from another project. #3157

rundeckapp/grails-app/conf/application.yml
Spring boot 2 changed the config path for setting http only cookies and the cookie tracking modes.
Fixes #6419
=> Migrate pre spring boot 2 cookie configs to valid configs.

core/src/main/java/com/dtolabs/rundeck/core/execution/impl/local/NewLocalNodeExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtils.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtilsSpec.groovy, core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/TestScriptFileNodeStepExecutor.java, core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/TestScriptURLNodeStepExecutor.java
Fix https://github.com/rundeckpro/rundeckpro/issues/1080
Sometimes, if there is a lot of scripts running in parallel and this scripts produce output and output erros, some lines should be printed on a single line (i.e. merging more than one line).
A newLocalExecutor had already been implemented and fixed part of the problem. However, the "chmod" command executed before the script was causing the file to be busy at the time it was called to execute. A change was made to try again after a short wait
Before was implemented a solution to capture the stdout and stderr in separate streams before this lines is printed and breaks this line to print …
=> Forcing a new attempt when to execute script and the script file is busy because of chmod command executed just before

rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/grails-app/views/framework/_projectSelect.gsp, rundeckapp/grails-app/views/framework/_projectSelectSidebar.gsp, rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
Cleanup and improve loading Project list and labels for the user session.
* fixes a Concurrent Modification Exception sometimes seen in server log at the `projects.sort()` call within gsps by ensuring session project data is sorted prior to gsp rendering
* removes extra call that loads and authorizes list of projects when loading project labels
* simplifies some code
=> Improve project list loading for user session

rundeckapp/grails-app/init/rundeckapp/init/servlet/JettyServletContainerCustomizer.groovy
bugfix: fix error creating and editing jobs for jetty form keys limit
increase jetty parameter `org.eclipse.jetty.server.Request.maxFormKeys` 
change the way notifications plugins are saved on the form 
=> fix error creating and editing jobs in 3.3.3

rundeckapp/grails-app/assets/javascripts/jobedit.js
Fix issue https://github.com/rundeck/rundeck/issues/6430
`restrictOptName` must be applied just for the option name in job edition form
apply the restrict option just  for the option name
=> restrictOptName must be applied just for option name

rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/WorkflowControllerSpec.groovy
bugfix:
When you save a step plugin with errors, and the plugin uses dynamic properties, the dynamic properties are not loaded on the form.
Call dynamic properties when the validation form returns an error
=> dynamic properties are not loaded when on form validation error

README.md
I struggled to find the appropriate way to build packages for Rundeck. This seems to work well. The existing documentation is incorrect and should either be removed, as it is confusing, or corrected.
and get feedback …
=> Add proper packaging steps to readme

rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Fix https://github.com/rundeck/rundeck/issues/6401
**Is this a bug fix, or an enhancement? Please describe.**
This is a bug that appears when a job is marked as "Incomplete" and the system sends an email notification, the problem causes the string "${globals.environment}" to appear in the subject.
The method "frameworkService.getProjectGlobals()" has been added in the code that generates the email's subject. If the method has already been called it will be not called again.
=> Fixes when send an email notification when a job is marked as "Incomplete" #6401

rundeckapp/grails-app/domain/rundeck/JobExec.groovy, rundeckapp/src/test/groovy/rundeck/JobExecSpec.groovy
Fix https://github.com/rundeck/rundeck/issues/6442
**Is this a bug fix, or an enhancement? Please describe.**
When the user imports a job definition with the "_importOptions_" flag set to "_true_", Rundeck fails to save it on the database.
Fixed the job importing logic by adding an added an alternative block to the code that obtains  "_importOptions_" from “_commands_” when there are no options on “_jobref_”
=> ImportOptios flag is not importing correctly when upload a job definition #6442

gradle.properties, rundeckapp/build.gradle, rundeckapp/grails-app/conf/application.groovy, rundeckapp/grails-app/conf/application.yml, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/HealthController.groovy, rundeckapp/grails-app/controllers/rundeck/interceptors/InterceptorHelper.groovy, rundeckapp/grails-app/init/rundeckapp/Application.groovy, rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy, rundeckapp/grails-app/init/rundeckapp/cli/CommandLineSetup.groovy, rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy, rundeckapp/grails-app/init/rundeckapp/init/RundeckWebAppInitializer.groovy, rundeckapp/grails-app/init/rundeckapp/init/prebootstrap/AddonClasspathInjectorPrebootstrap.groovy, rundeckapp/grails-app/init/rundeckapp/init/prebootstrap/InitializeRundeckPreboostrap.groovy, rundeckapp/grails-app/init/rundeckapp/init/prebootstrap/ServerLibInjectorPreBoostrap.groovy, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy, rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy, rundeckapp/src/integration-test/groovy/rundeck/init/RundeckInitializerTest.groovy, rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionsCleanUpTest.groovy, rundeckapp/src/main/groovy/org/rundeck/app/AppRestarter.groovy, rundeckapp/src/main/resources/META-INF/services/org.rundeck.app.bootstrap.PreBootstrap, rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy, rundeckapp/src/test/groovy/rundeckapp/ApplicationTest.groovy, rundeckapp/src/test/groovy/rundeckapp/init/RundeckInitializerSpec.groovy, rundeckapp/templates/config/rundeck-config.properties.template
Refactor server uuid assignment and loading.
Cleanup initialization code, and refactor it to work the same in container and non-container installations.
Add an unsecured health check endpoint.
Add cleanup code for metrics and log storage service upon server restart or shutdown.
Add plumbing for hot restart capability.
The initialization method in the FrameworkService has been removed and the serverUuid now comes from a system property that is set in the prebootstrap phase of the Rundeck startup. This helps avoid some of the issues we've had in the past with the system triggering the initialization at the wrong time.
~~The server uuid now comes from a file called `serverId` located in the server config directory. The id from framework.properties is migrated into the file if it exists. If …
=> Rundeck initialization refactoring

rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerTest.groovy
Fix https://github.com/rundeck/rundeck/issues/6436
**Is this a bug fix, or an enhancement? Please describe.**
If a node executor or file copier plugin are missing, the project's "Default Node Executor" or "Default File Copier" section will appear empty. 
This error is generated when importing a project that has a node executor or file copier plugins selected from a cluster to another cluster that does not have these plugins previously installed
Validation messages are added so that the user knows that the plugin is not available
=> Node Executor or File Copier Plugin are missing #6436

core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/AcceptsServices.java, rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/grails-app/services/rundeck/services/PluginService.groovy, rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/KeyStorageSelector.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginPropEdit.vue, rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/PluginServiceSpec.groovy
enhancement: 
* adding access to key storage for notification plugins. So, authentication parameters can be loaded from key storage
* enabling key storage selector on VUE plugin form 
Notification plugins must AcceptsServices to get access to key storage services.
```
class TestNotificationPlugin implements NotificationPlugin, AcceptsServices{
private Services services
@Override
void setServices(Services services) {
this.services = services
}
@Override
boolean postNotification(String trigger, Map executionData, Map config) {
StorageTree storageTree = this.services.getService(KeyStorageTree)
def resource = storageTree.getPassword("keys/path/sth")
.....
}
}
```
**Describe alternatives …
=> Notification plugin key storage

core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtils.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtilsSpec.groovy, core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/TestScriptFileNodeStepExecutor.java, core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/TestScriptURLNodeStepExecutor.java
Fix #6449 
The message "sync: ignoring all arguments" appears when using script-step on Rundeck 3.3.3 for some OS despite the script is running ok.
Some OS were returning a warning message because the command does not use any arguments so it was dropped. I also changed the default behavior so that sync is disabled by default and being enabled via node attribute "enable-sync = true"
=> Fix #6449 - Sync command disabled as default and without arguments

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/conf/application.groovy, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/views/scheduledExecution/_editNotificationsForm.gsp, rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginConfig.vue, rundeckapp/grails-spa/packages/ui/src/components/job/notifications/NotificationsEditor.vue, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/notification/DummyEmailNotificationPlugin.groovy, test/selenium/src/__tests__/selenium/jobs/job-notification.test.ts, test/selenium/src/pages/jobCreate.page.ts
=> Update notifications: enable vue ui in production, update selenium tests

test/selenium/src/__tests__/selenium/jobs/job-notification.test.ts, test/selenium/src/pages/jobCreate.page.ts
Add wait to make sure modal dismiss animation completes
=> Fix timing of test for new notification ui

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
Config values for project list GUI were not working, and produced a warning log:
```
[2020-09-21T13:32:36,879] WARN  services.ConfigurationService - Could not get value for property: gui.home.projectList.pagingMax
```
the static config class needed updating.
=> Fix: project list gui config values not working

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
fix for **https://github.com/rundeck/rundeck/issues/6483**
Problem:
userSummaryShowLoginStatus is not being read
Solution:
Add userSummaryShowLoginStatus and userSummaryShowLoggedUsersDefault fields to RundeckConfigBase.java class
=> User manager login status not shown

rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
GORM dirty checking wasn't picking up the changes unless the setter was used explicitly.
=> Fix #6304 where changing only the crontab would not update the scheduled execution.

rundeckapp/build.gradle, test/docker/docker-compose-api-mysql.yaml, testbuild.groovy
Removes the MySQL driver from the bundle and updates tests to use the MariaDB Connector/J driver.
=> Remove MySQL JDBC driver from bundle

rundeckapp/grails-spa/packages/ui/src/pages/repository/components/PluginCard.vue
Fix the display of Enterprise plugins when going to the "Find Plugins" page, then choosing to filter by installed and uninstalled.
=> Fix the display of Enterprise plugins when listing plugins

rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy, rundeckapp/grails-app/views/layouts/base.gsp, rundeckapp/src/integration-test/groovy/rundeck/init/RundeckInitializerTest.groovy
Fixes #6512
Update to use new context path property.
=> Fix old property for contextPath was being used to set the context ref in the UI

core/src/main/java/com/dtolabs/rundeck/core/config/Features.java, core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/interceptors/ProjectSelectInterceptor.groovy, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/grails-app/views/common/_sidebar.gsp, rundeckapp/grails-app/views/menu/home.gsp, rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/interceptors/ProjectSelectInterceptorSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy, test/api/test-metrics.sh
Add feature toggle to disable sidebar project listing, this can speed up UI when many projects are present.
rundeck.feature.sidebarProjectListing.enabled=false
Also adds feature toggle to enable session project list caching. The user session projects cache is enabled by default, but can be disabled:
rundeck.feature.userSessionProjectsCache.enabled=false
cache delay can be configured, default 5 minutes:
rundeck.userSessionProjectsCache.refreshDelay=300000
cache can be refreshed if `?refresh=true` is added to home page request URL
=> add feature toggle for sidebar project list 

rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerTests.groovy
Fix #6497 500 error if project is not found for executions query API
=> Fix #6497 500 error on exec query api for missing project

rundeckapp/src/main/groovy/org/rundeck/web/infosec/ContainerRoleSource.groovy, rundeckapp/src/test/groovy/org/rundeck/web/infosec/ContainerRoleSourceSpec.groovy
No longer checks against Rundeck ACLs for group name match.
=> Update ContainerRoleSource to return roles from Spring Security. 

core/src/main/java/com/dtolabs/rundeck/core/config/Features.java, core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/conf/application.groovy, rundeckapp/grails-app/services/rundeck/services/AuthorizationService.groovy, rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy
Preloads caches for projects and authorization at app bootstrap, to speedup user login the first time.
can be disabled with:
```properties
rundeck.feature.authorizationServiceBootstrapWarmupCache=false
#disable project cache bootstrap warmup
rundeck.feature.projectManagerServiceBootstrapWarmupCache=false
```
=> Add cache warmup at bootstrap time for auth and project services

rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
Fixes https://github.com/rundeckpro/rundeckpro/issues/1212
There is an issue when editing an option of a job where is not possible to change the its name.
Was needed to change the place of a hidden field with the original name so that this field can be passed to controller when editing the option.
=> Changing place of the hiddenField "origName" to be possible renaming options when editing a job

core/src/main/java/com/dtolabs/rundeck/core/config/Features.java, core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/assets/javascripts/menu/home.js, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/interceptors/ProjectSelectInterceptor.groovy, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/grails-app/views/common/_sidebar.gsp, rundeckapp/grails-app/views/menu/home.gsp, rundeckapp/grails-spa/packages/ui-trellis/src/components/utils/Pagination.vue, rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/interceptors/ProjectSelectInterceptorSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy, test/api/test-metrics.sh
Extends https://github.com/rundeck/rundeck/pull/6513
more improvements to project list (home) page speed
=> Project list updates

rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/execution-output-styles.scss
Fix for https://github.com/rundeckpro/rundeckpro/issues/1267
It will show all the log output when printing from the browser.
=> modified css for log output when printing screen from the browser

rundeckapp/grails-app/views/user/_user.gsp
In some cases the string returned by request.getRemoteUser() is not just a username,
which causes the username check on the user gsp template to fail and the groups column will not be shown.
Changing to check against session.user fixes the issue.
Fixes: https://github.com/rundeckpro/rundeckpro/issues/1286
=> Change username check in user gsp template

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Fixes https://github.com/rundeckpro/rundeckpro/issues/1213
File was not uploaded to a job option if it is empty
A verification was changed to allow an empty file to be uploaded.
=> Changes to allow upload an empty file to a job option.

rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy, rundeckapp/src/test/groovy/rundeckapp/init/RundeckInitializerSpec.groovy
Fixes #6543 by loading the framework.properties from the correct location in rpm and deb packages.
=> Fix server uuid loading in rpm/deb

rundeckapp/grails-app/conf/application.groovy, rundeckapp/src/test/groovy/testhelper/TestAppInitializer.groovy, rundeckapp/src/test/resources/META-INF/spring.factories
In some cases having imports from application code in the application.groovy can prevent startup. I have added a spring initializer to the test suite to do the preboot initialization instead, which fixes this issue.
=> Removes Rundeck preboot initialization from application.groovy 

rundeckapp/grails-app/views/menu/home.gsp
`projectNames` in `home.gsp` is not `null` with zero projects when running a  _build_.
Check if `null` **or** if `projectnames.Size() == 0`.
Checking in the javascript for it. Passing around empty lists is preferable to `null` though as it composes better, and appears to be the original intention.
I could not reproduce this running in development mode; the `null` check was enough. I'm not sure why this is.. I created a build to verify the issue and then created a build with the fix to verify it was resolved..
=> Fix loading zero projects

test/api/test-job-flip-scheduleEnabled.sh
Hopefully this will give enough time for the execution to happen and for the api to return the correct execution number.
=> Allow another second wait time in the schedule enabled flip test.

test/api/test-job-flip-scheduleEnabled.sh
Update timing to let scheduling operations have time to complete in flip job schedule enabled api test.
=> Flip job schedule enabled api test timing update

rundeckapp/grails-app/views/scheduledExecution/_editCrontab.gsp
Fixes #6533
The `empty` option checks the `value` property which doesn't seem to be working properly. Using `checked/unchecked` appears to be working.
=> Fix crontab everyday/everymonth checkbox fields always hidden

rundeckapp/grails-app/conf/application.groovy
Without the defaults set in `application.groovy` the project list will be disabled as well as the user session project list cache.
Setting these defaults to `true` resolves the issue in testing.
=> Set defaults for project list and cache

rundeckapp/build.gradle, rundeckapp/grails-app/conf/application.groovy
Upgrade grails mail plugin to latest, previous version used was based on a pr (via jitpack) to support java 10+, the latest released version includes that fix.
Tested mail behavior using Java 11 and local smtp server (mailslurper)
=> update mail plugin to 3.0.0, placeholders for dev mode testing

rundeckapp/grails-app/services/rundeck/services/AuthorizationService.groovy, rundeckapp/grails-app/services/rundeck/services/DbStorageService.groovy
Fixes https://github.com/rundeckpro/rundeckpro/issues/1283
If the acl policy is changed on a instance, the others instances on cluster will keep the old policy on cache and the changes will not affect them.
A new event will be triggered if acl policy changes so that all instances on a cluster have their caches cleaned
The DbStorageService was changed to refresh the resource after it is obtained from the database because the object returned did not contain the changes that had just been made in the db.
=> Sending an event to cleanup acl caches If cluster mode is active

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/AuthContextEvaluatorCacheManager.groovy, rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/AuthContextEvaluatorCacheManagerSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerTests.groovy
Fixes https://github.com/rundeckpro/rundeckpro/issues/1275
When using `ReloadablePropertyFileLoginModule`, if the user properties is changed on `realm.properties` file the changes have no effect without restart Rundeck because the ACL rules validation will already stored in cache.
Now, if roles changes the cache value will not be used.
Also removed some unused lines of codes
=> Changing to consider logged user roles for ACL cache

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
Reports the 'incomplete' status in the abort response reason field. Updates tests.
=> Report incomplete status in abort response reason

rundeckapp/grails-app/views/execution/_wfitemEdit.gsp, rundeckapp/grails-app/views/framework/_nodesEmbedKO.gsp
Fixes https://github.com/rundeckpro/rundeckpro/issues/1176
An error in the GUI was preventing the selection of a node to apply to the filter from the popup that is displayed in the matched nodes field 
Some attributes was on wrong places and it was avoinding the string values to be applied on filter inputs
=> Fixing GUI to allow select a node clicking at arrow link on matched nodes popup

core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/BaseWorkflowExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/EngineWorkflowExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/NodeFirstWorkflowExecutor.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/EngineWorkflowExecutorSpec.groovy
fixes https://github.com/rundeckpro/rundeckpro/issues/1149
The "If node set empty" setting had no effect when using Workflow Strategies other than "Node First"
The EngineWorkflowExecutor was changed to handle the workflow when no node is matched and the "if node set empty" config is marked to continue the job execution.
=> Applying "if node set empty" config for workflow strategies other than "Node First"

core/src/main/java/com/dtolabs/rundeck/core/execution/service/ProviderCreationException.java, core/src/main/java/com/dtolabs/rundeck/core/execution/service/ProviderLoaderException.java, core/src/main/java/com/dtolabs/rundeck/core/execution/service/ServiceProviderException.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/BaseProviderRegistryService.java
Fix potential issue loading plugins I encountered a runtime error during instance initialization caused by ClassNotFound exception loading a plugin, this caused the Plugins > Show Installed Plugins page to hang.  this seems like a rare occurrence, but the fix would treat it as any other failure loading plugin classes.
=> fix: Constructor.newInstance can throw runtime error, not just exception

rundeckapp/grails-app/views/layouts/base.gsp
Fixes #6538 .
It is no longer created by the bundler. Attempting to load the missing asset shouldn't have been causing perceptible performance issues though; supported by the timings that have been posted.
=> Remove vendor.js script tag from base

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/assets/javascripts/menu/aclListing.js, rundeckapp/grails-app/assets/javascripts/util/loader.js, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/views/menu/_aclListItemKO.gsp, rundeckapp/grails-app/views/menu/_aclValidationRowKO.gsp, rundeckapp/grails-app/views/menu/acls.gsp, rundeckapp/grails-app/views/menu/projectAcls.gsp, rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
* only load list of ACL names ahead of time
* defer metadata loading about ACLs (validation, structure) to on-demand when paged into view
Fix very slow loading of system ACLs page with many thousands of ACLs.
=> performance: Update ACL list GUI pages to have asynch behavior

build.yaml, testbuild.groovy
enhancement: adding the new SSHJ plugin 
https://github.com/rundeck-plugins/sshj-plugin
Node Executor/ File Copier (based on SSHJ lib) as an alternative of JSCH plugin 
* It has the same configuration name attributes as the JSCH plugin, so this [documentation](https://docs.rundeck.com/docs/administration/projects/node-execution/ssh.html) works for this plugin 
* sudo authentication is experimental
=> new sshj plugin

rundeckapp/grails-spa/packages/ui/src/components/activity/activityList.vue
Fixes #6600
Add `@click.middle` handlers to the activity rows which will open the execution in a new tab.
Add `@click.middle.stop` to the anchor to prevent the multiple tabs from opening.
=> Open execution in new tab on middle-click

plugins/object-store-plugin/build.gradle
Update testcontainers to 1.15.0 release for better mac integration.
Ensures compatibility with later versions of DockerDesktop on mac.
=> Update testcontainers to 1.15.0 release for better mac integration

rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/init/rundeckapp/Application.groovy, rundeckapp/grails-app/init/rundeckapp/init/ReloadableRundeckPropertySource.groovy, rundeckapp/grails-app/init/rundeckapp/init/RundeckConfigReloader.groovy, rundeckapp/src/test/groovy/rundeckapp/ApplicationTest.groovy, rundeckapp/src/test/groovy/rundeckapp/init/ReloadableRundeckPropertySourceSpec.groovy
rundeck-config.properties can be reloaded while Rundeck is running
=> Add the ability to reload rundeck-config.properties

rundeckapp/grails-app/services/rundeck/services/PluginService.groovy, rundeckapp/src/test/groovy/rundeck/services/PluginServiceSpec.groovy
bugfix:
* handling dynamic properties plugin errors to avoid errors in the job e…dition form page
* for mapping, the project level must be loaded before the framework level
add a try/catch block when the dynamicProperties method is called
If a plugin that implements the DynamicProperties interface has an error, an error can be triggered when in the job edit form UI. If the plugin is a Notification Plugin, the page won't be rendered
=> handling dynamicProperties plugin errors

rundeckapp/grails-app/assets/javascripts/menu/joboptions.js, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
Fixes rundeckpro/rundeckpro#1324
Is this a bugfix, or an enhancement? Please describe.
When a job has options and multivalued options with validations, if the validation of the non-multivalued options fails, all validations for the other multivalued options also fail.
was made a change on validation so If the option validation fail, it should not impact to the other options validations
Additional context
When multivalued option validation fail, the GUI it was breaking duplicating the options fields. A fix was made on javascript
=> Fixing multivalued options validation with no errors but that appear as invalid when another option (not multivalued) is invalid

rundeckapp/grails-app/domain/rundeck/StoredEvent.groovy
Remove the composite index. It is missing `topic` and isn't designed to match any particular query pattern.
Add index on `topic`, one of the more important columns to have indexed.
=> Remove composite index and add topic index

rundeckapp/grails-app/domain/rundeck/StoredEvent.groovy
Index size of `3072` can cause issues depending on database configuration and `1024` characters is likely overly large. Reduced to `255` and added extra explicit max constraints to columns.
```
CREATE TABLE `stored_event` (
`id` bigint(20) NOT NULL AUTO_INCREMENT,
`last_updated` datetime(6) DEFAULT NULL,
`meta` longtext,
`object_id` varchar(64) DEFAULT NULL,
`project_name` varchar(255) DEFAULT NULL,
`schema_version` int(11) DEFAULT NULL,
`sequence` bigint(20) DEFAULT NULL,
`server_uuid` varchar(36) DEFAULT NULL,
`severity` int(11) DEFAULT NULL,
`subsystem` varchar(128) DEFAULT NULL,
`topic` varchar(255) DEFAULT NULL,
PRIMARY KEY (`id`),
KEY `IDX2ggk8b4ha1gtyq671u34ggo40` (`project_name`),
KEY `IDXq0qhj662jxkdkydtt3ks62vy2` (`subsystem`),
KEY `IDXtol9rfxy40x2iq6xb6p557920` …
```
=> Adjust EventStore column max lengths

rundeckapp/grails-app/domain/rundeck/StoredEvent.groovy, rundeckapp/grails-app/services/rundeck/services/GormEventStoreService.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/domain/EventSeverity.groovy, rundeckapp/src/test/groovy/rundeck/GormEventStoreServiceSpec.groovy
The identity generation type of `IDENTITY` did not work with Oracle. `AUTO` in theory would pick the best strategy for the database, however Hibernate 5.0 started using a sequence table for MySQL which is undesirable due to increased locking creating an effective `serialization` situation.
This can be worked around with a `@GenericGenerator(strategy='native')` to let the db dialect advise on the best strategy, however it causes a new sequence to be created along side the GORM mapped sequence. It may have been possible to re-use the GORM sequence, however it starts to get very messy and bespoke at this point.
The JPA annotations were removed in favor of GORM entity mappings. Table creation now works on Oracle and the best ident generation strategies are used(auto gen for MySQL, sequence …
=> Remove JPA annotations from EventStore

rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
fix GUI issue introduced with https://github.com/rundeck/rundeck/pull/6642 in option form allowed values list,  which is displayed misaligned
div column overcome the limit in  allowed values list
=> allowed values list in option form is displayed misaligned  in 3.3.7 

gradle/wrapper/gradle-wrapper.properties, rundeck-authz/build.gradle, rundeck-authz/rundeck-authz-api/build.gradle, rundeck-authz/rundeck-authz-core/build.gradle, rundeck-authz/rundeck-authz-yaml/build.gradle, rundeckapp/gradle/wrapper/gradle-wrapper.properties
Gradle 5.6.4 includes support for Groovy compile avoidance and incremental compile. This can greatly reduce test and startup times.
Some refactor was necessary to get the project to configure successfully.
=> Update Gradle to 5.6.4

rundeckapp/grails-spa/packages/ui/src/components/version-notification/App.vue
Fixes https://github.com/rundeckpro/rundeckpro/issues/1386
Clicking on "Get Update" lead to oss download webpage even if the version used is the Enterprise
The link will change to enterprise url if the `_RDPRO_EDITION` property is not undefined
=> Fixing enterprise download link that was point to OSS version (update available notification)

rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logBuilder.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue
Fixes rundeckpro/rundeckpro#1334
While running a job some settings from the new execution viewer does not keep saved as being enabled/disabled during the job execution.
I.e, during job execution > select settings > uncheck Display Gutter > Gutter disappears > when output is updated it reverts back to how it was configured since job started.
Fixed by assigning the current settings props in the store to the new entries before they are pushed to the log builder
=> Fix execution log viewer not updating settings on running job

rundeckapp/grails-app/services/rundeck/services/JobSchedulerService.groovy
Fixes #6580
Use Instant.now() in JobSchedulerService
=> Fixes #6580 by using Instant.now()

rundeckapp/grails-app/init/rundeckapp/init/ReloadableRundeckPropertySource.groovy
Some property file loaders require the get method to be called to transform the value data.
This fixes an issue where the property value was not being decrypted by the encrypted property loader in pro.
https://github.com/rundeckpro/rundeckpro/issues/1456
=> Pro property loader wasn't decrypting property value

rundeckapp/grails-app/assets/stylesheets/github-markdown.css
This previously had no effect but is not a good weight for the fixed Mulish font
=> Fix bold styling in markdown

test/docker/docker-compose-api-mysql.yaml
mysql is no longer the default driver
fix pattern for sql exception check in functional test
=> WIP fix pattern for sql exception check
