core/src/main/java/com/dtolabs/rundeck/core/tasks/net/SSHTaskBuilder.java
Hello
https://github.com/rundeck/rundeck/issues/897
This is my approach to solve this issue.
=> Support ServerAliveInterval and ServerAliveCountMax

core/src/main/java/com/dtolabs/client/services/RundeckAPICentralDispatcher.java, core/src/main/java/com/dtolabs/rundeck/core/common/Framework.java, core/src/main/java/com/dtolabs/rundeck/core/common/OrchestratorConfig.java, core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionContext.java, core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionContextImpl.java, core/src/main/java/com/dtolabs/rundeck/core/execution/dispatch/NodeDispatcherService.java, core/src/main/java/com/dtolabs/rundeck/core/execution/dispatch/OrchestratorNodeDispatcher.java, core/src/main/java/com/dtolabs/rundeck/core/execution/dispatch/OrchestratorNodeProcessor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/orchestrator/OrchestratorService.java, core/src/main/java/com/dtolabs/rundeck/plugins/ServiceNameConstants.java, core/src/main/java/com/dtolabs/rundeck/plugins/orchestrator/Orchestrator.java, core/src/main/java/com/dtolabs/rundeck/plugins/orchestrator/OrchestratorPlugin.java, examples/example-java-orchestrator-plugin/pom.xml, examples/example-java-orchestrator-plugin/src/main/java/org/rundeck/plugin/example/MaxPercentageOrchestator.java, examples/example-java-orchestrator-plugin/src/main/java/org/rundeck/plugin/example/MaxPercentageOrchestatorPlugin.java, examples/example-java-orchestrator-plugin/src/test/java/org/rundeck/plugin/example/MaxPercentageOrchestatorTest.java, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/domain/rundeck/Orchestrator.groovy, rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/OrchestratorPluginService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/views/execution/_execDetails.gsp, rundeckapp/grails-app/views/execution/_execDetailsOrchestrator.gsp, rundeckapp/grails-app/views/scheduledExecution/_edit.gsp, rundeckapp/grails-app/views/scheduledExecution/_editOrchestratorForm.gsp, rundeckapp/test/unit/rundeck/controllers/ScheduledExecutionControllerTests.groovy
Hello
This is my approach to solving this use case
https://groups.google.com/forum/#!topic/rundeck-discuss/2Ck5dByfsGM
Will also supply a example orchestrator that just makes sure only a maximum percentage of the nodes get processed at once regardless of how many threads are configured.
Will supply this example once we agree on the plugin interfaces
=> adding orchestrator

RELEASE.md
=> repaired external link in release notes

docs/en/api/rundeck-api.md
I could not find this documented anywhere. Thanks to @gschueler for pointing this feature out on the mailing list.
=> Document filtering on custom attribute in the API

docs/en/api/rundeck-api.md, rundeckapp/grails-app/conf/UrlMappings.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/test/unit/rundeck/controllers/ScheduledExecutionControllerSpec.groovy, rundeckapp/test/unit/rundeck/services/ScheduledExecutionServiceSpec.groovy
=> Enhance cluster mode schedule takeover API

docs/en/administration/07-relational-database.md
Fix MySQL connector download not needed
typo
=> Documentation: MySQL connector download not usually necessary

docs/en/administration/09-authentication.md
Cribbed from http://meinit.nl/connect-rundeck-active-directory
=> Update Active Directory example configuration.

.travis.yml
https://github.com/travis-ci/travis-ci/issues/3120
=> add workaround for travis openjdk build issue

docs/en/api/rundeck-api.md, rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/src/groovy/com/dtolabs/rundeck/app/support/ExecutionQuery.groovy, rundeckapp/test/unit/com/dtolabs/rundeck/app/support/ExecutionQuerySpec.groovy, rundeckapp/test/unit/rundeck/controllers/ExecutionControllerSpec.groovy, rundeckapp/test/unit/rundeck/controllers/ExecutionControllerTests.groovy, test/api/test-execution-404.sh, test/api/test-execution-abort-404.sh, test/api/test-execution-delete-404.sh, test/api/test-execution-output-404.sh, test/api/test-execution-state-404.sh
=> execution query api for older than relative date

rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy, rundeckapp/test/unit/rundeck/services/ProjectManagerServiceSpec.groovy
=> fix #1525 project storage file read should not close stream

core/src/main/java/com/dtolabs/rundeck/core/execution/dispatch/OrchestratorNodeDispatcher.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/dispatch/OrchestratorNodeDispatcherSpec.groovy
=> Fix for orchestrator config values not being expanded

rundeckapp/grails-app/domain/rundeck/PluginMeta.groovy
=> change field mapping for jsonData for #1579

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/test/unit/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
=> fix #1508 retry failed nodes with dynamic filter and spaces in node name

core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/state/StateUtils.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/state/StepIdentifierImpl.java, core/src/main/java/com/dtolabs/rundeck/core/utils/TextUtils.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/state/StateUtilsSpec.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/utils/TextUtilsSpec.groovy, rundeckapp/grails-app/assets/javascripts/workflow.js, rundeckapp/grails-app/assets/javascripts/workflow.test.js
=> fix #1457 escape significant chars in step context ids

plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy, rundeckapp/grails-app/services/rundeck/services/ScmService.groovy, rundeckapp/test/unit/rundeck/services/ScmServiceSpec.groovy
=> fix #1624 git remote fetch error should be handled

plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy
=> fix #1515 reconfigure git scm plugin with new branch should re-clone

core/src/main/java/com/dtolabs/rundeck/core/common/ProjectNodeSupport.java, core/src/main/java/com/dtolabs/rundeck/core/resources/DelegateResourceModelSource.java, core/src/main/java/com/dtolabs/rundeck/core/resources/DirectoryResourceModelSource.java, core/src/main/java/com/dtolabs/rundeck/core/resources/ResourceModelSourceErrors.java, core/src/main/java/com/dtolabs/rundeck/core/resources/format/json/ResourceJsonFormatParser.java, core/src/test/groovy/com/dtolabs/rundeck/core/resources/DirectoryResourceModelSourceSpec.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/resources/format/json/ResourceJsonFormatParserSpec.groovy
=> fix #1828 json and directory source errors

docs/en/manual/04-jobs.md, docs/jp/manual/04-jobs.md
Refer #1781
There is a dead link on http://rundeck.org/docs/manual/jobs.html#scheduled-jobs and I fixed the dead links(both en document and jp document).
=> Fix deadlink quartz

packaging/debroot/tmp/rundeck/README
See issue #1663. Please not that I'm not a packaging expert, somebody else should review this.
=> Ensure creation of /tmp/rundeck directory

core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkBase.java, core/src/main/resources/com/dtolabs/launcher/setup/templates/framework.properties.template, core/src/main/resources/com/dtolabs/launcher/setup/templates/project.properties.template, core/src/test/groovy/com/dtolabs/rundeck/core/common/FrameworkBaseSpec.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/test/unit/ExecutionServiceSpec.groovy, rundeckapp/test/unit/ExecutionServiceTests.groovy
some cleanup and additional tests from https://github.com/rundeck/rundeck/pull/1884
ref #1629 #1270
=> Add framework and project global variables

rundeckapp/grails-app/assets/javascripts/application.js, rundeckapp/grails-app/assets/javascripts/jobedit.js, rundeckapp/grails-app/assets/javascripts/util/markdeep.js, rundeckapp/grails-app/conf/BuildConfig.groovy, rundeckapp/grails-app/conf/Config.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy, rundeckapp/grails-app/utils/rundeck/codecs/SanitizedHTMLCodec.groovy, rundeckapp/grails-app/views/common/_js.gsp, rundeckapp/grails-app/views/scheduledExecution/_edit.gsp, rundeckapp/grails-app/views/scheduledExecution/_showHead.gsp, rundeckapp/grails-app/views/scheduledExecution/create.gsp, rundeckapp/grails-app/views/scheduledExecution/edit.gsp, rundeckapp/grails-app/views/scheduledExecution/runbook.gsp
=> Improvements for runbook

rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/views/user/_user.gsp, rundeckapp/grails-app/views/user/profile.gsp, rundeckapp/test/unit/rundeck/UserTests.groovy
1699: Added drop down that enables users to switch rundeck language from their profile page.
=> Added drop down to switch language for application

core/src/main/java/com/dtolabs/rundeck/core/plugins/JarPluginProviderLoader.java, core/src/test/java/com/dtolabs/rundeck/core/plugins/TestJarPluginProviderLoader.java
Hi @gschueler @miguelantonio 
Enhanced error message to be more informative with appending "expected class YY, with a public constructor with no parameters"
=> 1894: Enhanced error message

rundeckapp/grails-app/assets/javascripts/executionStateKO.js, rundeckapp/grails-app/assets/javascripts/ko/binding-popover.js, rundeckapp/grails-app/assets/javascripts/util/testing.js, rundeckapp/grails-app/assets/javascripts/workflow.js, rundeckapp/grails-app/assets/javascripts/workflow.test.js, rundeckapp/grails-app/conf/Config.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy, rundeckapp/grails-app/services/rundeck/services/feature/FeatureService.groovy, rundeckapp/grails-app/taglib/rundeck/FeatureTagLib.groovy, rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy, rundeckapp/grails-app/views/common/_js.gsp, rundeckapp/grails-app/views/execution/_nodeCurrentStateSimpleKO.gsp, rundeckapp/grails-app/views/execution/_showFragment.gsp, rundeckapp/grails-app/views/execution/_wfstateNodeModelDisplay.gsp, rundeckapp/grails-app/views/execution/_wfstateSummaryDisplay.gsp, rundeckapp/grails-app/views/execution/show.gsp, rundeckapp/test/unit/rundeck/services/ConfigurationServiceSpec.groovy, rundeckapp/test/unit/rundeck/services/feature/FeatureServiceSpec.groovy, rundeckapp/web-app/js/executionControl.js
fix #1370 #667 
* load correct step descriptions instead of only showing the top-level job reference name
* Show more context information about steps in the Monitor tab
* show full path within workflow
* link to job references
Previous UI behavior can be restored using: `rundeck.feature.workflowDynamicStepSummaryGUI.enabled=false`
=> Enhance execution step summary display

rundeckapp/grails-app/conf/BuildConfig.groovy, rundeckapp/grails-app/views/common/_topbar.gsp
=> upgrade asset-pipeline for #1326

plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/ImportJobs.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy
=> only compare existing commit id if import url matches and commit exists

plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BuilderUtil.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/exp/actions/CommitJobsAction.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/exp/actions/FetchAction.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/exp/actions/PushAction.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/exp/actions/SynchAction.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/exp/actions/TagAction.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/FetchAction.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/ImportJobs.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/PullAction.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/SetupTracking.groovy
=> git plugin: remove static imports in groovy code

rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
fixes a minor firefox css bug with the filter label on the execution screen,
=> firefox GUI fix

rundeckapp/grails-app/controllers/rundeck/controllers/StorageController.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/app/support/StorageParams.groovy, rundeckapp/test/unit/rundeck/controllers/StorageControllerSpec.groovy, rundeckapp/test/unit/rundeck/controllers/StorageControllerTests.groovy
fix api storage key path endpoints from allowing blank path
=> key storage api: fix blank resource path bug

core/src/main/java/com/dtolabs/rundeck/core/dispatcher/DataContextUtils.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/common/DefaultFileCopierUtil.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/common/FileCopierUtil.java, core/src/main/java/com/dtolabs/rundeck/core/execution/script/ScriptfileUtils.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/RemoteScriptNodeStepPluginAdapter.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtils.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/ScriptFileNodeStepExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/ScriptFileNodeStepUtils.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/ScriptURLNodeStepExecutor.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/RemoteScriptNodeStepPluginAdapterSpec.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtilsSpec.groovy, core/src/test/java/com/dtolabs/rundeck/core/dispatcher/TestDataContextUtils.java, docs/en/administration/03-configuration.md, docs/en/manual/04-jobs.md
=> Add global setting to disable inline script token expansion

core/src/main/resources/com/dtolabs/launcher/setup/templates/server-log4j.properties.template, packaging/debroot/etc/rundeck/log4j.properties, packaging/debroot/etc/rundeck/rundeck-config.properties, packaging/root/etc/rundeck/log4j.properties, packaging/root/etc/rundeck/rundeck-config.properties, rundeck-launcher/launcher/src/main/java/com/dtolabs/rundeck/ExpandRunServer.java, rundeck-launcher/launcher/src/main/resources/templates/config/rundeck-config.properties.template, rundeck-launcher/launcher/src/main/resources/templates/exp/webapp/WEB-INF/classes/log4j.properties.template, rundeckapp/grails-app/conf/BuildConfig.groovy, rundeckapp/grails-app/conf/Config.groovy, rundeckapp/grails-app/conf/DataSource.groovy
=> Upgrade h2 lib to 1.4.187

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
=> don't block all jobs when checking for multiple executions

docker/debinstall/Dockerfile, docker/debinstall/Readme.md, docker/debinstall/entry.sh, docker/package/Dockerfile, docker/package/Readme.md, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/test/integration/rundeck/services/ScheduledExecutionServiceTest.groovy
=> Fix takeover schedule repeating for a job

.travis.yml, packaging/debroot/etc/rundeck/profile, packaging/root/etc/rundeck/profile, run-docker-ssl-tests.sh, rundeck-launcher/rundeck-jetty-server/src/main/java/com/dtolabs/rundeck/RunServer.java, test/docker/docker-compose-multinode-test.yml, test/docker/docker-compose-ssl-test.yml, test/docker/dockers/rundeck/scripts/run_tests.sh, test/docker/dockers/rundeck/scripts/start_rundeck.sh, test/docker/dockers/rundeck/tests/run-tests.sh, test/docker/dockers/rundeck/tests/ssltests/basic-client-test.sh, test/docker/test-ssl.sh
=> 2.7.0: Fix ssl connector setup

packaging/debroot/etc/init/rundeckd.conf
fix for https://github.com/rundeck/rundeck/issues/2242
=> Fix upstart issue

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/test/unit/rundeck/services/ScheduledExecutionServiceSpec.groovy
=> Fix #2277 upload job definition should overwrite timeout/retry

rundeckapp/grails-app/conf/UrlMappings.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy, rundeckapp/grails-app/views/menu/wait.gsp
Use url mapping parameter instead of method argument
=> Fix #2249 Project archive download shows Not Found error

packaging/debroot/DEBIAN/control
Add missing dependency. See:
https://github.com/rundeck/rundeck/issues/2316
=> Issue 2316: add missing dependency of uuid-runtime

rundeckapp/grails-app/conf/ClusterEvents.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/test/unit/ExecutionServiceSpec.groovy, rundeckapp/test/unit/rundeck/controllers/ExecutionControllerTests.groovy, rundeckapp/test/unit/rundeck/quartzjobs/ExecutionJobSpec.groovy, rundeckapp/test/unit/rundeck/services/ScheduledExecutionServiceSpec.groovy
=> Improve abort action robustness and cluster mode behavior

docs/en/administration/07-relational-database.md, docs/jp/administration/07-relational-database.md
Page was moved on dev.mysql.com side.
=> Fix URL for MySQL JDBC Connector docs

.travis.yml, README.md, gradle/java.gradle, test/docker/dockers/rundeck/scripts/run_tests.sh
=> Build with Java 8

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/views/framework/_editProjectForm.gsp, rundeckapp/grails-app/views/menu/_groupTree.gsp, rundeckapp/grails-app/views/menu/_workflowsFull.gsp, rundeckapp/grails-app/views/menu/admin.gsp, rundeckapp/grails-app/views/menu/jobs.gsp
=> fix #921 add project.jobs.gui.groupExpandLevel configuration

docs/en/api/rundeck-api.md, rundeckapp/grails-app/conf/UrlMappings.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy, rundeckapp/grails-app/views/menu/admin.gsp, rundeckapp/src/groovy/com/dtolabs/rundeck/app/api/project/ProjectExport.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/app/support/ProjectArchiveParams.groovy, rundeckapp/test/unit/rundeck/controllers/ProjectControllerSpec.groovy, rundeckapp/test/unit/rundeck/controllers/ProjectControllerTest.groovy
* update API to support the inclusion options
* update API to support async export
=> Add options to project archive export

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy, rundeckapp/grails-app/domain/rundeck/BaseReport.groovy, rundeckapp/grails-app/domain/rundeck/ExecReport.groovy, rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/domain/rundeck/Workflow.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ReportService.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/app/support/DomainIndexHelper.groovy
* Add some database index definitions
* simplify/improve some queries
=> Improve slow db queries related to activity page and home page

rundeckapp/grails-app/assets/javascripts/user/profile.js
=> Fix for Admin tokens

core/src/main/java/com/dtolabs/rundeck/core/utils/PropertyLookup.java
force deferred properties loading for properties map
=> Potential fix to #2538

rundeckapp/grails-app/assets/javascripts/menu/joboptions.js, rundeckapp/grails-app/assets/javascripts/menu/joboptionsTest.js, rundeckapp/grails-app/assets/javascripts/util/testing.js
=> Remote Option selected values fixes

docs/en/administration/03-configuration.md
Token that don't expire documentation
=> Token documentation

rundeckapp/grails-app/utils/rundeck/codecs/AnsiColorCodec.groovy, rundeckapp/grails-app/utils/rundeck/codecs/AnsiColorStripCodec.groovy
=> ignore clear screen ansi code

docs/en/manual/05-nodes.md
s/do do/to do/
s/sufficeint/sufficient/
=> typos in 05-nodes

docs/en/manual/05-nodes.md
=> typo: Columned

docs/en/manual/05-nodes.md
=> typo: diaglog

docs/en/manual/04-jobs.md
=> typo: sytanxes

docs/en/manual/04-jobs.md
=> typo: usernae

packaging/rundeck.spec
fixes https://github.com/rundeck/rundeck/issues/1590
=> added web.xml to rpmbuild spec so it doesnt get replaced on update

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/server/plugins/logging/SimpleDataFilterPlugin.groovy
data capture adds data as it is captured
fix #1780
=> fix: mask passwords plugin not applied at top level

packaging/rundeck.spec
Fix #2666  
This reverts commit df1e8d3ca5b7b3de0875124e91471fb6fa9dff53.
=> Revert "added web.xml to rpmbuild spec so it doesnt get replaced on update"

docs/en/administration/09-authentication.md
=> Fix jetty-all jar version

docs/en/api/rundeck-api.md, rundeckapp/grails-app/conf/UrlMappings.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy, rundeckapp/test/unit/rundeck/controllers/UserControllerSpec.groovy
New API endpoint for get user profile and update data.
Get same user profile data.
**Request:**
GET /api/20/user/info/
**Response:**
Success response, with profile data:
`Content-Type: application/xml`:
~~~ {.xml}
<user>
<login>user</login>
<firstName>Name</firstName>
<lastName>LastName</lastName>
<email>user@server.com</email>
</user>
~~~
`Content-Type: application/json`:
~~~ {.json}
{
"login":"user",
"firstName":"Name",
"astName":"LastName",
"email":"user@server.com"
}
~~~
Get another user profile data. Requieres system `admin` permission.
**Request:**
GET /api/20/user/info/[User]
**Response:**
Success response, with profile data:
`Content-Type: application/xml`:
~~~ {.xml}
<user>
<login>user</login>
<firstName>Name</firstName>
<lastName>LastName</lastName> …
=> Api endpoint to modify user profile.

docs/en/manual/02-getting-help.md
=> Fix link in manual/getting-help

docs/en/manpages/man5/job-v20.md
=> Fix link in man5/job-xml

core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionContextImpl.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/ExecutionContextImplSpec.groovy
=> fix #2766 don't modify original data context

docs/en/manpages/man5/job-yaml-v12.md
=> Fix typo/link in man5/job-yaml

rundeckapp/grails-app/assets/javascripts/menu/aclListing.js, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/views/menu/_aclListItemKO.gsp, rundeckapp/grails-app/views/menu/_aclValidationRowKO.gsp, rundeckapp/test/unit/rundeck/controllers/MenuControllerSpec.groovy
Show description for each policy in files
=> Display description for each policy doc in file

core/src/main/java/com/dtolabs/rundeck/core/authorization/providers/YamlParsePolicy.java
=> Revert "Simple syntax error messages on ACL"

core/src/main/java/com/dtolabs/rundeck/core/authorization/providers/YamlParsePolicy.java
=> Revert "Revert "Simple syntax error messages on ACL""

core/src/test/groovy/com/dtolabs/rundeck/core/authorization/providers/YamlProviderSpec.groovy
Missing spec modification from last PR
=> Fix for #2830

core/src/main/java/com/dtolabs/rundeck/core/common/ProjectNodeSupport.java
=> Fix: model source plugin failure should log project name

docs/en/administration/13-tuning-rundeck.md
Delete last whitespace
Update dead link
Fix http to https
=> Improve document in administration/tuning-rundeck

docs/en/administration/14-scaling-rundeck.md
Delete last whitespace
Fix http to https
=> Improve document in administration/scaling-rundeck

docs/en/administration/16-email-settings.md
Update link
Delete last whitespace
=> Improve document in administration/email-settings

rundeckapp/grails-app/controllers/rundeck/controllers/ControllerBase.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy
=> Fix potential RXSS

docs/en/administration/18-localization.md
Update links
Delete last whitespace
=> Improve document in administration/localization

docs/en/tutorials/project-setup.md
=> Improve document in tutorials/project-setup

docs/en/api/rundeck-api.md
Fix typos
Upgrade links
Delete last whitespaces
=> Improve document in api/index

core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/engine/StepOperation.java, core/src/main/java/com/dtolabs/rundeck/core/logging/OverridableStreamingLogWriter.java, core/src/main/java/com/dtolabs/rundeck/core/rules/WorkflowEngine.java, core/src/test/groovy/com/dtolabs/rundeck/core/logging/OverridableStreamingLogWriterSpec.groovy, rundeckapp/grails-app/services/rundeck/services/LoggingService.groovy, rundeckapp/grails-app/services/rundeck/services/logging/MultiLogWriter.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/app/internal/logging/FSStreamingLogWriter.groovy, rundeckapp/test/unit/rundeck/services/LoggingServiceTests.groovy, rundeckapp/test/unit/rundeck/services/logging/MultiLogWriterSpec.groovy
=> Fix logging issues

docs/en/developer/01-plugin-development.md
=> Improve document developer/plugin-development

docs/en/developer/02-plugin-annotations.md
=> Improve document developer/plugin-annotations

docs/en/developer/03-model-source-format-parser-generator-plugins.md
=> Improve document in developer/model-format-parser-and-generator-plugin

docs/en/developer/03-model-source-plugins.md
=> Improve document developer/resource-model-source-plugin

docs/en/developer/04-file-copier-plugins.md
=> Improve document developer/file-copier-plugin

docs/en/developer/04-node-execution-plugins.md
=> Improve document developer/node-executor-plugin

docs/en/administration/storage-facility.md
=> Improve document in administration/storage-facility

docs/en/administration/project-setup.md
=> Improve document in administration/project-setup

docs/en/developer/10-scm-plugins.md
=> Improve document developer/scm-plugins

docs/en/developer/09-orchestrator-plugin.md
=> Improve document developer/orchestrator-plugin

docs/en/developer/08-storage-converter-plugins.md
=> Improve document developer/storage-converter-plugin

core/build.gradle, core/src/main/java/com/dtolabs/shared/resources/ResourceXMLGenerator.java, packaging/rundeck.spec, rundeckapp/grails-app/conf/BuildConfig.groovy, rundeckapp/grails-app/conf/spring/resources.groovy
update/remove some dependencies:
- dom4j 1.6.1 -> 2.1.0
- xerces->remove
- xml-apis->remove
- jaxen->remove
- xom -> grails code-coverage plugin -> remove
=> Dependency cleanup

rundeckapp/build.gradle, testbuild.groovy
Include Editable S3 resource model source v1.0 of [rundeck-plugins/aws-s3-model-source](https://github.com/rundeck-plugins/aws-s3-model-source)
=> Include aws resource model source plugin

docs/en/administration/07-relational-database.md
=> Fix links in administration/setting-up-an-rdb-datasource

rundeckapp/src/groovy/com/dtolabs/rundeck/app/support/PluginResourceReq.groovy, rundeckapp/test/unit/com/dtolabs/rundeck/app/support/PluginResourceReqSpec.groovy
* improve path validation regex 
* add tests
=> fix: plugin resource file path validation regex slowness

docs/en/developer/01-plugin-development.md, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/views/common/_js.gsp, rundeckapp/grails-app/views/menu/_jobslist.gsp, rundeckapp/grails-app/views/menu/_workflowsFull.gsp, rundeckapp/grails-app/views/menu/jobs.gsp, rundeckapp/test/unit/rundeck/controllers/MenuControllerSpec.groovy
Moved the file status of the SCM plugin from the job list controller to a new ajax call, reducing the load time of the job list.
Plus a new button on the Job Actions menu to enable/disable the SCM in a fast way.
=> Scm speed enhancement

core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmExportPlugin.java, core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmImportPlugin.java
To prevent compilation error on others SCM plugins
=> Default to cluster fix methods

rundeckapp/grails-app/domain/rundeck/User.groovy, rundeckapp/test/unit/rundeck/UserTests.groovy
Accented and foreign characters on `User` `firstName` and `lastName`.
Fix #1581
=> Accents into firstName and lastName

rundeckapp/grails-app/assets/javascripts/menu/joboptions.js, rundeckapp/grails-app/domain/rundeck/Option.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/views/framework/_jobOptionsKO.gsp, rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp, rundeckapp/grails-app/views/scheduledExecution/_optionsSummary.gsp, rundeckapp/test/unit/rundeck/services/ScheduledExecutionServiceSpec.groovy
Added label to option.
The new label, if not empty, is displayed instead of the option name on the job page. If its empty, the job name will be displayed as usual.
On edit:
On run:
=> Option "label" field for display name

.travis.yml
whitespace changes from travis cli tool
=> Add slack integration to travis

core/src/main/java/com/dtolabs/rundeck/plugins/scm/JobImporter.java, core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmExportPlugin.java, core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmImportPlugin.java, core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmImportTrackedItem.java, core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmImportTrackedItemBuilder.java, docs/en/api/rundeck-api.md, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/ImportJobs.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/SetupTracking.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ScmService.groovy, rundeckapp/grails-app/services/rundeck/services/scm/ContextJobImporter.groovy, rundeckapp/grails-app/services/rundeck/services/scm/ResolvedJobImporter.groovy, rundeckapp/grails-app/services/rundeck/services/scm/ScmJobImporter.groovy, rundeckapp/grails-app/views/scm/_statusIcon.gsp, rundeckapp/grails-app/views/scm/performAction.gsp, rundeckapp/src/groovy/com/dtolabs/rundeck/app/api/scm/ScmExportActionItem.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/app/api/scm/ScmImportActionItem.groovy
Option to delete job when the Git file is removed.
Fix an unusual bug when creating a job. 
Sporadically, duplicate definition files were created, causing the message "Modified" to appear on the job list page, without any associated job:
=> Scm usability enhancements

docs/en/administration/project-setup.md
https://github.com/rundeck/rundeck/issues/3227
=> Correct storage type from "filesystem" to "file" (Documentation only)

core/src/main/java/com/dtolabs/rundeck/core/common/PluginControlService.java, core/src/main/java/com/dtolabs/rundeck/core/common/PluginDisabledException.java, core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionContext.java, core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionContextImpl.java, core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionServiceImpl.java, core/src/main/java/com/dtolabs/rundeck/core/logging/LoggingManagerImpl.java, core/src/main/java/com/dtolabs/rundeck/core/logging/PluginFilteredStreamingLogWriter.java, core/src/main/java/com/dtolabs/rundeck/plugins/ServiceNameConstants.java, docs/en/administration/10-authorization.md, rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
modify documentation to avoid running commands or jobs on the rundeck server
=> add doc: prevent local rundeck execution (acls)

rundeckapp/grails-app/assets/javascripts/executionControl.js
wonder if these show up the same for everyone?
⏱ ⛔
=> Add unicode icons to HTML page title for execution results

core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschNodeExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschScpFileCopier.java
adding passphrase storage in simple configuration GUI: 
https://github.com/rundeck/rundeck/issues/3051
=> adding passphrase storage in simple configuration GUI

rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/test/unit/rundeck/controllers/MenuControllerSpec.groovy
Fix for project label and description on new projects after prerelease merge.
=> Fix label description 2.11

rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/test/unit/rundeck/controllers/FrameworkControllerSpec.groovy
Fix #3256 
The description is returned as a parameter to the view when some error appears on the creation of the project.
=> Fix Bug 3256

rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy, rundeckapp/test/unit/rundeck/controllers/ScmControllerSpec.groovy
Fix null pointer on git-import manual fetch when the tracking items list is empty.
#3273
=> Fix git-import plugin error 

rundeckapp/grails-app/assets/javascripts/jobedit.js, rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/test/unit/rundeck/ExecutionTest.groovy
https://github.com/rundeck/rundeck/issues/3207
=> Add "Initial Execution ID" as a context variable for Job Retries jobs:

rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/test/unit/ExecutionServiceSpec.groovy, rundeckapp/test/unit/rundeck/controllers/ReportsControllerSpec.groovy
=> Job Ref Stats on multiple threads

plugins/orchestrator-plugin/src/main/java/org/rundeck/plugin/example/RandomSubsetOrchestratorPlugin.java
Improve the reproducible seed generation, use bytes from a SHA1 digest
=> Fix random orchestrator to improve the reproducible seed generation

rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
Force session for options on `edit` page.
=> Fix exception saving a job when there is an error

rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy, rundeckapp/test/unit/rundeck/services/ExecutionUtilServiceTests.groovy
Fix #2976 Project automatically added to job's definition after execution of nest referenced job.
=> Fix #2976 

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/views/menu/jobs.gsp, rundeckapp/test/unit/rundeck/controllers/MenuControllerSpec.groovy
=> Slowness on projects with many jobs

rundeckapp/build.gradle, testbuild.groovy
- Upgrading ansible plugin to 2.3.0 (as 2.11.x)
For https://github.com/rundeck/rundeck/issues/3361
=> - Adding missing plugins: openssh-node-exec, py-winrm

rundeckapp/build.gradle
=> grails3: include springboot repackaged war for archive upload

rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy, rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy, test/api/test-project-space-in-name-fails.sh
Respond with error when create project api is called with an invalid project name.
=> Fix #3423 by responding with error 

rundeckapp/build.gradle
=> JDK10 fixes

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Fixes ExecutionServiceSpec tests that weren't running.
=> Fix #3450. ExecutionServiceSpec tests now run correctly.

rundeckapp/grails-app/init/rundeckapp/WarInitializer.groovy
Addresses feature attempted by user in PR: https://github.com/rundeck/rundeck/pull/3438
=> Fix #3461. Add support for ServletContext init params.

rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy
Use system property if specified.
=> Fix #3466. Use configured value if present.

core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkProject.java, core/src/main/java/com/dtolabs/rundeck/core/utils/ZipUtil.java, core/src/test/groovy/com/dtolabs/rundeck/core/utils/ZipUtilSpec.groovy, core/src/test/java/com/dtolabs/rundeck/core/common/TestFrameworkProject.java, rundeck-launcher/launcher/src/main/java/com/dtolabs/rundeck/ZipUtil.java, rundeck-storage/rundeck-storage-filesys/src/main/java/org/rundeck/storage/data/file/FileTree.java, rundeck-storage/rundeck-storage-filesys/src/test/groovy/org/rundeck/storage/data/file/FileTreeSpecification.groovy, rundeckapp/grails-app/services/rundeck/services/DbStorageService.groovy, rundeckapp/src/groovy/com/dtolabs/rundeck/util/ZipReader.groovy, rundeckapp/test/unit/rundeck/services/DbStorageServiceTests.groovy
Fixes #3471 Zip Slip vulnerability for 2.11 branch
Validate zip file destination with target dir.
Cherry pick some changes from master and add some cleanup
=> backport: Zip Slip fix for 2.11

rundeckapp/build.gradle, testbuild.groovy
Update some dependencies flagged by snyk
=> Dependency upgrades

core/build.gradle, gradle.properties, plugins/copyfile-plugin/build.gradle, plugins/git-plugin/build.gradle, plugins/job-state-plugin/build.gradle, plugins/localexec-plugin/build.gradle, plugins/upvar-plugin/build.gradle, rundeck-storage/build.gradle, rundeckapp/build.gradle
Synchronize the groovy version used by all gradle projects to 2.4.15, to make sure the same groovy version libs are included in the artifacts for both Rundeck Core and Pro.
Build dependency changes
=> Update and synch groovy version used for all projects to 2.4.15

rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy
=> Fix #3500. Moved install marker to var.

rundeckapp/grails-app/views/menu/acls.gsp
Fix js error on System Acl page.
Relocate gsp template with modal definition
=> fix: #3541 js console error on system acls page

rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
Fix #3538 node filter select all /select none buttons don't work
Fix css selectors used.
=> Fix selectors for node filter select buttons fixes #3538

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/SaveProjAclFile.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/SaveSysAclFile.groovy
Fix #3535
Removed error 500 for NPE and correct validation of fields
=> rd3 Upload ACL File

rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy
Fix #3490 
Use correct app metadata key for version info.
=> fix #3490 read correct app metadata key for version

rundeckapp/grails-app/domain/rundeck/Project.groovy, rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy, rundeckapp/grails-app/domain/rundeck/Storage.groovy, rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/views/menu/_workflowsFull.gsp, rundeckapp/grails-app/views/menu/jobs.gsp
Implements #2113 by adding a feature switch that can enable job pagination.
Also adds indexes on frequently queried columns.
=> Feature switch to enable job pagination

rundeckapp/grails-app/assets/javascripts/jobedit.js
Fix some issues with new drag and drop in workflow editor:
=> Fix wf/opts dragdrop issues

rundeckapp/grails-app/views/menu/_editAclFile.gsp, rundeckapp/grails-app/views/menu/createProjectAclFile.gsp
Fix typo and some layout issues for Project Acls.
=> Fix Project ACL editor page layout

rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
Fixing https://github.com/rundeck/rundeck/issues/3566
=> Fix for Job Execution Page, Report Tab , Node output

rundeckapp/grails-app/views/execution/_showFragment.gsp
for https://github.com/rundeck/rundeck/issues/3560
=> fixing rd3: The "node" checkbox in the Execution view options 

rundeckapp/grails-app/views/menu/_projectImportForm.gsp, rundeckapp/grails-app/views/menu/executionMode.gsp
=> Fix Radio button labels on import project file and execution mode.

rundeckapp/grails-app/conf/application.groovy, rundeckapp/grails-app/conf/application.yml, rundeckapp/grails-app/controllers/rundeck/interceptors/ApiAccessInterceptor.groovy, rundeckapp/grails-app/controllers/rundeck/interceptors/AuthorizationInterceptor.groovy, rundeckapp/grails-app/controllers/rundeck/interceptors/ControllerBaseInterceptor.groovy, rundeckapp/grails-app/controllers/rundeck/interceptors/FormTokenInterceptor.groovy, rundeckapp/grails-app/controllers/rundeck/interceptors/InterceptorHelper.groovy, rundeckapp/grails-app/controllers/rundeck/interceptors/ProjectSelectInterceptor.groovy, rundeckapp/grails-app/controllers/rundeck/interceptors/RefererInterceptor.groovy, rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy, rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy, rundeckapp/grails-app/views/common/_sidebar.gsp
=> Fix /favicon.ico error

rundeckapp/build.gradle, rundeckapp/metricsweb/build.gradle, rundeckapp/metricsweb/src/main/groovy/metricsweb/MetricswebGrailsPlugin.groovy
Register metrics servlet for grails 3
Fix #3584
=> rd3 metrics endpoints

rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
=> Add API version to System Report

rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy, rundeckapp/grails-app/domain/rundeck/AuthToken.groovy
Fix #3601 
Sanitize logging of auth token strings.
=> Fix #3601 sanitize logging of auth tokens

core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmExportPlugin.java, core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmImportPlugin.java, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy, rundeckapp/grails-app/services/rundeck/services/ScmService.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
fix #3623 problem with https configuration on `clusterFixJobs`
=> Fix for 3623

rundeckapp/grails-app/assets/javascripts/jobedit.js
=> Fix #3646 wf editor drag and drop works in firefox

rundeckapp/grails-app/views/common/_sidebar.gsp, rundeckapp/grails-app/views/user/login.gsp
=> Add element ids to nav links and login page.

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
Fix Error message: ORA-01795 in `menu/home` with Oracle database over 1000 projects.
For release `2.11`
=> Fix Error message: ORA-01795

rundeckapp/grails-app/domain/rundeck/ReferencedExecution.groovy, rundeckapp/test/unit/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Backport of #3652 fix #3474 for release 2.11
=> NPE on referenced Job

rundeckapp/grails-app/views/scheduledExecution/_editForm.gsp
Fix "Not found" when pressing cancel on job edit view in French or Spanish
=> Action to Cancel button

packaging/Makefile
=> Fit date into package versions.

rundeckapp/grails-app/services/rundeck/services/NodeService.groovy, rundeckapp/src/test/groovy/rundeck/services/NodeServiceSpec.groovy
Fix #3675 
* Change default app-level config to firstLoadAsynch=false
* Add project-level config `project.nodeCache.firstLoadSynch` to set on per-project basis
**Documentation**
forthcoming..
=> Fix #3675 change default to firstLoadAsynch=false, add project config

core/src/main/java/com/dtolabs/rundeck/core/execution/service/FileCopierService.java, core/src/main/java/com/dtolabs/rundeck/core/execution/service/NodeExecutorService.java
=> Fix broken project config edit page

rundeckapp/grails-app/views/scm/performAction.gsp
Working checkboxes on git plugins
=> fix scm plugin working checkboxes

.github/mergeable.yml
Adds the mergeable config https://github.com/jusx/mergeable
=> Add mergeable config

rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp
Fix #3715 
Remove extra encoding required to fix a grails 2 bug no longer present in grails 3
ref issue: https://github.com/grails/grails-core/issues/10256
=> Fix #3715 revert extra encoding for grails bug

test/api/test-metrics.sh
=> Fix metrics api tests again

grails-persistlocale/build.gradle, grails-persistlocale/gradle.properties, grails-persistlocale/grails-app/conf/application.yml, grails-persistlocale/grails-app/conf/logback.groovy, grails-persistlocale/grails-app/controllers/grails/persistlocale/UrlMappings.groovy, grails-persistlocale/grails-app/init/grails/persistlocale/Application.groovy, grails-persistlocale/grails-app/init/grails/persistlocale/BootStrap.groovy, grails-persistlocale/grails-app/views/error.gsp, grails-persistlocale/grails-app/views/index.gsp, grails-persistlocale/grails-app/views/layouts/main.gsp, grails-persistlocale/grails-app/views/notFound.gsp, grails-persistlocale/src/main/groovy/grails/persistlocale/PersistlocaleGrailsPlugin.groovy, rundeckapp/build.gradle, rundeckapp/grails-app/views/user/profile.gsp, settings.gradle
Fix #3410 
* Persist the locale using cookies
* use `en_US` locale name instead of blank for the English selection, in case the browser's default is not English.
=> Fix #3410 persist locale in cookie

gradle.properties, rundeckapp/build.gradle, rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/domain/rundeck/Project.groovy, rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy, rundeckapp/grails-app/domain/rundeck/Storage.groovy, rundeckapp/grails-app/init/rundeckapp/Application.groovy
WIP: changes to improve oracle support
=> Fix use of Oracle backend

rundeckapp/build.gradle, rundeckapp/src/main/groovy/org/rundeck/jaas/jetty/JettySupport.java, test/docker/docker-compose-pam-test.yaml, test/docker/dockers/rundeck/Dockerfile, test/docker/dockers/rundeck/scripts/config-pam.sh, test/docker/dockers/rundeck/tests/pamtests/should-use-pam-test.sh, test/docker/test-pam.sh, testbuild.groovy
Update libpam4j dependency. Add a password callback to Jetty support to retrieve the password from the form and pass it to the PAM module. Add docker test for PAM auth.
=> Fix PAM login issues

rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
Fix #3749 fix selector for node checkboxes
=> Fix #3749 fix selector for node checkboxes

docker/official/Dockerfile, docker/official/README.md, docker/official/confd/conf.d/jaas-loginmodule.toml, docker/official/confd/templates/jaas-loginmodule.conf.tmpl, docker/official/confd/templates/rundeck-config.properties.tmpl
Adds an initial implementation for configuring JAAS auth via environment variables.
=> Add official docker auth config.

rundeckapp/build.gradle
This PR bundles the `RundeckOracleDialect` with core.
=> Bundle custom Oracle dialect.

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
fix missing auth on export status method and test for `jobfragment` using SCM
=> fix api error 500 on scm export

rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy, rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
Fix #3804 
don't assume a plugin is configured in cluster mode, allow local file storage only (e.g. nfs)
=> Fix NFS log file storage in cluster mode

rundeckapp/grails-app/assets/javascripts/ko/binding-datetimepicker.js, rundeckapp/grails-app/assets/javascripts/ko/binding-message-template.js, rundeckapp/grails-app/assets/javascripts/ko/binding-popover.js, rundeckapp/grails-app/assets/javascripts/ko/binding-url-path-param.js, rundeckapp/grails-app/assets/javascripts/ko/handler-bootstrapPopover.js, rundeckapp/grails-app/assets/javascripts/ko/handler-bootstrapTooltip.js, rundeckapp/grails-app/assets/javascripts/ko/handler-datetimepicker.js, rundeckapp/grails-app/assets/javascripts/ko/handler-messageTemplate.js, rundeckapp/grails-app/assets/javascripts/ko/handler-urlPathParam.js
move handlers into separate files so they can be included piecemeal
if needed
=> Minor js refactor of ko bindings

.travis.yml, Makefile, build.gradle, core/build.gradle, rundeck-storage/build.gradle, rundeckapp/build.gradle, rundeckapp/metricsweb/build.gradle, scripts/travis-build.sh, scripts/travis-helpers.sh
* Bintray publishing of maven artifacts
* Restores snapshot artifact publishing to OSS
* Bintray and OSS snapshot publishing from previously built artifacts
=> Bintray and snapshot publishing from existing sources

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerTests.groovy
Remove disabled plugins from create/edit job page
See #3820
=> Plugin Control remove disabled plugins

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy, rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy, rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy, rundeckapp/src/integration-test/groovy/rundeck/services/PluginApiServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/PluginControllerSpec.groovy
These API calls will allow an SPA to be built to manage plugins.
=> Add JSON API for listing plugins and retrieving plugin details.

rundeckapp/build.gradle
- Add Playbook and Playbook Inline Workflow Node Steps.
- Add Vault file/password/key-storage to RM/NE/FC
=> Updating Ansible Plugin to version 2.5.0.

.travis.yml, scripts/travis-build.sh
Build and push docker snapshot optimistically before triggering downstream builds on master.
=> Build docker snapshot before triggering downstream builds

rundeckapp/grails-app/controllers/rundeck/controllers/ControllerBase.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy
Fix #3871 
Handle missing `Accept-Encoding` header
=> Fix #3871 accept-encoding may be missing in request

rundeckapp/grails-spa/src/components/motd/motd.vue
=> Fixes max height, fixes character count limit.

rundeckapp/grails-app/views/common/_mainbar.gsp
fixes #3752 with https://github.com/rundeck/rundeck/pull/3890
=> Clean up mainbar project name link code

rundeckapp/grails-app/views/menu/home.gsp
Fixes styling issues with First Run messaging on the Dashboard
=> #3894 cleans up the h1 and stylingof the welcome message on dashboard

.travis.yml, scripts/travis-build.sh
=> Fix fork builds.

rundeckapp/grails-app/views/menu/home.gsp
Project description back to the project list on menu/home
=> fix #3921 project description back to project list on menu/home

rundeckapp/grails-app/assets/javascripts/user/profile.js, rundeckapp/grails-app/views/user/_edit.gsp, rundeckapp/grails-app/views/user/_token.gsp, rundeckapp/grails-app/views/user/_user.gsp
Fix #3919 
Fix incorrect dom structure for delete token button form.
lutions or features you've considered.
Also fixed:
=> Fix delete expired tokens button in GUI

examples/example-groovy-notification-plugins/MailNotificationPlugin.groovy
fix: java package name for mail message builder changed
fix: config type used
fix: email validator should be less strict
fix: markupbuilder yield usage was not correct
Fix #3969 update to work with rundeck 3
Update code to work in grails3/rundeck3 environment.
=> Fix #3969 update to work with rundeck 3

gradle.properties, rundeckapp/application.properties, rundeckapp/grails-app/services/rundeck/services/DbStorageService.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, version.properties
Backport for #3875 version 2.11.x
=> fix jobs failing over lock exception on mysql and mariadb

docker/official/lib/entry.sh, docker/official/remco/templates/framework.properties, docker/official/remco/templates/rundeck-config-storage.properties, docker/official/test/remco/test.yml
* Allow server name to be set
* Fix storage config
=> Fix storage config

rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/domain/rundeck/ReferencedExecution.groovy, rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy, rundeckapp/grails-app/views/scheduledExecution/_renderJobStats.gsp
=> optimization execution count query

rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy, rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy, rundeckapp/src/test/groovy/rundeck/controllers/UserControllerSpec.groovy
`user.filterPref` to `session.filterPref` on login and refresh on `UserController.addFilterPref` method.
=> user filterPref to session

packaging/debroot/etc/init/rundeckd.conf
Fix #3974 
Remove quotes from exec statement
=> Fix #3974 startup failure in deb install

core/src/main/java/com/dtolabs/rundeck/core/plugins/JarPluginProviderLoader.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginMetadata.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginMetadataValidator.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginUtils.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/ScriptPluginProviderLoader.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/ScriptPluginScanner.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/metadata/PluginMeta.java, core/src/test/groovy/com/dtolabs/rundeck/core/plugins/PluginMetadataValidatorTest.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/plugins/ScriptPluginProviderLoaderTest.groovy, core/src/test/java/com/dtolabs/rundeck/core/plugins/TestJarPluginProviderLoader.java, gradle.properties, rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/builder/ScriptPluginBuilder.groovy, rundeckapp/src/test/groovy/rundeck/controllers/PluginControllerSpec.groovy
The new 2.0 format will be used with Verb. This format should not introduce compatibility issues with older format plugins.
=> Introduce Rundeck plugin format version 2.0.

core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginManagerService.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginProviderConfiguration.java, core/src/main/java/com/dtolabs/rundeck/plugins/ServiceTypes.java, core/src/main/java/org/rundeck/core/plugins/PluginProviderServices.java, core/src/main/java/org/rundeck/core/plugins/PluginTypes.java, rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy
Adds a mechanism for using java ServiceLoader to define plugin types.
=> Define a plugin service loader

core/src/main/java/com/dtolabs/rundeck/core/authorization/AuthContextProvider.java, core/src/main/java/com/dtolabs/rundeck/core/cluster/ClusterInfoService.java, core/src/main/java/com/dtolabs/rundeck/core/jobs/JobService.java, core/src/main/java/org/rundeck/app/spi/AppService.java, core/src/main/java/org/rundeck/app/spi/AuthorizedServicesProvider.java, core/src/main/java/org/rundeck/app/spi/Services.java, core/src/main/java/org/rundeck/app/spi/ServicesProvider.java, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/src/main/groovy/org/rundeck/app/authorization/RundeckAuthorizedServicesProvider.groovy, rundeckapp/src/main/groovy/org/rundeck/app/cluster/ClusterInfo.groovy, rundeckapp/src/main/groovy/org/rundeck/app/spi/RundeckSpiBaseServicesProvider.groovy
Defines some SPI interfaces which will be used to allow plugins access to internal services in a better way.
=> Initial SPI changes for future use with plugins

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Fix for https://github.com/rundeck/rundeck/issues/4015.
=> Fix Multi-value option delimiter variable not available within a Job Reference

core/src/main/java/com/dtolabs/rundeck/core/plugins/DirPluginScanner.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/JarPluginProviderLoader.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginScanner.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/VersionCompare.java
Expose some method and classes to be extended for custom loader.
WIP
=> expose classes and method to plugin loader

rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy
This allows install to run on version upgrade
=> Install complete marker now includes version

rundeckapp/grails-app/assets/javascripts/jobedit.js
Fixing https://github.com/rundeck/rundeck/issues/4073
=> Adding execution variable context to notification config options.

grails-persistlocale/src/main/groovy/grails/persistlocale/PersistlocaleGrailsPlugin.groovy
=> Fix #4050 by adding the ability to configure the locale expiration time. 90 days is default.

rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
Fix #3980 
Fix stylesheet reference.
=> Fix #3980 date time picker unstyled

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
=> Uncaught Error on job without commands

plugins/upvar-plugin/src/main/java/org/rundeck/plugin/vars/ExportVarWorkflowStep.java
Plugin info corrected and expanded.
fix #3704
=> Export plugin info

rundeckapp/grails-app/views/user/login.gsp
ENHANCEMENT 
Adds a new GUI customization for use with rundeck-config.properties named 'login.disclaimer'. This feature allows for much larger/verbose content to be added to the Login page directly under the login container.
Perfect for legal notifications of system misuse and unauthorized access.
=> Adds loginDisclimer to login.gsp

rundeckapp/grails-app/init/rundeckapp/Application.groovy, rundeckapp/src/test/groovy/rundeckapp/ApplicationTest.groovy
Groovy file was being loaded as a property file which caused unexpected configuration overwrite behavior.
=> Fix groovy config file loading problem

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/test/unit/ExecutionServiceSpec.groovy
=> fix #4077 jobref respect successOnEmptyNodeFilter for release 2.11

rundeckapp/grails-app/views/menu/home.gsp
Set an ID for the "first run message"  in order to overwrite it on a UI plugin
=> Set an ID for the "first run message" div

core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/BaseWorkflowExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/FlowController.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/state/WorkflowExecutionStateListenerAdapter.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/HasSourceStepExecutionResult.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/NodeDispatchStepExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/StepExecutionResultWrapper.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/BaseWorkflowExecutorSpec.groovy, plugins/job-state-plugin/src/main/java/org/rundeck/plugin/jobstate/JobStateWorkflowStep.java
Fix #4178 
Fix failure status handling from flow control Halt
=> Fix flow control status handling for job state conditional step

rundeckapp/grails-spa/src/components/tour/tourPicker/App.vue
Adds an id of "appTour" to the tour (duck) list item that is added to the main nav bar.
=> Adds ID to tour list item

rundeckapp/grails-app/assets/scss/pages/jobs.scss, rundeckapp/grails-app/views/menu/_groupTree.gsp
=> Fix #4020 indent job groups in tree

docker/official/remco/templates/rundeck-config-storage.properties
=> Remove extranious spaces from config

rundeckapp/grails-app/views/menu/systemInfo.gsp, rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
Fix broken links to Docs pages #4259
=> Fix #4259 broken help link

core/src/main/java/org/rundeck/app/gui/MenuItem.java, rundeckapp/grails-app/views/common/_sidebar.gsp, rundeckapp/grails-app/views/menu/_appUserMenu.gsp, rundeckapp/grails-app/views/menu/_sidebarProjectMenu.gsp, rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp
Enhance menuitem interface for specifying icon, and update gsp for rendering menu items.
=> add icon value for menuitem interface, update gsp

rundeckapp/repository/build.gradle
Fix #4256 
mailapi-1.4.3.jar was incorrectly included via transitive dependency
=> Fix mail notification doesnt work

rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/EditOptsControllerSpec.groovy
Fixes #4299 
Fixes error response to use correct method call instead of calling a closure. Add tests.
=> Fix #4299 correct invalid call to error response action

docker/official/README.md, docker/official/remco/templates/framework.properties
Fixes #4308
Adds support for the `RUNDECK_TOKENS_FILE` environment variable.
=> Add tokens file envar

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy, rundeckapp/grails-app/views/menu/systemInfo.gsp, test/selenium/src/__tests__/visual-regression/navigation.test.ts, test/selenium/src/pages/navigation.page.ts
Fix #4325
Startup warning
System Configuration
System Report
=> H2 warnings UI and startup

core/src/main/java/org/rundeck/utils/UUIDPropertyValidator.java, core/src/main/java/org/rundeck/utils/UUIDs.java
Add utils for validating UUID strings.
=> Add UUID validator

rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy, rundeckapp/src/test/groovy/rundeck/services/PluginApiServiceSpec.groovy
Fix a bug when a UI plugin is installed it is not flagged as installed when listing repository plugins.
=> UI plugin install status fix

rundeckapp/build.gradle
This PR updates the spring security plugin to the last version.
=> Update spring security plugin to last version.

rundeckapp/grails-app/assets/javascripts/workflowStepEditorKO.js, rundeckapp/grails-app/views/execution/_wfitemEdit.gsp
Fix #4406 
Prevents stored XSS on Job Edit page via inline script configuration.
=> Fix #4406: stored xss vulnerability

rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy
Looks like old code was merged into this controller. This PR repoints it back to the correct service.
=> Fix Plugin list api by referencing correct plugin list information service

rundeckapp/grails-app/assets/javascripts/workflowStepEditorKO.js, rundeckapp/grails-app/views/execution/_wfitemEdit.gsp
=> (2.11) Fix #4406: stored xss vulnerability

rundeckapp/build.gradle
Bug on python wirn plugin
https://github.com/rundeck-plugins/py-winrm-plugin/issues/16
add a try/catch block when the command is run
=> new version of winrm plugin 1.0.10

docker/official/remco/templates/rundeck-config-csp.properties, docker/official/test/remco/test.yml
=> Ensure newlines are added when options are rendered

docker/official/remco/templates/rundeck-config.properties
=> Remove extraneous login module config

rundeckapp/grails-app/views/common/_footer.gsp, rundeckapp/grails-app/views/menu/licenses.gsp, rundeckapp/grails-spa/package-lock.json, test/selenium/__image_snapshots__/navigation-test-ts-expanded-navigation-bar-visits-activity-1-snap.png, test/selenium/__image_snapshots__/navigation-test-ts-expanded-navigation-bar-visits-commands-1-snap.png, test/selenium/__image_snapshots__/navigation-test-ts-expanded-navigation-bar-visits-jobs-1-snap.png, test/selenium/__image_snapshots__/navigation-test-ts-expanded-navigation-bar-visits-nodes-1-snap.png, test/selenium/package.json
Updates the Copyright date in the footer and licenses page
=> Updates the Copyright date in the footer and licenses page

core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/EngineWorkflowExecutor.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/EngineWorkflowExecutorSpec.groovy
Backport fix for #3443 to 2.11
=> Fix #3443 ensure new builder used for workflow system

core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/ContextManager.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/ContextManagerSpec.groovy
=> Fix #4454 resume correct step context after handler

rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy, rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy, rundeckapp/src/test/groovy/rundeck/controllers/UserControllerSpec.groovy, test/api/include.sh
API endpoint for a user to list their roles.
=> Add API endpoint that allows a user to list their roles

core/src/main/java/com/dtolabs/rundeck/core/execution/NodeExecutionService.java, core/src/main/java/com/dtolabs/rundeck/core/execution/NoopExecutionListener.java, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/src/main/groovy/org/rundeck/app/authorization/RundeckAuthorizedServicesProvider.groovy, rundeckapp/src/main/groovy/rundeck/services/AuthorizingNodeExecutionService.groovy, rundeckapp/src/main/groovy/rundeck/services/DirectNodeExecutionService.groovy
Adds "NodeExecutionService" to available SPI services for plugins
=> Node exec SPI

core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginRegistry.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/PropertyResolverFactory.java, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy, rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy, rundeckapp/src/test/groovy/rundeck/services/PluginServiceTests.groovy
Fix #4475 
Fix incorrect parameter ordering
=> Fix project/framework prop resolution

core/src/main/java/com/dtolabs/rundeck/core/common/ProjectNodeSupport.java, core/src/main/java/com/dtolabs/rundeck/plugins/ServiceNameConstants.java, core/src/main/java/com/dtolabs/rundeck/plugins/ServiceTypes.java, core/src/main/java/com/dtolabs/rundeck/plugins/nodes/NodeEnhancerPlugin.java, rundeckapp/grails-app/assets/javascripts/nodeFiltersKO.js, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/NodeService.groovy, rundeckapp/grails-app/services/rundeck/services/PluginService.groovy, rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy, rundeckapp/grails-app/services/rundeck/services/feature/FeatureService.groovy, rundeckapp/src/main/groovy/org/rundeck/app/services/EnhancedNodeService.groovy, rundeckapp/src/main/groovy/org/rundeck/app/services/ProjectNodesEnhancer.groovy, rundeckapp/src/main/groovy/org/rundeck/app/services/TypedNodeEnhancerPlugin.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy, rundeckapp/src/test/groovy/org/rundeck/app/services/EnhancedNodeServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/NodeServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
Adds new plugin type "NodeEnhancerPlugin" (name?)
Plugins that can augment node sources by adding new attributes.
Allow a plugin to add node attributes.
=> (wip) Feature/node plugin enhancer

rundeckapp/grails-app/assets/javascripts/nodeFiltersKO.js, rundeckapp/grails-app/views/framework/_allnodesKO.gsp, rundeckapp/grails-app/views/framework/_nodesEmbedKO.gsp
Enables "status" UI features for node attributes
Node attributes can display a status icon with text:
* `ui:status:icon` icon name to use
* `ui:status:color` color to use
* `ui:status:bgcolor` bg color to use
* `ui:status:text` text to display
=> Node status UI attributes

rundeckapp/grails-spa/src/pages/repository/App.vue, rundeckapp/repository/build.gradle
=> Update repository version.

rundeckapp/grails-app/views/user/login.gsp
When SSO is enabled this PR makes the login page make more sense.
=> Render the SSO login button in a more sensible way.

rundeckapp/grails-app/services/rundeck/services/ApiService.groovy, rundeckapp/src/test/groovy/rundeck/services/ApiServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/ApiServiceTests.groovy
Fix writing output stream on Tomcat 7
=> Fix #4488. Help Grails write output stream correctly on Tomcat 7.

core/src/main/java/com/dtolabs/rundeck/plugins/nodes/IModifiableNodeEntry.java, rundeckapp/src/main/groovy/org/rundeck/app/services/ModifiableNode.groovy, rundeckapp/src/main/groovy/org/rundeck/app/services/ProjectNodesEnhancer.groovy, rundeckapp/src/test/groovy/org/rundeck/app/services/EnhancedNodeServiceSpec.groovy, rundeckapp/src/test/groovy/org/rundeck/app/services/ProjectNodesEnhancerSpec.groovy
* tags not preserved from node sources
* allow plugins to remove tags/attributes
=> Update node enhancer. fix tags issue

rundeckapp/grails-app/assets/scss/app.scss, rundeckapp/grails-app/assets/scss/custom/nodes-embed.scss, rundeckapp/grails-app/assets/scss/custom/table.scss, rundeckapp/grails-app/assets/scss/custom/tabs.scss, rundeckapp/grails-app/assets/scss/custom/text.scss, rundeckapp/grails-app/assets/scss/pages/nodes.scss, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/views/execution/_nodeCurrentStateSimpleKO.gsp, rundeckapp/grails-app/views/execution/_wfItemView.gsp, rundeckapp/grails-app/views/framework/_allnodesKO.gsp, rundeckapp/grails-app/views/framework/_nodeDetailsSimpleKO.gsp, rundeckapp/grails-app/views/framework/_nodeTooltipView.gsp, rundeckapp/grails-app/views/framework/_nodesEmbed.gsp, rundeckapp/grails-app/views/framework/_nodesEmbedKO.gsp, rundeckapp/grails-app/views/framework/_nodesTable.gsp, rundeckapp/grails-app/views/framework/_nodesTableContent.gsp, rundeckapp/grails-app/views/framework/_tagsummary.gsp, rundeckapp/grails-app/views/framework/nodes.gsp, rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
Improvements to layout and styles
=> Misc nodes page UI updates

rundeckapp/grails-app/assets/javascripts/nodeFiltersKO.js, rundeckapp/grails-app/assets/scss/custom/nodes-embed.scss, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy, rundeckapp/grails-app/views/framework/_nodeDetailsSimpleKO.gsp, rundeckapp/grails-app/views/framework/_nodeFilterInputExcludeGroup.gsp, rundeckapp/grails-app/views/framework/_nodeFilterInputGroup.gsp, rundeckapp/grails-app/views/framework/_nodesEmbed.gsp, rundeckapp/grails-app/views/framework/_nodesEmbedKO.gsp, rundeckapp/grails-app/views/framework/_nodesTableContent.gsp, rundeckapp/grails-app/views/framework/adhoc.gsp, rundeckapp/grails-app/views/framework/nodes.gsp, rundeckapp/grails-app/views/scheduledExecution/_edit.gsp, rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerTests.groovy, test/selenium/__image_snapshots__/create-test-ts-job-has-not-visually-regressed-1-snap.png, test/selenium/docker-compose.yml, test/selenium/docker-local-compose.yml, test/selenium/package.json
UI updates for the job exclude filter.
* fix: "exclude" filter links were shown in nodes/adhoc pages when they should only be shown in job edit page
* ui tweaks: layout fixes in node checkbox lists, job run page should show the select all/none/tags controls in node groups when you run the job 
* show node icon, status, excluded state in run job form
=> exclude filter updates

rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy
=> Fix #4541 remove debug

core/src/main/java/com/dtolabs/rundeck/net/api/Client.java, core/src/main/java/com/dtolabs/rundeck/net/api/RundeckApi.java, core/src/main/java/com/dtolabs/rundeck/net/model/ProjectImportStatus.java, core/src/test/java/com/dtolabs/rundeck/net/api/ClientTest.java, rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ProjectControllerSpec.groovy
"Export to Another Instance" with SCM fixed.
Fix #4364
=> Add scm import to instance to instance process

rundeckapp/grails-app/services/rundeck/services/DbStorageService.groovy
=> Fix lock wait timeout exceeded on the storage table

plugins/upvar-plugin/src/main/java/org/rundeck/plugin/vars/ExportVarWorkflowStep.java
=>  Typo Fix insted > instead

rundeckapp/grails-app/assets/javascripts/resourceModelConfig.js, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_ja.properties, rundeckapp/grails-app/i18n/messages_pt_BR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/views/framework/_nodeDetailsSimpleKO.gsp, rundeckapp/grails-app/views/framework/_renderPluginDesc.gsp, rundeckapp/grails-app/views/framework/_viewResourceModelConfig.gsp, rundeckapp/grails-app/views/framework/createResourceModelConfig.gsp, rundeckapp/grails-app/views/framework/editProjectNodeSources.gsp
Minor touchups to resource model source config ui for projects:
* use plugin icons
* use bs modal instead of inline list to add new plugins
=> Touchup node source edit UI

rundeckapp/grails-app/views/user/login.gsp
Rundeck SSO login floats around when window is resized. This fixes that issue.
=> Fix icon movement when window is resized.

core/src/main/java/org/rundeck/utils/UUIDPropertyValidator.java, core/src/test/groovy/org/rundeck/utils/UUIDPropertyValidatorSpec.groovy
Include info about invalid input in UUID validation
=> Improve UUID validation by reporting input, add tests

rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_ja.properties, rundeckapp/grails-app/i18n/messages_pt_BR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties
=> Updated Quartz crontab link

rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy, rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
Allows users who are trying to use static tokens to gain more insight about the token check.
=> Fix and add debugging for static tokens

rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy
Fix first install issue on Tomcat 7 with RPM based installation.
=> Fix tomcat 7 init issue. #4420.

core/src/main/java/org/rundeck/app/gui/MenuItem.java, rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy, rundeckapp/grails-app/views/common/_sidebar.gsp, rundeckapp/grails-app/views/menu/_sidebarProjectMenu.gsp
Add enabled flag to MenuItem, allowing menu item beans to be hidden via configuration
=> menuitem enabled flag

core/src/main/java/com/dtolabs/rundeck/core/api/ApiInfoService.java, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/src/main/groovy/org/rundeck/app/api/ApiInfo.groovy
Add ApiInfoService SPI for getting latest api version and base URL info via spring bean.
=> Add ApiInfoService SPI

rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/StorageController.groovy, rundeckapp/grails-app/services/rundeck/services/UiPluginService.groovy
=> Move plugin controller response writing to static compiled method

rundeckapp/grails-spa/package-lock.json, rundeckapp/grails-spa/package.json
Set ui-trellis dependency to particular commit id
=> Use master branch of ui trellis

rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
=> Fix #4606 handle missing plugin

core/src/main/java/com/dtolabs/rundeck/core/common/IProjectNodes.java, core/src/main/java/com/dtolabs/rundeck/core/common/ProjectNodeSupport.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/ExtPluginConfiguration.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/SimplePluginConfiguration.java, core/src/test/groovy/com/dtolabs/rundeck/core/common/ProjectNodeSupportSpec.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-spa/src/pages/project-nodes-config/App.vue, rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
Update the project plugin config ajax/ui to support extended properties
=> Add extended project plugin config

rundeckapp/repository/build.gradle
Update repository to the latest version.
=> Bump repository dependency

rundeckapp/grails-spa/package.json
Updates ui-trellis to latest commit
=> update ui-trellis commit

core/build.gradle, packaging/rundeck.spec, rundeckapp/grails-app/conf/BuildConfig.groovy
Enhancement, updating JSCH lib to the last version
=> updating jsch version to 0.1.55

rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_ja.properties, rundeckapp/grails-app/i18n/messages_pt_BR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/views/framework/projectNodeSources.gsp
Adds link to Node Enhancer plugins edit page if feature is enabled
=> UI: Button to Edit node enhancer plugins if enabled

core/src/main/java/com/dtolabs/rundeck/plugins/ServiceNameConstants.java, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/services/rundeck/services/FileUploadService.groovy, rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy, rundeckapp/src/integration-test/groovy/rundeck/services/FileUploadServiceIntegrationSpec.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/fileupload/FSFileUploadPlugin.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/services/FileUploadPluginProviderService.java, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/services/FileUploadProviderService.java, rundeckapp/src/main/resources/META-INF/services/org.rundeck.core.plugins.PluginProviderServices, rundeckapp/src/test/groovy/rundeck/services/FileUploadServiceSpec.groovy
Fixes configurability of file upload plugin #4369
=> Fixes configurability of file upload plugin #4369

rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java, rundeckapp/src/main/groovy/org/rundeck/security/RundeckJaasAuthenticationProvider.groovy, rundeckapp/src/test/groovy/org/rundeck/security/RundeckJaasAuthenticationProviderTest.groovy
The fix is in a Jetty lib that is not compatible with our current grails version.
When we upgrade grails this issue will be truly fixed. This commit provides suppression for the spurious error.
=> Addresses #1111 and #3939. 

core/src/main/java/com/dtolabs/rundeck/core/plugins/ScriptPluginProviderLoader.java, core/src/test/groovy/com/dtolabs/rundeck/core/plugins/ScriptPluginProviderLoaderTest.groovy
Fix date NPE for script plugins that specify no date.
=> Fix date NPE for script plugins that specify no date.

rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy, rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
Fixing bug https://github.com/rundeck/rundeck/issues/4582
- reorder the way that the zip file is read
- moving the flash message to flash.warn
=> fixing project configuration not overwritten when importing archive

rundeckapp/grails-app/assets/javascripts/historyKO.js, rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/views/reports/_activityLinks.gsp, rundeckapp/grails-app/views/reports/_eventsFragment.gsp, rundeckapp/grails-app/views/reports/index.gsp
This changes allow user to select executions in more than one page for bulk delete.
=> Allow multi-page selections on job exections history report #4416

rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/grails-app/views/scheduledExecution/_editNotificationsTriggerForm.gsp, rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Fixing https://github.com/rundeck/rundeck/issues/4643
compatibility for old versions of email notification (log output as attached file)
=> compatibility for old versions of email notification (issue #4643)

core/src/main/java/com/dtolabs/rundeck/core/plugins/ScriptPluginProviderLoader.java, core/src/test/groovy/com/dtolabs/rundeck/core/plugins/ScriptPluginProviderLoaderTest.groovy, rundeckapp/src/main/groovy/org/rundeck/security/passwordutil/HiddenInputPasswordUtilityEncrypter.groovy, rundeckapp/src/main/resources/META-INF/services/com.dtolabs.rundeck.core.encrypter.PasswordUtilityEncrypter, rundeckapp/src/test/groovy/org/rundeck/security/passwordutil/HiddenInputPasswordUtilityEncrypterTest.groovy
Add password encryption utility according to user's request.
=> Use Password field type for password encryptor input

rundeckapp/grails-app/views/scheduledExecution/_editNotificationsTriggerForm.gsp
=> Fix style on job form for Notification plugins, and webhook field

core/src/main/java/com/dtolabs/rundeck/core/common/PluginControlService.java, core/src/main/java/com/dtolabs/rundeck/core/common/PluginControlServiceImpl.java, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
Fix #3905 
fix incorrect shared instance used for multiple projects
=> Fix: project does not exist error

rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
Allow custom cookies to be expired upon logout.
Make the logout redirection url configurable.
Fixes #4707.
=> Logout enhancements.

plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/BaseGitPluginSpec.groovy
Fixes issue with StaticHostKeyChecking when using username and password credentials in git scm plugin.
=> Fixes StaticHostKeyChecking when using password for git plugin via ssh

rundeckapp/grails-app/utils/rundeck/codecs/AnsiColorCodec.groovy
=> Fix #4754 some ansi colorization is broken

rundeckapp/grails-app/assets/javascripts/executionState.js
Fix: [issue 4738](https://github.com/rundeck/rundeck/issues/4738)
=> Change to make update job state continuous while job is not completed

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Fix [issue 3164](https://github.com/rundeck/rundeck/issues/3164)
=> Improvements on message error when call API to enable or disable for a job without a schedule #3164

rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy, rundeckapp/src/integration-test/groovy/rundeck/services/PluginApiServiceIntegrationSpec.groovy
Node enhancer plugins now show up on installed plugins page.
=> Fixes #4801. 

plugins/object-store-plugin/build.gradle, plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/ObjectStorePlugin.groovy, plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/directorysource/ObjectStoreMemoryDirectorySource.groovy, plugins/object-store-plugin/src/test/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreTreeWithMemoryDirSourceTest.groovy, plugins/object-store-plugin/src/test/groovy/org/rundeck/plugin/objectstore/tree/TimeoutTest.groovy
Object store init will throw exception after default timeout.
=> Fixes #4702. Default timeout is 3 minutes for connections.

rundeckapp/repository/build.gradle
Update dependency to bring in better error handling.
=> Update dependency to bring in better error handling.

rundeckapp/repository/build.gradle, rundeckapp/repository/grails-app/controllers/repository/RepositoryController.groovy, rundeckapp/repository/src/main/groovy/repository/RepositoryGrailsPlugin.groovy
Fix issue with object store repo regarding tree paths.
Fix issue with uninstall.
=> Fix issue with object store repo regarding tree paths.

rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
Changing importing apache common class from lang3 to lang to fix a dependency error
=> Changing importing apache common class from lang3 to lang

rundeckapp/grails-spa/package.json, rundeckapp/grails-spa/src/pages/project-nodes-config/ProjectPluginConfig.vue, rundeckapp/grails-spa/src/pages/project-nodes-config/nodeSourcesUtil.ts
Fix broken Node Config page when using a web app context path like `/rundeck`
Fix request URLs used by javascript.
=> Fix #4804 broken node config page with web context path

rundeckapp/grails-app/assets/scss/custom/expand.scss
Fix #4809 
CSS was too lenient
=> fix #4809 more/less text not changing for job description in group

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
For issue https://github.com/rundeck/rundeck/issues/4760
Cleaning the exclude filter when the target nodes were changed
=> Wrong list nodes using "Change the Target Nodes" with exclude filter

rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowController.groovy, rundeckapp/grails-app/domain/rundeck/JobExec.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/views/execution/_wfItemView.gsp, rundeckapp/grails-app/views/execution/_wfitemEdit.gsp, rundeckapp/grails-app/views/execution/_wflistitemContent.gsp, rundeckapp/src/test/groovy/rundeck/JobExecSpec.groovy
cherry pick https://github.com/rundeck/rundeck/pull/4815 into maint-3.0.x
=> Fix: job ref "not found" red text (3.0.x)

rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowController.groovy, rundeckapp/grails-app/domain/rundeck/JobExec.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/views/execution/_wfItemView.gsp, rundeckapp/grails-app/views/execution/_wfitemEdit.gsp, rundeckapp/grails-app/views/execution/_wflistitemContent.gsp, rundeckapp/src/test/groovy/rundeck/JobExecSpec.groovy
Fix #4785 
Job reference search logic was consolidated
Job references were still functioning in workflows, but the UI showed "Not Found" incorrectly
=> Fix: Job ref Not Found red text

packaging/common/etc/rundeck/artifact-repositories.yaml, packaging/common/etc/rundeck/rundeck-config.properties, rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp, rundeckapp/grails-app/views/menu/plugins.gsp, rundeckapp/repository/build.gradle, rundeckapp/repository/grails-app/controllers/repository/UrlMappings.groovy, rundeckapp/repository/grails-app/init/repository/BootStrap.groovy, rundeckapp/repository/grails-app/views/artifact/index.gsp, rundeckapp/repository/src/main/groovy/repository/RepositoryGrailsPlugin.groovy, rundeckapp/repository/src/main/groovy/repository/RepositoryPluginService.groovy, rundeckapp/repository/src/main/resources/default-repo-defn.yaml, rundeckapp/repository/src/test/groovy/repository/BootStrapTest.groovy, rundeckapp/templates/config/rundeck-config.properties.template
Adds official repository when the repository feature is enabled.
=> Add official repository to default template.

rundeckapp/grails-app/taglib/rundeck/RepositoryTagLib.groovy, rundeckapp/grails-app/views/menu/systemInfo.gsp, rundeckapp/repository/src/main/groovy/repository/RepositoryGrailsPlugin.groovy, rundeckapp/src/test/groovy/rundeck/RepositoryTagLibSpec.groovy
Add repository information to the system report page.
=> Add repository information to the system report page.

rundeckapp/grails-app/views/menu/systemConfig.gsp
Updates verbiage for Repositories section of System Config page
=> Updates verbiage for Repositories section of System Config page

rundeckapp/build.gradle
Bug fix for python winrm plugin:
https://github.com/rundeck-plugins/py-winrm-plugin/issues/27
- fixing encoding issues
- tested on python 2.7.x and 3.x
=> upgrading python winrm to version 2.0.2

rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/EditOptsControllerSpec.groovy
Adding option with option value plugin and using enforced values now works.
=> Fixes #4732

rundeckapp/grails-app/services/rundeck/services/UserService.groovy, rundeckapp/src/test/groovy/rundeck/services/UserServiceSpec.groovy
Fix issue where a mis-configured user group source plugin would emit an NPE.
=> Fix issue when processing user group source plugins

core/src/main/java/com/dtolabs/rundeck/core/tasks/net/SSHTaskBuilder.java, core/src/test/groovy/com/dtolabs/rundeck/core/tasks/net/SSHTaskBuilderSpec.groovy
bugfix for https://github.com/rundeck/rundeck/issues/4771
adding timeouts settings on the buildScpXXX functions
=> ssh timeout on JSCH File Copier

rundeckapp/grails-app/services/rundeck/services/DbStorageService.groovy, rundeckapp/src/test/groovy/rundeck/services/DbStorageServiceTests.groovy
backing to the previous version to fix https://github.com/rundeck/rundeck/issues/4742
the current version of DbStorageService produce the refresh issue
=> fixing updating project settings

rundeckapp/grails-app/assets/javascripts/executionControl.js, rundeckapp/grails-app/views/execution/show.gsp
=> UI tweaks 3.1: part G

rundeckapp/grails-app/services/rundeck/services/DbStorageService.groovy
Bug fix for https://github.com/rundeck/rundeck/issues/4742
Back to the previous version of DbStorageService
=> fixing upgrade project settings, back previous version 

rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/EditOptsControllerSpec.groovy
Fixes option values enforcement issue.
=> Option values plugin does not work with enforce from allowed values (backport) Fixes #4857

docker/official/README.md, docker/official/remco/templates/rundeck-config.properties
=> [Docker] Add template option for setting contextPath

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/ExecutionServiceSpec.groovy
Allow multiple project query for running executions
=> Enhance running query to specify projects

rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
Add support for spring security x509 client cert authentication.
=> Add support for spring security x509 client cert authentication.

rundeckapp/grails-app/assets/javascripts/menu/projectHome.js, rundeckapp/grails-app/assets/scss/custom/mainbar.scss, rundeckapp/grails-app/assets/scss/custom/text.scss, rundeckapp/grails-app/assets/scss/paper/mixins/_sidebar.scss, rundeckapp/grails-app/views/framework/_projectSelectSidebar.gsp, rundeckapp/grails-app/views/menu/home.gsp, rundeckapp/grails-app/views/menu/projectHome.gsp, rundeckapp/grails-spa/src/components/motd/motdIndicator.vue, rundeckapp/grails-spa/src/pages/project-dashboard/App.vue
=> Enh/ui tweaks 3.1 i

rundeckapp/grails-app/services/rundeck/services/workflow/StateMapping.groovy, rundeckapp/src/test/groovy/rundeck/services/workflow/StateMappingSpec.groovy
Fix #4684 
test key is present before retrieving it. (grails JSON parser object throws exception when `.get(key)` is called for missing key).
=> Fix node state doesn't load #4684

rundeckapp/grails-app/assets/javascripts/scheduledExecution/jobRunFormOptionsKO.js, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_ja.properties, rundeckapp/grails-app/i18n/messages_pt_BR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/views/framework/_jobOptionsKO.gsp, rundeckapp/grails-app/views/scheduledExecution/_execOptionsFormButtons.gsp, rundeckapp/grails-app/views/scheduledExecution/_renderJobStats.gsp, rundeckapp/grails-spa/src/components/activity/activityList.vue, rundeckapp/grails-spa/src/pages/project-activity/i18n.js
=> 3.1 UI tweaks part J

rundeckapp/build.gradle, testbuild.groovy
enhancement, adding the plugin multiline-regex-datacapture-filter plugin by default
=> adding multiline-regex-datacapture-filter plugin

rundeckapp/grails-app/assets/scss/paper/_buttons.scss, rundeckapp/grails-app/assets/scss/paper/_sidebar-and-main-panel.scss, rundeckapp/grails-app/views/execution/_showFragment.gsp, rundeckapp/grails-app/views/execution/show.gsp, rundeckapp/grails-app/views/framework/adhoc.gsp, rundeckapp/grails-app/views/framework/nodes.gsp, rundeckapp/grails-app/views/framework/projectNodeSources.gsp, rundeckapp/grails-app/views/menu/_projectExportForm.gsp, rundeckapp/grails-app/views/menu/_projectImportForm.gsp, rundeckapp/grails-app/views/menu/jobs.gsp, rundeckapp/grails-app/views/menu/systemInfo.gsp, rundeckapp/grails-spa/package-lock.json, rundeckapp/grails-spa/src/components/activity/activityList.vue, rundeckapp/grails-spa/src/pages/community-news/App.vue, rundeckapp/grails-spa/src/pages/repository/components/ProviderCard.vue, rundeckapp/grails-spa/src/pages/repository/views/PluginConfigurationView.vue, rundeckapp/grails-spa/src/pages/repository/views/PluginRepositoryView.vue
A number of minor CSS and HTML issues. 
- Incidents of <div> having a class of "row" creating a card with a width 30px wider than other cards. Selected without the additional "row" class as standard/default UI.
- Sets "primary" buttons to have a 2x border but keeping the 1px external border and adding a 1px inset boxshadow. 
- Removing instances of "btn-simple" to keep with the button style usage.
- Adds property of "word-break":"break-all" where visually seen. (this occured, for example, on the BASE shown in System Report"
- Minor changes to Repository/Plugins UI
=> UI fixes, minor css and html changes, flattened

rundeckapp/grails-app/services/rundeck/services/workflow/StateMapping.groovy, rundeckapp/src/test/groovy/rundeck/services/workflow/StateMappingSpec.groovy
backport for #4684 to 3.0.x
Fixes #4922
=> [3.0.x backport] Fix #4684 #4922 node state doesn't load

core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/BaseWorkflowExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/FlowController.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/state/WorkflowExecutionStateListenerAdapter.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/HasSourceStepExecutionResult.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/NodeDispatchStepExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/StepExecutionResultWrapper.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/BaseWorkflowExecutorSpec.groovy, plugins/flow-control-plugin/src/main/java/org/rundeck/plugin/flowcontrol/FlowControlWorkflowStep.java, plugins/job-state-plugin/src/main/java/org/rundeck/plugin/jobstate/JobStateWorkflowStep.java
Backport of PRs #4700 and #4235 for rundeck 2.11.11
=> Backport of Fixes flow control status handling

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/test/unit/rundeck/services/ScheduledExecutionServiceSpec.groovy
Backport of #4886 for rundeck 2.11.11
=> Log the enable/disable execution or scheduled of a Job

rundeckapp/grails-app/assets/scss/app.scss, rundeckapp/grails-app/assets/scss/custom/jobs.scss
=> [3.0.x backport] Fix: #4284 job schedule display is incorrect

rundeckapp/repository/build.gradle
Update repository dependency to a version that doesn't depend on a snapshot version of Rundeck.
=> Update repository dependency.

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/views/common/_sidebar.gsp, rundeckapp/grails-app/views/execution/show.gsp, rundeckapp/grails-app/views/framework/adhoc.gsp, rundeckapp/grails-app/views/menu/jobs.gsp, rundeckapp/grails-app/views/menu/projectHome.gsp, rundeckapp/grails-app/views/scheduledExecution/_show.gsp, rundeckapp/grails-spa/src/pages/project-dashboard/App.vue, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerTests.groovy
activity/history should be hidden if user does not have authorization
=> 3.1: event access update

rundeckapp/grails-app/conf/application.groovy
enhancement, enabling option plugin by default
=> enabling option plugins by default

rundeckapp/grails-app/assets/javascripts/nodeFiltersKO.js, rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-app/views/common/_nodefilterStringHelp.gsp, rundeckapp/grails-app/views/framework/_nodeFilterInputGroup.gsp, rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
=> 3.1: Nodes updates

rundeckapp/grails-app/views/user/_token.gsp, rundeckapp/grails-app/views/user/_user.gsp
=> Change conditional to ignorecase when open Profile/API Tokens information

rundeckapp/grails-app/assets/javascripts/nodeFiltersKO.js, rundeckapp/grails-app/assets/scss/custom/rows.scss, rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp, rundeckapp/grails-app/views/scheduledExecution/_execOptionsFormButtons.gsp, rundeckapp/grails-app/views/scheduledExecution/_jobActionButtonMenuContent.gsp, rundeckapp/grails-app/views/scheduledExecution/_show.gsp
=> UI: Job Show/Run page updates

rundeckapp/grails-app/assets/javascripts/scheduledExecution/jobRunFormOptionsKO.js, rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
=> 3.1: Updates: node filters in job run page

rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java, rundeckapp/src/main/groovy/org/rundeck/jaas/jetty/JettyAuthPropertyFileLoginModule.java, rundeckapp/src/main/groovy/org/rundeck/jaas/jetty/JettyRolePropertyFileLoginModule.java, rundeckapp/src/main/groovy/org/rundeck/jaas/jetty/ReloadablePropertyFileLoginModule.java
In some cases the debug attribute set in the JAAS module was being ignored. Extra debug messages were being emitted.
=> Fix #4778. Normalize JAAS debugging log messages.

rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_ja.properties, rundeckapp/grails-app/i18n/messages_pt_BR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/views/layouts/base.gsp, rundeckapp/grails-spa/src/components/motd/motd.vue, rundeckapp/grails-spa/src/components/motd/motdIndicator.vue
=> 3.1: motd updates

rundeckapp/src/main/groovy/org/rundeck/app/services/EnhancedNodeService.groovy
Node enhancer caching could cause NPE during race
=> Fix: potential npe caused by race

rundeckapp/build.gradle
enhancement, Adding support for Kerberos authentication
https://github.com/rundeck-plugins/py-winrm-plugin/issues/9
add a wrapper for kinit command to generate the kerberos ticket 
using python pexpect to handler the password prompt
=> upgrade python winrm 2.0.3. Adding support for kerberos authentication

rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
=> [3.0.x backport] remove reference to scriptaculous

rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy, rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy, rundeckapp/grails-spa/src/pages/repository/components/ProviderCard.vue, rundeckapp/grails-spa/src/pages/repository/components/ProviderCardRow.vue, rundeckapp/grails-spa/src/pages/repository/views/PluginConfigurationView.vue, rundeckapp/src/integration-test/groovy/rundeck/services/PluginApiServiceIntegrationSpec.groovy
Add UI plugins to the new installed plugin list.
=> Add UI plugins to the new installed plugin list.

rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy, rundeckapp/src/test/groovy/rundeck/UtilityTagLibSpec.groovy
=> Update runbook marker parsing fixes #4973 

rundeckapp/grails-app/assets/javascripts/menu/home.js
=> [3.0.x backport] fix #4149 correctly trigger project ui loading

core/src/main/java/com/dtolabs/rundeck/core/common/PluginControlService.java, core/src/main/java/com/dtolabs/rundeck/core/common/PluginControlServiceImpl.java, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerTests.groovy, rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
Job Edit/Copy is very slow in some cases
=> Improve performance when copying/editing a job

rundeckapp/grails-app/assets/scss/app.scss, rundeckapp/grails-app/assets/scss/custom/_jumbotron.scss, rundeckapp/grails-app/views/menu/home.gsp, rundeckapp/grails-app/views/menu/projectHome.gsp, rundeckapp/grails-spa/src/pages/project-dashboard/App.vue
=> 3.1: misc ui tweaks

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerTests.groovy
faster use of pluginControlService in job update/create/save actions
=> more optimized use of pluginControlService

rundeckapp/grails-app/assets/javascripts/jobedit.js, rundeckapp/grails-app/assets/scss/custom/process-flow.scss, rundeckapp/grails-app/assets/scss/pages/jobs.scss, rundeckapp/grails-app/assets/scss/paper/_collapse.scss, rundeckapp/grails-app/assets/scss/paper/_dropdown.scss, rundeckapp/grails-app/views/execution/_execDetailsWorkflow.gsp, rundeckapp/grails-app/views/scheduledExecution/_detailsOptions.gsp, rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
Fixes #5006
Minor UI fixes to include: 
* Removes specificity to LI class concerning new pflowlist OL LIs. The creation of new Workflow steps didn't include a class that was added to existing steps. The classes specificity was unnecessary and didn't impact other UI 
* Fixes dropdown padding issue in flowlist LIs
* Removes loading() and emptyHTML() from edit/save Options -> Job Workflow UI
* Fixes misalignment of text in option listing
* Replaces Pale with Smoke grey on Jobs page
=> Fixes #5006 - ui issues in workflow editor

rundeckapp/grails-app/conf/spring/resources.groovy
EnhancedNodeService bean was not being loaded then the node enhancement was not processed.
=> fix #5004 EnhancedNodeService bean was not loaded

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
=> Takeover endpoint with multiple ids correctly using api v32 #5069

rundeckapp/src/main/groovy/org/rundeck/app/services/EnhancedNodeService.groovy
=> [3.0.x backport] fix potential npe caused by race condition in node enhancer

rundeckapp/grails-app/assets/javascripts/menu/jobs.js
Replacing `self.message` for `self.messages` since the first property doesn't exist.
See: https://github.com/rundeck/rundeck/blob/master/rundeckapp/grails-app/assets/javascripts/menu/jobs.js#L47
Fix #5074
=> Uncaught TypeError on jobs page using SCM. #5074

RELEASE.md
WIP: release notes for 3.1-rc2
=> Release notes for 3.1-rc2

core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionReference.java, core/src/main/java/com/dtolabs/rundeck/core/execution/WorkflowExecutionServiceThread.java, core/src/main/java/com/dtolabs/rundeck/core/jobs/JobEventResult.java, core/src/main/java/com/dtolabs/rundeck/core/jobs/JobEventStatus.java, core/src/main/java/com/dtolabs/rundeck/core/jobs/JobExecutionEvent.java, core/src/main/java/com/dtolabs/rundeck/plugins/jobs/JobEventResultImpl.java, core/src/main/java/com/dtolabs/rundeck/plugins/jobs/JobExecutionEventImpl.java, rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/JobPluginService.groovy, rundeckapp/grails-app/services/rundeck/services/JobStateService.groovy, rundeckapp/grails-app/services/rundeck/services/execution/ExecutionReferenceImpl.groovy, rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionJobTest.groovy, rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/TestWEServiceThread.groovy, rundeckapp/src/test/groovy/rundeck/services/JobPluginServiceSpec.groovy
Enhancements for job plugin type
todo:
=> Job plugin type ext1

docker/official/remco/templates/rundeck-config-storage.properties
=> Convert projectStorageType key to lowercase

gradle.properties, rundeckapp/repository/build.gradle
Update repository version to address library vulnerabilities. 
Bump Jackson version that fixes CVEs.
=> Address library vulnerabilities

core/src/main/java/com/dtolabs/rundeck/core/rules/StateWorkflowSystem.java, core/src/main/java/com/dtolabs/rundeck/core/rules/WorkflowEngine.java, core/src/main/java/com/dtolabs/rundeck/core/rules/WorkflowEngineOperationsProcessor.java, core/src/main/java/com/dtolabs/rundeck/core/rules/WorkflowSystemEventHandler.java, core/src/test/groovy/com/dtolabs/rundeck/core/rules/WorkflowEngineOperationsProcessorSpec.groovy
=> Backport : fix #5023 wfengine premature exit due to race condition

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
Fixes #5149
This moves the average duration notification into the same transaction/session as the success/failure notification. This will ensure the session for the proxy object is still active when accessed in the notification service.
=> Fix proxy initialization exception for avg duration notifications

rundeckapp/grails-app/assets/javascripts/executionStateKO.js
=> Backport - Dedupe setps on stepctx

rundeckapp/grails-app/assets/javascripts/executionStateKO.js
=> Backport - Dedupe steps on stepctx

rundeckapp/grails-app/controllers/rundeck/controllers/TourController.groovy, rundeckapp/grails-app/services/rundeck/services/TourLoaderService.groovy, rundeckapp/grails-spa/src/components/tour/main.js, rundeckapp/grails-spa/src/components/tour/services.ts, rundeckapp/src/test/groovy/rundeck/services/TourLoaderServiceSpec.groovy
Add project information to tour http calls so tours can be configured at a project level.
=> Tour plugin project configuration

rundeckapp/grails-app/init/rundeckapp/Application.groovy, rundeckapp/src/test/groovy/rundeckapp/ApplicationTest.groovy
Bugfix for: https://github.com/rundeck/rundeck/issues/5160
Rundeck should get the proper config file
=> Fixes #5160. Rundeck to load specified config file

docker/official/remco/templates/rundeck-config.properties
Add webhooks feature flag to Docker `rundeck-config.properties` template.
=> Docker - Add webhooks feature flag to template

rundeckapp/grails-app/assets/javascripts/vue.js
Vue.js lib that is required for running in dev mode.
=> Adds dev version of vue.js that is necessary for running in dev mode.

core/src/main/java/com/dtolabs/rundeck/core/plugins/metadata/PluginMeta.java, core/src/test/groovy/com/dtolabs/rundeck/core/plugins/ScriptPluginProviderLoaderTest.groovy
Adds missing attribute on PluginMeta
=> Fix #5232 by adding the display attribute to PluginMeta.

rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy
Adds api endpoint for listing installed plugins.
=> Adds api endpoint for listing installed plugins. Fixes #495.

rundeckapp/grails-spa/src/pages/repository/stores/pluginConfig.module.js, rundeckapp/repository/grails-app/controllers/repository/RepositoryController.groovy, rundeckapp/repository/grails-app/controllers/repository/UrlMappings.groovy, rundeckapp/repository/src/main/groovy/repository/RepositoryPluginService.groovy, rundeckapp/repository/src/test/groovy/repository/RepositoryControllerSpec.groovy
Enhance the UI plugin uninstaller with the ability to remove manually installed plugins.
=>  Fix #5193. Plugin uninstaller can now uninstall manually installed plugins

rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy, rundeckapp/repository/grails-app/controllers/repository/RepositoryController.groovy
Fix uninstall of manually installed plugin when only artifact id is sent to API.
=> Fix manual plugin uninstall

rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
=> Fix mispelled word. Fixes #5241.

rundeckapp/grails-spa/src/pages/repository/main.js
Fixes missing uiv translations in plugin repo
=> Fix i18n in plugin repository UI

rundeckapp/grails-app/services/rundeck/services/JobEventsService.groovy, rundeckapp/grails-app/services/rundeck/services/ScmService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
fix #5306 
backport of https://github.com/rundeck/rundeck/issues/5301#issuecomment-536041720
=> [3.0 backport] fix #5306 scm memory leak

rundeckapp/build.gradle, rundeckapp/grails-app/services/rundeck/services/JobEventsService.groovy, rundeckapp/grails-app/services/rundeck/services/ScmService.groovy, rundeckapp/test/unit/rundeck/services/ScmServiceSpec.groovy
Fix #5307 
backport of https://github.com/rundeck/rundeck/pull/5304
=> [2.11 backport] Fix #5301 fix initProject, and clean old listeners

.github/mergeable.yml
Update mergeable bot config, require a milestone before merging a pr
=> Update mergeable config, require milestone for merge

core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmExportPlugin.java, core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmImportPlugin.java, gradle.properties, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy, rundeckapp/application.properties, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy, rundeckapp/grails-app/services/rundeck/services/ScmService.groovy, rundeckapp/test/unit/rundeck/controllers/ScmControllerSpec.groovy, version.properties
=> [2.11 backport] Fix problem with https configuration with clusterFixJob method

.travis.yml, test/docker/dockers/rundeck/scripts/run_tests.sh
Attempt to fix travis builds using openjdk8 (see also #5352 )
=> Travis env fix: use openjdk8

rundeckapp/grails-app/conf/application.yml, rundeckapp/webhooks/grails-app/controllers/webhooks/UrlMappings.groovy, rundeckapp/webhooks/src/main/groovy/webhooks/WebhooksGrailsPlugin.groovy
Fixes #5369
Webhooks on by default.
=> Webhooks on by default.

rundeckapp/grails-spa/src/pages/project-nodes-config/ProjectPluginConfig.vue
bugfix: fixing an issue using additional props on project plugin config vue  ( issue detected with node enhancer plugin)
initialize then map with 
an empty value
=> fixing issue using additional props on project plugin config vue 

rundeckapp/grails-app/utils/rundeck/codecs/JobsXMLCodec.groovy, rundeckapp/src/test/groovy/rundeck/codecs/JobsXMLCodecSpec.groovy
* Fix import error for job xml with single ExecutionLifecycle plugin config entry
handle single plugin entry
=> Fix: error importing job xml with single exec lifecycle plugin entry

core/src/main/java/com/dtolabs/rundeck/core/encrypter/EncrypterResponse.java, core/src/main/java/com/dtolabs/rundeck/core/encrypter/PasswordUtilityEncrypterPlugin.java, plugins/jasypt-encryption-plugin/src/main/java/org/rundeck/plugin/encryption/JasyptEncryptionConverterPlugin.java, rundeckapp/grails-app/controllers/rundeck/controllers/PasswordUtilityController.groovy, rundeckapp/src/integration-test/groovy/rundeck/services/PluginApiServiceIntegrationSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/passwordencrypt/PasswordUtilityEncrypterLoaderServiceSpec.groovy
Fix a broken test, and update naming for the encrypter plugin type
=> Fix test, update naming for encrypter plugin

rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/grails-app/services/rundeck/services/UserService.groovy, rundeckapp/src/main/groovy/rundeck/services/audit/AuditEventsService.groovy, rundeckapp/src/test/groovy/rundeck/services/UserServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/audit/AuditEventsServiceSpec.groovy
Fixes failing test in audit event service.
Provides equivalent data in a test friendly way.
=> Fixes failing test in audit event service.

rundeckapp/grails-app/services/rundeck/services/UserService.groovy, rundeckapp/src/test/groovy/rundeck/services/UserServiceSpec.groovy
=> Restores a method that was removed by a merge. 

rundeckapp/grails-app/assets/scss/custom/mainbar.scss, rundeckapp/grails-app/assets/scss/paper/_responsive.scss
In support of mobile access to Rundeck instances, adjusts the Job Title to be responsive by adding ellipses and a max width at mobile/tablet breakpoints.
fixes #5342
=> Responsive Job Title - Fixes #5342

docker/official/remco/resources.d/rundeck-config-features.properties.toml, docker/official/remco/templates/rundeck-config-features.properties, docker/official/remco/templates/rundeck-config.properties
* Moves feature config into own template
* Enables webhook features by default
* Adds lifecycle plugin feature switch
=> Docker - Move features into separate template

docker/official/remco/templates/rundeck-config-features.properties
enhancement: adding an option on the feature template to enable job lifecycle plugin on docker image
adding an option on the feature template
=> Docker variable to enable/disable job lifecycle plugin

rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp, rundeckapp/grails-app/views/menu/plugins.gsp, rundeckapp/grails-app/views/menu/systemInfo.gsp, rundeckapp/repository/grails-app/conf/plugin.yml, rundeckapp/repository/grails-app/controllers/repository/UrlMappings.groovy, rundeckapp/repository/grails-app/views/artifact/index.gsp, rundeckapp/repository/src/main/groovy/repository/RepositoryGrailsPlugin.groovy
Also fixes issue where repository config previously ignored the boolean value for enable/disable.
=> Enable the repository feature with in-app config

docker/official/remco/templates/rundeck-config-features.properties
Defaults handled by app
Depends on #5483
=> Restructure so we do not need to add each feature explicitly

core/src/main/java/com/dtolabs/rundeck/plugins/jobs/JobOptionImpl.java, examples/example-java-job-lifecycle-plugin/src/main/java/org/rundeck/example/plugin/ExampleJobLifecyclePlugin.java, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/services/rundeck/services/JobLifecyclePluginService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/JobLifecyclePluginServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Fix #5468
Handle errors/exceptions from job lifecycle plugin service layer
=> Fix #5468 joblifecycle plugin error handling

rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
Reduce log level for feature enabled message in bootstrap
=> Change loglevel for cleanExecutionHistoryJob message in bootstrap

rundeckapp/grails-spa/src/components/activity/activityFilter.vue
=> Fix #5501 saving filters should work

gradle.properties
Fix #5377. Upgrades Jackson library to the latest release.
=> Fix #5377. Upgrades Jackson library to the latest release.

rundeckapp/webhooks/grails-app/controllers/webhooks/UrlMappings.groovy, rundeckapp/webhooks/grails-app/controllers/webhooks/WebhookController.groovy, rundeckapp/webhooks/src/test/groovy/webhooks/WebhookControllerSpec.groovy
Constrain webhook post url to POST http method.
=> Fixes #5494. Constrain webhook post url to POST http method.

rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
Sets any auth token with a type empty string to USER.
=> Fixes #5497 by ensuring the auth token type is set to a valid value.

rundeckapp/grails-spa/src/pages/webhooks/views/WebhooksView.vue
Enhance Webhook UI - add a placeholder text for the Post Url field.
=> Enhance Webhook UI - add a placeholder text for the Post Url field.

core/src/main/java/org/rundeck/core/auth/AuthConstants.java
Add webhook type to AuthConstants. This is needed for Acl tooling.
=> Add webhook type to AuthConstants.

rundeckapp/build.gradle
Enhancement: new version of ansible plugin
https://github.com/Batix/rundeck-ansible-plugin/releases/tag/3.1.0
adding ssh-agent support (https://github.com/Batix/rundeck-ansible-plugin/pull/257)
fix NullPointerException for #213 (https://github.com/Batix/rundeck-ansible-plugin/pull/256)
Fix typo in privilege escalation descriptions (https://github.com/Batix/rundeck-ansible-plugin/pull/250)
=> new version of ansible plugin (3.1.0)

core/src/main/java/com/dtolabs/rundeck/core/utils/ThreadBoundLogOutputStream.java
Removing some comment text that was causing a build issue for me
=> Fix: build/run error in idea, remove extended charset chars

rundeckapp/grails-spa/src/pages/webhooks/views/WebhooksView.vue, rundeckapp/webhooks/grails-app/views/webhook/admin.gsp
Remove error icon on webhook error notification. Fix dismiss button position. Fix webhook post url label overflow.
=> Address Webhook UI feedback issues

rundeckapp/grails-app/assets/scss/pages/login.scss
Alligators appeared by a merge conflict and made their way in. Selenium fail.
=> Removes alligators in login.scss

rundeckapp/grails-app/views/common/_sidebar.gsp, rundeckapp/grails-spa/package-lock.json
following a merge issue that allowed for the License notified to appear in the sidebar, this removes that issue and updates the package-lock.json to match what is being built.
=> Removes sidebar license notification, updates package-lock.json

rundeckapp/webhooks/src/main/groovy/webhooks/plugins/JobRunWebhookEventPlugin.groovy, rundeckapp/webhooks/src/main/groovy/webhooks/plugins/LogWebhookEventPlugin.groovy
Fix incorrect description
Use correct logger name, shorten text
=> Fix description of webhook logger plugin

rundeckapp/grails-spa/src/pages/webhooks/i18n.js, rundeckapp/grails-spa/src/pages/webhooks/views/WebhooksView.vue
Update webhooks UI.
* add some help text
* spacing and layout changes
* change plugin selection input
* add Cancel button for new webhooks
=> Some ui updates for webhooks

rundeckapp/repository/grails-app/controllers/repository/RepositoryController.groovy, rundeckapp/repository/src/test/groovy/repository/RepositoryControllerSpec.groovy
Ensure value being parsed is valid before attempting to parse it.
=> Fix #5589 by adding additional checks to the method input value.

rundeckapp/grails-spa/src/pages/menu/components/userSummary.vue
Updates UI for User Summary. Moves search into modal, removes second (top) card, moves checkboxes into top of table, general UI cleanup.
=> adds modal search, moves checkboxes, cleanup UI

rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy, rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy, rundeckapp/webhooks/grails-app/services/webhooks/WebhookService.groovy, rundeckapp/webhooks/src/test/groovy/webhooks/WebhookServiceSpec.groovy
Fixes #5611. Delete all webhooks in project when project is deleted.
=> Fixes #5611. Delete all webhooks in project when project is deleted.

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Fixes an issue where job next execution times may display incorrectly in a cluster.
=>  Fix incorrect job schedule display in cluster mode

docker/official/remco/templates/rundeck-config-features.properties, docker/official/test/remco/test.yml
=> Support toggling features with case sensitive names (bp #5615)

rundeckapp/grails-app/services/rundeck/services/UserService.groovy, rundeckapp/src/test/groovy/rundeck/services/UserServiceSpec.groovy
UserService should correctly report errors on saving user. A simple copy paste error was preventing this.
=> Fix #5704 copy paste err message issue in UserService.

plugins/git-plugin/build.gradle, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitUtil.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy
A clear and concise description of the bug you are fixing (reference issue number), or enhancement you are implementing.
This is a simple dependency update for the jgit library. Quite a few bugs have been fixed in the last 4 years by this library.
I've updated the library, and fixed 1 api call. The `release()` has now been changed to `close()`.
=> update jgit to 5.6.0.201912101111-r

rundeckapp/grails-app/views/menu/_projectExportForm.gsp
=> Fix #5620 webhook checkbox label should work

build.gradle, docker/build.gradle, gradle/wrapper/gradle-wrapper.properties, rundeckapp/build.gradle, settings.gradle
This is required for future Grails upgrade work.
=> [build] Upgrade to gradle 4.8 compatible project structure. 

core/build.gradle, core/src/test/java/com/dtolabs/rundeck/core/common/TestNodesYamlParser.java, grails-persistlocale/build.gradle, grails-securityheaders/build.gradle, rundeckapp/build.gradle, rundeckapp/metricsweb/build.gradle, rundeckapp/repository/build.gradle, rundeckapp/webhooks/build.gradle
Fixes #5702 by upgrading snakeyaml to the same version used by the repository library.
=> Upgrade snakeyaml

core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginRegistry.java, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/fileupload/FSFileUploadPlugin.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/logging/PluginFactoryBean.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/logstorage/TreeExecutionFileStoragePlugin.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/storage/DbStoragePlugin.groovy, rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy, rundeckapp/src/test/groovy/rundeck/services/PluginServiceTests.groovy
Backporting PR #5737 to maint-3.1.x
=> Backport PR 5737 to maint-3.1.x

build.gradle, core/build.gradle, plugins/build.gradle, rundeckapp/build.gradle
Adjusts the Rundeck project to allow for easier external configuration.
=> Allow bundled plugins to be externally specified

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Fixes #5761 by adding scheduled true to the dynamic finder.
=> Fixes #5761 by adding scheduled true to the dynamic finder.

test/selenium/Dockerfile, test/selenium/docker-local-compose.yml, test/selenium/entry.sh, test/selenium/package.json, test/selenium/src/test/selenium.ts
This updates the containers used for the Selenium "viz" testing to be compatible with OSX and to fix breakage from newer Chrome versions(browser crashing during tests).
=> Update selenium viz setup to work on OSX

build.gradle
fixing an issue with multiples matches 
https://github.com/rundeck-plugins/attribute-match-node-enhancer/pull/3
use regex to detect the new lines on the matcher field, in order to use multiples conditionals on the node match plugin
=> upgrade attribute-match-node-enhancer plugin 

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/services/rundeck/services/ScmService.groovy, rundeckapp/grails-app/views/menu/_groupTree.gsp, rundeckapp/grails-app/views/menu/_jobslist.gsp, rundeckapp/grails-app/views/menu/_workflowsFull.gsp, rundeckapp/grails-app/views/menu/jobs.gsp, rundeckapp/grails-app/views/scheduledExecution/_uploadForm.gsp
* job list page with many jobs is slow
* reduce inefficient resource access and curtail unnecessary code paths
* fix UI issue when job list paging was enabled
=> Some improvements to job list page speed with many jobs

rundeckapp/build.gradle, rundeckapp/grails-spa/build.gradle, rundeckapp/grails-spa/package-lock.json, rundeckapp/grails-spa/package.json
* Prevents `package-lock.json` from being constantly updated
* Ensures we are installing the same packages every build; no surprises
=> Install npm packages with ci

rundeckapp/grails-app/views/framework/_storageBrowser.gsp
Fix incorrect html tag content that was added
It does not appear to cause any issues, but is incorrect.
=> Remove spurious text

rundeckapp/grails-app/services/rundeck/services/UserService.groovy
* can occur if user login happens frequently (automated tests)
fixes #5835
handle optimistic locking failure
=> fix #5835 handle registerLogin optimistic locking failure

gradle.properties, grails-persistlocale/build.gradle, grails-securityheaders/build.gradle, rundeckapp/build.gradle, rundeckapp/grails-app/assets/less/library/bootswatch.less, rundeckapp/grails-app/assets/less/library/markdeep.less, rundeckapp/grails-app/assets/scss/custom/buttons.scss, rundeckapp/grails-app/assets/scss/custom/execution-page.scss, rundeckapp/grails-app/assets/scss/custom/expand.scss, rundeckapp/grails-app/assets/scss/custom/flexbox.scss, rundeckapp/grails-app/assets/scss/custom/forms.scss, rundeckapp/grails-app/assets/scss/custom/jobs.scss, rundeckapp/grails-app/assets/scss/custom/links.scss, rundeckapp/grails-app/assets/scss/custom/mainbar.scss, rundeckapp/grails-app/assets/scss/custom/nav-tabs.scss, rundeckapp/grails-app/assets/scss/custom/popovers.scss, rundeckapp/grails-app/assets/scss/custom/rows.scss, rundeckapp/grails-app/assets/scss/custom/table.scss, rundeckapp/grails-app/assets/scss/custom/text.scss, rundeckapp/grails-app/assets/scss/custom/workflow-step.scss, rundeckapp/metricsweb/build.gradle, rundeckapp/repository/build.gradle, rundeckapp/webhooks/build.gradle
Update asset pipeline plugin for gradle and grails.
=> Update asset pipeline plugin for gradle and grails.

plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/BaseGitPluginSpec.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginFactorySpec.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitUtilSpec.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/TestSystemReader.groovy
jgit upgrade causes user git gpg signing config to be applied during the git-plugin unit tests.
Use a mock SystemReader
=> Fix: user git config should not be used during tests

rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy, rundeckapp/src/test/groovy/rundeck/services/PluginApiServiceSpec.groovy
Fixes #5727 by using the plugin registry source that includes groovy plugin metadata.
=> Fixes #5727 by using the plugin registry source that includes groovy plugin metadata.

rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp
* cleans up bugfix from earlier grails versions
Fixes #5830 
Remove extra encoding that was added to mitigate earlier grails bug
Previous change that was incomplete: https://github.com/rundeck/rundeck/commit/c80f85d523935f64085159441c5a075b134af9e4#diff-4bcd998d18397eeab932e174eed27a0c
* ref https://github.com/grails/grails-core/issues/10256
=> Fix #5830 select values should not be encoded

rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Refactoring code notification service when the context variables are built for the email and notification plugins.
common code for building context variables that are passed to email and notification plugins.
=> Refactoring context variables for email and plugins notification 

rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Fix test failures after pr merging
=> Fix test failure

rundeckapp/grails-app/views/user/list.gsp
I was just browsing the code and spotted what appears to be a random 'e'.
=> Remove random 'e' character

rundeckapp/grails-app/views/menu/jobs.gsp, test/selenium/lib/SeleniumBasic/rundeck-SeleniumBasic/jobs/job-0088e04a-0db3-4b03-adda-02e8a4baf709.xml, test/selenium/src/__tests__/run-job/jobs-list-page.test.ts, test/selenium/src/pages/jobsList.page.ts
Fix #5063 
Replace old usage of prototype with jquery
=> Fix #5063 show error in job exec popup

rundeckapp/grails-app/services/rundeck/services/scm/ScmJobImporter.groovy, rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp, rundeckapp/src/test/groovy/rundeck/services/scm/ScmJobImporterSpec.groovy
Fixes #5868 
adds test
* Fixing behavior due to project import refactor
* Fixed GSP error
=> Fix #5868 git import should not fail

rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy, rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
=> Fix #5872 broken link to remote option usage docs

rundeckapp/grails-app/views/framework/editProjectNodeSourceFile.gsp
disabling prototype node file editor page
=> disabling prototype node file editor page

rundeckapp/grails-app/services/rundeck/services/scm/ScmJobImporter.groovy, rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp, rundeckapp/src/test/groovy/rundeck/services/scm/ScmJobImporterSpec.groovy
Ref #5868 
cherry pick changes to master
=> Fix #5868 git import (port to master)

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
=> Fix orchestrator issue

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy, test/selenium/src/__tests__/run-job/jobs-list-page.test.ts, test/selenium/src/pages/jobsList.page.ts
Handling of `groupPath` query parameter was not returning the correct paging data for UI endpoints.
Fix difference b/w query and count criteria formulation, and fix issue with groupPath response for `-` value.
=> Fix job query group/paging

rundeckapp/grails-app/views/menu/jobs.gsp
Adds some json data about query parameters for use by ui plugins.
=> Include some filter params as json on page

rundeckapp/grails-app/init/rundeckapp/Application.groovy, rundeckapp/grails-app/init/rundeckapp/init/RundeckInitializer.groovy, rundeckapp/src/test/groovy/rundeckapp/ApplicationTest.groovy
Add a directory for addon features.
=> Add a directory for addon features.

rundeckapp/src/test/groovy/rundeck/controllers/ProjectControllerSpec.groovy
fix test error after merging #5833
=> Fix test error ref #5833

build.yaml
fix issue https://github.com/rundeck/rundeck/issues/5895
removing bash wrapper and using the config variable on the script-interpreter
=> upgrade py-winrm plugin version

SECURITY.md
Adds Security Document to repo
=> Adds Security and Vulnerability Content

.circleci/config.yml, .travis.yml, rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceIntegrationSpec.groovy
Ensures integration tests are run
=> Run check command for tests

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
=> fix for issue 5889 global variables delete

core/src/main/java/com/dtolabs/rundeck/core/resources/format/ResourceFormatParserService.java, rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
Fixes #5964 
1. Fix authorization checks for API endpoint
2. Handle IOExceptions
3. Clean the MIME type before comparison
=> Some fixes for saving writeable project node data

rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/gui/UserSummaryMenuItem.groovy
Update user summary menu item to use a spring bean.
=> Update user summary menu item to use a spring bean.

rundeckapp/grails-spa/src/pages/menu/components/userSummary.vue
Add the ability to refresh the user summary page using the event bus.
=> Add the ability to refresh the user summary page using the event bus.

rundeckapp/build.gradle
Update grails spring security plugin to 3.3.1
=> Update grails spring security plugin to 3.3.1

docker/official/Dockerfile, docker/ubuntu-base/Dockerfile
=> Docker - Refresh base image and update remco

docker/official/remco/templates/rundeck-config-storage.properties
=> Docker - Fix default value for config storage converter path

rundeckapp/grails-spa/build/webpack.base.conf.js, rundeckapp/grails-spa/package-lock.json, rundeckapp/grails-spa/package.json
Prevents overriding global styles/resets
=> Scope global antd styles

test/selenium/src/cli.ts, test/testdeck/src/DockerCompose.ts, test/testdeck/src/commands/Cluster.ts, test/testdeck/src/commands/cluster_commands/DownCommand.ts
* Fixes help on nested commands
* Displays docker-compose output when running cluster commands
=> Test - Testdeck fixes

rundeckapp/grails-app/assets/javascripts/menu/joboptions.js
Fix #6065 
use plugin values for multivalue list
=> Fix #6065 plugin values should be shown in multivalued list

rundeckapp/grails-app/conf/application.groovy, rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy, rundeckapp/src/main/groovy/org/rundeck/web/infosec/ContainerPrincipalRoleSource.groovy
Better spring security integration.
=> Better spring security integration.

rundeckapp/grails-spa/packages/ui/babel.config.js
Fixes a change to babel config that snuck in during refactor preventing beta exec viewer style deps from being loaded.
=> Fix style import

rundeckapp/grails-spa/package-lock.json, rundeckapp/grails-spa/packages/ui/src/components/tour/interfaces/Tours.ts, rundeckapp/grails-spa/packages/ui/src/components/tour/tourDisplay/App.vue, rundeckapp/grails-spa/packages/ui/src/components/tour/tourPicker/App.vue, rundeckapp/grails-spa/packages/ui/vue.config.js
Tour enhancement:
- resume button
- current-url on tour's steps
- Add a resume button to back to the page where the tour started. 
- adding a new field on tour's steps with the currentUrl. When a step defines a current-url, that URL will be loaded when the step is active. The nextStepUrl is still working to maintain compatibility.
=> tours enhancement

rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/internal/framework/FrameworkPropertyLookupFactory.groovy
=> Remove debug println.

.travis.yml, core/build.gradle, rundeck-authz/build.gradle, rundeck-storage/build.gradle, rundeckapp/build.gradle, scripts/travis-build.sh, scripts/travis-helpers.sh
* Sync to maven on tag release
* Publish Docker image on tag release
* Trigger packaging build on tag release
=> Build enhancements

rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
Fix #6139 
fix method call arguments
add tests
=> Fix #6139 500 error manually setting project exec disabled property

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Log scheduler exceptions as warnings, which are usually "The schedule will never fire", instead of dumping stacktraces into the log.
- reduces stacktraces in rundeck log
=> Handle quartz scheduler failures and log as warning

core/src/main/java/com/dtolabs/rundeck/core/config/Features.java, core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/build.gradle, rundeckapp/grails-app/conf/application.groovy, rundeckapp/grails-app/conf/application.yml, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-app/controllers/rundeck/interceptors/InterceptorHelper.groovy, rundeckapp/grails-app/controllers/rundeck/interceptors/RefererInterceptor.groovy, rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionLifecyclePluginService.groovy, rundeckapp/grails-app/services/rundeck/services/JobLifecyclePluginService.groovy, rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy, rundeckapp/grails-app/services/rundeck/services/feature/FeatureService.groovy, rundeckapp/grails-app/taglib/rundeck/ConfigTagLib.groovy, rundeckapp/grails-app/views/framework/projectNodeSources.gsp, rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp, rundeckapp/grails-app/views/user/login.gsp, rundeckapp/src/integration-test/groovy/rundeck/services/PluginApiServiceIntegrationSpec.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/config/RundeckConfig.groovy, rundeckapp/src/main/groovy/org/rundeck/app/services/EnhancedNodeService.groovy, rundeckapp/src/test/groovy/rundeck/ConfigTagLibSpec.groovy, rundeckapp/src/test/groovy/rundeck/interceptors/RefererInterceptorSpec.groovy, rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/ConfigurationServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/ExecutionLifecyclePluginServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/feature/FeatureServiceSpec.groovy
This PR is designed to provide a starting place for adding and using Rundeck configs in a type safe way. The underlying mechanism uses Spring's configuration mapping feature.
Please give feedback regarding the technical solution and structuring of the typed configs.
=> Use typed configuration for Rundeck configs.

core/src/main/java/com/dtolabs/rundeck/plugins/tours/TourLoaderPlugin.java, rundeckapp/grails-app/assets/scss/custom/mainbar.scss, rundeckapp/grails-app/services/rundeck/services/TourLoaderService.groovy, rundeckapp/grails-app/views/framework/adhoc.gsp, rundeckapp/grails-app/views/framework/nodes.gsp, rundeckapp/grails-app/views/layouts/base.gsp, rundeckapp/src/test/groovy/rundeck/services/TourLoaderServiceSpec.groovy
enhancement: 
- modify tour loader plugins to pass project name
- change layout to the better positioning of tours on the node and adhoc page
=> tours enhancement 3

rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/PluginControllerSpec.groovy
=> Fix #6160 ui plugin detail not showing

docker/official/remco/templates/jaas-loginmodule.conf
rebased version of  https://github.com/rundeck/rundeck/pull/5828
fixes #6172
=> add supplemental roles to ldap config

core/src/main/java/com/dtolabs/rundeck/core/config/Features.java, core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/conf/application.groovy, rundeckapp/grails-app/views/layouts/base.gsp
Fix #6174 
Set production default for feature flag, update UI code checking feature flag.
=> Fix #6174 broken ui without legacy feature flag config

rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue
=> Replace magic variable with constant

docker/official/remco/templates/rundeck-config.properties
Add ability to toggle the workflow config 973 fix in docker.
=> Add ability to toggle the workflow config 973 fix in docker.

test/testdeck/package.json
Types just updated within the past couple hours and broke some tests :/
=> Pin types for js-yaml

docker/official/remco/templates/rundeck-config.properties
Fix camel case key in docker remco template for workflow fix.
Update server.session.timeout to server.servlet.session.timeout in docker template.
=> Fix a couple of issues in docker remco template

rundeckapp/build.gradle
=> Open additional modules for reflective access to avoid illegal reflective access warnings

rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy
=> Updates an existing plugin when using plugin upload GUI instead of reporting error

rundeckapp/grails-spa/packages/ui-trellis/vue.config.js, rundeckapp/grails-spa/packages/ui/package-lock.json, rundeckapp/grails-spa/packages/ui/package.json, rundeckapp/grails-spa/packages/ui/vue.config.js
Process the source maps generated from UI Trellis so browser dev tools can resolve.
Eval does not appear to be supported via this pipeline and setup.
=> Build - Fix source map loading from ui-trellis

rundeckapp/grails-app/assets/stylesheets/ansi24.css, rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/utils/rundeck/codecs/AnsiColorCodec.groovy, rundeckapp/grails-app/views/layouts/base.gsp, rundeckapp/src/test/groovy/rundeck/codecs/AnsiColorCodecSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy
Fix #6198 
handle ansi modes combined with colors
**also**
=> Ansi color 24 bit support, Fix #6198 bold mode plus 256 color should work

rundeckapp/grails-app/conf/application.groovy
=> Set ehcache missing cache strategy to 'create' to avoid warnings

core/build.gradle, gradle.properties, grails-persistlocale/build.gradle, grails-securityheaders/build.gradle, rundeck-authz/rundeck-authz-yaml/build.gradle, rundeckapp/build.gradle, rundeckapp/metricsweb/build.gradle, rundeckapp/repository/build.gradle, rundeckapp/webhooks/build.gradle
=> Update snakeyaml to 1.26

rundeckapp/src/test/groovy/rundeck/services/audit/AuditEventsServiceSpec.groovy
Fix random test failure due to timing issue
=> Fix: remove timing issue for test

rundeckapp/grails-app/views/menu/userSummary.gsp, rundeckapp/grails-spa/packages/ui/src/pages/menu/components/userSummary.vue, rundeckapp/grails-spa/packages/ui/src/pages/menu/i18n.js
* remove "card" layout from inside vue component
* match other app styles
* allows user summary vue component to better embed in other layouts
=> Cleanup User Summary page vue/layout

rundeckapp/grails-app/conf/application.groovy
Use create for missing cache strategy with jcache.
=> Fix noisy cache warnings on startup

plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy
Fix #5801. Remove reference to plugin that doesn't exist.
=> Fix #5801. Remove reference to plugin that doesn't exist.

core/src/main/java/org/rundeck/app/bootstrap/PreBootstrap.java, rundeckapp/grails-app/init/rundeckapp/Application.groovy, rundeckapp/grails-app/init/rundeckapp/cli/CommandLineSetup.groovy, rundeckapp/src/test/groovy/rundeckapp/ApplicationTest.groovy, rundeckapp/src/test/groovy/rundeckapp/TestPrebootstrap.groovy, rundeckapp/src/test/resources/META-INF/services/org.rundeck.app.bootstrap.PreBootstrap
Introduce PreBoostrap service interface.
Allow config loading routines to be bypassed if they are already loaded by another process.
=> Core config enhancements

rundeckapp/grails-app/init/rundeckapp/cli/CommandLineSetup.groovy, rundeckapp/src/test/groovy/rundeckapp/cli/CommandLineSetupTest.groovy
=> Restores the ability to specify the server config dir with the command line option -c.

rundeckapp/grails-app/init/rundeckapp/Application.groovy
Remove Logger in Application class.
Fix #6363 by removing the Logger.
=> [3.3.2] Fix logging system initialization

rundeckapp/grails-app/assets/javascripts/menu/home.js, rundeckapp/grails-app/taglib/rundeck/ConfigTagLib.groovy, rundeckapp/grails-app/views/menu/home.gsp, rundeckapp/src/test/groovy/rundeck/ConfigTagLibSpec.groovy
Adds paging to the Project list to improve speed for thousands of projects.
Configuration flags:
``` properties
rundeck.gui.home.projectList.pagingEnabled=true
rundeck.gui.home.projectList.pagingMax=30
```
=> Paged Project List

cve-suppress.xml, plugins/object-store-plugin/build.gradle, plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreTree.groovy, plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreUtils.groovy, plugins/object-store-plugin/src/test/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreTreeWithDirectAccessDirSourceTest.groovy, plugins/object-store-plugin/src/test/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreTreeWithMemoryDirSourceTest.groovy, plugins/object-store-plugin/src/test/groovy/testhelpers/MinioTestUtils.groovy
=> Bring minio client library up to 7.1.0

rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/grails-app/services/rundeck/services/PluginService.groovy, rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
fix issue creating/editing a job loading notification dynamic properties
moving call of getDynamicProperties to pluginService
=> fix issue creating a job loading notification dynamic properties

test/selenium-docker-compose.yml, test/selenium/docker-compose.yml, test/selenium/docker-local-compose.yml, test/testdeck/package.json
Chrome update requiring new chromedriver version and container.
=> Test - Update chrome and chromedriver

rundeckapp/grails-app/assets/javascripts/menu/home.js
Update to fix some issues with previous pr #6391 
=> Project list speed update2

rundeckapp/grails-app/assets/javascripts/menu/home.js, rundeckapp/grails-app/assets/javascripts/menu/project-model.js, rundeckapp/grails-app/views/menu/home.gsp
* Use common pager/search code utility for KO.
* add mechanism for extra KO component for project items
=> Project list page update2

rundeckapp/grails-app/assets/javascripts/jobedit.js, rundeckapp/grails-app/views/framework/_stepPluginFilterInputGroup.gsp, rundeckapp/grails-app/views/scheduledExecution/create.gsp, rundeckapp/grails-app/views/scheduledExecution/edit.gsp
bugfix:
- allow underscore characters option name
- fix keypress event in step search filter
=> fix js issues job create/edit form

rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerTests.groovy, test/api/include.sh
=> Change http return when execution status is passive from 503 to 200

test/selenium/package.json
=> Pin js-yaml types

rundeckapp/grails-app/assets/javascripts/util/pager.js, rundeckapp/grails-app/views/menu/home.gsp
not just searches (e.g will include project favorites)
Shows "X Projects Found" when results are filtered, not just via search box.
=> Project List minor UI: Show result count indicator when using any filter method

rundeckapp/grails-app/assets/javascripts/menu/home.js, rundeckapp/grails-app/assets/javascripts/util/pager.js, rundeckapp/grails-app/views/menu/_aclsPagingKO.gsp, rundeckapp/grails-app/views/menu/acls.gsp, rundeckapp/grails-app/views/menu/home.gsp, rundeckapp/grails-spa/packages/ui-trellis/src/components/utils/Pagination.vue, rundeckapp/grails-spa/packages/ui/src/components/ko-paginator/main.ts, rundeckapp/grails-spa/packages/ui/vue.config.js
Replaces the initial stand-in KO project pagination controls with the `Pagination` Vue component.
=> Vue project pagination controls

build.yaml
Fix exposing ssh keys inside plugin
=> update openssh version

rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/WorkflowControllerSpec.groovy
=> port pr 6441 to main

rundeckapp/grails-app/domain/rundeck/JobExec.groovy, rundeckapp/src/test/groovy/rundeck/JobExecSpec.groovy
=> Fix #6335 failOnDisable flag in jobref definition not serialized/loaded correctly

README.md
Added link to community survey and set release notes url to docs site.
=> Add Community Survey to Readme + Release Notes Fix
