rundeck/rundeck

build.yaml
upgrade pywinrm plugin version
add support for kerberos delegation
https://github.com/rundeck-plugins/py-winrm-plugin/pull/65
=> upgrade pywinrm plugin. Adding flag for enabling kerberos delegation

gradle.properties, version.properties
=> Set version to 3.3.4-SNAPSHOT

rundeckapp/webhooks/grails-app/views/webhook/admin.gsp
=> Fix sidebar active indicator on webhooks page

core/src/main/java/com/dtolabs/rundeck/core/plugins/DirPluginScanner.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/JarPluginScanner.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginDirChangeEvent.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginDirChangeEventListener.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginDirChangeType.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginDirProvider.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/ScriptPluginScanner.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/WatchingPluginDirProvider.java, core/src/test/groovy/com/dtolabs/rundeck/core/plugins/DirPluginScannerSpec.groovy, core/src/test/java/com/dtolabs/rundeck/core/plugins/TestDirPluginScanner.java, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/init/rundeckapp/init/PluginCachePreloader.groovy, rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy, rundeckapp/grails-app/services/rundeck/services/UiPluginService.groovy, rundeckapp/src/integration-test/groovy/rundeck/services/FileUploadServiceIntegrationSpec.groovy, rundeckapp/src/integration-test/groovy/rundeck/services/PluginApiServiceIntegrationSpec.groovy
Speed up Rundeck by making filesystem plugin access faster. Added a plugin cache preloader. Also adjusted some places in the UIPluginService to enhance caching.
=> Speed up filesystem plugin access

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
incorrect parameters to rescheduleJob method prevented the job from being properly deleted from scheduler
Fix #6357
=> Fix #6357 disabling schedule in job edit does not work

rundeckapp/build.gradle
=> Upgrade mariadb driver to 2.7.0

rundeckapp/grails-spa/packages/ui/src/pages/repository/components/PluginCard.vue
=> Revert "Fix the display of Enterprise plugins when listing plugins"

.github/workflows/dependencyCheck.yml, .travis.yml
Run owasp dependency check on a schedule
=> Run owasp dependency check every 6 hours

.circleci/config.yml
enable dependencyCheck in circleci
=> Run owasp dependency checks in circleci

.circleci/config.yml
* Allows normal builds to continue if OWASP checks fail
* Sets up a nightly build that fails if OWASP checks fail
=> Only fail owasp check on nightly

rundeckapp/grails-spa/packages/ui/src/components/activity/activityFilter.vue
for issue https://github.com/rundeck/rundeck/issues/6089
VUE component needs to add the filter `dostartdateXXX/doenddateXXX` on date filters.
=> Fix Activity Date Filter 

core/src/main/java/com/dtolabs/rundeck/core/config/Features.java, core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/conf/application.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy, rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ExecutionCleanerConfig.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ExecutionCleanerConfigImpl.groovy, rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerTest.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ProjectControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
Speedup app startup with many projects
=> Async startup of execution history cleaner tasks

gradle.properties
Update Spring framework to address OWASP report.
Fixes #6541
=> Update Spring framwork to 5.1.18.RELEASE

rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
=> Update projectLabels method

rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java, rundeckapp/src/test/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModuleTest.groovy
This allows the bind password to be changed at runtime without a server restart in Enterprise.
=> Update Ldap module to try bind password from the configuration service.

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
Add rundeck.login.localLogin.enabled to config base class.
=> Add rundeck.login.localLogin.enabled to config base class.

.travis.yml
=> Update travis slack integration

rundeckapp/build.gradle
Resolves rundeckpro/rundeckpro#1326 .
=> Update tomcat-jdbc version to 9.0.39

rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy, rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceTests.groovy
Fix por issue https://github.com/rundeck/rundeck/issues/6528
It fixes the exception and also the file storage counter
=> fix #6528 exception in log file storage

rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/domain/rundeck/ExecReport.groovy, rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/grails-app/services/rundeck/services/data/ExecutionDataService.groovy, rundeckapp/grails-app/services/rundeck/services/data/ScheduledExecutionDataService.groovy, rundeckapp/grails-app/views/execution/mailNotification/_newStatus.gsp, rundeckapp/grails-app/views/execution/mailNotification/_oldStatus.gsp, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/exec-status.scss, rundeckapp/grails-spa/packages/ui/src/components/activity/activityFilter.vue, rundeckapp/grails-spa/packages/ui/src/components/activity/activityList.vue, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ExecQuery.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
Add the ability to create an entry in the execution and exec report tables for a job that did not execute at its scheduled time.
=> Add ability to mark a schedule as missed.

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
Add missing config for rundeck.api.tokens.duration.max
=> Add missing config for rundeck.api.tokens.duration.max

rundeckapp/grails-app/assets/javascripts/menu/aclListing.js, rundeckapp/grails-app/assets/javascripts/util/loader.js, rundeckapp/grails-app/views/menu/acls.gsp
Fix #6609 
Fix https://github.com/rundeckpro/rundeckpro/issues/1355
FS acls do not need ajax loader, so should not attempt to
=> [3.3.6-rc1] Fix #6609 warning shown for filesystem acls

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/controllers/rundeck/interceptors/UserInterceptor.groovy, rundeckapp/src/test/groovy/rundeck/interceptors/UserInterceptorSpec.groovy
Adds feature requested in pro: https://github.com/rundeckpro/rundeckpro/issues/1405
=> Add ability to redirect login page to a different uri.

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/src/main/groovy/org/rundeck/security/RundeckPreauthSuccessEventHandler.groovy, rundeckapp/src/main/groovy/org/rundeck/security/RundeckUserDetailsService.groovy, rundeckapp/src/test/groovy/org/rundeck/security/RundeckPreauthSuccessEventHandlerSpec.groovy
=> Allow syncing user info in preauthenticated mode.

rundeckapp/grails-app/controllers/rundeck/utils/OptionsUtil.groovy, rundeckapp/src/test/groovy/rundeck/controllers/OptionsUtilsSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/OptionsUtilsTests.groovy
=> Add user email to the context that is used to resolve parameters for options.

build.yaml
Upgrade pywinrm plugin version
added a function to remove/replace simple quotes when execute CMD command
https://github.com/rundeck-plugins/py-winrm-plugin/pull/69
=> Update pywinrm plugin. Added a function to remove/replace simple quotes when execute CMD command

rundeckapp/repository/grails-app/controllers/repository/RepositoryController.groovy, rundeckapp/repository/src/test/groovy/repository/RepositoryControllerSpec.groovy
Fixes auth call using frameworkService.
=> Migrate auth call from framworkService to new acl classes in repository controller.

core/src/main/java/org/rundeck/app/acl/AppACLContextImpl.java, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Fix an issue in ACL refactor: ACL lists are not sorted
=> Fix: ACL listing should be sorted (refactor update)

rundeckapp/grails-app/domain/rundeck/AuthToken.groovy, rundeckapp/grails-app/services/rundeck/services/ApiService.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/tokens/Token.groovy, rundeckapp/src/test/groovy/rundeck/AuthTokenSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ApiControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/RundeckAuthTokenManagerServiceSpec.groovy
=> fix #6703 oracle reserved word 'mode'

rundeckapp/src/main/groovy/rundeck/services/AuthorizingNodeExecutionService.groovy, rundeckapp/src/main/groovy/rundeck/services/DirectNodeExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/AuthorizingNodeExecutionServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/DirectNodeExecutionServiceSpec.groovy
Fix NPE error performing node health checks
Fixes https://github.com/rundeckpro/rundeckpro/issues/1472
Update use of auth context evaluator
=> (3.3.8rc5) Fix: NPE performing Node Health Checks

README.md
Survey is no longer running
3. Please be sure the issue you are addressing is referenced in a commit, or the body …
=> remove OSS survey

build.yaml
**Is this a bug fix, or an enhancement? Please describe.**
Upgrade pywinrm plugin version
added a function to remove/replace simple quotes when execute command
https://github.com/rundeck-plugins/py-winrm-plugin/pull/71
=> Update pywinrm plugin. Added a function to remove/replace simple quotes when execute command

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/assets/javascripts/application.js, rundeckapp/grails-app/assets/javascripts/jobedit.js, rundeckapp/grails-app/conf/application.groovy, rundeckapp/grails-app/views/layouts/base.gsp
* Publish events when the job has been edited
* Add a feature flag
=> Add hooks for workflow designer

rundeckapp/grails-app/assets/javascripts/menu/jobs.js
JS access to synchstatus enum values from scm is broken in jobs.js
FIXES  #6668
=> Fix SCM icons lost after 3.3.7 upgrade

rundeckapp/grails-app/assets/javascripts/menu/jobs.js
Additional fix for #6668 (adding onto #6735), fixes display of overall project status.
=> Additional fix for #6668, fix display of overal scm state

rundeckapp/grails-spa/packages/ui-trellis/src/stories/theme.stories.tsx, rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/app.js, rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_tabs-navs-pagination.scss, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/app.js
=> Update tabs style

rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_tabs-navs-pagination.scss, rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_variables.scss
=> add animation effects to nav tabs

rundeckapp/grails-app/conf/application.groovy, rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/NavBar.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/NavBarContainer.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/NavBarDrawer.vue, rundeckapp/grails-spa/packages/ui/package-lock.json
=> add drawer style

rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_view.scss
=> Do not set z-index to prevent children being stuck in stacking context

rundeckapp/grails-app/services/rundeck/services/AuthorizationService.groovy
Enable cache clear for system acl path directly
rundeckpro issue https://github.com/rundeckpro/rundeckpro/issues/1535
=> Add method for cache clean for system path directly

rundeckapp/grails-app/views/common/_mainbar.gsp, rundeckapp/grails-app/views/menu/home.gsp, rundeckapp/grails-app/views/menu/projectHome.gsp, rundeckapp/grails-spa/packages/ui-trellis/package-lock.json, rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/app.scss, rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/custom/mainbar.scss, rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/custom/project-list.scss, rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_cards.scss, rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_sidebar-and-main-panel.scss, rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_variables.scss, rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/mixins/_buttons.scss, rundeckapp/grails-spa/packages/ui/package-lock.json
=> CSS Refine

core/src/main/java/com/dtolabs/rundeck/core/authorization/AclsUtil.java, core/src/main/java/com/dtolabs/rundeck/core/authorization/SubjectAuthContext.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/PropertyObjectValidator.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/PropertyUtil.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/Validator.java, core/src/test/groovy/com/dtolabs/rundeck/core/plugins/configuration/ValidatorSpec.groovy, rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/Authorization.java, rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/Authorizations.java, rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/RuleEvaluator.java, rundeck-authz/rundeck-authz-api/src/test/groovy/com/dtolabs/rundeck/core/authorization/AuthorizationsSpec.groovy, rundeckapp/grails-app/views/framework/_pluginConfigPropertySummaryValue.gsp
* update some Property validation methods
* update some Authorization utilities: add ability to merge Authorizations which are not AclRuleSetSources (ie. authorizations which are not defined by acl rules)
Minor internal enhancement.
=> Updates: property validation and authorization utilities

plugins/upvar-plugin/src/main/java/org/rundeck/plugin/vars/ExportVarWorkflowStep.java, plugins/upvar-plugin/src/test/groovy/org/rundeck/plugins/vars/ExportVarWorkflowStepSpec.groovy
=> minor code correction

rundeckapp/grails-app/views/common/_mainbar.gsp, rundeckapp/grails-app/views/layouts/base.gsp, rundeckapp/grails-spa/packages/ui-trellis/package-lock.json, rundeckapp/grails-spa/packages/ui-trellis/package.json, rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/Popper.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/UtilityWidgetItem.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelect.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelectButton.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/projectSelect.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/rundeck-info/info.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/stores/Projects.ts, rundeckapp/grails-spa/packages/ui-trellis/src/stores/RootStore.ts, rundeckapp/grails-spa/packages/ui-trellis/src/vue-virtual-scroller.d.ts, rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/app.scss, rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/custom/mainbar.scss, rundeckapp/grails-spa/packages/ui/package-lock.json, rundeckapp/grails-spa/packages/ui/src/components/project-picker/main.ts, rundeckapp/grails-spa/packages/ui/vue.config.js
Adds a project picker widget to the main bar. Replaces the existing project "breadcrumb".
=> Project Picker

test/ci-test-docker-selenium.sh, test/selenium/package.json, test/testdeck/package.json
This change attempts to _unpin_ the Chrome and ChromeDriver versions so they can update together.
Hopefully this will allow the selenium tests to self-correct when new versions are released.
=> Chrome and ChromeDriver greenfields

rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/news/News.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/news/news.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/stores/News.ts, rundeckapp/grails-spa/packages/ui-trellis/src/stores/RootStore.ts, rundeckapp/grails-spa/packages/ui/src/components/community-news-notification/main.js, rundeckapp/grails-spa/packages/ui/src/components/project-picker/main.ts
New community news widgets. This is an initial implementation and will need some follow-up to add unread indicators and etc.
=> Add news widget

core/src/main/java/com/dtolabs/rundeck/core/common/Framework.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/FilePluginCache.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/JarPluginScanner.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/WatchingPluginDirProvider.java
Update java access modifiers to enhance extensibility.
=> Update java access modifiers to enhance extensibility.

rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_cards.scss
This should un-explode the exploded button groups.
=> Fix exploded button groups

rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/Popper.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/UtilityActionItem.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/UtilityWidgetItem.vue, rundeckapp/grails-spa/packages/ui-trellis/src/stores/NavBar.ts, rundeckapp/grails-spa/packages/ui-trellis/src/stores/Releases.ts, rundeckapp/grails-spa/packages/ui-trellis/src/stores/System.ts, rundeckapp/grails-spa/packages/ui-trellis/src/stores/UtilityBar.ts, rundeckapp/grails-spa/packages/ui/src/components/navbar/main.ts
Cleanup for and small changes for external consumption.
=> Utility bar updates

gradle.properties, rundeckapp/src/main/groovy/org/rundeck/security/CliAuthTester.groovy, rundeckapp/src/main/groovy/org/rundeck/security/RundeckJaasAuthenticationProvider.groovy, testbuild.groovy
=> Bump Jetty to 9.4.38.v20210224

rundeckapp/grails-spa/README.md, rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/UtilityActionItem.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/UtilityBar.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/UtilityWidgetItem.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/utilitybar.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/stores/UtilityBar.ts
=> Add support for utility bar counters

build.yaml, rundeckapp/build.gradle
Move jackson dataformat cbor dependency into Rundeck for coordinated lib versioning.
=> Update AWS source model plugin version.

rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy, rundeckapp/grails-app/views/404.gsp, rundeckapp/grails-app/views/405.gsp, rundeckapp/grails-app/views/common/_footer.gsp, rundeckapp/grails-app/views/user/login.gsp, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/pages/four-oh-four.scss, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/pages/login.scss, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_footers.scss, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_responsive.scss
* Cleanup login layout and footer
* Update bare help link location to the getting help page
=> Login footer cleanup

rundeckapp/grails-app/views/common/_navBarProjectSettingsData.gsp, rundeckapp/grails-app/views/framework/adhoc.gsp, rundeckapp/grails-app/views/framework/nodes.gsp, rundeckapp/grails-app/views/menu/jobs.gsp
Fixes up the subtitle sections on some screens to more or less look/feel as previously.
Fixes up the subtitle section on:
* Adhoc commands
* Nodes
* Jobs
Leaves along:
* Execution show
* Dashboard
=> Fixup for subtitle sections

rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy, rundeckapp/grails-app/services/rundeck/services/ScmService.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
It performs a clean before deleting the configuration.
=> scm delete nows perfoms a clean before deleting the configuration

rundeckapp/grails-spa/packages/ui/package-lock.json, rundeckapp/grails-spa/packages/ui/src/pages/repository/App.vue, rundeckapp/grails-spa/packages/ui/src/pages/repository/components/PluginCard.vue, rundeckapp/grails-spa/packages/ui/src/pages/repository/components/Repository.vue
- Adjusted styles of plugin card
=> Plugin Repository UI Refine

rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/gui/SystemConfigMenuItem.groovy
enhancement 
moved system configuration to menu item so it can be overwritten if needed
=> move System Configuration to a menu item

grails-metricsweb/build.gradle, grails-persistlocale/build.gradle, grails-repository/build.gradle, grails-securityheaders/build.gradle, grails-webhooks/build.gradle
Ensure all grails plugins use the same version specified in project root.
=> Align asset pipeline plugin versions for all grails plugins.

rundeckapp/grails-spa/packages/ui-trellis/src/components/version/ServerDisplay.vue, rundeckapp/grails-spa/packages/ui-trellis/src/stores/System.ts
* Stop hardcoding my UUID :)
* Properly set the color
* Use correct UUID component for the icon lookup
=> Fixup server display

rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/domain/rundeck/LogFileStorageRequest.groovy
Backport for same change on 3.4.0.
=> Add indexes to Execution and LogFileStorageRequest to improve performance.

rundeckapp/grails-app/migrations/changelog.groovy, rundeckapp/grails-app/migrations/core/ConstraintsIndexesKeys.groovy
=> fix for db migration with mariadb

rundeckapp/grails-app/views/menu/_projectExportForm.gsp, rundeckapp/grails-app/views/menu/_workflowsFull.gsp, rundeckapp/grails-app/views/menu/projectAcls.gsp, rundeckapp/grails-spa/packages/ui/src/components/activity/activityFilter.vue
- Add .btn-cta to buttons that have first priority action on the screen
=> Enhance Call to Action Buttons

rundeckapp/build.gradle
Update tomcat jdbc lib to 9.0.44.
=> Update tomcat jdbc lib to 9.0.44.

rundeckapp/grails-app/views/scm/performAction.gsp, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/app.scss, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_utilities.scss, rundeckapp/grails-spa/packages/ui/src/pages/repository/components/ProviderCard.vue
- Fix orientation of row content
- Adjust spacing between rows
- Add card container
- Installed Plugins adjust style
=> Adjust SCM UI and Installed Plugins Style

rundeckapp/grails-app/views/scm/_statusBadge.gsp, rundeckapp/grails-app/views/scm/diff.gsp, rundeckapp/grails-app/views/scm/performAction.gsp, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/app.scss, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_utilities.scss
- Add styles to match current UI
- Fix Spacing issues
- Inline Diff file export path
=> Enhance SCM UI 

rundeckapp/grails-app/views/menu/jobs.gsp
Fix https://github.com/rundeckpro/rundeckpro/issues/1638 run job error might not be viewable, replace with modal
=> Fix: run job error might not seen, replace with modal

rundeckapp/grails-spa/packages/ui/src/pages/repository/components/ProviderCard.vue
- Align style to match Plugin Search
=> Update Style of Installed Plugins 

rundeckapp/grails-app/views/menu/_jobPickerModalPagination.gsp, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_tabs-navs-pagination.scss
UI Enhancement
Adjust the styling of the modal pagination and spacing of pagination context
=> Adjust style of modal pagination

rundeckapp/grails-app/views/execution/show.gsp, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/execution-page.scss, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/jobs.scss
**Enhancement** : Allows more visibility to many options
Adjust the Subtitle bar to not be fixed to the top of the content section to be able to scroll through the page better, and see all options without items being hidden
=> Adjust Executions Options Section

plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy
Fixes https://github.com/rundeckpro/rundeckpro/issues/1703
=> SCM import button in jobs page

rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
SCM merged cleanup related with https://github.com/rundeck/rundeck/pull/6998
=> Scm enhancement cleanup

rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/views/scheduledExecution/_createForm.gsp, test/selenium/src/__tests__/selenium/jobs/job-create-cancel-i18n.test.ts, test/selenium/src/pages/jobCreate.page.ts, test/selenium/src/pages/userProfile.page.ts
Fixes #6790 
Fix use of i18n text in form button.
Add selenium tests
=> Fix: #6790 cancel job create/edit with FR/JA lang doesn't work

rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/gui/SystemReportMenuItem.groovy
bugfix, fix url mapping to the System Report Menu Item
Change action and controller to intended mapping
=> fix url mapping for System Report Menu Item

rundeckapp/grails-app/views/menu/_groupTree.gsp, rundeckapp/grails-app/views/menu/_workflowsFull.gsp
Fixes https://github.com/rundeckpro/rundeckpro/issues/1615
Job search was broken when using grouped job list and with paged job list enabled
It was included job list type on parameters for searching jobs
=> Including job list type on parameters when triggering job search

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
bugfix , fix rundeckpro/rundeckpro#1699 
cherry picked from commit be2a67558729ff1edeb4c2363b6a81768c5d2f04
fixes #6459
=> "Event" resource ACLs at project level are not being honored (cherry picked from commit be2a67558729ff1edeb4c2363b6a81768c5d2f04)

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
bugfix.  fix missingpropertyexception
fixes log view issue
=> initialize cmdDatavariable used in closure

rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/execution.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue, rundeckapp/grails-spa/packages/ui-trellis/tests/data/fixtures/ExecOverSize.json
fixes rundeckpro/rundeckpro#1746
* Removes -1 completely from the progress bar logic
* Adds story for oversized log
=> Fix stuck progress bar on oversized logs

rundeckapp/grails-app/domain/rundeck/User.groovy, rundeckapp/grails-app/views/user/login.gsp
Issue:
https://github.com/rundeckpro/rundeckpro/issues/1743
Enhancement description:
Change Okta login button with rounded corners and hover white text like Rundeck style buttons
=> Fixed css style of okta login button

rundeckapp/grails-spa/packages/ui-trellis/src/components/skeleton/Skeleton.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelect.vue
=> Adjust Size of Skeleton List & Color

rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_cards.scss
Re-do #7042 but the correct file this time.
Fixes margin
=> fix margin again

rundeckapp/grails-app/views/error.gsp
fixes rundeckpro/rundeckpro#1761
Adds the standard layout wrapper divs.
=> Fix error page layout

core/src/main/java/com/dtolabs/rundeck/core/config/Features.java, core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/assets/javascripts/executionStateKO.js, rundeckapp/grails-app/assets/javascripts/framework/adhoc.js, rundeckapp/grails-app/conf/application.groovy, rundeckapp/grails-app/views/execution/show.gsp, rundeckapp/grails-app/views/framework/adhoc.gsp, rundeckapp/grails-app/views/layouts/base.gsp, rundeckapp/grails-app/views/scheduledExecution/_execOptionsFormButtons.gsp
fixes https://github.com/rundeckpro/rundeckpro/issues/1740
Removes the feature flag "legacyExecOutputViewer" and associated code.
=> Remove legacy log output feature

docker/official/remco/templates/log4j2.properties
=> Fix #7073 docker rolling logs not working

rundeckapp/grails-app/views/execution/show.gsp, test/selenium/src/__tests__/selenium/execution/adhoc-command-page-abort.test.ts, test/selenium/src/__tests__/selenium/execution/execution-show-page-abort.test.ts, test/selenium/src/pages/adhocCommand.page.ts, test/selenium/src/pages/executionShow.page.ts
=> Fix #7075 kill job button doesn't work

gradle.properties, version.properties
Ran setversion.sh script to update the version to 3.4.1 for snapshots
=> Bump SNAPSHOT version to 3.4.1

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/conf/application.groovy, rundeckapp/grails-app/conf/application.yml, rundeckapp/src/integration-test/groovy/rundeck/services/PluginApiServiceIntegrationSpec.groovy
Fix dev mode issue: option values plugin feature flag was not enabled in dev mode by default.
also clean up the feature flag configs in application.groovy
=> Fix: option values enabled by default dev mode

rundeckapp/grails-app/views/user/profile.gsp
enhancement:
Allows users to change their password using User Manager (Enterprise)
https://github.com/rundeckpro/rundeckpro/issues/1802
=> RUN-106: Enh: Support for Enteprise Change Password on user profile

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
fixes #run-167, bug for variables not being exported when ignoreNotifications are true.  
Refactored by moving the clause to export the variables out of the if statement and wrote a corresponding test to validate functionality 
N/A
=> fix issue on exported data vars for job references not being exported… [RUN-167]

gradle.properties, version.properties
Bumping the snapshot version to 3.4.2
=> Bump snapshot to 3.4.2

rundeckapp/grails-app/views/menu/wait.gsp, test/selenium/src/__tests__/selenium/project-export/export.test.ts, test/selenium/src/pages/projectExport.page.ts
Fixes #7161
Bug fix.
Update KO import location.
=> RUN-253: Fix project export errors

rundeckapp/grails-app/views/user/login.gsp
related to https://github.com/rundeckpro/rundeckpro/pull/1888
=> RUN-191: Fix to properly show SSO login button

rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
Comments for PR https://github.com/rundeck/rundeck/pull/7153
reformatting retry block
using delay in backoff style 
=> RUN-222: SCM Loader enhancement Part 2

setversion.sh
Adds a line to record the new tag being set
=> Hotfix: Update to output new TAG

plugins/object-store-plugin/build.gradle
fix build issue https://github.com/testcontainers/testcontainers-java/issues/3574
Fix a build issue that sometimes occurs
https://github.com/testcontainers/testcontainers-java/issues/3574
there may be a newer testcontainers that should be used, this was the version I tried and it fixed the specific issue i had
=> update testcontainers due to build issue in object store plugin

gradle.properties, version.properties
Bump snapshot version to 3.4.3
=> Bump snapshot to 3.4.3

rundeckapp/grails-app/assets/javascripts/menu/aclListing.js, rundeckapp/grails-app/views/common/_modal.gsp, rundeckapp/grails-app/views/menu/_aclManageKO.gsp, rundeckapp/grails-app/views/menu/_aclValidationRowKO.gsp, rundeckapp/grails-app/views/menu/acls.gsp, test/selenium/src/__tests__/selenium/acls/system-acls.test.ts, test/selenium/src/pages/systemAcls.page.ts
Fix #7219 
Fix JS error. add selenium tests.
=> Fix: unable to upload an acl policy file with the gui

core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkBase.java, core/src/main/java/com/dtolabs/rundeck/core/common/IFrameworkServices.java, core/src/main/java/com/dtolabs/rundeck/core/common/ServiceSupport.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschNodeExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschScpFileCopier.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschSecretBundleUtil.java, core/src/main/java/com/dtolabs/rundeck/core/execution/proxy/DefaultSecretBundle.java, core/src/main/java/com/dtolabs/rundeck/core/execution/proxy/ProxySecretBundleCreator.java, core/src/main/java/com/dtolabs/rundeck/core/execution/proxy/SecretBundle.java, core/src/main/java/com/dtolabs/rundeck/core/execution/service/FileCopierService.java, core/src/main/java/com/dtolabs/rundeck/core/execution/service/NodeExecutorService.java, core/src/main/java/com/dtolabs/rundeck/core/execution/service/ScriptPluginFileCopier.java, core/src/main/java/com/dtolabs/rundeck/core/execution/service/ScriptPluginNodeExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/BaseScriptPlugin.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/impl/jsch/JschNodeExecutorSpec.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/execution/impl/jsch/JschSecretBundleUtilSpec.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/plugins/BaseScriptPluginSpec.groovy, core/src/test/java/com/dtolabs/rundeck/core/execution/impl/common/TestDefaultFileCopierUtil.java
Allow creation of bundles of secrets to be used by node executor proxies.
=> RUN-334: Node executor secret bundle creation

rundeck-authz/rundeck-authz-yaml/src/main/java/com/dtolabs/rundeck/core/authorization/providers/YamlParsePolicy.java, rundeck-authz/rundeck-authz-yaml/src/test/groovy/com/dtolabs/rundeck/core/authorization/providers/YamlParsePolicySpec.groovy
Fix for: ACL policy `by: urn: ` clause does not work with a list.
fixes #7229
=> RUN-335: Fix: by: urn list is not working

rundeckapp/grails-app/views/menu/_aclValidationRowKO.gsp, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/input-group.scss, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/text.scss, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_inputs.scss, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_typography.scss
Enhancement: add refinement to colors across the app
Odds & Ends of color correction
=> RUN-373: Fix/accessible styles mr

README.md
fixes #7232 
Updated Documentation on repository readme.md
Fixed outdated links.
=> Fix Readme Download Issues

rundeck-authz/rundeck-authz-core/src/main/java/org/rundeck/core/auth/AuthConstants.java
Additional constants for authorization utils
This has no functional changes
=> Add app_admin/ops_admin, added resource type definitions

rundeckapp/grails-app/domain/rundeck/BaseReport.groovy, rundeckapp/grails-app/domain/rundeck/ExecReport.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy, rundeckapp/grails-app/views/menu/_projectDeleteForm.gsp
Issue:
https://github.com/rundeckpro/rundeckpro/issues/1240
Modified the project deletion action to improve the process and also it is added a spinner with a description to show the deletion process is running.
=> RUN-113: unable to delete project with 100 k executions

gradle.properties, version.properties
Bump snapshot version to 3.4.5
=> bump snapshot version to 3.4.5

core/src/main/java/com/dtolabs/rundeck/core/authentication/tokens/AuthTokenType.java, rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy, rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
Add api token type RUNNER to differentiate from user and webhook types.
=> Add api token type RUNNER

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
Fixes logic of retry when modifying aborted execution.
Fix logic.
=> fix: abort attempt may fail to retry

grails-webhooks/src/test/groovy/webhooks/WebhookControllerSpec.groovy
Fix a test broken by multiple merges
=> Update test for app admin

rundeckapp/grails-app/assets/javascripts/ace/theme-tomorrow_night.js, rundeckapp/grails-app/assets/javascripts/application.js, rundeckapp/grails-spa/packages/ui-trellis/src/components/first-run/FirstRun.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/first-run/firstrun.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/skeleton/Skeleton.vue, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/_theme.scss, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/autocomplete.scss, rundeckapp/grails-spa/packages/ui/src/components/motd/motd.vue
* Adds the ace `tomorrow_night` theme
* Wires Ace theme into the color theme selection
* Fixes auto-complete suggestion colors being hard coded
* Removes MOTD error due to loading with no content
* Wires the first-run screen colors into the theme props
=> Dark mode fixes

rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_labels.scss
Bugfix: tag colors were preventing visibility of text
Adjust colors for higher contrast. and readability
=> #7342 : Address color issues in tags

rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_tables.scss
Enhancement: add darkmode styling to Vue Good Table
Add custom properties to vgt classes
=> add darkmode styles for vue good table

rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_input-groups.scss
Bugfix: height of select inputs
add class override
=> fix height for input

rundeckapp/build.gradle
Update sanitizer dependency found in wasp
=> update sanitizer dependency

rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_alerts.scss
Enhancement: Update UI for alerts
Update color properties and adjust margin spacing
=> update style for alerts

rundeckapp/grails-app/views/framework/_nodeFilterInputGroup.gsp, rundeckapp/grails-app/views/framework/nodes.gsp, rundeckapp/grails-spa/packages/ui-trellis/src/components/inputs/MultiInput.stories.tsx, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_input-groups.scss, test/selenium/src/pages/adhocCommand.page.ts
Enhancement: improve appearance of multi input 
add style changes to update appearance
=> Enh: Multi Input Style

rundeckapp/grails-spa/packages/ui-trellis/theme/scss/_theme.scss, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/exec-status.scss
Enhancement: update icon color for dark mode
update icon color
=> update icon color

gradle.properties, version.properties
=> bump to 3.4.7 version

rundeckapp/build.gradle
exclude guava dependency to fix duplicate issue
=> exclude guava dependency from owasp

rundeckapp/grails-app/migrations/changelog.groovy, rundeckapp/grails-app/migrations/core/Tag-3.4.7.groovy, rundeckapp/grails-app/migrations/core/Tag-3.4.8.groovy, rundeckapp/grails-app/migrations/core/WorkflowStepNVARCHAR.groovy
Fix for https://github.com/rundeckpro/rundeckpro/issues/2143
Changes "description" and "adhoc_remote_string" on workflow_step table from varchar to nvarchar when using mssql
=> RUN- 514 Mssql to nvarchar on workflow_step

rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy, rundeckapp/grails-app/services/rundeck/services/ReportService.groovy
Issue:
https://github.com/rundeckpro/rundeckpro/issues/2121
It was forced the saving at the end of the db transaction in Oracle and Postgres. This was rolled out to Executions and Reports records.
=> RUN-492: Project import including all but executions

rundeckapp/grails-app/views/layouts/base.gsp, rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/NavBar.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/NavBarContainer.vue, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_view.scss
This is a bugfix to the pop-out nav bar. The project settings (Edit Configuration) button was hidden behind the top nav bar.
Simply moves the navigation list down so it doesn't end up hidden.
=> RUN-523: Fix display bug with Project Settings

rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_utilities.scss, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_variables.scss
Enhancement: add's re-usable classes that can be used in general across the UI
Added utilities for Max width and Flex
=> Enh | Add utility classes for Max Width and Flex

rundeckapp/grails-app/controllers/rundeck/interceptors/ProjectSelectInterceptor.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/views/execution/_execDetails.gsp, rundeckapp/grails-app/views/execution/_execDetailsOrchestrator.gsp, rundeckapp/grails-app/views/scheduledExecution/_editForm.gsp, rundeckapp/grails-spa/packages/ui/src/components/job/notifications/NotificationsEditor.vue, rundeckapp/grails-spa/packages/ui/src/components/job/resources/ResourcesEditor.vue, rundeckapp/grails-spa/packages/ui/src/pages/job/editor/NotificationsEditorSection.vue, rundeckapp/grails-spa/packages/ui/src/pages/job/editor/ResourcesEditorSection.vue, rundeckapp/src/test/groovy/rundeck/interceptors/ProjectSelectInterceptorSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy, test/selenium/src/__tests__/selenium/jobs/job-node-selector.test.ts, test/selenium/src/pages/jobCreate.page.ts, test/selenium/src/pages/jobShow.page.ts
Fix #7409 
* fix: prompt shown to confirm leaving Job Edit page, even if no changes were made. (caused by Node and Notifications editor UIs)
* fix: NPE if a job is saved with orchestrator plugin configured, but no orchestrator plugin configuration properties exist in the plugin
* fix: wrong error page message ("Invalid Project name") when displaying error caused by NPE or other uncaught exception on certain pages
=> RUN-532: fix cannot edit job with basic orchestrator

test/selenium/src/__tests__/selenium/jobs/job-node-selector.test.ts
Disable a flaky selenium test that is failing in main CI
=> Disable flaky test

rundeckapp/grails-app/conf/application.groovy, rundeckapp/grails-app/conf/application.yml, rundeckapp/grails-app/controllers/rundeck/interceptors/DefaultInterceptorHelper.groovy
Enable unsecured path for user password reset page.
=> RDCLOUD-62 Add /user/reset to unsecured path

rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy
Fixes #7399 
* remove unnecessary date parsing
* remove use of servlet context attributes
=> RUN-569: fix #7399 plugin date parsing fails in non-english locale

test/api/include.sh, test/api/test-job-flip-scheduleEnabled.sh, test/api/test-job-scheduled.sh
Some updates for CI tests to address flakiness.
* Add additional debug output for API test scripts.
* Update some tests that depend on date and time to specify GMT timezone
=> CI test updates

build.gradle, plugins/azure-object-store-plugin/build.gradle, plugins/object-store-plugin/build.gradle, rundeck-authz/build.gradle, rundeck-storage/build.gradle, rundeckapp/build.gradle, rundeckapp/grails-app/init/rundeckapp/Application.groovy, rundeckapp/grails-app/init/rundeckapp/cli/CommandLineSetup.groovy, rundeckapp/grails-app/init/rundeckapp/cli/RundeckCliOptions.groovy, rundeckapp/grails-app/init/rundeckapp/init/RundeckInitConfig.groovy, rundeckapp/src/test/groovy/rundeckapp/ApplicationTest.groovy
Run the app with `-m` and it will apply any unapplied database migrations, then shut down.
=> Add command line -m option to run db migrations then stop the app

test/selenium/src/__tests__/selenium/jobs/job-node-selector.test.ts, test/selenium/src/pages/jobShow.page.ts
fix flaky selenium test
change the way the edit job is opened and press a tab before saving the job
=> RUN-582: fix flaky selenium test

rundeckapp/grails-app/views/menu/home.gsp
Bugfix: On first Run create project button is shown off screen
Re-adjust html positioning of elements
=> RUN-579: #579 fix create project button position in first run

rundeckapp/grails-app/assets/javascripts/application.js, rundeckapp/grails-app/assets/javascripts/executionControl.js, rundeckapp/grails-app/assets/javascripts/filterStepPluginsKOTest.js, rundeckapp/grails-app/assets/javascripts/menu/home.js, rundeckapp/grails-app/assets/javascripts/util/testing.js, rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logViewer.vue, rundeckapp/grails-spa/packages/ui/src/pages/execution-show/main.js
Fix at least one JS error issue in execution show page, because the reference to the dom element was incorrect.
Fix dom element Id used
ID of main dom element in base.gsp was modified in 3.4.0 and some code referenced the old ID
=> RUN-628: Fix dom id reference

rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy, test/api/include.sh
=> RUN-642: API Updates for 4.x

core/src/main/java/com/dtolabs/rundeck/plugins/notification/NotificationPlugin.java
enhancement
Fixed a typo in the NotificationPlugin.java javadocs
=> RUN-693: Fix typo successul to successful in NotificationPlugin.java javadocs

test/selenium/lib/projects/SeleniumBasic/rundeck-SeleniumBasic/jobs/job-b7b68386-3a52-46dc-a28b-1a4bf6ed87de.xml, test/selenium/src/__tests__/selenium/edit-job.test.ts, test/selenium/src/pages/jobCreate.page.ts, test/selenium/src/pages/jobShow.page.ts
Is this a bugfix, or an enhancement? Please describe.
This is a draft enhancement to add selectors and simple tests for the Schedule tab.
Adds basic tests to existing Selenium files and adds many locators.
Additional context
Needs to be merged after the listed preceding PR.
=> [MERGE AFTER #7515] RUN-638: Update Schedule Tab Tests

rundeckapp/grails-spa/packages/ui-trellis/package-lock.json, rundeckapp/grails-spa/packages/ui-trellis/package.json
bugfix: failing build from markdown-it-katex
revert to default markdown-it-katex
=> revert to default katex

test/selenium/lib/compose/cluster/docker-compose.yml, test/testdeck/src/commands/TestCommand.ts
=> WIP: CI updates

.circleci/config.yml
Don't require tests to publish
=> Remove tests from release builds

rundeckapp/grails-app/assets/javascripts/filterStepPluginsKOTest.js, rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_ja.properties, rundeckapp/grails-app/i18n/messages_pt_BR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-spa/packages/ui/src/components/job/schedule/ScheduleEditor.vue, rundeckapp/grails-spa/packages/ui/src/components/job/schedule/services/scheduleDefinition.ts
Bugfix. Fix the simple schedule editing feature that users can select specific days of week and months.
Both front-end and back-end features are not completed at all. The fix corrects the front-end form fields setup and the server-side handler for extracting the related parameters from the form.
The code is hard to read and very fragile. A refactor of this whole feature is necessary but it requires too much effort.
=> RUN-760: Correct daysOfWeek and months selection in simple schedule

rundeckapp/grails-app/views/common/_mainbar.gsp
Fix for the custom user logo not displaying correctly. [link to issue](https://github.com/rundeck/rundeck/issues/7352)
=> RUN-502 Custom Logo Fix

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ExecutionController2Spec.groovy
* Fix a flaky test with a race condition
* refactor the test to only test the controller behavior
* add a new test to test service behavior
=> RUN-741: fix flaky test in ExecutionController2Spec

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
Enhancement.  Need to add SSO {Okta, Ping} to config base in order to be refreshable
=> RUN-732: add Oauth Okta and Ping to config base

gradle.properties, rundeckapp/build.gradle, rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy, testbuild.groovy
enhancement: upgrade to grails 5.1.3
=> RUN-745: Upgrade grails 5.1.5

core/src/main/java/com/dtolabs/rundeck/core/execution/ExecArg.java, core/src/main/java/com/dtolabs/rundeck/core/execution/ExecArgList.java, core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionServiceImpl.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/RemoteScriptNodeStepPluginAdapter.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/RemoteScriptNodeStepPluginAdapter_Ext.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtils.java, core/src/main/java/com/dtolabs/rundeck/core/utils/ScriptExecUtil.java, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/RemoteScriptNodeStepPluginAdapterSpec.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/RemoteScriptNodeStepPluginAdapter_ExtTest.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtilsSpec.groovy, core/src/test/java/com/dtolabs/rundeck/core/execution/ExecArgListTest.java, core/src/test/java/com/dtolabs/rundeck/core/execution/service/TestScriptPluginFileCopier.java, rundeckapp/src/test/groovy/rundeck/services/AuthorizingNodeExecutionServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/DirectNodeExecutionServiceSpec.groovy
fixes https://github.com/rundeck/rundeck/issues/7187
A new property has been added to allow users to keep using the old rundeck quoting behavior (before 3.4.1) at framework.properties file
new property key and values:
rundeck.feature.quoting true/false
true = old quoting
false (default) = new quoting
Job definition:
```
<joblist>
<job>
<defaultTab>nodes</defaultTab>
<description></description>
<executionEnabled>true</executionEnabled>
<group>bug</group>
<id>adeed2d5-cf64-4792-b62f-37cee510b546</id>
<loglevel>INFO</loglevel>
<name>quoting option regression (test)</name>
<nodeFilterEditable>false</nodeFilterEditable>
<plugins />
<scheduleEnabled>true</scheduleEnabled>
<sequence keepgoing='false' strategy='node-first'>
<command>
<description>local command - no quotes</description> …
```
=> Allow old quoting behavior

rundeckapp/grails-app/assets/javascripts/_package-manager/package.json
Originally submitted by @paulcalabro as PR #7594 
Moved to local branch so CircleCI can run.
=> RUN-801: Bump postcss to resolve build error

rundeckapp/grails-app/views/menu/_projectExportForm.gsp, rundeckapp/grails-app/views/menu/_projectImportForm.gsp
Fix for unauthorized ACL policy showing up for AppAdmin
=> RUN-788 Fix Duplicated ACL Policies on Export

core/src/main/java/com/dtolabs/rundeck/core/execution/ExecArgList.java
It solves issue with RPRO introduced by this pr https://github.com/rundeck/rundeck/pull/7592
=> overload method to avoid rpro issues

gradle.properties, rundeckapp/build.gradle, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/src/main/groovy/rundeck/GrailsIssue12460PostProcessor.groovy
Update grails and spring dependencies
=> RUN-800: Update grails to 5.1.6, spring to 5.3.18

rundeckapp/build.gradle
=> Fixes org.postgresql:postgresql vulns

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
=> Fix: HTTP Options broken in 4.0

rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/i18n/messages_es_419.properties, rundeckapp/grails-app/i18n/messages_fr_FR.properties, rundeckapp/grails-app/i18n/messages_ja.properties, rundeckapp/grails-app/i18n/messages_pt_BR.properties, rundeckapp/grails-app/i18n/messages_zh_cn.properties, rundeckapp/grails-app/views/menu/_workflowsFull.gsp, rundeckapp/grails-app/views/menu/jobs.gsp, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_input-groups.scss
Enhancement: Added search bar to jobs page
=> RUN-806 Jobs Search Bar

rundeckapp/grails-app/migrations/changelog.groovy
fixes https://github.com/rundeckpro/rundeckpro/issues/2470
Column change was applied to mssql but it should be only on h2 database
The change is applied on h2 only
=> The varchar type change should be applied to h2 only

docker/official/remco/templates/rundeck-config-csp.properties
Fix #6960 
Use correct remco path
=> RUN-856: Fix #6960 incorrect remco template for csp form action

rundeckapp/build.gradle
Merge of #7631 from @paulcalabro see details there.  
This PR is sourced from a local branch so CI/CD will run.
=> RUN-807: Fixes org.postgresql:postgresql vulns

rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_input-groups.scss
bugfix: background color did not match the input
update the focus color of the input background
=> RUN-864 - Update input group addon class

rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_popovers.scss, rundeckapp/grails-spa/packages/ui/src/pages/project-nodes-config/ProjectPluginConfig.vue
Bugfix: non-visible calendar in darkmode https://github.com/rundeckpro/rundeckpro/issues/2504
Update color styles for date picker
=> RUN-868 - Update Calendar Darkmode Classes and Buttons

gradle.properties, rundeckapp/build.gradle, rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy, rundeckapp/grails-app/init/rundeckapp/Application.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy, rundeckapp/src/main/groovy/org/rundeck/app/api/model/SystemInfoModel.groovy
Is this a bugfix, or an enhancement? Please describe.
Recreating reverted PR https://github.com/rundeck/rundeck/pull/7355
Add openapi spec generation ability.
=> RUN-861: Support for OpenAPI documentation Generation (rerecreated)

rundeckapp/grails-app/views/404.gsp, rundeckapp/grails-app/views/405.gsp, rundeckapp/grails-app/views/layouts/base.gsp, rundeckapp/grails-app/views/user/loggedout.gsp, rundeckapp/grails-app/views/user/login.gsp
Bugfix: server-identity.css is not being used
Remove include of server-identity.css
=> RUN-822 - Remove Unused Css file

.circleci/config.yml, rundeckapp/grails-spa/packages/ui-trellis/.storybook/main.js, rundeckapp/grails-spa/packages/ui-trellis/package.json, rundeckapp/grails-spa/packages/ui-trellis/src/components/containers/copybox/containers.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/containers/drawer/drawer.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/containers/tabs/tabs.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/data/list.stories.tsx, rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/execution.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/filter-list/filterList.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/first-run/firstrun.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/inputs/MultiInput.stories.tsx, rundeckapp/grails-spa/packages/ui-trellis/src/components/inputs/inputs.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/inputs/text.stories.tsx, rundeckapp/grails-spa/packages/ui-trellis/src/components/layouts/base.stories.tsx, rundeckapp/grails-spa/packages/ui-trellis/src/components/layouts/sidebar.stories.tsx, rundeckapp/grails-spa/packages/ui-trellis/src/components/layouts/wizards.stories.tsx, rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/navbar.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/skeleton/skeleton.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/utilitybar.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/version/version.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/news/news.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/projectSelect.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/rundeck-info/info.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/webhook-select/webhookSelect.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/stories/theme.stories.tsx, rundeckapp/grails-spa/packages/ui/package-lock.json
Bugfix: Builds are failing due to deprecated dependency
Remove dependency and update storybook
=> RUN-903 |  Storybook Knobs Deprecated

grails-webhooks/grails-app/services/webhooks/WebhookService.groovy, rundeckapp/grails-spa/packages/ui/src/pages/webhooks/views/WebhooksView.vue
Fix: https://github.com/rundeckpro/rundeckpro/issues/2546
When using custonCofig on webhook the error messages were not shown.
=> RUN-902: Fix:Webhook minimum actions error message showing incorrectly

rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/DelegateStorageTree.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/StorageTreeCreator.groovy, rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/tree/DelegateStorageTreeSpec.groovy
=> RUN-913: When recreating storage tree, include converter plugin props

rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginConfig.vue
Fix js error on nodes config page
=> RUN-836: Fix js error on nodes config page

rundeckapp/grails-spa/packages/ui-trellis/.storybook/main.js, rundeckapp/grails-spa/packages/ui-trellis/package-lock.json, rundeckapp/grails-spa/packages/ui-trellis/package.json, rundeckapp/grails-spa/packages/ui-trellis/src/components/containers/copybox/containers.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/containers/drawer/drawer.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/containers/tabs/tabs.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/data/list.stories.tsx, rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/execution.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/filter-list/filterList.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/first-run/firstrun.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/inputs/MultiInput.stories.tsx, rundeckapp/grails-spa/packages/ui-trellis/src/components/inputs/inputs.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/inputs/text.stories.tsx, rundeckapp/grails-spa/packages/ui-trellis/src/components/layouts/base.stories.tsx, rundeckapp/grails-spa/packages/ui-trellis/src/components/layouts/sidebar.stories.tsx, rundeckapp/grails-spa/packages/ui-trellis/src/components/layouts/wizards.stories.tsx, rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/navbar.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/skeleton/skeleton.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/utilitybar.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/version/version.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/news/news.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/projectSelect.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/rundeck-info/info.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/webhook-select/webhookSelect.stories.ts, rundeckapp/grails-spa/packages/ui-trellis/src/stories/theme.stories.tsx, rundeckapp/grails-spa/packages/ui/package.json
Bugfix: Deprecated dependency 
Removal of Storybook Addon Knobs
=> remove addon-knobs from storybook

.circleci/config.yml
bugfix: Cache is disabled
Re-enable cache
=> Re-Enable Gradle Cache

rundeck-authz/rundeck-authz-core/src/main/java/org/rundeck/core/auth/AuthConstants.java, rundeck-authz/rundeck-authz-core/src/main/java/org/rundeck/core/auth/AuthResources.java
Include acl runner resource to the auth constants
=> RUN-890: Add runner ACL resources to ACL Editor dropdown

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Fix https://github.com/rundeckpro/rundeckpro/issues/2512
Now it only sort remote url options only if "sort" option is selected at option level.
=> RUN-882 remote url options sort

rundeckapp/grails-app/conf/spring/resources.groovy
Set the storage rewrite feature enabled by default
=> Set rundeck.feature.storageRewrite.enabled default to true

gradle.properties, version.properties
=> Bump snapshot version to 4.5.0

rundeckapp/grails-app/services/rundeck/services/logging/LoggingThreshold.groovy, rundeckapp/src/test/groovy/rundeck/services/logging/LoggingThresholdSpec.groovy
Issue:
https://pagerduty.atlassian.net/browse/RUN-1013
Fixed global log limit adding a Failed status on a job.
=> RUN-1013: Fixed global log limit adding a Failed status on a job

.circleci/config.yml, scripts/circle-helpers.sh
=> RUN-771: Enable Twistlock Scan

gradle.properties
Upgrade grails to 5.1.9 to address CVE-2022-35912
=> RUN-1105: Upgrade grails to 5.1.9

core/build.gradle, rundeckapp/build.gradle
Update okhttp to address PRISMA-2022-0239 https://github.com/square/okhttp/issues/6738
=> RUN-1092: Update okhttp to 4.9.2

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/views/user/login.gsp
Also adds missing configuration properties to the RundeckConfigBase to prevent WARN messages in the logs
=> RCLOUD-561 - Add a location on login page where another login button can be inserted

grails-execution-mode-timer/grails-app/services/com/rundeck/plugin/UpdateModeProjectService.groovy, grails-execution-mode-timer/grails-app/utils/com/rundeck/plugin/jobs/ExecutionStatusJob.groovy, grails-execution-mode-timer/src/test/groovy/com/rundeck/plugin/UpdateModeProjectServiceSpec.groovy
Fix: https://github.com/rundeckpro/rundeckpro/issues/1311
=> RUN-224: Fix: Enabling/Disabling both Scheduling and Executions at the same time using timer mode

gradle.properties, version.properties
=> Bump version to 4.6.0

rundeckapp/grails-spa/packages/ui/src/components/activity/activityList.vue
Fix to the job's activity list queue issue.
=> RUN-1178 The activity page doesn't work with running jobs / Auto-refresh doesn't work

rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
I believe this was flaky because it relied on a timing issue
the ExecutionJob calls thread.join(1000), however the
thread object was a spock Mock, so the default behavior is return
immediately.  This was causing the average duration exceeded check
to only sometimes fail, because the average duration would be set
to 1ms, and the notification method not be called.
the fix replaces the Mock with a real thread that waits for a
countdownlatch, causing the thread.join(1000) to actually wait for
1000ms, guaranteeing the average duration will exceed, and the
notification method will be called. when the averge notification method
is called, the countdownlatch is set to 0 allowing the real thread
to finish
Fixes a flaky test 
**Describe the …
=> RUN-986: Fix flaky test for avg duration notification

rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelect.vue, rundeckapp/grails-spa/packages/ui-trellis/src/stores/Projects.ts, rundeckapp/grails-spa/packages/ui/src/components/project-picker/main.ts
Fix issues with Project Select dropdown:
* Create Project button doesn't work if there is an app context path
* Project names should be links
* Create Project/View All buttons should be links
ref: https://github.com/rundeckpro/rundeckpro/issues/2528
---
will need refactor after: #7818
=> RUN-1022: project menu dropdown create project doesnt work with an app context path

.gitmodules
Fix submodule branch used for packaging repo
=> fix packaging submodule branch

rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy, rundeckapp/grails-app/services/rundeck/services/ApiService.groovy, rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
bugfix, fix renamed methods not caught in compile time
Add more `@CompileStatic`
=> fix bugs with AuthToken refactor

rundeckapp/grails-app/services/rundeck/services/FileUploadService.groovy, rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy, rundeckapp/src/test/groovy/rundeck/UtilityTagLibSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/FileUploadServiceSpec.groovy
This PR adds validation to uploaded filenames. 
Also adds some content sanitation on some UtilityTagLib methods
=> RUN-1208: Improvements on job file option input sanitation

rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
Adding a jmx metric meter to measure job start failures.
=> RCLOUD-601: Adding job start failure metric.

core/src/main/java/com/dtolabs/rundeck/core/authentication/tokens/AuthTokenManager.java, grails-webhooks/grails-app/services/webhooks/WebhookService.groovy, grails-webhooks/src/test/groovy/webhooks/WebhookServiceSpec.groovy, rundeckapp/grails-app/services/rundeck/services/RundeckAuthTokenManagerService.groovy, rundeckapp/src/test/groovy/rundeck/services/RundeckAuthTokenManagerServiceSpec.groovy
Fix issue: webhook listing and project export fails
=> RUN-1263: fix webhook listing and project export

rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_dropdown.scss
(cherry picked from commit 27f525c621f9f21453e05c46aa27f0ba4179a839)
This adds a fix needed for RC4 to the release branch. It was merged to main in https://github.com/rundeck/rundeck/pull/7947
=> Backport a fix for 4.7.0-RC4

gradle.properties, version.properties
=> update version 4.8-snapshot

rundeckapp/grails-app/views/menu/home.gsp
=> RSE-140: Fix: Incorrect html structure, broken extra components

rundeckapp/grails-app/assets/javascripts/application.js, rundeckapp/grails-app/assets/javascripts/jobedit.js, rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp, rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginConfig.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginPropEdit.vue, rundeckapp/grails-spa/packages/ui-trellis/src/components/utils/TextAutocomplete.vue, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/autocomplete.scss, rundeckapp/grails-spa/packages/ui/src/components/job/notifications/NotificationsEditor.vue, test/selenium/src/__tests__/selenium/jobs/job-notification.test.ts, test/selenium/src/__tests__/selenium/jobs/job-wf-autocomplete.test.ts, test/selenium/src/pages/jobCreate.page.ts, test/selenium/src/pages/jobShow.page.ts
Fix autocomplete job context variables in job notifications
- rollback https://github.com/rundeck/rundeck/pull/7704
- set ace autocomplete per element
- in vue plugin component, use the UIV autocomplete instead of using jquery (for compatibility)
=> RUN-1163:  Fix Autocomplete job context variables in job notifications

rundeckapp/grails-app/assets/javascripts/_package-manager/mix-manifest.json, rundeckapp/grails-app/assets/javascripts/_package-manager/package-lock.json, rundeckapp/grails-app/assets/javascripts/_package-manager/package.json, rundeckapp/grails-app/assets/javascripts/_package-manager/webpack.mix.js, rundeckapp/grails-app/views/layouts/base.gsp
Security Enhancement: Addresses XSS vulnerabilities
Include Jquery migrate to the webpack mix and upgrade Jquery and its dependencies
=> RUN-1211: Upgrade Jquery and add Jquery migrate

grails-securityheaders/build.gradle, grails-securityheaders/src/main/groovy/grails/securityheaders/SecurityheadersGrailsPlugin.groovy, grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/SessionIdChangeFilter.groovy, test/ci-test-docker-selenium.sh, test/selenium-docker-compose.yml, test/test-tokens.properties, test/testdeck/src/RundeckCluster.ts, test/testdeck/src/commands/ProjectExportCommand.ts, test/testdeck/src/commands/ProjectImportCommand.ts, test/testdeck/src/commands/SeleniumCommand.ts, test/testdeck/src/commands/TestCommand.ts, test/testdeck/src/test/api.ts, test/testdeck/src/test/rundeck.ts, test/testdeck/src/test/selenium.ts
Avoid potential for session fixation attack.
Change session ID after first authenticated request
=> RUN-1207: change session id after login

rundeckapp/grails-app/assets/javascripts/_package-manager/mix-manifest.json, rundeckapp/grails-app/assets/javascripts/_package-manager/package-lock.json, rundeckapp/grails-app/assets/javascripts/_package-manager/package.json, rundeckapp/grails-app/assets/javascripts/_package-manager/webpack.mix.js, rundeckapp/grails-app/views/layouts/base.gsp
=> Revert "RUN-1211: Upgrade Jquery and add Jquery migrate"

gradle.properties, version.properties
=> Bump SNAPSHOT version to 4.9.0

rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/SimpleTokenBuilder.java, rundeck-data-model/src/main/java/org/rundeck/app/data/utils/Utils.java, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/services/rundeck/services/ApiService.groovy, rundeckapp/grails-app/services/rundeck/services/UserService.groovy, rundeckapp/grails-app/views/user/_token.gsp, rundeckapp/src/test/groovy/rundeck/services/ApiServiceSpec.groovy
Bugfixes for matching auth token functionality.  Remove substring on encoded hash, add clear token for created token responses.  Add gormTokenProvider needed for plugins
=> AuthToken fixes/updates

rundeckapp/grails-spa/packages/ui-trellis/theme/scss/pages/login.scss, rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_view.scss
Bugfix: Unnecessary scroll bars on the login page
Remove the overflow property that isn't necessary
=> RUN-1353 | Overflow Scrollbars on Login Page Removal

core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/StringRenderingConstants.java, rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp, rundeckapp/grails-app/views/layouts/base.gsp, rundeckapp/grails-app/views/scheduledExecution/_tabsEdit.gsp, rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginConfig.vue, rundeckapp/grails-spa/packages/ui-trellis/src/stores/RootStore.ts, rundeckapp/grails-spa/packages/ui-trellis/src/stores/UIStore.ts, rundeckapp/grails-spa/packages/ui/src/components/job/resources/ResourcesEditor.vue, rundeckapp/grails-spa/packages/ui/src/components/ui/UIComponent.vue, rundeckapp/grails-spa/packages/ui/src/components/ui/UiSocket.vue, rundeckapp/grails-spa/packages/ui/src/components/ui/main.ts, rundeckapp/grails-spa/packages/ui/src/pages/job/editor/ResourcesEditorSection.vue, rundeckapp/grails-spa/packages/ui/src/pages/job/editor/i18n.js, rundeckapp/grails-spa/packages/ui/vue.config.js
UI enhancements for plugin properties and UI componentization
=> RUN-1223: hidden plugin property rendering and UI components

rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-spa/packages/ui/src/pages/project-config/PluginSetConfig.vue, rundeckapp/grails-spa/packages/ui/src/pages/project-config/ProjectPluginGroups.vue
Confirm config has been provided before enabling plugin group, otherwise do not enable
=> RUN-1385: Fix null definitions in plugin groups

build.yaml
upgrade sshj version implementing ProxySecretBundleCreator
depending on https://github.com/rundeck-plugins/sshj-plugin/pull/6
=> RUN-1388: upgrade sshj version

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
A bugfix to tackle the security issue of HTTP Header Injection
Use a customized HttpFirewall based on the Spring security StrictHttpFirewall to add HTTP head validation.
The change in the OSS code is just adding the configuration parameters.
=> Fixes RSE-229: Fix the Http Header Injection Vulnerability

rundeckapp/src/test/groovy/rundeck/services/UserServiceSpec.groovy
It is a fix for a flaky test
Fix a date as a base to correct date comparison
=> RCLOUD-344: Fix test

gradle.properties, version.properties
Bump SNAPSHOT version to 4.10.0
=> Bump SNAPSHOT version to 4.10.0

build.yaml
for https://github.com/rundeck-plugins/ansible-plugin/pull/330
=> RUN-1426: update ansible plugin to version 3.2.3

rundeckapp/grails-app/views/menu/projectHome.gsp
recreate https://github.com/rundeck/rundeck/pull/8082 by @leandromqrs
=> Fix class name inconsistency in projectHome.gsp

test/selenium/package.json, test/testdeck/package.json
Update Chromedriver version to 109, fix Selenium tests
=> RUN-1474: Update chromedriver to 109

test/selenium/src/__tests__/selenium/jobs/job-notification.test.ts, test/selenium/src/pages/jobCreate.page.ts, test/selenium/src/pages/jobShow.page.ts
Fix the flaky selenium test "fix job edit job notifications"
=> RUN-1496: fix job edit job notifications selenium test

rundeckapp/build.gradle
upgrade commons-fileupload to 1.5
=> RUN-1502: upgrade commons-fileupload 

rundeckapp/src/main/groovy/rundeck/services/JobLifecycleComponentService.groovy
Update the error message to the desired error message described in this [ticket](https://pagerduty.atlassian.net/browse/RUN-1473)
=> RUN-1473: Update error message for runner not found

rundeckapp/grails-app/views/execution/show.gsp
A new socket is needed to include runner info related to #8108 
Includes new section in execution head page for the runner info socket
=> RUN-1479: Establish new section in execution head page for feature use.

rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java, rundeckapp/src/test/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModuleTest.groovy
It changes the default behavior to retrieve the paged roles from "false" to "true"
=> RSE-255: AD paged results default

rundeckapp/grails-app/assets/javascripts/_package-manager/package-lock.json, rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
Enhancement. Actually, this is housekeeping to make the package-lock.json up to date.
Build the latest main locally and update the changed package-lock.json
=> RUN-1518: Update two pckage-lock json file

build.yaml
=> RUN-1485: upgrade sshj-plugin to 0.1.6

gradle.properties, version.properties
Bump SNAPSHOT version to 4.12.0
=> Bump SNAPSHOT version to 4.12.0

rundeckapp/src/main/groovy/org/rundeck/app/components/JobJSONFormat.groovy, rundeckapp/src/main/groovy/org/rundeck/app/components/JobYAMLFormat.groovy, rundeckapp/src/test/groovy/org/rundeck/app/components/JobJSONFormatSpec.groovy
* match behavior of YAML formatter
* add tests
* add indented output by default in JSON document fix RUN-1540
=> RUN-1542: Fix: scm import/export options for job JSON

rundeckapp/src/main/groovy/org/rundeck/app/components/JobJSONFormat.groovy, rundeckapp/src/main/groovy/org/rundeck/app/components/JobYAMLFormat.groovy, rundeckapp/src/test/groovy/org/rundeck/app/components/JobJSONFormatSpec.groovy
Backport https://github.com/rundeck/rundeck/pull/8178 to release/4.11.x
=> RUN-1542: backport to 4.11.x

test/selenium/package.json, test/testdeck/package.json
Fix: chromedriver incompatible with latest chrome
=> Update chromedriver to 110

grails-webhooks/grails-app/services/webhooks/WebhookService.groovy, rundeckapp/src/test/groovy/rundeck/services/WebhookServiceSpec.groovy
backport https://github.com/rundeck/rundeck/pull/8188 to release/4.11.x
=> RUN-1552: backport to 4.11.x

rundeckapp/grails-app/assets/javascripts/_package-manager/package-lock.json, rundeckapp/grails-app/assets/javascripts/_package-manager/package.json
RUN-1614: upgrade jquery to 3.6.4
=> RUN-1614: Update jquery to 3.6.4

rundeckapp/grails-app/conf/spring/resources.groovy
Inject session beans even if maxsessions isn't enforced excluding concurrentSessionControlAuthenticationStrategy
Needed for https://github.com/rundeckpro/rundeckpro/pull/2946
=> RUN-1615: Invalidate user sessions upon password change/reset 

test/selenium/package.json, test/testdeck/.gitignore, test/testdeck/.npmrc, test/testdeck/package.json
Also update testdeck, and package.json
=> More testdeck chromedriver update

rundeckapp/build.gradle
fix json-smart duplicate dependency
=> fix json-smart duplicate dependency

rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageView.vue
Bug fix to correct a typo in the KeyStorageView component.
=> RUN-1657:Fix KeyStorageUpload vue typo

rundeckapp/grails-app/views/layouts/base.gsp, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/schedule/ScheduleEditor.vue
Bugfix: Scripts for plugins were not rendering properly
Defer scripts to after DOM is rendered
=> RUN 1655 | Schedules Page is not Being Displayed

rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/src/main/groovy/org/rundeck/app/jobs/options/JobOptionConfigRemoteUrl.groovy, rundeckapp/src/test/groovy/rundeck/OptionSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/EditOptsControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Backport of:
https://github.com/rundeck/rundeck/pull/8247
https://github.com/rundeck/rundeck/pull/8244
https://github.com/rundeck/rundeck/pull/8242
=> Backport RUN-1664 RUN-1665 RUN-1666 to 4.12.x

rundeckapp/grails-app/views/menu/storage.gsp, rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/KeyStorageSelector.vue
Bugfix. Revert changes to storage.gsp to avoid the new feature bugs introduced by the KeyStoragePage.vue component.
=> RUN-1684: Revert storage.gsp

gradle.properties, version.properties
Set snapshot Version to 4.13.0-SNAPSHOT
=> Update version to 4.13.0-SNAPSHOT

rundeckapp/grails-app/views/menu/_jobslist.gsp, rundeckapp/grails-app/views/scheduledExecution/_showHead.gsp, rundeckapp/grails-spa/packages/ui-trellis/src/library/components/utils/UiSocket.vue
* Adds ui-sockets for some job info
* updates ui-socket to support cases where socket data is passed as JSON
=> RUN-1693: job UI socket

test/selenium/src/__tests__/selenium/key-storage-test.ts, test/selenium/src/pages/keyStorage.page.ts
Add selenium tests for key storage creating, overwriting and deleting keys
=> RUN-1700: Keystorage selenium tests

core/src/main/java/com/dtolabs/rundeck/plugins/ExecutionEnvironmentConstants.java, plugins/flow-control-plugin/src/main/java/org/rundeck/plugin/flowcontrol/FlowControlWorkflowStep.java, plugins/job-state-plugin/src/main/java/org/rundeck/plugin/jobstate/JobStateWorkflowStep.java, plugins/source-refresh-plugin/src/main/java/org/rundeck/plugin/nodes/NodeRefreshWorkflowStep.java, plugins/stub-plugin/src/main/java/com/dtolabs/rundeck/plugin/stub/LogDataStep.java, plugins/stub-plugin/src/main/java/com/dtolabs/rundeck/plugin/stub/StubDataNodeStep.java, plugins/stub-plugin/src/main/java/com/dtolabs/rundeck/plugin/stub/StubDataStep.java, plugins/upvar-plugin/src/main/java/org/rundeck/plugin/vars/ExportVarWorkflowStep.java
enhancement:
- add plugin metadata to set the execution environment type
add plugin metadata for plugins that need to run locally in any case.
=> RUN-1642: Plugins that default to Local Runner execution

rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
This is a unit test that considers the changes made on: https://github.com/rundeck/rundeck/pull/8169
=> Added unit test for RSE-335

.github/workflows/release.yml
=> remove release branch trigger

gradle.properties
Upgrade spring-security to 5.8.3 (CVE-2023-20862)
=> RUN-1706: Upgrade spring-security to 5.8.3

core/src/main/java/com/dtolabs/rundeck/core/config/Features.java, core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/views/menu/storage.gsp, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/storage/i18n.js, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/storage/main.ts, rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/KeyStorageSelector.vue, rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageEdit.vue, rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStoragePage.vue, rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageView.vue
The legacy code is still available behind a feature flag. By setting:
rundeck.feature.vueKeyStorage.enabled=false 
the UI will be rendered using the legacy code. that feature is enabled by default, but can be turned off
=> RUN-1701: key storage vue conversion

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
Update the plugin groups feature flag to enabled by default
=> RUN-1576: PluginGroups Feature Flag Defaults to true

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/views/framework/adhoc.gsp, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiRunAdhocRequest.groovy, test/selenium/src/pages/adhocCommand.page.ts
Enhancement. Let user can select Runner when execution ad-hoc command
=> RUN-1625: Select Runner For Adhoc Command

gradle.properties, version.properties
Bump snapshot version to 4.14.0 after 4.13.0-RC1 was released.
=> Bump SNAPSHOT version to 4.14.0

grails-webhooks/grails-app/views/webhook/admin.gsp, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/webhooks/views/WebhooksView.vue
Adaptations for consolidation of Pro Wehbooks UI
Needed for: https://github.com/rundeckpro/rundeckpro/pull/3033
=> RUN-1724: Ui consolidation of Pro webhooks

gradle.properties, grails-securityheaders/build.gradle, rundeckapp/build.gradle, rundeckapp/grails-app/conf/application.groovy
- Consolidates plugin version into build configuration
- Disable unnecessary status messages
=> Minor improvements on spring security plugin config.

rundeckapp/grails-app/views/menu/userSummary.gsp, rundeckapp/grails-app/views/user/profile.gsp, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/menu/main.js
Change attach mechanism for user-summary to use ui-socket
=> RUN-1708: change user summary UI attach to use ui-socket

SECURITY.md
Update Security details on repo to current contact methods.
=> Update Security email and form

scripts/convert_tl_junit.sh
Add packagePath to twistlock report to obtain the offending file in detected vulnerabilities
=> Add packagePath to twistlock junit report

rundeckapp/build.gradle
Update the postgres driver version to remove vulnerability
=> Update Postgres driver version

core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschNodeExecutor.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschScpFileCopier.java, core/src/main/java/com/dtolabs/rundeck/core/execution/impl/jsch/JschSecretBundleUtil.java, core/src/main/java/com/dtolabs/rundeck/core/execution/proxy/ProxySecretBundleCreator.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/AbstractDescribableScriptPlugin.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/BaseScriptPlugin.java, core/src/main/java/com/dtolabs/rundeck/core/storage/service/PluggableStoragePluginProviderService.java, core/src/main/java/com/dtolabs/rundeck/core/storage/service/StoragePluginProviderService.java, core/src/main/java/com/dtolabs/rundeck/core/tasks/net/SSHTaskBuilder.java, core/src/test/groovy/com/dtolabs/rundeck/core/plugins/BaseScriptPluginSpec.groovy, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy
move StoragePluginProviderService to core
=> RUN-1537: Runner support for Key Storage plugins

build.yaml
=> RUN-1773: upgrade ansible version

build.yaml
Update aws-s3-model-source plugin version that has a fix for CVE-2022-31159 
Update plugin version
=> RUN-1781: Update aws-s3-model-source plugin version

build.yaml
upgrade sshj plugin
upgrade ansible-plugin
plugins return the list of keys that will use in the execution
=> RUN-1537: upgrade oss plugins 

rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
Fix wrong uuid being passed to certain service calls
=> RUN-1762: Fix notifications not triggering

plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
This PR: https://github.com/rundeck/rundeck/pull/8253 was merged with `release/4.11.x` by mistake.
The same changes were added to this new PR to merge with main.
Ticket: https://pagerduty.atlassian.net/browse/RSE-522
=> RSE-522: import status not consistant in cluster after importing jobs through gui

docker/ubuntu-base/Dockerfile
Update to remco 0.12.4 to fix several golang related CVEs
=> Update to remco 0.12.4

rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy, rundeckapp/grails-app/views/feed/_jobreportItem.gsp, rundeckapp/grails-app/views/feed/index.gsp, rundeckapp/grails-app/views/reports/_baseReport.gsp
backport https://github.com/rundeck/rundeck/pull/8388
=> 8388 Fix references to ctxProject backport 

rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy, rundeckapp/src/main/groovy/org/rundeck/app/data/providers/logstorage/GormLogFileStorageRequestProvider.groovy, rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
Fix param name in countByIncompleteAndClusterNodeNotInExecIds method.
=> Fixes an incorrect method param name in the GormLogFileStorageProvider.

core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/Validator.java, core/src/main/java/org/rundeck/app/components/jobs/JobDefinitionManager.java, rundeckapp/src/main/groovy/org/rundeck/app/components/RundeckJobDefinitionManager.groovy, rundeckapp/src/test/groovy/org/rundeck/app/data/providers/GormJobDataProviderSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Updates JobDefinitionManager to provide an interface.
* parameterize job type
* add methods to interface
* refactor validator set
=> RUN-1815: Update Job definition manager interface

rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageView.vue, rundeckapp/grails-spa/packages/ui-trellis/src/library/modules/filterPrefs.ts, rundeckapp/grails-spa/packages/ui-trellis/src/library/rundeckService.ts, rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/NavBar.ts, rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/UtilityBar.ts
=> RUN-1814: fix: typescript build errors

test/README.md, test/docker/common.sh, test/docker/test-ansible.sh, test/docker/test-api-plugin-blocklist.sh, test/docker/test-api-tomcat.sh, test/docker/test-api.sh, test/docker/test-ldap-sync.sh, test/docker/test-ldap.sh, test/docker/test-pam.sh, test/docker/test-ssl.sh, test/docker/test.sh, test/testdeck/src/ClusterManager.ts
Ticket: https://pagerduty.atlassian.net/browse/RSE-473
Added docs on how to run tests in `test` directory the same as they are run in circleci.
Also added more console output to the scripts that run tests to better understand what's happening behind.
=> RSE-473: Doc: Run API on local environment

build.yaml
upgrade sshj-plugin version to 0.1.8
=> upgrade sshj-plugin version

rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckEmbeddedPluginExtractor.groovy
Removes an internal feature that extracts and loads bundled groovy plugins.
* no groovy plugins are included in current versions, so this does not affect any plugins
* Jar plugins are preferred for bundled plugins, so future bundled plugins should use jar packaging
* prevents an issue at startup time
=> RUN-1831: remove extraction/loading of bundled groovy plugins

rundeckapp/grails-spa/build.gradle
Backport #8440 to release/4.15.x
=> backport #8440: remove caching from spa build

docker/official/remco/templates/rundeck-config.properties
add to config type, add to remco templates
=> RUN-1561: fix: rundeck.scm.startup.initDeferred config not defined in remco

gradle.properties, testbuild.groovy
Update Jetty due to CVE-2023-26048 - CVE-2023-26049
=> RUN-1850: Update Jetty due to CVE-2023-26048 - CVE-2023-26049

core/src/main/java/com/dtolabs/rundeck/core/common/NodeSourceLoader.java, core/src/main/java/com/dtolabs/rundeck/core/common/NodeSourceLoaderConfig.java, core/src/main/java/com/dtolabs/rundeck/core/common/ProjectNodeSupport.java, core/src/main/java/com/dtolabs/rundeck/core/common/SourceDefinition.java, core/src/main/java/com/dtolabs/rundeck/core/common/SourceDefinitionImpl.java, core/src/main/java/com/dtolabs/rundeck/core/execution/proxy/ProxySecretBundleCreator.java, core/src/main/java/com/dtolabs/rundeck/core/resources/ScriptPluginResourceModelSource.java, core/src/main/java/com/dtolabs/rundeck/core/resources/ScriptPluginResourceModelSourceFactory.java, core/src/main/java/com/dtolabs/rundeck/core/resources/ScriptResourceUtil.java, core/src/test/groovy/com/dtolabs/rundeck/core/common/ProjectNodeSupportSpec.groovy, core/src/test/groovy/com/dtolabs/rundeck/core/resources/ScriptPluginResourceModelSourceFactorySpec.groovy, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/services/rundeck/services/NodeService.groovy, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/project-nodes-config/ProjectNodeSourcesConfig.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/project-nodes-config/ProjectPluginConfig.vue, rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/pluginConfig.vue, rundeckapp/src/main/groovy/rundeck/services/NodeSourceLoaderService.groovy, rundeckapp/src/test/groovy/rundeck/services/NodeServiceSpec.groovy
=> RUN-1823: support for setting runner in Node source

.circleci/config.yml, test/selenium/.npmrc, test/testdeck/.npmrc
* Fix selenium tests
* update chromedriver
* force circleCI image to remove old chromedriver
=> update chromedriver 

rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
=> update ace-builds in package-lock.json

.circleci/config.yml
It changes the circleci config to use browser tool orb to install google chrome and driver.
=> Chrome installation with orb (circleci)

rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageView.vue
Implement force reload feature
Disable retry after dialog closed.
=> Run 1808 force reload runner keys

rundeckapp/build.gradle
Problem: The Microsoft JDBC Driver for SQL Server in use was deprecated.
Solution: Change it to a newer version with support.
=> RSE-737 Upgrade jdbc mssql driver

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/DelegateStorageTree.groovy
Improvements on Enterprise SSO configuration reload
=> RUN-1893: Fix sso settings reloading

rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageView.vue
=> backport RUN-1864

rundeckapp/grails-app/views/user/profile.gsp
Fix regression from vue 3 changes
replace a div with a span
writing css
=> RUN-1959: replace div for a span to make it inline

.github/pull_request_template.md
Avoid always including the following output:
```
Comment out instruction text to avoid displaying it when people don't update it
and get feedback from maintainers …
```
=> Update PR template: add comments around instructional text

gradle.properties, version.properties
=> Update version to 5.0.0-SNAPSHOT

rundeckapp/grails-spa/packages/ui-trellis/src/library/components/execution-log/logViewer.vue
Manual backport, forgot to rebase the main PR (#8595)
=> RUN-2005: manual backport

rundeckapp/grails-spa/packages/ui-trellis/src/library/components/execution-log/logViewer.vue
Fix for runner name (need a second PR on pro side);
Originally had flattened the settings to solve a console error, but this caused another issue that was preventing the runner name from showing. I've undone the change and saw that the console error isn't showing up anymore. 
Will make a second PR on pro side to ensure that the runner name will show up
=> RUN-2008: runner name

core/src/main/java/com/dtolabs/rundeck/core/execution/PreparedExecutionReference.java, core/src/main/java/com/dtolabs/rundeck/core/execution/logstorage/ExecutionFileLoader.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/state/StateExecutionFileProducer.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/state/WorkflowStateDataLoader.java, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/services/rundeck/services/WorkflowService.groovy, rundeckapp/grails-app/services/rundeck/services/execution/ExecutionReferenceImpl.groovy, rundeckapp/grails-app/services/rundeck/services/logging/LogFileLoader.groovy, rundeckapp/grails-app/services/rundeck/services/workflow/DefaultStateExecutionFileProducer.groovy, rundeckapp/grails-app/services/rundeck/services/workflow/DefaultWorkflowStateDataLoader.groovy, rundeckapp/src/test/groovy/rundeck/services/WorkflowServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/workflow/DefaultStateExecutionFileProducerSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/workflow/DefaultWorkflowStateDataLoaderSpec.groovy
Add abstraction for loading workflow state data.
=> RCLOUD-1061: Add abstraction for loading workflow state data.

rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/ExecReportDataProvider.java, rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormExecReportDataProvider.groovy, rundeckapp/src/test/groovy/org/rundeck/app/data/providers/GormExecReportDataProviderSpec.groovy
Add ability to create ExecReport using an Execution uuid
=> RCLOUD-1064: Add ability to create ExecReport using an Execution uuid

grails-rundeck-data-shared/src/main/groovy/rundeck/data/validation/ValidationResponse.groovy, grails-rundeck-data-shared/src/main/groovy/rundeck/data/validation/exception/DataValidationException.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/RdExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/RdJobController.groovy, rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormExecutionDataProvider.groovy, rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormJobDataProvider.groovy, rundeckapp/src/test/groovy/rundeck/controllers/RdExecutionControllerSpec.groovy
Enhancing reusability of data validation classes
=> Move DataValidationException and response class to shared plugin

grails-rundeck-data-shared/src/main/groovy/rundeck/data/notification/SendNotificationEvent.groovy, rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Add ability to trigger job notification using an event
=> RCLOUD-1068: Add ability to trigger job notification using an event

grails-rundeck-data-shared/src/main/groovy/rundeck/data/quartz/QuartzJobSpecifier.groovy, rundeckapp/grails-app/conf/spring/resources.groovy, rundeckapp/grails-app/services/rundeck/services/JobSchedulerService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/main/groovy/org/rundeck/app/quartz/ExecutionJobQuartzJobSpecifier.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Allow quartz job type to be supplied by a bean.
=> RCLOUD-1069: Allow quartz job type to be supplied by a bean.

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionService2Spec.groovy, rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceTests.groovy
Add a create execution method that looks up the ScheduledExecution by uuid
=> RCLOUD-1070: Add createExecution method with alternate parameters

grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/OptionsParserUtil.groovy, grails-rundeck-data-shared/src/test/groovy/rundeck/data/util/OptionsUtilTests.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy, rundeckapp/grails-app/services/rundeck/services/ApiService.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy, rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionServiceTempSpec.groovy, rundeckapp/src/test/groovy/rundeck/FrameworkServiceTests.groovy, rundeckapp/src/test/groovy/rundeck/controllers/OptionsParserUtilsSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/OptionsParserUtilsTests.groovy
Extract option parsing to a shared gradle project.
Convert some places that process options to use the JobData and OptionData models.
=> RCLOUD-1070: Update option processing

grails-job-kill-handler/build.gradle, grails-job-kill-handler/gradle.properties, grails-job-kill-handler/grails-app/conf/application.yml, grails-job-kill-handler/grails-app/conf/logback.groovy, grails-job-kill-handler/grails-app/controllers/com/rundeck/plugins/killhandler/UrlMappings.groovy, grails-job-kill-handler/grails-app/init/com/rundeck/plugins/killhandler/Application.groovy, grails-job-kill-handler/grails-app/init/com/rundeck/plugins/killhandler/BootStrap.groovy, grails-job-kill-handler/grails-app/views/error.gsp, grails-job-kill-handler/grails-app/views/index.gsp, grails-job-kill-handler/grails-app/views/layouts/main.gsp, grails-job-kill-handler/grails-app/views/notFound.gsp, grails-job-kill-handler/src/main/groovy/com/rundeck/plugins/killhandler/JobKillHandlerGrailsPlugin.groovy, grails-job-kill-handler/src/main/groovy/com/rundeck/plugins/killhandler/KillHandlerExecutionLifecyclePlugin.groovy, grails-job-kill-handler/src/main/groovy/com/rundeck/plugins/killhandler/KillHandlerExecutionLifecyclePluginFactory.groovy, grails-job-kill-handler/src/main/groovy/com/rundeck/plugins/killhandler/KillHandlerLogFilterPlugin.groovy, grails-job-kill-handler/src/main/groovy/com/rundeck/plugins/killhandler/KillHandlerLogFilterPluginFactory.groovy, grails-job-kill-handler/src/main/groovy/com/rundeck/plugins/killhandler/KillHandlerProcessTrackingService.groovy, grails-job-kill-handler/src/test/groovy/com/rundeck/plugins/killhandler/KillHandlerProcessTrackingServiceSpec.groovy, rundeckapp/build.gradle, settings.gradle, test/api/blocklist-plugin-count-test.sh
enhancement: Integrate rundeck-plugins/job-kill-handler-addon into Rundeck Core
=> RUN-1954: Integrate rundeck-plugins/job-kill-handler-addon into Rundeck Core

core/src/main/java/com/dtolabs/rundeck/core/execution/proxy/ProxyRunnerPlugin.java, core/src/main/java/com/dtolabs/rundeck/core/execution/proxy/ProxySecretBundleCreator.java
new interface for running plugins in runner
=> RUN-1987: new interface for running plugins in runner

rundeckapp/grails-app/views/menu/_projectExportForm.gsp
Update the resource allowed to pass any="true"
=> RUN-1967: Fix Project Component Export

rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionTest.groovy, rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
manual backport PR https://github.com/rundeck/rundeck/pull/8635 
to branch release/4.17.x
=> RUN-2031: [release/4.17.x] Merge pull request #8635 from rundeck/RUN-2031

core/src/main/java/com/dtolabs/rundeck/core/common/NodesYamlParser.java, core/src/main/java/com/dtolabs/rundeck/core/plugins/ScriptPluginProviderLoader.java, core/src/test/java/com/dtolabs/rundeck/core/common/TestNodesYamlGenerator.java, rundeck-authz/rundeck-authz-yaml/src/main/java/com/dtolabs/rundeck/core/authorization/providers/yaml/model/YamlPolicyDocConstructor.java
Updates snakeyaml usage to be compatible with snakeyaml 2.0
=> RUN-2025: Update snakeyaml usage to be forward compatible with snakeyaml 2.0

rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/schedule/ScheduleEditor.vue
ScheduleEditor wasn't showing the helper messages regarding what was being edited in the crontab.
Fixed how the input was being selected. Instead of passing the element via parameter, replaced with just javascript as the function isn't a vue method.
Using refs and/or refactoring code.
After changes:
=> RUN-2023 fix getCaretPos

rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/ProjectController2Spec.groovy
This will backport the following commits from `main` to `release/4.17.x`:
- [Merge pull request #8624 from rundeck/RUN-2019](https://github.com/rundeck/rundeck/pull/8624)
=> RUN-2019: [release/4.17.x] Merge pull request #8624 from rundeck/RUN-2019

build.yaml
upgrade ansible plugin to 3.2.8
=> RUN-1987: upgrade ansible plugin to 3.2.8

core/src/main/java/com/dtolabs/rundeck/core/config/FeatureService.java, rundeck-app-util/src/main/java/org/rundeck/app/config/ConfigService.java, rundeck-app-util/src/main/java/org/rundeck/app/config/SysConfigProp.java, rundeck-app-util/src/main/java/org/rundeck/app/config/SystemConfig.java, rundeck-app-util/src/main/java/org/rundeck/app/config/SystemConfigurable.java, rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy, rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy, rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy, rundeckapp/grails-app/services/rundeck/services/NodeService.groovy, rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy, rundeckapp/grails-app/services/rundeck/services/feature/FeatureService.groovy, rundeckapp/src/test/groovy/rundeck/services/ConfigurationServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceTests.groovy, rundeckapp/src/test/groovy/rundeck/services/NodeServiceSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/feature/FeatureServiceSpec.groovy
Internal maintenance/refactor:
* add Java types for defining System configuration properties
* update ConfigurationService to use the new interfaces
* update LogFileStorageService to use new system configuration prop definition types.
* remove some unused configuration methods, and other minor refactoring
=> RUN-459: add interfaces for system configuration

rundeck-app-util/src/main/java/org/rundeck/app/config/ConfigService.java, rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy
=> restore getConfig method

.circleci/config.yml, scripts/circleci/dependencies-functions.sh
Switch CI to Azul Zulu JDK and update executor images.
=> Switch CI to Azul Zulu JDK and update executor images.

test/docker/dockers/rundeckansible/Dockerfile
fix ansible docker test using the `ansible-core` version
=> use ansible-core in docker test

grails-rundeck-data-shared/src/main/groovy/rundeck/data/notification/SendNotificationEvent.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionService2Spec.groovy
Updates to execution context generation and notification service
=> Small tweaks to execution and notification services for RCLOUD-1046

rundeckapp/grails-app/init/rundeckapp/Application.groovy
**Problem:**
If for some reason when starting rundeck theres a connection issue with the DB, liquibase migration process can get stuck with a "locked" status, this prevents rundeck starting process to run normally.
**Solution:**
Add a log indicating the user that the database is "locked" and how to recover from it. Forcing a release was discarded since this could be dangerous, specially on a cluster environment.
=> RSE-896: Add specific message when facing a liquibase LockException

.circleci/config.yml
Prevent triggering CI in PRs from forks
=> Prevent CI on external pull requests

rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/savedFilters.vue
Confirm the list of filters for the project to ensure it doesn't include a filter with the same name
=> RUN-2077: Duplicate named filters should not be able to save

gradle.properties, version.properties
=> Update version to 5.1.0-SNAPSHOT

rundeckapp/grails-app/views/user/edit.gsp
Action name for the cancel button changes depending on the chosen language
Set the action name
=> RUN-2091: Fix cancel action in user edit page

rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/homeSummary/HomeSummary.groovy, rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Need a new endpoint to fetch API information regarding the number of executions/projects/users in the last day.
Made a new endpoint while keeping the previous ajax method to avoid breaking the project
This info is needed for the homepage conversion.
=> RUN-2088 add api endpoint for home summary

rundeckapp/grails-spa/packages/ui-trellis/src/library/utilities/RundeckVersion.ts
=> add version 5 names and tilt

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/AceEditorSpec.groovy
=> Missing package fix

rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
Update some OpenAPI docs for naming improvements.
=> RUN-2110: Minor update for openapi docs

rundeckapp/grails-app/services/rundeck/services/ExecutionUtilService.groovy, rundeckapp/src/test/groovy/rundeck/services/ExecutionUtilServiceTests.groovy
Fix: workflow strategy fails to resolve step labels
=> RSE-956: fix: step labels unavailable for workflow strategy

rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy, rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
skip check of `rundeck.security.requiredRole` if the call is from the runner
=> RUN-2123: skip rundeck.security.requiredRole if the call is from the runner

plugins/git-plugin/build.gradle, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/PluginSshSessionFactory.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/ssh/SshjSession.groovy, plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/ssh/SshjSessionFactory.groovy, plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/BaseGitPluginSpec.groovy
=> Backport PR #8809 Jgit version update

build.yaml
upgrade pywinrm plugin to 2.1.3
=> RUN-2098: upgrade pywinrm plugin to 2.1.3

build.yaml
=> RUN-2152: upgrade sshj plugin to 0.1.10

.circleci/config.yml
=> fix tag filters in circleci

gradle.properties, version.properties
=> Update version to 5.2.0-SNAPSHOT

functional-test/src/test/groovy/org/rundeck/tests/functional/api/ResponseModels/Job.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/ResponseModels/JobsExportResponse.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecutionSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/schedule/ScheduleSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/api/JobUtils.groovy, functional-test/src/test/groovy/org/rundeck/util/api/WaitingTime.groovy
=> RSE-966 Testdeck Migration: test-job-flip-scheduleEnabled-scheduler-bug.sh, test-job-flip-scheduleEnabled.sh, test-job-long-run.sh

rundeckapp/grails-app/controllers/rundeck/controllers/StorageController.groovy
If any exception is thown when calling hasPath, the message error is not showing on the GUI
Move the code to the try/catch block
=> RUN-2171: Moving code to the try/catch block in order to show errors in the GUI

rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/activityFilter.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/activityList.vue
Fix some broken spacing and layout in activity list view.
---
before:
---
after:
=> RUN-2133: UI: activity list spacing and layout fixes

core/src/main/java/com/dtolabs/rundeck/core/common/BaseFrameworkExecutionProviders.java, core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkBase.java, core/src/main/java/com/dtolabs/rundeck/core/common/IExecutionProviders.java, core/src/main/java/com/dtolabs/rundeck/core/common/ServiceSupport.java, core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionServiceImpl.java, core/src/test/java/com/dtolabs/rundeck/core/execution/impl/common/TestDefaultFileCopierUtil.java, rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/AppExecutionPluginLoader.groovy
RUN-2172: add compatibility to execute script/runner old runners
=> RUN-2172: add compatibility to execute script/runner old runners

rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/StorageController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy, rundeckapp/src/test/groovy/rundeck/controllers/StorageControllerSpec.groovy
fixes #8860 
* fix check for allow XML inside withFormat closures
* use '*' to return json by default and whenever format is not identified
=> RUN-2175: fix: legacyXml flag not working

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/tests/jobs/JobsSpec.groovy, rundeckapp/grails-app/assets/javascripts/optionEditKO.js, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp, rundeckapp/src/test/groovy/rundeck/ExecutionServiceTempSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
manual backport of https://github.com/rundeck/rundeck/pull/8859
=> RUN-2173:  Backport/release/5.1.x/pr-8859

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
* fixes problem with defaultEnabled setting for feature flags
* cleanup
=> RUN-2191: fix: feature flag defaultEnabled doesn't work

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
manual Backport RUN-2191 to 5.0.x
=> RUN-2191: backport to 5.0.x

build.yaml
=> RUN-2180: upgrade sshj-plugin version to 0.1.11

rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormTokenDataProvider.groovy, rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormUserDataProvider.groovy, rundeckapp/src/test/groovy/org/rundeck/app/providers/GormTokenDataProviderSpec.groovy, rundeckapp/src/test/groovy/rundeck/services/ApiServiceSpec.groovy
Enhancement to allow transactional writes on the database for RdUser
Add `@Transactional` to every write-to-database method.
Also a fix for user being fetch for wrong id
=> RCLOUD-1163: RdUser ready for migration

test/selenium/src/__tests__/api/legacy/api_scm.test.ts
related to https://github.com/rundeck/rundeck/pull/8897
Remove api_scm.test.ts
=> RSE-1012 Remove old API SCM tests

functional-test/src/test/groovy/org/rundeck/tests/functional/api/basic/BasicSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/basic/UnauthorizedSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecutionSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/export/ExportSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobImportSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/plugin/PluginSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/ConfigSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/schedule/ScheduleSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/container/RdClient.groovy
Update the default api version to test to 47 and adds cleanup to set back version to default value
=> update api version to 47 and setup cleanup when api version is changed

rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/pluginConfig.vue
* fix a semantic error in pluginConfig.vue
* reformat with prettier
=> RUN-2208: cleanup: prettier for pluginConfig

test/selenium/src/__tests__/api/legacy/api_execution_shm.test.ts, test/selenium/src/__tests__/api/legacy/api_project_shm.test.ts
Remove shim tests for empty set of bash tests
=> Test: remove shims for empty test sets

rundeckapp/build.gradle
Update postgresql driver to address CVE-2024-1597
=> RUN-2213: Update pg driver due CVE-2024-1597

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/tests/appadmin/KeyStorageSpec.groovy
Add sleep and wait to allow js to perform the request
=> Add wait on key creation

functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginActionsSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginInputsSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginJobActionInputSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginJobActionsPerformSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginJobDiffSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginJobStatusSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginSetupSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginStatusSpec.groovy
ticket: https://pagerduty.atlassian.net/browse/RSE-1036
As the original tests from testdeck, exclude scm tests from pro test tasks
=> RSE-1036: Fix: Scm tests are flaky on pro

functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobScheduledSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobsSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/schedule/ScheduleSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/container/RdClient.groovy
it just changes some test from incorrect packages and sets finalApiVersion to static
=> fix incorrect packaging for some tests

functional-test/build.gradle, functional-test/src/test/groovy/org/rundeck/tests/functional/api/basic/BasicSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/extensions/CustomCookieJar.groovy, gradle.properties
Doc: https://docs.rundeck.com/docs/api/#authentication
=> RSE-1040 Migrate testdeck jSecurityCheck

functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginJobDiffSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
Move hold method from ClusterBaseContainer to the base container and make it available  for test_check_diff_after_actions
=> RSE- 1042 Move hold method from ClusterBaseContainer 

.circleci/config.yml
remove use of deprecated images
=> Update CircleCI Remote Docker Image

functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginJobDiffSpec.groovy
Add extra waiting time to avoid NPE on "exportNeededStatus.commit.size()"
=> Rse 1042 move hold method from cluster base container

rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/nodeUi.ts
Manual backport of #8990. A lot of changes showing due to linting.
=> [release/5.1.x] Merge pull request #8990 from rundeck/RSE-981-ui-fix

rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/NodeCard.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/services/nodeServices.ts
=> [release/5.1.x] Merge pull request #8988 from rundeck/RSE-1051-system-execution-nodes

core/build.gradle, rundeckapp/grails-app/services/rundeck/services/JobMetadataService.groovy, rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormPluginMetaDataProvider.groovy
Use the new version of rundeck-data-models which updates the PluginMetaDataProvider
=> RCLOUD-1185: Update pluginMeta provider

.circleci/config.yml, test/docker/dockers/rundeck/Dockerfile
Fix issue with docker test on circleci
=> Fix docker test

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobReferenceSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobsSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/LogViewerOutputSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/execution/ExecutionShowPage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobCreatePage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobReferenceStep.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobShowPage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobStep.groovy, functional-test/src/test/resources/projects-import/jobref/ImportOptionsTest.rdproject/rundeck-ImportOptionsTest/jobs/job-59f6e0dd-be4e-446c-839a-f85cea40a9fc.xml, functional-test/src/test/resources/projects-import/jobref/ImportOptionsTest.rdproject/rundeck-ImportOptionsTest/jobs/job-ffc04705-13c1-47b7-840e-3f23f0dd4f86.xml, functional-test/src/test/resources/projects-import/jobref/JobRefThreadCountTest.rdproject/rundeck-JobRefThreadCountTest/jobs/job-278a6702-2946-4bae-9e06-dcd4712794a5.xml, functional-test/src/test/resources/projects-import/jobref/JobRefThreadCountTest.rdproject/rundeck-JobRefThreadCountTest/jobs/job-9b559a6a-4578-4a8c-9c55-3e7ab2056341.xml, functional-test/src/test/resources/projects-import/jobref/JobReferenceCreationUsingArgTest.rdproject/rundeck-JobReferenceCreationUsingArgTest/jobs/job-52fd314a-ffaa-46c5-9c22-efa768c0d3ea.xml, functional-test/src/test/resources/projects-import/jobref/JobReferenceCreationUsingArgTest.rdproject/rundeck-JobReferenceCreationUsingArgTest/jobs/job-54dc738b-02aa-4d56-8b6b-45f93f47a0d6.xml, functional-test/src/test/resources/test-files/simple-job-ref.xml
Ticket: https://pagerduty.atlassian.net/browse/RSE-1066
This PR migrates the following tests from the [`qa.framework.test.oss`](https://github.com/rundeckpro/rundeck-tester/tree/master/qa-framework-test-runner/selenium-test-runner/src/test/java/qa/framework/test/oss) package:
* `ImportOptionsTest`
* `JobReferenceCreationUsingArgTest`
* `JobReferenceUUIDTest`
* `JobRefNodeStepTest`
* `JobRefThreadCountTest`
* `JobRefWorkflowStepTest`
=> RSE-1066: Tests: Migrated Job Reference tests from qafw

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobsSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/steps/LogDataStepSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/execution/ExecutionShowPage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobReferenceStep.groovy, functional-test/src/test/resources/projects-import/JobTimeOutTest.rdproject/rundeck-JobTimeOutTest/jobs/job-1032a729-c251-4940-86b5-20f99cb5e769.xml, functional-test/src/test/resources/projects-import/LogDataStepTest.rdproject/rundeck-LogDataStepTest/jobs/job-1b560606-909d-43c0-aaa6-77894f2fc952.xml
Ticket: https://pagerduty.atlassian.net/browse/RSE-1066
This PR migrates the following tests from the [qa.framework.test.oss](https://github.com/rundeckpro/rundeck-tester/tree/master/qa-framework-test-runner/selenium-test-runner/src/test/java/qa/framework/test/oss) package:
• `LogDataStepTest`
• `JobTimeOutTest`
=> RSE-1067: Tests: Migrated job timeout and log data wf step tests

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ExpandedJobGroupsSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobEditSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobsSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ScheduledJobSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/project/CreateProjectSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/project/EditProjectSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/project/ExecutorSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/webhook/WebhooksSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/execution/ExecutionShowPage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/CreateDuplicatedJobPage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobCreatePage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobListPage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobShowPage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/project/ActivityPage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/project/DashboardPage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/project/ProjectCreatePage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/project/ProjectEditPage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/webhooks/WebhooksPage.groovy, functional-test/src/test/resources/docker/compose/oss/docker-compose.yml, functional-test/src/test/resources/projects-import/expanded-job-groups/rundeck-ExpandedJobGroupsSpec/files/etc/project.properties, functional-test/src/test/resources/projects-import/expanded-job-groups/rundeck-ExpandedJobGroupsSpec/jobs/job-02ac10de-459a-405c-bdbf-4b908ea1ddb4.xml, functional-test/src/test/resources/projects-import/expanded-job-groups/rundeck-ExpandedJobGroupsSpec/jobs/job-5e115a47-e2fa-4081-bf72-1f4c92c5f5b4.xml, functional-test/src/test/resources/projects-import/expanded-job-groups/rundeck-ExpandedJobGroupsSpec/jobs/job-b2c2124c-a54e-4465-a4f5-17ab7d99c67b.xml, functional-test/src/test/resources/projects-import/expanded-job-groups/rundeck-ExpandedJobGroupsSpec/jobs/job-bbfca140-68f4-4ee1-a68e-7136b9fb876d.xml, functional-test/src/test/resources/test-files/saved_searches-A.json, functional-test/src/test/resources/test-files/saved_searches-B.json, functional-test/src/test/resources/test-files/saved_searches-C.json, functional-test/src/test/resources/test-files/saved_searches-D.json
This PR is to migrate this tests:
- AdvModifyJobGroupExpLevelValuesTest
- ChangeProjectDescriptionTest
- ChangeProjectLabelTest
- CheckWebHookTest
- CreateProjectEmptyDescriptionTest
- CreateProjectEmptyLabelTest
- CreateProjectEmptyNameTest
- CreateProjectTest
- CreateProjectWithDescriptionTest
- CreateProjectWithInvalidCharactersOnDescriptionTest
- CreateProjectWithInvalidCharactersTest
- CreateProjectWithLabelAndDescriptionTest
- CreateProjectWithLabelTest
- DeleteDescriptionTest
- DeleteLabelTest
- EditCurrentDescriptionTest
- EditCurrentLabelTest
- filterNodesInEditJobs
- checkNodeExecutorList
- sshConfig
- localConfig
- scriptExecutionConfig
- sshjSShConfig
- runJobLater
- scheduledJob
- searchPluginWorkflowAddStep
- selectedAllByDefault
- stepDuplication
- URLOptions
=> RSE-1061 pt2: QAF's Oss Migration Package

build.yaml
upgrade ansible plugin
https://github.com/rundeck-plugins/ansible-plugin/pull/350
https://github.com/rundeck-plugins/ansible-plugin/pull/349
=> RUN-2224: upgrade ansible-plugin 3.2.10

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/DuplicateOptionsSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/execution/ExecutionShowPage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobCreatePage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobShowPage.groovy
Ticket: https://pagerduty.atlassian.net/browse/RSE-1069
This PR migrates the following tests from the [qa.framework.test.oss](https://github.com/rundeckpro/rundeck-tester/tree/master/qa-framework-test-runner/selenium-test-runner/src/test/java/qa/framework/test/oss) package:
* `JobOptionRepDateTest`
* `JobOptionRepFileTest`
* `JobOptionReplicationTest`
=> RSE-1069: Tests: Added tests for job options duplication

rundeckapp/grails-app/domain/rundeck/Execution.groovy
Backport of https://github.com/rundeck/rundeck/pull/9012
=> [backport] RSE-985: Fix error when deleting jobs after upgrade

gradle.properties, version.properties
Update version to 5.3.0-SNAPSHOT
=> Update version to 5.3.0-SNAPSHOT

gradle.properties
upgrade spring-security.version to 5.8.11
=> RUN-2257: upgrade spring-security.version to 5.8.11

test/selenium/__image_snapshots__/create-test-ts-job-has-not-visually-regressed-1-snap.png, test/selenium/__image_snapshots__/create-test-ts-project-has-not-visually-regressed-1-snap.png, test/selenium/__image_snapshots__/navigation-test-ts-expanded-navigation-bar-visits-activity-1-snap.png, test/selenium/__image_snapshots__/navigation-test-ts-expanded-navigation-bar-visits-commands-1-snap.png, test/selenium/__image_snapshots__/navigation-test-ts-expanded-navigation-bar-visits-jobs-1-snap.png, test/selenium/__image_snapshots__/navigation-test-ts-expanded-navigation-bar-visits-nodes-1-snap.png
=> RUN-2313: Delete unused image files

functional-test/src/test/groovy/org/rundeck/util/common/jobs/JobUtils.groovy
minor improvement to allow TZ specific when creating scheduled jobs
=> RPL-7: add TZ to scheduled jobs in tests

build.yaml
=> RUN-2199: bump sshj plugin version to 0.1.12

build.yaml
**Solution**
Update the version of the aws-s3-model-source library dependency that contains a fix for the [CVE-2024-21634](https://nvd.nist.gov/vuln/detail/CVE-2024-21634) vulnerability 
Resolves: https://app.circleci.com/pipelines/github/rundeck/rundeck/14677/workflows/54521e2a-a422-4099-9130-4ee866827a0c/jobs/160768/tests
=> RUN-2312 : Update aws-s3-model-source dependency version

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobsSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ScheduledJobSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobCreatePage.groovy
This changes the test from using the API to create the job to use the UI.
=> RPL-7: testdeck schedule job

rundeck-authz/rundeck-authz-core/src/main/java/org/rundeck/core/auth/AuthResources.java
Include auth resources for project runner management and configuration
=> RUN-2158: Add ACL's for project runner management

gradle.properties, version.properties
Update version to 5.4.0-SNAPSHOT
=> Update version to 5.4.0-SNAPSHOT

docker/official/Dockerfile
- Fixes execution log not working when using a named volume.
- Declares execution log dir as volume
=> Fixes on Docker images directories and permissions

rundeckapp/build.gradle
remove unused "geb" dependency and related properties
remove specified version for grails-plugin-codecs
=> RUN-2483: Cleanup some dependencies

rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy, rundeckapp/src/test/groovy/rundeck/controllers/UserControllerSpec.groovy
Bugfix
An ambigous call was made by naming the argument on user controller, it was solved by deleting the `login: user` call
=> Fix buildUser call

functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionSpec.groovy
It adds a functional test for a multiple execution job using API
=> RUN-2335: QAF migration for multi execution job

functional-test/src/test/groovy/org/rundeck/util/container/RdClient.groovy, functional-test/src/test/groovy/org/rundeck/util/container/RdContainer.groovy
This is a minor change to just increase timeouts
- Timeout when waiting for container startup
- Timeout for http requests
=> Testdeck: increase timeout

core/src/main/resources/com/dtolabs/launcher/setup/templates/admin.aclpolicy.template
=> RUN-2459: add runner permissions to admin.aclpolicy template

grails-job-kill-handler/src/main/groovy/com/rundeck/plugins/killhandler/KillHandlerExecutionLifecyclePlugin.groovy
=> RUN-2545: relabel property

functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobListPage.groovy
This just adds locator for the job list page
=> add locator for jobgraph and job dashboard

rundeckapp/grails-app/views/menu/welcome.gsp
Change of behavior for rba
Adding the option to hide the version number from the menu welcome
https://pagerduty.atlassian.net/browse/RCLOUD-1273
=> RCLOUD-1273: Add ui-socket to hide version from menu welcome

build.yaml
upgrade ansible plugin
for https://github.com/rundeck-plugins/ansible-plugin/pull/373
=> RUN-2566: upgrade ansible version

grails-webhooks/grails-app/controllers/webhooks/WebhookController.groovy, grails-webhooks/src/test/groovy/webhooks/WebhookControllerSpec.groovy
Change behavior for disabled webhooks to return 404 rather than 503.
=> RCLOUD-1340: When posting to a disabled webhook return a 404

scripts/circleci/packaging-functions.sh
Fix the packaging publish step failing for 5.4.0 rc1
=> Fix packaging publish

scripts/circleci/packaging-functions.sh
backport pr for https://github.com/rundeck/rundeck/pull/9186
=> Backport release fix

functional-test/src/test/groovy/org/rundeck/util/gui/pages/BasePage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobCreatePage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/nodes/NodesPage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/project/NodeSourcePage.groovy
It adds the NodesPage and some locators for selenium testing
=> RUN-2339: qaf testdeck

rundeckapp/build.gradle, rundeckapp/grails-app/init/rundeckapp/init/servlet/JettyServletContainerCustomizer.groovy
=> RCLOUD-1345: Add jetty jmx metrics

core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/WorkflowExecutionListenerStepMetrics.java, core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/WorkflowMetricsWriter.java, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/grails-app/services/rundeck/services/workflow/WorkflowMetricsWriterImpl.groovy
Added new JMX metrics to track step executions
Jira ticket https://pagerduty.atlassian.net/browse/RCLOUD-1316
=> RCLOUD-1316: add step metric

core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/WorkflowExecutionListenerStepMetrics.java
Added new log for failed steps
Jira ticket https://pagerduty.atlassian.net/browse/RCLOUD-1317
=> RCLOUD-1317: add step failed log

rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
Add a JMX metric that reports the quartz thread pool size.
=> RCLOUD-1367: Add JMX metric that reports the quartz thread pool size

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/webhook/WebhooksSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/project/ProjectExportPage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/project/SideBarPage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/webhooks/WebhooksPage.groovy, functional-test/src/test/resources/projects-import/webhooks-test/rundeck-importProjectWithWebhook/webhooks.yaml
https://pagerduty.atlassian.net/browse/RUN-2343
QA Framework webhook test migration to testdesk webhook test
=> RUN-2343: testdesk webhook migration

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/KeyValueDataLogFilterSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/LogFilterSpec.groovy
[RUN-2505](https://pagerduty.atlassian.net/browse/RUN-2505)
Added functional tests for the Key-Value Data log filter
[RUN-2505]: https://pagerduty.atlassian.net/browse/RUN-2505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RUN-2505 : Functional tests for Key Value Data log filter

functional-test/src/test/groovy/org/rundeck/tests/functional/api/executor/JschNodeExecutorSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/executor/OpenSshNodeExecutorSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/executor/SshjNodeExecutorSpec.groovy, functional-test/src/test/resources/docker/compose/oss/Dockerfile, functional-test/src/test/resources/docker/compose/oss/executor/helloWorld.sh, functional-test/src/test/resources/docker/compose/oss/executor/openssh-node.yaml, functional-test/src/test/resources/docker/compose/oss/executor/sshj-node.yaml, functional-test/src/test/resources/projects-import/core-jsch-executor-test/rundeck-executor-test/jobs/job-a5fbe8c2-1a8b-4a6f-ae34-92e5b3d4f8a9.xml, functional-test/src/test/resources/projects-import/core-jsch-executor-test/rundeck-executor-test/jobs/job-c7d2b5e9-3c4b-48c1-88e9-1f93c6a4bcd7.xml, functional-test/src/test/resources/projects-import/core-sshj-executor-test/rundeck-executor-test/files/acls/node-acl.policy, functional-test/src/test/resources/projects-import/core-sshj-executor-test/rundeck-executor-test/files/etc/project.properties, functional-test/src/test/resources/projects-import/core-sshj-executor-test/rundeck-executor-test/jobs/job-7c58a292-d987-4864-8882-6f5e5c6a4cb9.xml, functional-test/src/test/resources/projects-import/core-sshj-executor-test/rundeck-executor-test/jobs/job-d9f12a60-7b2f-4e92-8b37-b6c9e23f7df7.xml, functional-test/src/test/resources/projects-import/openssh-executor-test/rundeck-executor-test/files/acls/node-acl.policy, functional-test/src/test/resources/projects-import/openssh-executor-test/rundeck-executor-test/files/etc/project.properties, functional-test/src/test/resources/projects-import/openssh-executor-test/rundeck-executor-test/jobs/job-881725be-0266-47e5-b2ae-64e978c42ce3.xml, functional-test/src/test/resources/projects-import/openssh-executor-test/rundeck-executor-test/jobs/job-9532efbb-bd36-49c6-bd3a-203177ea876b.xml
Move jsch and sshj executor code to core
=> Move SSHJ and JSCH functional executor tests to core

rundeckapp/grails-app/controllers/rundeck/interceptors/AuthorizationInterceptor.groovy
=> RCLOUD-1389: Remove wrong increment

build.yaml, functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
Upgrade ansible plugin with fixes:
**RUN-2626**
- https://github.com/rundeck-plugins/ansible-plugin/pull/375
**RUN-2651**
- https://github.com/rundeck-plugins/ansible-plugin/pull/368
- https://github.com/rundeck-plugins/ansible-plugin/pull/378
=> upgrade ansible plugin for issues RUN-2448 and RUN-2626

rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy, rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormExecReportDataProvider.groovy, rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
There was a problem when exporting reports. During the export, a conversion was taking place where the job ID from the report table was being updated to the job UUID, and that was persisted to the database. This caused missing activity because the query wouldn't return results, as the filter was set by job ID.
- Removed the conversion from job ID to job UUID, since there is already a `job_uuid` being exported.
- Updated the query so that databases that have already updated the column will fetch the reports correctly.
- Added some missing references to the job UUID and execution UUID, which were causing missing activities during import. …
=> RCLOUD-1351: Fix get reports

docker/official/etc/admin.aclpolicy
Missing admin ACL in docker image for runners project management
=> add runner acl admin permissions in docker image

gradle.properties, version.properties
=> Update version to 5.5.0-SNAPSHOT

gradle.properties, version.properties
Update version to 5.6.0-SNAPSHOT
=> Update version to 5.6.0-SNAPSHOT

core/src/main/java/com/dtolabs/rundeck/core/config/Features.java, core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
**Jira Ticket**:  
Add alphaUi feature flag 
<details>
<summary>
More details and context about this PR, including info relevant for the release
</summary>
<br />
**Customer Impact:**
**Release Notes:**
**Kind of Change**
**Development Checklist**
Specific Considerations:
GUI Changes:
</details>
<details>
<summary>
Information for testing/bug bash
</summary>
<br />
**Docker Usage**:
> Note: After the CircleCI "Build" step completes, this branch can be tested in Docker with the following command (replace `$BRANCH` with the branch name, e.g. "RUN-123"):
~~~bash
docker run  -P -p 4440:4440  \
-e RUNDECK_SERVER_ADDRESS=0.0.0.0 \
-e RUNDECK_GRAILS_URL=http://localhost:4440 \
rundeckpro/ci:$BRANCH
~~~
**Testing setup:**
**Acceptance Criteria:**
**QA/Bug Bash Needed?**
**Manual QA Notes:** …
=> RUN-2721: Add alphaUi flag

rundeckapp/grails-spa/packages/ui-trellis/build.gradle
=> Update runNpmVersion for RBA

grails-execution-mode-timer/build.gradle
=> Exp: remove rundeck version

functional-test/src/test/groovy/org/rundeck/util/common/WaitingTime.groovy
=> RUN-2737: Add new longer waiting time for test executions lasting more than 1 min

functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecExportSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecutionSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/executor/JschNodeExecutorSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/executor/OpenSshNodeExecutorSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/executor/SshjNodeExecutorSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobScheduledSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/ConfigSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/ExecuteScriptSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/RunUrlSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/workflowSteps/FileUrlScriptStepSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/appadmin/KeyStorageSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobReferenceSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/common/WaitingTime.groovy, functional-test/src/test/groovy/org/rundeck/util/common/jobs/JobUtils.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobReferenceStep.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/scm/PerformScmActionPage.groovy
Enhancement to the functional api, to improve the execution waiting api.
Changed the api to use java.time and consistent measurements, to avoid confusion between seconds and milliseconds.
=> Refactor execution waiting helper for a more clear api.

functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
Minor enhancements on initialization of BaseContainer to allow inheritors to reuse settings.
Simplifies provider synchronization scheme
=> Minor enhancements on testdeck init synchronization.

.circleci/config.yml, functional-test/build.gradle, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/alphaUi/jobs/JobsSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/annotations/AlphaUiSeleniumCoreTest.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobCreatePage.groovy, functional-test/src/test/resources/spock-configs/IncludeAlphaUiSeleniumCoreTestsConfig.groovy
Add structure to be able to add selenium tests with the alphaUi feature flag enabled upon initializing the tests.
Will uncomment the test once merged to RUN-575 that consumes the flag.
=> Add Alpha UI selenium tests structure

functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/RunCommandSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/execution/CommandOnMultipleNodesSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/execution/CommandSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/common/jobs/JobUtils.groovy, functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/execution/CommandPage.groovy
Additional selenium functional tests for the Command execution flows per
https://pagerduty.atlassian.net/browse/RUN-2610?atlOrigin=eyJpIjoiNTJmY2NjYjg2Y2NiNDE3OTg4NWI1MjhlMDk0MjZiMTAiLCJwIjoiaiJ9
=> add additional functional tests for Command executions

README.md
Update java/nodejs versions used and copyright
=> RUN-2769: Readme update java version, copyright

functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionOnMultipleNodesSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/api/responses/jobs/Job.groovy, functional-test/src/test/groovy/org/rundeck/util/api/responses/jobs/JobBase.groovy, functional-test/src/test/groovy/org/rundeck/util/api/responses/jobs/JobDetails.groovy, functional-test/src/test/groovy/org/rundeck/util/api/responses/jobs/JobsExportResponse.groovy, functional-test/src/test/groovy/org/rundeck/util/common/jobs/JobUtils.groovy, functional-test/src/test/resources/test-files/job-template-common.xml
Additional functional API tests for the Job Creation flows per
https://pagerduty.atlassian.net/browse/RUN-2611
Note: Depends on https://github.com/rundeck/rundeck/pull/9283
=> add additional functional api tests for Job Creation

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/JobTakeoverQueryBuilder.groovy, grails-rundeck-data-shared/src/test/groovy/rundeck/data/util/JobTakeoverQueryBuilderSpec.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceIntegrationSpec.groovy
Backport to 5.5.x RCLOUD-1427 enhanced takeover query
=> Manual backport RCLOUD-1427

core/src/main/java/com/dtolabs/rundeck/core/resources/ScriptResourceModelSourceFactory.java, plugins/stub-plugin/src/main/java/com/dtolabs/rundeck/plugin/stub/StubResourceModelSourceFactory.java
Improvement on the Resource Model plugins configuration using runners:
- mark StubResourceModelSource as a local plugin
=> RUN-2623: Improvement on the Resource Model plugins configuration using runners

functional-test/src/test/resources/docker/compose/oss/docker-compose.yml
Fix test databases exposed ports so dont clash with other local dbs.
=> Fix test databases exposed ports so dont clash with other local dbs.

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/BulkJobActionsSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/common/jobs/JobUtils.groovy, functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/BasePage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobListPage.groovy, functional-test/src/test/resources/test-files/api-test-executions-running-scheduled.xml, functional-test/src/test/resources/test-files/job-template-common.xml, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/JobBulkEditControls.vue
Additional functional tests per https://pagerduty.atlassian.net/browse/RUN-2639
=> RUN-2639 : Functional Tests for Job List Actions UI

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/BulkJobActionsSpec.groovy
Removed the test failing in `pro`.
=> remove nextUI test failing in pro

rundeckapp/build.gradle
Security enhancement
Upgrade the `json-path` library version to `2.9.0`
=> RUN-2305: Fix CVE-2023-51074

.circleci/config.yml
Update Circle CI job names for more clarity.
=> circle test jobs renamed

.circleci/config.yml
Add parameter to disable wizcli scan by default
=> Add parameter to disable wizcli scan by default

.circleci/config.yml
Add a parameter to allow the pipeline to run without triggering the enterprise pipeline.
=> CircleCI: Add parameter for conditional enterprise triggering

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/nodes/NodesSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/BasePage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/execution/CommandPage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/nodes/NodesPage.groovy, functional-test/src/test/resources/docker/compose/oss/executor/jsch-node.yaml, functional-test/src/test/resources/docker/compose/oss/executor/openssh-node.yaml, functional-test/src/test/resources/docker/compose/oss/executor/sshj-node.yaml, functional-test/src/test/resources/projects-import/nodes-test/import-dir/files/acls/node-acl.policy, functional-test/src/test/resources/projects-import/nodes-test/import-dir/files/etc/project.properties, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/NodeCard.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/NodeFilterInput.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/NodeFilterLink.vue
Additional functional tests for the Nodes Pager per
https://pagerduty.atlassian.net/browse/RUN-2608
=> RUN-2608 :  Functional tests for the Nodes Pager

core/src/test/groovy/com/dtolabs/rundeck/core/plugins/configuration/PluginAdapterUtilitySpec.groovy, rundeckapp/grails-app/domain/rundeck/CommandExec.groovy, rundeckapp/grails-app/utils/rundeck/codecs/JobsXMLCodec.groovy, rundeckapp/src/test/groovy/org/rundeck/app/components/RundeckJobDefinitionManagerSpec.groovy, rundeckapp/src/test/groovy/rundeck/JobsXMLCodecSpec.groovy, rundeckapp/src/test/groovy/rundeck/JobsYAMLCodecSpec.groovy, rundeckapp/src/test/groovy/rundeck/PluginStepTests.groovy
=> RUN-2766: 5.6.0-rc1: fix script step job definition imported boolean values

functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
In case the setupProject fails for some reason, (e.g. 400 or 403 error), fail fast instead of succeeding silently.
=> Functional tests: fail fast if unable to access or create project

gradle.properties, version.properties
=> Chore: Update version to 5.7.0-SNAPSHOT

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ScheduledJobSpec.groovy
https://app.circleci.com/pipelines/github/rundeck/rundeck?branch=RUN-2853-ScheduledJobSpec
Used the new utils for waiting
=> RUN-2853: Flaky - rundeck: T Selenium > Scheduled job

functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobsSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/common/jobs/JobUtils.groovy
Additional functional tests to test the [project's jobs](https://docs.rundeck.com/docs/api/#listing-jobs)  API.
=> RUN-2612: Functional Tests for Job Listing API

functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecutionSpec.groovy
https://app.circleci.com/pipelines/github/rundeck/rundeck?branch=RUN-2860
Increase waiting time to the test
=> Increase waiting time to fix flaky test

core/src/main/java/org/rundeck/app/auth/RequiredRoleProvider.java, rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy, rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
Add ability to load required role from spring bean
=> RCLOUD-1489: Add ability to load required role from spring bean

functional-test/src/test/groovy/org/rundeck/tests/functional/api/basic/BasicSpec.groovy, grails-securityheaders/src/main/groovy/grails/securityheaders/SecurityheadersGrailsPlugin.groovy, grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/CSPSecurityHeaderProvider.groovy, grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/PermissionsPolicySecurityHeaderProvider.groovy, grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/ReferrerPolicySecurityHeaderProvider.groovy, grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/StrictTransportSecurityHeaderProvider.groovy, rundeckapp/grails-app/conf/application.yml
=> RCLOUD-1199: Add missing security headers

rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Fix: scheduled jobs can stop running if the job is modified, this can happen by manual editing, API or SCM import.
=> RUN-2865: Fix: scheduled jobs stop running

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/DuplicateJobSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobSummarySpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobsSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ScheduledJobSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobCreatePage.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobShowPage.groovy, functional-test/src/test/resources/test-files/jobWithOptions.xml
Jira https://pagerduty.atlassian.net/browse/RUN-2620
Add selenium tests
=> RUN-2620: selenium job definition view tests

gradle.properties, version.properties
=> Update version to 5.8.0-SNAPSHOT

functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecExportSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionOnMultipleNodesSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/input/SecureInputSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/ExecuteScriptSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/api/schedule/ScheduleSpec.groovy, functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ScheduledJobSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/common/jobs/JobUtils.groovy
Validate response to job import does not indicate any failure
=> Functional Test improvement: validate job import response

build.yaml, functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecSudoSpec.groovy, functional-test/src/test/resources/docker/compose/oss/executor/sshj-node.yaml, functional-test/src/test/resources/projects-import/core-sshj-executor-test/rundeck-executor-test/jobs/job-fbf165bd-b5d9-44a7-98b9-fb8aa273ff9d.xml
This PR is intended to add functional tests for sshj when having pty enabled/disabled from the PR listed bellow. These tests will fail until having this changes in a new release and set the new sshj plugin version
https://github.com/rundeck-plugins/sshj-plugin/pull/66
EDIT: This also updates the sshj version to 0.1.16
=> RUN-2634: add functional test for sshj with pty enabled/disabled

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/project/NavSidebarSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy, functional-test/src/test/groovy/org/rundeck/util/container/RdClient.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/common/navigation/NavLinkTypes.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/project/SideBarPage.groovy, functional-test/src/test/resources/NavSidebarSpec.aclpolicy, functional-test/src/test/resources/realm.properties, rundeckapp/grails-app/views/common/_navBarProjectSettingsData.gsp
* merge https://github.com/rundeck/rundeck/pull/9415
* fixes #9414 
* add functional tests
=> RUN-2937: (merge) Fix the project export right managing both export and delete action

examples/example-java-audit-plugin/pom.xml, examples/example-java-execution-lifecyle-plugin/build.gradle, examples/example-java-job-lifecycle-plugin/build.gradle, examples/example-java-logging-plugins/build.gradle, examples/example-java-nodeexecutor-plugin/build.gradle, examples/example-java-notification-plugin/build.gradle, examples/example-java-step-plugin/build.gradle, examples/example-java-storage-converter-plugin/build.gradle, examples/example-java-storage-plugin/build.gradle, examples/json-plugin/build.gradle
=> RPL-68: update java plugin examples to use more recent rundeck core library

.circleci/config.yml
=> add retry in package signing publish step

.github/mergeable.yml, .github/workflows/check-milestone.yml
Replace buggy Mergeable check with a github action.
The mergeable check is often showing "success" even for PRs which have no milestone :(
=> Create github action to check milestone requirement on PRs

rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy, rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy, rundeckapp/src/test/groovy/rundeck/ExecutionTest.groovy
Cleanup: remove unused data in results for efficiency
=> RUN-2975: cleanup: for "events" and now running data sets

build.gradle, rundeckapp/build.gradle, testbuild.groovy
Removes all inclusions of junit binaries from the build package.
Includes an enhacement to testbuild.groovy to be able to match regex or negate instructions.
=> RUN-2815: Remove JUnit from build distribution

rundeckapp/grails-app/assets/stylesheets/tokens-rundeck.css, rundeckapp/grails-app/views/layouts/base.gsp
This is an Enhancement. Adding a new CSS file to override variables. 
Created `tokens-rundeck.css` to override `tokens.css` variables with updated colors based on the Figma design and Rundeck theme requirements
=> Run-2978: Created tokens-rundeck.css to override tokens.css variables

.circleci/config.yml
=> add missing install-node to maven-publish

gradle.properties, version.properties
=> Update version to 5.9.0-SNAPSHOT

rundeckapp/grails-spa/packages/ui-trellis/jest.global-mocks.js, rundeckapp/grails-spa/packages/ui-trellis/package-lock.json, rundeckapp/grails-spa/packages/ui-trellis/package.json, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/activityList.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/mocks/mock.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/tests/activityList.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/home/HomeBrowserItem.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/home/HomeCardList.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/home/tests/HomeBrowserItem.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/home/tests/HomeCardList.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/home/tests/HomeHeader.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/home/tests/HomeView.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/options/OptionView.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/options/tests/OptionView.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/options/tests/OptionsEditor.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/NodeFilterResults.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/tests/NodeCard.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/tests/NodeTable.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/util/tests/UndoRedo.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/JobBulkEditControls.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/tests/JobScmStatus.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/project-dashboard/components/activitySummary.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/project-dashboard/components/activitySummary.vue
Security fixes
Update vue-i18n to version 10, following this guide: https://vue-i18n.intlify.dev/guide/migration/breaking10.html
Fixes [CVE-2024-52809](https://redirect.github.com/intlify/vue-i18n/security/advisories/GHSA-9r9m-ffp6-9x4v)
+ bump webpack to latest version
=> RUN-3014: Update vue-i18n to version 10 and webpack 5 to latest

rundeckapp/grails-spa/packages/ui-trellis/package-lock.json, rundeckapp/grails-spa/packages/ui-trellis/package.json, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/tests/activityList.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/options/tests/OptionView.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/NodeDetailsSimple.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/tests/NodeDetailSimple.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/readme-motd/EditProjectFile.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/library/components/containers/copybox/CopyBox.test.ts, rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/tests/pluginPropView.spec.ts
Fixes https://github.com/rundeck/rundeck/security/dependabot/416
Update tests as needed to comply with update.
=> RUN-3015: Update happy-dom test dependency

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ExpandedJobGroupsSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobListPage.groovy, functional-test/src/test/resources/projects-import/expanded-job-groups/rundeck-ExpandedJobGroupsSpec/jobs/job-02ac10de-459a-405c-bdbf-4b908ea1ddb4.xml, functional-test/src/test/resources/projects-import/expanded-job-groups/rundeck-ExpandedJobGroupsSpec/jobs/job-b2c2124c-a54e-4465-a4f5-17ab7d99c67b.xml, functional-test/src/test/resources/projects-import/expanded-job-groups/rundeck-ExpandedJobGroupsSpec/jobs/job-bbfca140-68f4-4ee1-a68e-7136b9fb876d.xml
https://pagerduty.atlassian.net/browse/RPL-246
The name of the main group has been modified to avoid any other test with the same name interfering with the subgroups of the jobs
=> RPL-246: Added modification to ExpandedJobGroupsSpec

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy, rundeckapp/grails-app/views/layouts/base.gsp, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/community-news-notification/App.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/community-news/CommunityNewsFeed.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/community-news/NewsletterSubscribe.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/repository/views/PluginRepositoryView.vue, rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/News.ts, rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/Releases.ts
add a new config value to set the AWS API gateway endpoint
=> RUN-2108: add a new config value to set the AWS API gateway endpoint

core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java, rundeckapp/grails-app/domain/rundeck/Execution.groovy, rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
This is a patch release branch for RBA that includes a safer takeover behavior, improvements for metrics and a fix for a P0 bug.
=> RBA Patch Release

.circleci/config.yml, scripts/circleci/build-functions.sh, scripts/circleci/helper-functions.sh
[RUN-3026](https://pagerduty.atlassian.net/browse/RUN-3026) : Implement Snyk CLI scan in rundeck/rundeck and rundeckpro/rundeckpro
- Add the Snyk security scan to the build pipeline
- To avoid adding additional time to the build, the snyk scan is done in parallel with the fat `war` build.
[RUN-3026]: https://pagerduty.atlassian.net/browse/RUN-3026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> RUN-3026 : Add snyk security scanning

gradle.properties, version.properties
=> Update version to 5.10.0-SNAPSHOT

.circleci/config.yml, rundeckapp/grails-spa/packages/ui-trellis/build.gradle, rundeckapp/grails-spa/packages/ui-trellis/package-lock.json, rundeckapp/grails-spa/packages/ui-trellis/package.json, rundeckapp/grails-spa/packages/ui-trellis/scripts/export_package.sh, scripts/circleci/build-functions.sh
Development enhancement:  
* Disable UI unit tests from being invoked via `gradle check`
* Add separate CircleCI config to run the UI unit tests
=> RUN-3111: separate UI tests in Circle

.circleci/config.yml
=> RUN-3026: Snyk: set severity threshold high

docker/official/Dockerfile, docker/official/README.md, docker/official/lib/includes/110_sideload_container_plugins.sh
Changes name as suggested in https://github.com/rundeck/rundeck/pull/9559.
=> RCLOUD-1588: Renames the container plugin directory.

rundeckapp/grails-spa/packages/ui-trellis/src/library/components/widgets/project-select/ProjectSelect.vue, rundeckapp/grails-spa/packages/ui-trellis/src/library/components/widgets/project-select/tests/ProjectSelect.spec.ts
Enhancement
Added unit tests for the projectSelect component to ensure its functionality works as expected.
=> RUN-3109: Added unit tests for ProjectSelect component

rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy, rundeckapp/grails-app/i18n/messages.properties, rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Creates new endpoint to get job components data
New endpoint `/api/{api_version}/job/{job_id}/components` that returns a json file with job components values on the format:
```
{
"componentPropertyName1":"{\"key1\":\"value1\"}",
"componentPropertyName2":"{\"key2\":\"value2\"}"
}
```
And another endpoint `/api/{api_version}/jobs/components` to return the job components properties:
```
{
"job-comp":{
"properties":[
{
"blankIfUnexpandable":true,
"defaultValue":"default_value",
"description":"Component Description",
"name":"componentPropertyName",
"renderingOptions":{
"displayType":"HIDDEN",
"hidden_identity":"job-comp-definition"
},
"required":false,
"scope":null,
"selectLabels":null, …
```
=> RUN-2953 Add new API endpoint to get job components data

rundeckapp/grails-app/services/rundeck/services/NodeService.groovy, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/project-nodes-config/ProjectConfigurableForm.vue
* Improve the Node Sources Configuration page by displaying related configuration properties together
=> RUN-3136: Group properties in Node Source configuration

rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/activityFilter.vue
Fix a visual issue in activity filter
=> RUN-3164: fix: activity filter has extra >

build.yaml
Update sshj plugin to 0.1.17 that include a fix for CopyFileFailed for recurisve copy after update to rundeck 5.3.0/5.4.0
=> Update sshj plugin version to 0.1.17

gradle.properties, version.properties
Bumps to 5.11.0-SNAPSHOT after creating the rc for 5.10.0
=> Update version to 5.11.0-SNAPSHOT

README.md, rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/workflow/WorkflowEditor.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/workflow/WorkflowSteps.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/workflow/WorkflowStrategy.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/workflow/tests/WorkflowEditor.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/workflow/tests/WorkflowSteps.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/workflow/tests/workflowTypes.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/workflow/types/workflowTypes.ts, rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/pluginPropEdit.vue, rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/tests/pluginPropEdit.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/library/components/utils/AceEditor.vue, rundeckapp/grails-spa/packages/ui-trellis/src/library/components/utils/UiSocket.vue, rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
RUN-2727
* changes to support Workflow Strategy Vue updates in pro
* Refactor WorkflowStrategy.vue slightly, change the data model
* Modify WorkflowSteps.vue to additionally emit the steps data on the global eventBus
* Modify pluginPropEdit.vue: enable some customization of the property rendering, hiding the label, and putting a ui-socket around the Ace editor for CODE displayType properties.  
* Update UISocket to allow v-model
=> RUN-2727: alphaUi: workflow editor updates

rundeckapp/grails-spa/packages/ui-trellis/.storybook/preview.ts
Load i18n strings in storybook, so that we can use it for all sorts of use cases. 
=> RUN-3198: Load localized strings in storybook

docker/ubuntu-base/Dockerfile, functional-test/src/test/resources/docker/compose/oss/Dockerfile, test/docker/dockers/tomcat/Dockerfile
Remove CVEs alerts produced for remco and goland version
- CVE-2024-6104
- CVE-2024-45337
- CVE-2025-22870
- CVE-2024-24786
=> RUN-3226: Fix Remco CVEs

functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
Add a mechanism to use a custom environment in tests
=> RUN-3234: add option to set custom docker compose path

gradle.properties, version.properties
=> Update version to 5.12.0-SNAPSHOT

build.yaml
=> RUN-3318: Update attribute-match-node-enhancer plugin to 0.2.0

rundeckapp/build.gradle
Bugfix: CVE-2024-57699
Upgrade json-smart dependency to use latest version of the library
=> Upgrade json-smart version to fix CVE-2024-57699

grails-execution-mode-timer/grails-app/services/com/rundeck/plugin/ExecutionModeService.groovy, grails-execution-mode-timer/grails-app/services/com/rundeck/plugin/UpdateModeProjectService.groovy, rundeckapp/grails-app/init/rundeckapp/init/PluginCachePreloader.groovy, rundeckapp/grails-app/services/rundeck/services/JobSchedulerService.groovy, rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy, rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy, rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/RundeckBootstrapStorageTreeUpdater.groovy
RUN-3361: catch throwable inside scheduleAtFixedRate
additional:
- handle potential null value in pending trigger cleanup 
=> RUN-3361: catch throwable inside scheduleAtFixedRate

build.yaml
- revert updated plugin that has a bug
=> RUN-3412: Revert attribute-match plugin updates

build.yaml
**Jira Ticket**:  
https://pagerduty.atlassian.net/browse/RUN-3184
Update sshj plugin on to use the version with the lates Bouncy Castle update. 
<details>
<summary>
More details and context about this PR, including info relevant for the release
</summary>
<br />
**Customer Impact:**
**Release Notes:**
**Kind of Change**
**Development Checklist**
Specific Considerations:
GUI Changes:
</details>
<details>
<summary>
Information for testing/bug bash
</summary>
<br />
**Docker Usage**:
> Note: After the CircleCI "Build" step completes, this branch can be tested in Docker with the following command (replace `$BRANCH` with the branch name, e.g. "RUN-123"):
~~~bash
docker run  -P -p 4440:4440  \
-e RUNDECK_SERVER_ADDRESS=0.0.0.0 \
-e RUNDECK_GRAILS_URL=http://localhost:4440 \ …
=> Upgrade sshj plugin version

gradle.properties, version.properties
=> Update version to 5.13.0-SNAPSHOT

README.md, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/activityList.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/tests/activityList.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/readme-motd/editProjectFileService.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/project-nodes-config/nodeSourcesUtil.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/repository/components/PluginURLUploadForm.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/webhooks/views/WebhooksView.vue, rundeckapp/grails-spa/packages/ui-trellis/src/library/modules/pluginService.ts, rundeckapp/grails-spa/packages/ui-trellis/src/library/services/api.ts, rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/ExecutionOutput.ts, rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/NodeSourceFile.ts, rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/Plugins.ts, rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/Webhooks.ts, rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/test/Plugins.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/library/utilities/ExecutionLogConsumer.ts, rundeckapp/grails-spa/packages/ui-trellis/tests/unit/ExecutionOutput.spec.ts
* replacing ts-rundeck client with axios
=> RUN-3227: using api service instead of rundeck client (UI)

build.yaml
=> RUN-3422: Update attribute match plugin to 0.2.1

build.gradle
This is maintenance since sonatype legacy system will stop working on June 30th, 2025.
URL's has been changed as shown on this doc
[https://central.sonatype.org/publish/publish-portal-ossrh-staging-api/#configuration](url)
=> RUN-3329: Migrate to central portal 

gradle.properties, version.properties
=> Update version to 5.15.0-SNAPSHOT

build.yaml
Part 2 - follow up of https://github.com/rundeck/rundeck/pull/9729
Updates aws-s3-model-source plugin
=> RUN-3584/3594: Address CVE-2023-3635 and CVE-2025-48734

rundeckapp/grails-app/views/scheduledExecution/_createForm.gsp, rundeckapp/grails-app/views/scheduledExecution/_editForm.gsp, rundeckapp/grails-app/views/scheduledExecution/_jobEditCommon.gsp, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/editor/DetailsEditorSection.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/editor/HeaderSection.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/editor/main.js, rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/en_US.js, rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/es_419.js, rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/fr_FR.js, rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/ja_JP.js, rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/pt_BR.js, rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/zh_CN.js
For nextUi, job editor page header section in Vue
=> RUN-3680: Job editor card header section in vue

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/BasicJobsSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobShowPage.groovy, rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/NodeFilterInput.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/ResourcesEditor.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/tests/NodeFilterInput.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/workflow/JobRefForm.vue, rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/workflow/tests/JobRefForm.spec.ts, rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/nodes/main.ts
Node filter input wasn't correctly updating its value, causing issues in the following pages: 
- job edit (RUN-3686) - upon editing a job that has a job ref step, the node filter set in the step wouldn't be populated;
- running a job (RUN-3462) - upon trying to override the node filters for a job that allows it. Wouldn't update correctly either with a new filter nor if user selected a tag within a node;
- command page - Same as above, wouldn't update correctly either with a new filter nor if user selected a tag within a node;
Changed the syntax from v-model to value + added an immediate watcher on the value. There's a second PR on rundeckpro. …
=> RUN-3462+RUN-3686: Fix node filter input not updating value correctly

build.yaml
Update openssh-node-execution plugin
Update openssh-node-execution plugin version to apply the fix https://github.com/rundeck-plugins/openssh-node-execution/pull/32
=> RUN-3653: Update openshh-node-execution plugin version

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/scm/ScmStatusBadgeSpec.groovy
=> ignore flaky test

grails-execution-mode-timer/grails-app/controllers/com/rundeck/plugin/EditProjectController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/StorageController.groovy, rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy
Clean Swagger definition to use the generated file to generate a new Go client for the Terraform provider.
=> RUN-3689: edit swagger definition to make it work with code generator

gradle.properties, version.properties
=> Update version of SNAPSHOT(5.16.0)

functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/project/ImportProjectSpec.groovy, functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
- fix flakiness in ImportProjectSpec
- generate unique project names for test cases
=> RUN-3736: flaky test fix: use unique project name

build.gradle, gradle.properties, rundeckapp/build.gradle
- Update Hikari JDBC Pooling library
=> RUN-3679: Update hikari for improved JDBC pooling

cve-suppress.xml
=> RUN-3722: Exclude CVE-2025-41242

rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
This is a fix introduced on the PR below.
https://github.com/rundeck/rundeck/pull/9741/files#diff-41e5aefbf6961a45be9810ad43eab3972ffb66f3bde2bad578cf09992ab5192eR1243
=> Fix error logging in ExecutionService

.circleci/config.yml
=> test: older circleci ubuntu image
