- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/logging/MaskLogOutputByRegexPlugin.groovy
- rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/logging/MaskLogOutputByRegexPluginSpec.groovy
Fixes https://github.com/rundeckpro/rundeckpro/issues/1372
Sensitive data was being printed on log output as decribed on the linked issue where passwords from rundeckd file was being shown when performing some system commands
Was created a log filter plugin to define a regex to capture and mask sensitive data
> Creating a new log filter plugin to mask sensitive output log text

- rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
- rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
- rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
Enhancement
By default, Node Health checks and the Health Status enhancer will now be turned on in new projects for Enterprise customers. 
Updated the category predicate to include the resourceModelSources so they are included. Also updated the default value for the rundeckProHealthChecker and added a check for if the inputMap value at a key is null. If it is, set the value to its default value.
Added a iterator on valid props of the string type. If it is null, set to the defaultValue. If it is still null, remove it from the map to avoid a null pointer exception.
> edit framework controller to accept resourceModelSources config when creating a new project

- rundeckapp/grails-app/domain/rundeck/Notification.groovy
- rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/notification/DummyWebhookNotificationPlugin.groovy
- rundeckapp/src/test/groovy/rundeck/NotificationSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Fixes #6690 
Webhook notification is not working if use credentials on URL like `user:password@url`
When trying to reproduce the issue, I realized that Jenkins returns this error if it uses POST and not GET to trigger a job remotely. These changes are a suggestion to be able to use the webhook notification to make a GET request.
> Fixes webhook notification issue that use credentials in URL

- rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Fixes https://github.com/rundeckpro/rundeckpro/issues/1442
The API to get scheduled jobs was returning only jobs scheduled from job edit page but not the ones scheduled by enterprise-scheduled addon.
And the API to get job forecast, the field `futureScheduledExecutions` was being filled only with schedules via addon (if there was one where the job was linked)
The method of the controller was changed to get all scheduled jobs from jobSchedulesService and was created another PR (https://github.com/rundeckpro/enterprise-schedules/pull/63) to fix the addon so that the API to get job forecast returns the future scheduled executions correctly
> Fix to get schedules both via addon (enterprise-schedules) and via job scheduling (job edit page)

- rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/FrameworkController2Spec.groovy
Fix #6614 
Check plugin exists instead of configuration. if the plugin has no configuration properties it would return empty map
> Fix #6614 check plugin exists instead of configuration

- rundeckapp/grails-spa/packages/ui/src/pages/community-news/CommunityNewsFeed.vue
Fixes the date formatting so the correct date is displayed.
> Fix community news post dates

- docker/official/remco/templates/rundeck-config.properties
- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/core/utils/RequestAwareLinkGenerator.groovy
With this PR, we can now enable `multiURL` option (`rundeck.multiURL.enabled`). With this option enabled, we can access the server using different url's.
The implementation is based on override grails DefaultLinkGenerator.
**Expected behaviour**
Start rundeck server with a `grails.serverURL` (with or without `server.servlet.context-path`), `rundeck.multiURL.enabled=true` and access the service through `grails.serverURL`, a secondary DNS pointing to the same server, the server IP, etc.
- each of accessed url will ask for login and password;
- the address in navigation bar will not change;
- notifications will use `grails.serverURL`;
This also fixes #5795.
> Support to multiple URL's

- rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/EditOptsControllerSpec.groovy
Fixes https://github.com/rundeckpro/rundeckpro/issues/1369
pass in correct values to insert duplicate option
replaces pr https://github.com/rundeck/rundeck/pull/6768
> Fix 1369: duplicate secure option doesn't work correctly

- README.md
Remove outdated text about building docs with pandoc.
> Remove outdated docs build text

- README.md
Update readme to remove outdated download link.
> Remove "launcher jar" link from downloads list

- rundeckapp/grails-app/views/common/_baseUiNext.gsp
- rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp
- rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_view.scss
* Fixes the plugin subnav menu alignment so it's no longer stacked on top of the primary menu
* Removes the blue navbar flicker by setting the grid section to match the background color of the navbar
> Layout fixups

- rundeckapp/grails-app/views/user/loggedout.gsp
- rundeckapp/grails-app/views/user/login.gsp
- rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/pages/login.scss
- rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_pages.scss
- rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_view.scss
* Uses new background color for footer
* Jiggles the layout to remove the scrolling that appeared regardless of page height
> Fixup login and logout footer and scrolling

- rundeckapp/grails-app/services/rundeck/services/AuthorizationService.groovy
- rundeckapp/src/test/groovy/rundeck/services/AuthorizationServiceSpec.groovy
Fix: when acl cache is cleaned, the authorization eval cache should also be cleaned, by sending acl.modified event
Related to cluster messaging changes around cache cleanup
> Fix: when acl cache is cleaned, auth eval cache should be notified

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
Fix: error message about `fileCache` configuration, the ProjectManagerService requires a static config definition for the fileCache.
> Fix: ProjectManager fileCache config requires static config

- core/src/main/java/com/dtolabs/rundeck/core/execution/service/ScriptUserGroupSource.java
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/service/ScriptUserGroupSourceSpec.groovy
Fixes https://github.com/rundeckpro/rundeckpro/issues/1493
Was not possible to pass the username logged in the session to the UserGroupSource plugin if it uses a script to handle it
This changes include the username to the context so that it's possible to define `script-args: ${session.username}` and pass the username as argument to the script
> Fixes the UserGroupSource to pass the username to the script

- rundeckapp/grails-app/views/framework/_tagsummary.gsp
FIX: https://github.com/rundeckpro/rundeckpro/issues/1464
is this a bug fix, or an enhancement? Please describe.
the job screen's "Show all" button is not clickable when If too many of the same tags are used in the nodes. there is a JavaScript error show on the console.
Changing prototype to Jquery
> Fix: "Show all" button on Jobs list is not clickable #1464

- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/grails-app/domain/rundeck/Execution.groovy
- rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/test/groovy/rundeck/ExecutionService2Spec.groovy
- rundeckapp/src/test/groovy/rundeck/ExecutionTest.groovy
- rundeckapp/src/test/groovy/rundeck/ScheduledExecutionTest.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
fixes https://github.com/rundeckpro/rundeckpro/issues/1507
Executions were breaking if user roles had commas in it
There was a code that transforms the list of roles in a Json format string. So, the code was changed to use that instead of store the list as a simple text with the roles joined by a comma.
> Avoiding error when parsing user roles that contain commas

- rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/DynamicFormPluginProp.vue
This component introduced in #6752 is polluting existing css class names(at least `multiselect`).
The PR stops the pollution, but we will need to follow up to determine the impact on the notification UI..
> Scope multiselect css

- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/gui/SystemReportMenuItem.groovy
Refactor the System Report system config menu item to be defined in a bean.
> Move System Report config menu link to bean definition

- rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_cards.scss
Fixes button spacing in card footers when buttons are direct children of the footer.
Good ol' CSS.
> Apply margin rule to direct card footer children

- rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/RuleEvaluator.java
- rundeck-authz/rundeck-authz-api/src/test/groovy/com/dtolabs/rundeck/core/authorization/RuleEvaluatorSpec.groovy
This extends the ACL Policy format to allow using URNs
for user or role/group subjects in an exact match.
Using a `by: urn: "user:bob"` clause in the ACLpolicy defines
an exact match for a username "bob".
Using `by: urn: "group:dev"` defines exact match for group "dev".
Enhances ACL policy format to let an exact user or group match occur using the `urn:` clause.
> Add group: and user: urn support for ACL subjects

- rundeckapp/build.gradle
- rundeckapp/src/main/groovy/org/rundeck/jaas/jetty/BcryptCredentialProvider.groovy
- rundeckapp/src/main/groovy/org/rundeck/security/JettyCompatibleSpringSecurityPasswordEncoder.groovy
- rundeckapp/src/main/groovy/org/rundeck/security/passwordutil/HiddenInputPasswordUtilityEncrypter.groovy
- rundeckapp/src/main/groovy/org/rundeck/security/passwordutil/JettyPasswordUtilityEncrypter.groovy
- rundeckapp/src/main/resources/META-INF/services/org.eclipse.jetty.util.security.CredentialProvider
- rundeckapp/src/test/groovy/org/rundeck/security/passwordutil/JettyPasswordUtilityEncrypterTest.groovy
- rundeckapp/src/test/groovy/rundeckapp/cli/CommandLineSetupTest.groovy
Addresses #6817 
* Adds a bcrypt credential provider and type
* Requires jaas login to be enabled
* Spring security version we use apparently does not support salt revisions so `$2a$` but not `$2y$` works
> Add bcrypt credential type for PropertyFileLoginModule

- docker/official/Dockerfile
- docker/ubuntu-base/Dockerfile
Addresses #6850 
Refreshes the base Ubuntu 18.04 image used to build the Docker images.
> Update base Docker image

- rundeckapp/grails-app/views/scheduledExecution/_show.gsp
- rundeckapp/grails-app/views/scheduledExecution/_showHead.gsp
These actually appeared to be some of the rare uses of `btn-secondary` ..
> Remove secondary so buttons stand out better on darker background

- rundeckapp/grails-app/views/common/_mainbar.gsp
Removes the funky link showing up next to the project picker.
> Remove projtabs link

- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Fixes a 500 error calling the Job Workflow API, if the user doesn't have the `read` or `view` authorization for the job. It should return appropriate unauthorized response.
Fix a typo.
> fix: 500 error for workflow API response if no read or view auth

- rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionsCleanUp.groovy
- rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionsCleanUpTest.groovy
bug fix: execution cleanup doesn't work as expected when cluster mode is off
cleanup execution in non-cluster mode shouldn't filter by serverNodeUuid.
remove serverNodeUuid filter on execution table when cluster mode is off
issue https://github.com/rundeck/rundeck/issues/6674
> cleanup execution in non-cluster mode 

- rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Issue: some project-level access is checked using non project-scoped AuthContextProvider, which means that depending on how the auth context is generated, the incorrect authorization result would be cached.  Later, when checking using the correct AuthContextProvider via the cache, the incorrect result is still returned.
This fix addresses two specific places this occurs: checking "event read" and "job create" access for projects when loading the Project List metadata ("homeAjax").
> Fix: use correct project auth context to eval some project access

- rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
This same method name is called twice.
> Use correct method name in test

- docker/official/README.md
- docker/official/remco/templates/rundeck-config.properties
- rundeckapp/build.gradle
- rundeckapp/templates/config/rundeck-config.properties.template
- test/docker/dockers/rundeck/scripts/start_rundeck.sh
- test/docker/dockers/tomcat/rundeck-config.properties
resolves #6003
* Removes `MVCC` which had been deprecated and a noop but will cause error in `1.4.200+`
* Instructs h2 not to shutdown when VM is shutting down to mitigate hibernate errors during shutdown
This does not bump the H2 version. We are currently on the second-to-last patch release of H2 which has not been updated in over a year. The latest patch release removes the `MVCC` jdbc parameter and throws an error if it is used. The Grails GORM project still uses this directive and it is causing a test to break. They have removed it in `7.1`, but that is not the latest release version: https://www.gitmemory.com/issue/grails/grails-core/11630/705501839 .
> Mitigate h2 errors

- rundeckapp/grails-app/conf/application.groovy
- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/grails-spa/packages/ui/src/pages/project-nodes-config/ProjectNodeSourcesHelp.vue
* enabling projectKeyStorage feature by default
* for resource model plugin, add the option to create project ACLs
> project key storage ACL settings

- docker/official/remco/templates/rundeck-config.properties
This fixes #6744 by adding configuration hooks for the preauth user sync.
See above.
N/A — This is a minor change using existing patterns.
N/A
> Add usersync configuration options to Docker Remco templates

- core/src/main/java/org/rundeck/app/gui/MenuItem.java
- grails-webhooks/src/main/groovy/webhooks/menu/WebhooksMenuItem.groovy
- rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy
- rundeckapp/grails-app/views/common/_navBarProjectSettingsData.gsp
- rundeckapp/grails-app/views/common/_navData.gsp
- rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/navbar.stories.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/stores/NavBar.ts
Add the ability to specify a priority, defaulted to `0`, on menu items.
The navbar UI will sort the items based on this priority key for display.
> Implement navbar sort priority for menu items

- rundeckapp/grails-app/views/framework/_nodesEmbedKO.gsp
- rundeckapp/grails-app/views/menu/_jobslist.gsp
Fixes up references to the old `#main-panel`. This was causing a commands page model to be "in the way" while also not visible.
> Fix modal on commands and joblist screen

- rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
Fix #6889 
Fix form element ids
> fix #6889 incorrect ids for exclude filter radios

- docker/official/README.md
- docker/official/remco/templates/log4j2.properties
- docker/official/remco/templates/rundeck-config.properties
- docker/official/test/remco/test.yml
- rundeckapp/grails-app/migrations/core/NodeFilter.groovy
- rundeckapp/templates/config/log4j2.properties.template
- test/api/test-job-long-run.sh
- test/docker/dockers/rundeck/scripts/start_rundeck.sh
- test/docker/dockers/tomcat/rundeck-config.properties
* Adds the `grails.plugin.databasemigration.updateOnStart` option to Docker
* Defaults the above and `dbCreate` settings to the Rundeck default if no override is provided
* Fixes failing tests due to connection abandon timeout
* Adjusts the `node_filter` filter column
* Adds loggers for the Grails db migration plugin and Liquibase set to `INFO`
This would supersede #6923
> DB Migration fixup

- rundeckapp/grails-app/domain/rundeck/Execution.groovy
- rundeckapp/grails-app/domain/rundeck/LogFileStorageRequest.groovy
- rundeckapp/grails-app/migrations/core/ConstraintsIndexesKeys.groovy
Adding indexes on the server_nodeuuid column of the execution table, and the completed column of log_file_storage_request improves the app performance.
> Add indexes on Execution and LogFileStorageRequest columns that are used in queries.

- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/config/Export.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
Fixes https://github.com/rundeckpro/rundeckpro/issues/1657
Modified to not use cache when searching for scheduled executions.
> retrieving scheduled executions without using cache

- rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ProjectController2Spec.groovy
Fixes https://github.com/rundeck/rundeck-cli/issues/346
When trying to enable/disable project schedule/execution via API or Rundeck CLI, Rundeck was returning an error 500
The argument expect the project name and not a IRundeckProject type. This was happening only on the first run because in the following runs the method is not called again
> Fixes arguments of method called to handle schedules from project config API

- rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
fix:  use aclFileManager to read project acls for export
Fixes https://github.com/rundeckpro/rundeckpro/issues/1668
> fix:  use aclFileManager to read project acls for export

- rundeckapp/grails-app/assets/javascripts/jobedit.js
- rundeckapp/grails-app/views/menu/_groupTree.gsp
- rundeckapp/grails-app/views/menu/_jobPickerModalPagination.gsp
- rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_tabs-navs-pagination.scss
fixes https://github.com/rundeckpro/rundeckpro/issues/1571
If job pagination is enabled, there is no way to handle pagination on modal to choose job reference
Was included pagination mechanism to handle pagination calling controller without reloading page
> Handles job pagination (if enabled) on referenced job picker modal

- rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
- rundeckapp/grails-app/domain/rundeck/ReferencedExecution.groovy
- rundeckapp/src/test/groovy/rundeck/ReferencedExecutionSpec.groovy
fixes https://github.com/rundeckpro/rundeckpro/issues/1519
In the scenario where a job has many referenced executions, the method that returns the of parent jobs becomes quite slow and this slows down the loading of the job page
The method was changed to use criteria to improve query time.
> Replacing code that fetches the list of ScheduledExecutions parents to use criteria and improve query time

- core/build.gradle
- core/src/main/java/com/dtolabs/rundeck/core/common/impl/URLFileUpdater.java
- core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/ScriptURLNodeStepExecutor.java
- core/src/main/java/com/dtolabs/rundeck/core/http/ApacheHttpClient.java
- core/src/main/java/com/dtolabs/rundeck/core/http/HttpClient.java
- core/src/main/java/com/dtolabs/rundeck/core/http/RequestProcessor.java
- core/src/main/java/com/dtolabs/rundeck/core/resources/URLResourceModelSource.java
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/ScriptURLNodeStepExecutorSpec.groovy
- core/src/test/groovy/com/dtolabs/rundeck/core/http/ApacheHttpClientSpec.groovy
- core/src/test/java/com/dtolabs/rundeck/core/common/impl/TestURLFileUpdater.java
- core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/TestScriptURLNodeStepExecutor.java
- core/src/test/java/com/dtolabs/rundeck/core/resources/TestURLResourceModelSource.java
- gradle.properties
- rundeckapp/grails-app/conf/application.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- testbuild.groovy
Replace  apache http client 3.1 with newer apache http client version. Created new http client interface and replaced the locations where the 3.1 code was used with the new interface.
> Sec: Remove apache httpclient 3.1

- core/src/main/java/com/dtolabs/rundeck/plugins/scm/ScmExportPlugin.java
- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
- rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
Fixes https://github.com/rundeckpro/rundeckpro/issues/1710
The button was added in jobs list page instead of job show because when the user performs a push it cannot choose the commit to push, so if this would be in jobs show page, the user could think that he is pushing just that single job instead of all the pending commits.
The modification in scm controller was to avoid showing the pending jobs to be commited when the requested action is to push and also to know the push action id a new method was added to the export interface.
> Enh: Add button to Commit SCM changes in jobs list page

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
- plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy
- rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
- rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/scm/ScmLoaderServiceSpec.groovy
- check if the config was changed: issue https://github.com/rundeckpro/rundeckpro/issues/1726
- improve background process refresh
- expose background process configuration variables
```
rundeck.scmLoader.delay=1
rundeck.scmLoader.interval=10
```
* save config properties in the cache to check if stored values changed. If there is a change, SCM plugin is unregister and initialized again
* in GitExportPlugin, clusterFix jobs check must run only if detects a remote change
* ScmLoaderService must perform a fetch before call clusterFix (this improve the sync time between clusters)
* preload pluginMeta in ScmLoaderService
* moving the plugin meta refresh and the rename check from …
> Scm:  Loader Fix  and Sync Config Changes

- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/ImportJobs.groovy
- plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
- rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
fix for: https://github.com/rundeckpro/rundeckpro/issues/1727
- in ImportJobs, run the delete before importing the new job version
- removing plugin.getStatus from ScmLoaderService. If the pull automatic is enabled, the clusterFix won't refresh job status. clusterFix will call the fetch directly before the run.
- hasJobStatusCached was always returning null in GitImportPlugin
> SCM Import: fix import of renamed jobs 

- rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
- rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
- rundeckapp/grails-app/services/rundeck/services/scm/ScmJobImporter.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/scm/ScmJobImporterSpec.groovy
Fixes https://github.com/rundeckpro/rundeckpro/issues/1729
Fixes two issues:
1. corrects earlier change that removed metadata loading for jobs when getting export paths, and which prevented `${job.sourceId}` from working in template paths
2. Fixes an issue where imported jobs would be serialized with wrong file path when scm import and export were both enabled; the job metadata was stored after the event was fired triggering the export.  Fixed this to store the metadata before firing the job change event.
> SCM: Fix job sourceId not appearing in exported file path

- rundeckapp/grails-app/services/rundeck/services/JobMetadataService.groovy
- rundeckapp/src/test/groovy/rundeck/services/JobMetadataServiceSpec.groovy
Fix #6982 
Deletes plugin meta for project when project is deleted.
> Fix #6982 plugin meta was not deleted with project

- rundeckapp/grails-app/domain/rundeck/WorkflowStep.groovy
- rundeckapp/grails-app/migrations/changelog.groovy
- rundeckapp/grails-app/migrations/core/WorkflowStep.groovy
Fixes https://github.com/rundeck/rundeck/issues/5848
Deleting old execution logs were causing a lot of deadlocks in the database.
Creating index for errorHandler on WorkflowStep table
> Fix: Create index for errorHandler on WorkflowStep table to help prevent deadlocks in MSSQL

- grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
- grails-webhooks/src/test/groovy/webhooks/WebhookServiceSpec.groovy
Add a the keyStorage service provider to the context services being passed to onevent, so web hook processing can use key storage
> Enh: Adding access to Key Storage for Webhook Plugins

- rundeckapp/grails-app/conf/application.groovy
If ajax request happens after session expire/logout, it is
redirected to /login/authAjax which redirects to itself until
the browser fails with max redirects error.
This config change disables the ajax auth feature of spring security
by default
> Fix: /login/authAjax redirect loop for ajax requests

- core/src/main/java/com/dtolabs/rundeck/core/resources/ScriptPluginResourceModelSourceFactory.java
- core/src/test/groovy/com/dtolabs/rundeck/core/resources/ScriptPluginResourceModelSourceFactorySpec.groovy
- rundeckapp/grails-spa/packages/ui/src/pages/project-nodes-config/ProjectNodeSourcesConfig.vue
Enhancement: 
enable access to key storage for Node Resources Script Plugins
for https://github.com/rundeck/rundeck/issues/6775
passing services to ScriptPluginResourceModelSourceFactory
Just like Java resource model system, Script resource model plugin will need project/system ACLs to access key storage
> Enh: Allow access to Key Storage for Node Resources Script Plugins

- rundeckapp/grails-app/services/rundeck/services/DbStorageService.groovy
… cannot retrieve them in the create criteria when it is equated against an empty string
3. Please be sure the …
> Fix: Oracle saves empty fields as null and results in bug in comparison code

- core/src/main/java/com/dtolabs/rundeck/core/utils/ScriptExecUtil.java
- core/src/test/groovy/com/dtolabs/rundeck/core/utils/ScriptExecUtilSpec.groovy
Fixes https://github.com/rundeckpro/rundeckpro/issues/1518
When using an script executor plugin to run a job and then kill this job, the subprocess wasn't being killed by rundeck
when the Thread is interrupted when killing the job, the process should also be destroyed
> Kill process when thread for local command is interrupted

- rundeckapp/grails-app/taglib/rundeck/AuthTagLib.groovy
Fixes #6896.
Pass other project names to  authContextEvaluatorCacheManager.evaluate() in order to determine if the user has the specified authorization for other projects.
> Fix: "Duplicate to other project" option visibility

- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy
- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
- rundeckapp/grails-app/services/rundeck/services/JobMetadataService.groovy
- rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
- rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
- rundeckapp/src/test/groovy/rundeck/services/scm/ScmLoaderServiceSpec.groovy
Fixes https://github.com/rundeckpro/rundeckpro/issues/1730
* if a job is deleted in another cluster member, the scm import status is not reflected
detect jobs that were deleted and emit an event so that the scm plugin listeners are notified of deleted jobs
* does not fix issue with hibernate cache causing 500 error
There may be two events emitted for deleted jobs, if both import and export plugins are configured for a project. In that case both import and export loader tasks will emit a DELETED job change event, but the handlers of those events are idempotent, and so it will not affect the behavior. a future refactor could consolidate the loader code for …
> Fix: externally deleted job not reflected in scm import status

- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Some code cleanup for Jobs Import API
adds some tests
> Cleanup: jobs import api endpoint requires apiv14

- rundeckapp/grails-app/views/scm/performAction.gsp
Additional fixes for scm action page spacing issues:
import action items spacing
before
> Fix: layout issues: scm import screen

- core/src/main/java/org/rundeck/app/acl/ACLCacheControl.java
- rundeckapp/grails-app/services/rundeck/services/AuthorizationService.groovy
- rundeckapp/src/test/groovy/rundeck/services/AuthorizationServiceSpec.groovy
fix an issue where project acl modification was not communicated to cluster members.
fixes https://github.com/rundeckpro/rundeckpro/issues/1763
* adds interface to enable cache cleanup
> fix:  project ACL change is not refreshed in cluster

- rundeckapp/grails-spa/packages/ui-trellis/theme-next/scss/paper/_cards.scss
> Remove margin on text color in card

- rundeckapp/grails-app/views/common/_js.gsp
- rundeckapp/grails-spa/packages/ui-trellis/src/components/first-run/FirstRun.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelect.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/interfaces/AppLinks.ts
Add app link for `menuHome` and use this for the link. This should account for `rdbase`.
Using `rdbase` as the `href` as it redirects to the projects list. This didn't seem explicit enough..
> Fix project picker view all link

- rundeckapp/templates/config/rundeck-config.properties.template
By default, rundeck uses the machine hostname to generate both `server.address` and `grails.serverURL` properties when building the default rundeck-config.properties at first run. However, this assumes that the hostname is resolvable through DNS or /etc/hosts, which is not always the case, causing two side effects:
- The application binds to just one network interface, which can be any of the available.
- The grails.serverURL points to an unresolvable URL.
This causes the application to be unreachable after the first run, requiring the installer to run it, take it down to adjust the generated file, and run it again.
This PR makes the following changes to the default properties file to address those issues:
- server.address is now assigned to 0.0.0.0 so the application binds to all …
> Enh: Change default server.address to localhost instead of hostname to generate default rundeck-config.properties

- rundeckapp/grails-app/assets/javascripts/executionStateKO.js
- rundeckapp/grails-app/views/execution/show.gsp
- rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
- test/selenium/src/__tests__/selenium/execution/execution-show-page-views.test.ts
- test/selenium/src/pages/adhocCommand.page.ts
- test/selenium/src/pages/executionShow.page.ts
Enhances the Execution View page to enable UI plugin code to add new Views for an execution.
Updates NodeFlowViewModel js type with:
* renames `tabs` to `views`
* renames `activeTab` to `activeView` but retains `activeTab` for compatibility
* each view object can have `showButton: true` which enables a separate toggle button in addition to entry in the View selection dropdown
* each view object can have `hasContent: true` to enable generation of a dom element containing the content, which is revealed when the view is selected.  the `content` value can contain HTML to put in the view.
Also fixes an issue: Ace syntax editor was not working for Execution Lifecycle …
> [internal enhancement] execution views cleanup on execution show page

- rundeckapp/grails-app/views/execution/_execDetails.gsp
- rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_tables.scss
Bugfix: Table style breaks out of Modal width
Add fixed table layout class to constrain table into modal as well as adding `break words` to collapse long strings
> Add Style for Fixed Table and Word Breaks

- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/grails-app/services/rundeck/services/UserService.groovy
- rundeckapp/src/main/groovy/org/rundeck/security/RundeckJaasAuthenticationSuccessEventListener.groovy
- rundeckapp/src/main/groovy/org/rundeck/security/RundeckPreauthSuccessEventHandler.groovy
- rundeckapp/src/test/groovy/org/rundeck/security/RundeckJaasAuthenticationSuccessEventListenerTest.groovy
- rundeckapp/src/test/groovy/org/rundeck/security/RundeckPreauthSuccessEventHandlerSpec.groovy
* Use grails event to trigger user profile updates instead of directly calling UserService
* Fix spring dependency chain issue
Fixes https://github.com/rundeckpro/rundeckpro/issues/1796
Instead of depending on UserClass directly, change `RundeckPreauthSuccessEventHandler` and `RundeckJaasAuthenticationSuccessEventListener` to send a grails event with user detail for updating user profile. Modify UserService to react to the event.
Attempt to alter spring dependency chain to be less strict at load time did not work.
> Refactor: auth success user profile updates decoupled from UserService

- rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckEmbeddedPluginExtractor.groovy
Fix: bundled groovy plugins are not named with version number in the name, so should overwrite previous versions if they exist.
Set overwrite flag to true when extracting groovy plugins
For https://github.com/rundeckpro/rundeckpro/issues/1798
> Fix: bundled groovy plugins should be overwritten when extracted

- rundeckapp/grails-app/migrations/core/ConstraintsIndexesKeys.groovy
- rundeckapp/grails-app/migrations/core/HibernateIndex.groovy
Bugfix.  When upgrading from rundeck 3.3.x to 3.4.0 and the database used is Oracle, the hibernate_sequence, IDX_TOKEN and PROJECT_IDX_TOKEN exist and should be checked with a precondition before trying to add them.
Update changesets to apply a precondition which checks to see if these indexes and sequence already exist
None
> [RUN-61]fix rundeckpro/rundeckpro#1823 check if sequences

- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/grails-app/services/rundeck/services/PluginService.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/PluginCustomizer.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy
- rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/PluginServiceSpec.groovy
Fixes https://github.com/rundeckpro/rundeckpro/issues/1824
* A groovy plugin containing no definition would be registered but later cause NPE loading the plugin
* prevent NPE when loading spring bean plugins
* avoid registering groovy script plugins until after they are constructed
> Fix rundeckpro-1824 ent logstorage config [RUN-78]

- rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
fixes rundeckpro/rundeckpro#1846
[RUN-124]
**Bug**: This Ace setup was introduced in #7082 to attach the editor to lifecycle plugin property fields. It caused duplicate editors in at least one case.
I scoped the jQuery selector to the `#tab_execution_plugins` element so it would not apply to other DOM locations. I'm actually unsure if this satisfies the original intent.
[RUN-123]: https://pagerduty.atlassian.net/browse/RUN-123
[RUN-124]: https://pagerduty.atlassian.net/browse/RUN-124
> RUN-124: Scope Ace setup to execution plugin tab

- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
fixes https://github.com/rundeckpro/rundeckpro/issues/1569
The auth context was not loading the ACL rules on the project context
Change the method to create the auth context for subject and project context
> RUN-136: access control did not allow to toggle execution enabled/disabled option even if allowed by ACL policy

- rundeckapp/grails-app/assets/javascripts/jobedit.js
- rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginConfig.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginPropEdit.vue
- rundeckapp/grails-spa/packages/ui/src/components/job/notifications/NotificationsEditor.vue
fixes https://github.com/rundeckpro/rundeckpro/issues/1406
The fields of the notification plugins is not showing the dropdown context menu
It include the class on the fields that should have the dropdown and call the function to inclute this component when the plugin property fields is mounted on the modal
> RUN-7: dropdown context menu to be shown on the notification edit modal

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
Fixes https://github.com/rundeckpro/rundeckpro/issues/1826
It was not possible to upload larger files since the config prop settings `rundeck.fileUploadService.tempfile.maxsize` was not working.
The property should be included on RundeckConfigBase class
The grails config properties `grails.controllers.upload.maxFileSize` and `grails.controllers.upload.maxRequestSize` must also be defined since the default value on Grails application is approximately 25Mib or 26214400
> RUN-75: Adding maxsize and expiration time for fileUploadService config on RundeckConfigBase

- rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
- rundeckapp/grails-spa/packages/ui-trellis/package.json
- rundeckapp/grails-spa/packages/ui/package-lock.json
- rundeckapp/grails-spa/packages/ui/package.json
Related to rundeckpro/rundeckpro#1783
Bumps `@rundeck/client` to a version with a fix to `apiRequest` so that it calls the subclass implementation of `sendRequest` instead of super.
This method sets the base URL for you and in the browser based on `rdBase`. A small convenience and an explicit method for making raw API calls that doesn't rely on overloaded infrastructure method(`sendRequest`).
> Bump rundeck client version to 0.2.3

- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/grails-app/i18n/messages.properties
- rundeckapp/grails-app/i18n/messages_es_419.properties
- rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Issue:
fixes: rundeckpro/rundeckpro#1714
When a user try to edit a job and there is a broken or deleted plugin bound to this, is shown a warning message explaining the plugin must be removed before editing.
> RUN-127: Fix: Unable to edit a job after removing a plugin used in that job

- rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy
- rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/plugins/ApiPluginListProvider.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/PluginControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/PluginApiServiceSpec.groovy
- test/api/include.sh
- test/api/test-project-resources.sh
- test/selenium/src/__tests__/api/plugins.test.ts
This enhancement adds UI profile(`iconUrl`, `providerMetadata`) to the public `plugin/list` API endpoint along with the query parameter `service` to filter the results by provider.
**Additional Context**
This is part of ongoing efforts to move functionality out of UI specific endpoints and into the public API.
> RUN-89 Add UI profile and search to plugin list endpoint

- grails-metricsweb/build.gradle
- grails-persistlocale/build.gradle
- grails-repository/build.gradle
- grails-securityheaders/build.gradle
- grails-webhooks/build.gradle
grails plugins should not be published, remove the grails-plugin-publish which can conflict with other publish process
> RUN-153: remove grails-plugin-publish from grails plugins used by rundeckapp

- rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy
bugfix, optionListValue was not sent back to opsEdit view on validation error
return the optionValuesPlugins to the view on validation error exactly as it's sent during the initial edit
> RUN-64: Fix: optionValuePlugins list disappears when when a validation errors

- rundeckapp/grails-app/assets/javascripts/menu/home.js
Bugfix: In the default project list on the Home page, if there are more than 15 projects the remaining projects do not load
https://github.com/rundeck/rundeck/issues/7130
It appears that there is a conflict in the `project-list-item` selector since the data attribute is added by knockout after load. By referencing a child element of the selector that is available in the DOM on load, allows for the waypoint to trigger.
> RUN-141: Fix: UI Bug with Projects list that hinders display over 15 projects in a list.

- rundeckapp/grails-app/views/menu/jobs.gsp
- rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_tables.scss
Addresses #7125
This is not a regression in `3.4.x` and needs some further discussion. I have split this issue off into its own: #7141
Adjusted positioning:
A change was introduced to the `.table` class for a specific screen that caused the table columns to collapse on all work break opportunities. I moved this change to the `.table-fixed` class that was applied to the table from the previous fix to scope it more narrowly. This table needs some work but the previous, more usable display is restored:
> RUN-137: Fix 3.4.0 UI regressions

- rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
- rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
ref #7127 
Fixes handling of null result due to execution failing to start.
Original cause of #7127 was not determined
> RUN-220: FIX: npe if execution fails to start

- rundeckapp/grails-spa/packages/ui-trellis/src/stores/News.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/stores/Projects.ts
Fixes #7116 
Bugfix: Project Picker always took 1 sec to load 
Remove the timeout that cause the project picked to be forced to load after 1 sec
> RUN-121: Remove 1 second timeout for request

- rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
- rundeckapp/src/test/groovy/rundeck/services/scm/ScmLoaderServiceSpec.groovy
enhancement:
avoid SCM Loader try to load a failed plugin integration in each iteration (for example because the SCM folder is wrong or for authentication issues)
- add a list that saves failed plugins 
- each time the SCM background process fails to init an SCM plugin, that failed plugin is storage in the list
- if the plugin changes and it doesn't fail, it will be removed from the list.
> RUN-222: SCM Loader enhancement: avoid failed plugin will be init on background iteration

- core/src/main/java/com/dtolabs/rundeck/plugins/scm/JobImportState.java
- core/src/main/java/com/dtolabs/rundeck/plugins/scm/JobImporter.java
- core/src/main/java/com/dtolabs/rundeck/plugins/scm/JobRenamed.java
- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy
- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitExportPlugin.groovy
- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/ImportTracker.groovy
- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/JobImportGitState.groovy
- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/JobRenamedImp.groovy
- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/ImportJobs.groovy
- plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitExportPluginSpec.groovy
- plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
- rundeckapp/grails-app/services/rundeck/services/JobMetadataService.groovy
- rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
- rundeckapp/grails-app/services/rundeck/services/scm/ContextJobImporter.groovy
- rundeckapp/grails-app/services/rundeck/services/scm/ResolvedJobImporter.groovy
- rundeckapp/grails-app/services/rundeck/services/scm/ScmJobImporter.groovy
- rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
- rundeckapp/grails-app/views/scm/diff.gsp
- rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/scm/ScmJobImporterSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/scm/ScmLoaderServiceSpec.groovy
BigFix: when a job is renamed, SCM Import deletes and creates the job again
for issue https://github.com/rundeckpro/rundeckpro/issues/1731
- using jgit, check if a path was added and deleted (gitdiff)
- if that is the case save the renamed job in the import tracker
- when the job is imported, save the current UUID and the sourceId. Force to preserve original UUID when the job is re-imported.
- clean import trackers of the old path
- split job plugin metadata per integration
> RUN-151: Fix: Properly detect when a job was renamed in SCM Import

- rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/RuleEvaluator.java
- rundeck-authz/rundeck-authz-api/src/test/groovy/com/dtolabs/rundeck/core/authorization/RuleEvaluatorSpec.groovy
fixes https://github.com/rundeckpro/rundeckpro/issues/1381
A NullPointerException is thrown If a node resource does not have an attribute defined on ACL policy using `contains` rule
Include changes to handle null value on string when applying the test for the rule
> RUN-143:  Handles null value when resource does not have the attribute filtered by rule key

- rundeckapp/grails-app/services/rundeck/services/ReportService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ReportServiceSpec.groovy
Fixes https://github.com/rundeckpro/rundeckpro/issues/1873
Fix ORA-01795 error when using oracle database if there are more than 1000 executions for a referenced job
The executions id list should be partitioned if there are more than 1000 ids to be included on the query. This issue happens only if using oracle database
> RUN-194: Fix errors from 1000+ Executions on Oracle Database

- rundeckapp/grails-app/domain/rundeck/Option.groovy
Fixes #6364 
A potential bugfix for #6364 - I thought it would be simpler and clearer to submit a PR with the proposed changes.
I've revised my solution as I realised that it wasn't simple to change `values` from Set to List without unintended consequences.
I've updated the code to assign `data.values` to `optionValues` at the same time as the assignment to `values`.
I've also updated public method `productValuesList()` to use `optionValues` to populate the `valuesList` if `optionValues` is set, otherwise it drops back to the default functionality of using `values` if it is set.
I'm unsure if this change will have unintended consequences due to my lack of …
> RUN-232: Job import does not preserve option value ordering

- setversion.sh
Checked in with @gschueler and it seems like we no longer need to use this old release number argument. I removed it, so as to simplify script usage.
> RUN-190: Remove old release version arg from setversion.sh

- rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy
- rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
- rundeckapp/src/test/groovy/rundeck/controllers/EditOptsControllerSpec.groovy
enh, sort list of plugins by key in order for easy readability.  Add a test for the controller method
add groovy sort closure to collection used to display plugin list
> RUN-63 and RUN-155: Fixes Sort list of plugins by key order.

- docker/official/remco/templates/jaas-loginmodule.conf
For issue https://github.com/rundeck/rundeck/issues/7160
skip bindDn setting if the env var is not set for jass login module template
> RUN-252: Optional BindDN in JAAS login module template for Docker Image

- rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/NavBar.vue
Fixes #7188 
At various zoom levels `offsetHeight` and `scrollHeight` on the Nav Bar would be off by one in the positive even though no overflow was occurring. This would cause the overflow logic to place all items in the overflow container.
* The overflow check has been changed to look at the difference between the two and react if it becomes negative. In testing this appears to work at all zoom levels.
When removing an item from the overflow container no further overflow checks were made. In various circumstances this could cause one to be moved and no more even though there was more room for them.
* After moving an item out of the overflow container the overflow check is scheduled again on the next animation frame
The NavBar story in Storybook can be used reproduce this and check the …
> RUN-285: Fix navbar overflow during zoom

- rundeckapp/grails-spa/packages/ui-trellis/src/components/containers/copybox/CopyBox.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/components/inputs/Switch.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/utilities/Clipboard.ts
Fixes #7195
[RUN-288]
If the connection is insecure(not https) and not local in FireFox the navigator clipboard will not be present or `writeText` will not be present.
* Moves copying to clipboard to a utility method and adds a fallback method.
In FireFox the OS style for the checkbox input in our Switch component is still rendered on screen.
* Adds `appearance: none;` to hide the OS styles.
Storybook in UI Trellis can be used to verify both fixes:
* Containers -> Copy Box
Access Storybook via a host other than `localhost` over an insecure connection.
* Inputs -> Switch
View with FireFox.
[RUN-288]: https://pagerduty.atlassian.net/browse/RUN-288
> RUN-288: Fix copybox to work if connection is insecure

- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
fixes https://github.com/rundeckpro/rundeckpro/issues/1678
When a job is edited using the instance of the cluster that does not own the job and this instance becomes the owner after editing, the takeout message is sent to itself, then the owner never removes it from the schedule in quartz. 
Also, after a job is edited and saved, the remote execution node is assigned twice and then, two takeout messages are sent.
Another problem found was that, when unassigning the job from a schedule, the schedule was not being removed because scheduling at the project level does not change the `scheduled` attribute of ScheduledExecution to `true`. Therefore, if another instance of the cluster unassignee the job, the instance that owns it will not …
> RUN-165: Fix issue when scheduled jobs runs twice in a cluster

- rundeckapp/grails-app/assets/javascripts/optionEditKO.js
- rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
- test/selenium/src/pages/jobCreate.page.ts
Fixes https://github.com/rundeckpro/rundeckpro/issues/1899
> RUN-260: Fix/issue 1899 Wrong value after changing option type

- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
Retrieve JobComponent values when copying job and add it to the model. fix rundeckpro/rundeckpro#1764 fix run-260
bugfix.  Copy Job did not copy values for JobComponents.  
In the copy method, Job Component Values are retrieved from job being copied from and set in model returned to view
N/A
> Job tags not copied when duplicating job 

- rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/PluginControllerSpec.groovy
Updated the PluginController.installPlugin() action to fail and return an error if the feature flag is enabled
> Add plugin security feature check to installPlugin endpoint

- rundeckapp/grails-spa/packages/ui/src/components/project-picker/main.ts
Fixes #7214
The new project picker introduced in `3.4.0` does not take advantage of the `gui.startpage` setting which controls the project's homepage.
Updated to use the special endpoint `/?projectName=`. This endpoint will `302` redirect to the appropriate project page.
This setting can be set to `jobs` to test: https://docs.rundeck.com/docs/administration/configuration/gui-customization.html#rundeck-gui-startpage . A new Docker config option was recently merged `RUNDECK_GUI_STARTPAGE` which drives this.
After changing the setting to `jobs` selecting a project from the picker should land you on the Jobs screen.
> RUN-354: Update project picker to respect GUI startpage setting

- rundeckapp/grails-app/migrations/changelog.groovy
- rundeckapp/grails-app/migrations/core/Tag-3.4.4.groovy
- rundeckapp/grails-app/migrations/core/WorkflowStepVARCHARtoNVARCHAR.groovy
fixes https://github.com/rundeckpro/rundeckpro/issues/1970
Cannot use Unicode Characters on Rundeck using MSSQL database. (see description [here](https://github.com/rundeckpro/rundeckpro/issues/1970) )
This PR include a migration to change the column type of `adhoc_local_string` from `VARCHAR` to `NVARCHAR` to accept Unicode characters.
> RUN-366: Migration to change adhoc_local_string column type from VARCHAR to NVARCHAR on SQL Server database.

- grails-webhooks/grails-app/controllers/webhooks/WebhookController.groovy
- grails-webhooks/src/test/groovy/webhooks/WebhookControllerSpec.groovy
fixes https://github.com/rundeckpro/rundeckpro/issues/1935
Project based ACLs dont grant access to webhook actions
Changed method to get authorization context for subject and project to consider project based ACLs
> RUN-324: Grant webhooks permissions with project based ACL

- rundeckapp/grails-app/views/execution/_wflistitemContent.gsp
- rundeckapp/grails-spa/packages/ui-trellis/src/components/utils/AceEditor.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/components/utils/AceEditorVue.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/stores/Plugins.ts
- rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/rundeck-icon.scss
Changes in support of rundeckpro/rundeckpro#1996
**Updates plugin store to use provider name as id key**
The previously used `id` field is not unique for all provider types.
**Add fuller workflow item JSON to workflow editor steps in GSP**
This makes it easier to get step information without scraping or hitting the internal ajax editor API.
**Remove media query for icons**
Pixel ratios between 1 and 2(like 1.5) were not getting the hi-res icon images. This update lets the browser scaling handle it so the icons are always crisp.
**Optional AceEditor identifier**
Sets the id on the main div. Allows attaching to the editor session by externally by id.
> Enhancements and fixes in support of workflow editing

- rundeckapp/grails-spa/packages/ui-trellis/theme/scss/paper/_variables.scss
Font fill was white with an alpha causing a colored "haze" effect on colored buttons and reducing contrast on black buttons.
**Before**
**After**
> RUN-373: Change font fill to solid white

- rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
- rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ProjectController2Spec.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
Fix #7238 
Update auth checks to check `configure` or `admin`, and not require both.
> RUN-374: Fix SCM/Node Sources configuration auth checks to be less restrictive

- rundeckapp/grails-spa/packages/ui-trellis/theme/scss/bootstrap/stylesheets/bootstrap/_alerts.scss
Fix css issue; the close button on dismissible alerts is positioned wrongly and overlaps the border.
Remove the -21px right positioning. 
Before:
After:
> Fix: dismissible alert x button too far right

- rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
- rundeckapp/grails-app/views/common/_queryFilterManagerModal.gsp
- rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
fixes #7249 
When creating a job and setting up the node filter, the node filter value gets duplicated
Removed a template that include hidden fields that duplicated the filter string. Also, this PR fix an issue that doesn't allow saving more than one filter
> RUN-384: Fix duplicated node filter after save a job

- rundeckapp/grails-app/domain/rundeck/Notification.groovy
- rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/notification/DummyWebhookNotificationPlugin.groovy
- rundeckapp/src/test/groovy/rundeck/NotificationSpec.groovy
- rundeckapp/src/test/groovy/rundeck/ScheduledExecutionSpec.groovy
fixes https://github.com/rundeckpro/rundeckpro/issues/1830
The payload format and http method was not being included when importing a job
Correction in property name and adjustments in imported data for notification creation
> fix to include payload format and http method on notification importing

- grails-webhooks/grails-app/controllers/webhooks/WebhookController.groovy
- grails-webhooks/src/test/groovy/webhooks/WebhookControllerSpec.groovy
fixes https://github.com/rundeckpro/rundeckpro/issues/2015
Project based ACL to grant permission to delete awebhook was not working
Changed method to get authorization context for subject and project to consider project based ACLs
> Grant permission to delete webhook with project based ACL.

- core/src/main/java/com/dtolabs/rundeck/core/execution/impl/local/LocalFileCopier.java
- core/src/main/java/com/dtolabs/rundeck/core/execution/impl/local/LocalNodeExecutor.java
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/impl/local/LocalFileCopierSpec.groovy
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/impl/local/LocalNodeExecutorSpec.groovy
adding a flag to disable the Local Execution and Local File Copier
adding a system environment called  `RUNDECK_DISABLED_LOCAL_EXECUTOR`
> RUN-181: add a flag to disable Local Execution and Local File Copier

- rundeckapp/grails-app/assets/javascripts/user/profile.js
- rundeckapp/grails-app/views/user/_token.gsp
All modals are now attached to the `body` in `base.gsp` so that they will always display above other site content correctly.
The user token JS code was using jQuery DOM traversal to associate the modal data with the row. This has been replaced by keying both with the token UUID.
> Fix token management delete and create modals

- core/src/main/java/com/dtolabs/rundeck/core/jobs/JobReference.java
- rundeckapp/grails-app/services/rundeck/services/JobReferenceImpl.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
fixes https://github.com/rundeckpro/rundeckpro/issues/2093
Rundeck is not able to handle scheduling after renaming job making the job run multiple times for the same schedule
Was included the original job/group name on the job take over message in order to handle scheduling after renaming a job
> RUN-465 Fixes duplicated job scheduling after renaming job/group

- rundeckapp/grails-app/views/scheduledExecution/_show.gsp
- rundeckapp/grails-app/views/scheduledExecution/show.gsp
- rundeckapp/grails-spa/packages/ui/src/components/copybox/main.ts
- rundeckapp/grails-spa/packages/ui/vue.config.js
Enhancement: Provides user the ability to click to copy job id
Include Copy Box Vue  component to Job page
> Add Copy Box for job id

- .circleci/config.yml
It should always trigger the main packaging-core branch.
> reference main packaging-core branch always

- core/src/main/java/com/dtolabs/rundeck/core/authentication/Token.java
- rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
Adds a Token principal to auth Subject to enable behaviors based on token type.
> RUN-478: add found Token principal to subject when used for API requests

- gradle.properties
Our current version of spring-security (5.1.11) uses an old version of nimbus-jose-jwt (6.0.2) which has a critical CVE. We need to go to spring-security 5.2 to get to the patched version of nimbus (7.9)
This change builds, tests, and runs locally successfully.
> RUN-482: Bump to spring-security 5.2.0

- rundeckapp/grails-app/assets/javascripts/application.js
This is a new version of Rundeck/rundeck#7247, which brings in those changes and resolves merge conflicts that couldn't be fixed without access to @rijnier's fork. Their original text from the previous PR is as follows:
>This change fixes #7149
The new version of the Ace editor (introduced since 3.3) no longer supports the old method of resizing the editor window.
I've also added minLines so you don't have a single line editor when the textfield is empty.
> RUN-387: fix: new Ace editor supports min/maxLines for auto sizing of editor

- rundeckapp/grails-app/assets/javascripts/scheduler.js
fixes https://github.com/rundeckpro/rundeckpro/issues/2105
When scheduling a job via `Run Job Later` feature, the job runs immediately (does not wait for the scheduled time)
The parameter `RunAtTime` should be included on the request
> RUN-479: Including runAtTime parameter on Run Job Later feature

- rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy
https://docs.rundeck.com/docs/administration/configuration/config-file-reference.html#logout-behaviors talks about being able to use both a relative and absolute URL.
I therefore expected to be able to use an absolute redirectUrl in preauthenticated too. However, it just appended the URL in a slightly broken fashion.
As an example, given you are on https://rundeck.example.com/ and `rundeck-config.properties` contained the following properties:
```
rundeck.security.authorization.preauthenticated.redirectLogout=true
rundeck.security.authorization.preauthenticated.redirectUrl=https://auth.example.com/logout
```
When clicking logout in the top right menu of Rundeck, you would be redirected to …
> Allow absolute redirectUrl in preauthenticated

- build.yaml
Issue:
[#2147](https://github.com/rundeckpro/rundeckpro/issues/2147)
PR:
[py-winrm-plugin#78](https://github.com/rundeck-plugins/py-winrm-plugin/pull/83)
Bugfix description:
Added override option to plugin configuration for choosing whether overriding or appending to remote files.
> upgrade to pywinrm plugin 2.0.15

- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/grails-app/views/scheduledExecution/show.gsp
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
fixes https://github.com/rundeckpro/rundeckpro/issues/1895
When changing the scheduling and saving the job very close the next execution of the old scheduling (like 2 or 3 seconds), the job  will execute considering the old scheduling until the take over message is handled.
Since the scheduling changes takes effect after the job take over message is processed (if cluster mode is enabled), a message is shown on the Gui to warn user that the scheduling will take effect after few seconds.
> RUN-493 Add warning message if changing job scheduling on a cluster

- rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
editOption gsp template was doing an unnecesary html-encoding to the option default value so it was removed.
Fixes:
[Job Option default value bad parsing #2104](https://github.com/rundeckpro/rundeckpro/issues/2104)
[rundeckpro/rundeckpro #2112](https://github.com/rundeckpro/rundeckpro/issues/2112)
Test:
A test will be added to the qa framework to check that the option data is rendered corretly.
> RUN-513: option default value bad parsing

- rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_sidebar-and-main-panel.scss
- rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_view.scss
Enhancement: Adjust page layouts to prevent headers that block visibility of the main content
Move from Grid to absolute positioned items, and enable scrolling to the full main content
> add classes to fix layout

- .circleci/config.yml
- scripts/circle-helpers.sh
there will always be a latest set of artifacts so that packaging-core and packaging-pro can successfully build without rundeck context
> Post main branch generated artifacts to a latest bucket in S3

- rundeckapp/grails-app/controllers/rundeck/interceptors/DefaultInterceptorHelper.groovy
- rundeckapp/src/test/groovy/rundeck/interceptors/DefaultInterceptorHelperSpec.groovy
When attempting to access users assets in a sub directory eg /user-assets/sub1/asset1.png
Grails does not populate the controllerName correctly so the interceptor helper is
blocking the attempt with a 403. This changes works around the problem by
adding a prefix check for /user-assets if they have been enabled by the user.
> Fix issue serving user assets

- rundeckapp/build.gradle
- testbuild.groovy
Update log4j dependency to 2.15.0 to prevent CVE-2021-44228
update version
> Fix #7424 update log4j dependency

- rundeckapp/grails-app/views/framework/nodes.gsp
Bugfix: Save button on Node Filter is not functional
Return function to node filter save button
>  Node Filter Save Button

- rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/EditOptsControllerSpec.groovy
Now we do a shift right before inserting the duplicated option.
Fix:
https://github.com/rundeckpro/rundeckpro/issues/2037
> RUN-541: Fix: Job options misbehaviors when reordering/duplicating

- rundeckapp/grails-app/services/rundeck/services/UserService.groovy
- rundeckapp/src/main/groovy/org/rundeck/security/RundeckJaasAuthenticationSuccessEventListener.groovy
- rundeckapp/src/test/groovy/org/rundeck/security/RundeckJaasAuthenticationSuccessEventListenerTest.groovy
Issue:
https://github.com/rundeckpro/rundeckpro/issues/2155
Fixed problem when Rundeck tried to save ldap information at the DB.
> RUN-533: Fixed ldap user information on profile

- rundeckapp/grails-app/views/menu/_projectExportForm.gsp
Bootstrap extracts the modal from its container and puts it in another. Thus, when the modal shows up it has no parent form to submit.
Now, there's a script that copies the form data into the modal before bootstrap shows it.
Fix: [Export to another instance issue](https://github.com/rundeckpro/rundeckpro/issues/2187)
> RUN-548: Export to another instance fix

- rundeckapp/grails-app/services/rundeck/services/FileUploadService.groovy
- rundeckapp/src/test/groovy/rundeck/services/FileUploadServiceSpec.groovy
fixes https://github.com/rundeckpro/rundeckpro/issues/2110
If a job has a file type option and retry execution is enabled, the execution get stuck in running state and not attempt to retry since the file is marked as used and then it is deleted on the first attempt
If the execution should retry if it fails, the file should be kept to be used on subsequent attempts
> RUN-519 Allows file option uploaded for execution to be reused when retry execution feature is enabled.

- rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelect.vue
Fixes RUN-405
Root cause:
- The `View All Projects` is rendered as an <a> element with the attribute `href` set to the URL of the current project. When clicked the default behavior of <a> tag got triggered instead of executing the registered javascript handler. This causes the page to always be rendered with an active project so the sidebar is always displayed.
- There is another issue with the ProjectSelect Vue template definition. The allProjectsLink `eventHandler` used a non-existent handler name `handleSelectAll`. Since this event never got triggered due to the above issue, so it was undetected until this fix was applied.
Solution:
- Prevent the default behavior of the <a> tag by using Vue modifier e.g. change `@click` to `@click.prevent`.
- Change the select all projects event …
> Fixes Project Nav Remains when View All Projects link is clicked #RUN-405 

- rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelect.vue
this is an enhancement to add Create Project button into project picker. used the same color and styling as before.
[https://pagerduty.atlassian.net/browse/RUN-120](url)
> RUN-120 Added Create Project button into Project Picker

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- core/src/main/java/org/rundeck/app/components/jobs/JobQueryInput.java
- rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceIntegrationSpec.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ScheduledExecutionQuery.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
fixes https://github.com/rundeck/rundeck/issues/5780
ScheduledExecutionService was decoupled from its consumers:
* The pagination setup was moved from ScheduledExecutionService to MenuController _(excepting the offset=0 for compatibility)_.
* Added a new test for pagination on MenuController.jobs() endpoint.
* Added the alternative to disable pagination for api _(it will ignore pagination parameters if the `rundeck.api.paginatejobs.enabled` property is set to false explicitly)_
* Cleaned just a little some old code.
Examples:
With rundeck GUI pagination config:
rundeck.gui.paginatejobs.enabled=true
rundeck.gui.paginatejobs.max.per.page=3
(All the 7 jobs are returned)
Pagination parameters work perfectly fine (decoupled from others configuration), unless `rundeck.api.paginatejobs.enabled` …
> RUN-565: Fix/issue 5780 api gui pagination

- rundeckapp/src/main/groovy/org/rundeck/security/RundeckJaasAuthenticationSuccessEventListener.groovy
- rundeckapp/src/test/groovy/org/rundeck/security/RundeckJaasAuthenticationSuccessEventListenerTest.groovy
Issue:
Rundeck cannot sync the name and last name from user.
Changed property name way to obtain the correct value from rundeck-config.properties
> RUN-611: Ldap name and last name cannot sync

- docker/official/Dockerfile
- docker/ubuntu-base/Dockerfile
This is an enhancement as required by 
[RUN-236 Upgrade rundeck unbuntu image to version 20.04](https://pagerduty.atlassian.net/browse/RUN-236)
Update the docker/ubuntu-base/Dockerfile to use ubuntu:20.04 official image as its base
Milestone: 4.0.0
Rundeck offical image Built and Verified:
> RUN-236: Make official ubuntu 20.04 image the base image of rundeck ubuntu-base 

- grails-webhooks/grails-app/controllers/webhooks/WebhookController.groovy
- grails-webhooks/grails-app/domain/webhooks/Webhook.groovy
- grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
- grails-webhooks/src/main/groovy/webhooks/WebhooksGrailsPlugin.groovy
- grails-webhooks/src/main/groovy/webhooks/authenticator/AuthorizationHeaderAuthenticator.groovy
- grails-webhooks/src/main/groovy/webhooks/authenticator/WebhookAuthenticator.groovy
- grails-webhooks/src/test/groovy/webhooks/WebhookControllerSpec.groovy
- rundeckapp/grails-app/migrations/core/Webhook.groovy
- rundeckapp/grails-spa/packages/ui-trellis/src/components/help/HelpIcon.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/stores/Webhooks.ts
- rundeckapp/grails-spa/packages/ui/src/pages/webhooks/i18n.js
- rundeckapp/grails-spa/packages/ui/src/pages/webhooks/views/WebhooksView.vue
POSTs to webhooks can now be authenticated, by a value specified in the Webhook data or a value from the key store.
> RCLOUD-181: Add the ability to authenticate webhooks using the Authorization header

- rundeckapp/grails-spa/packages/ui-trellis/src/components/navbar/NavBarDrawer.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/components/utility-bar/Popper.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/components/utils/OffsetPagination.vue
Fix some errors in browser JS console due to Vue, e.g on Execution/show page:
* error about `data` must be a function
* error about `currentPage` of OffsetPagination component
---
Console errors:
```
vue.js?compile=false:635 [Vue warn]: The "data" option should be a function that returns a per-instance value in component definitions.
```
```
vue.js?compile=false:635 [Vue warn]: Property or method "currentPage" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.
found in
---> <OffsetPagination> at …
```
> RUN-632: Fix vue console errors

- docker/official/remco/templates/rundeck-config.properties
This is a small enhancement to add a few ENV vars as described here https://docs.rundeck.com/docs/administration/configuration/docker.html#environment-variables
Let me know if anything else is needed!
> RUN-648: Add some ENV variables to Docker Remco mapping

- rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
- rundeckapp/src/test/groovy/rundeckapp/BootStrapTest.groovy
This PR will ease the rotation of tokens used to authenticate to
the Rundeck API.
Currently, the token used by the clients of the Rundeck API must be in
sync with the one configured in the static file of Rundeck, which
creates a service disruption.  With this commit, the clients will be
able to switch to a new token without disruption.
A later commit in rundeck/docs will mention this feature in the
documentation.
> RUN-626: Allow several tokens per user for API authentication

- rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
- rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Fix an issue where `execution/follow` URL might be used instead of `execution/show`, but some UI code expects to see `execution/show` to drive certain behaviors.
* Replace all cases where URL generation uses 'follow' and use 'show' instead
* Update 'follow' action to redirect to 'show'
* Remove authZ check on 'follow' since it will redirect to authorized 'show' action
Some UI plugins were not working correctly on execution show page, because they were not detecting the correct route due to use of 'follow' instead of 'show'.
> RUN-631: Remove execution 'follow' action which duplicates 'show'

- test/selenium/src/__tests__/selenium/edit-job.test.ts
- test/selenium/src/pages/jobCreate.page.ts
- test/selenium/src/pages/jobShow.page.ts
A clear and concise description of the bug you are fixing (reference issue number), or enhancement you are implementing.
This expands the test suites and selectors to test everything on the Details pane of the Job Edit page. It also changes the order and method of checking the changes on the Job Show page. It does this reliant on the synchronous execution of `describe` blocks, which causes need for only one load of the edit page, and one of the show page.
I considered not adding the optimizations, but I didn't want to continue down the path of going between edit and show pages for each individual test.
Add any other …
> RUN-586: Expand and optimize Job Edit Details tests

- test/selenium/src/__tests__/selenium/edit-job.test.ts
- test/selenium/src/pages/jobCreate.page.ts
- test/selenium/src/pages/jobShow.page.ts
This PR adds additional selectors for elements on the Job Edit Nodes tab, to improve the ability to add tests later.
Simply added additional selectors
N/a
This change was forked from work in RUN-585, so it should not be merged until that PR, #7498, is merged.
> [MERGE AFTER #7498] RUN-629: Improve Job Edit Nodes Tests

- gradle.properties
- rundeckapp/build.gradle
- rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
- rundeckapp/grails-app/init/rundeckapp/Application.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/api/model/SystemInfoModel.groovy
enhancement.  Introducing generation of openapi documentation automatically through build process.  
Using  micronaut-openapi to generate documentation for rundeck open api methods.  Requires use of Micronaut and Swagger annotations.  Grails urls defined in UrlMappings.groovy takes precedence.  Documentation currently created in the {rundeck_home}/rundeckapp/build/classes/groovy/main/META-INF/swagger
spring-fox.  Micronaut is cleaner
Current api documented in this pull request
:
> OpenAPI documentation generator - RUN-668

- rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy
- rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
- rundeckapp/grails-app/views/user/login.gsp
- rundeckapp/src/test/groovy/rundeck/controllers/UserControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
**Is this a bug fix or an enhancement? Please describe.**
Enhancement for RUN-603
The original design of the Error action only displays a fixed message for any user login failure. By adding logic to retrieve error messages from query parameters we can make the error page display custom error messages. It provides a better user experience e.g. for RUN-603 we can display the specific rate-limiting error to end-users. 
Currently, this enhancement is only used by the enterprise version for the feature of login rate-limiting.
> RUN-603: Enhance UserController to support more flexible error message

- rundeckapp/grails-app/controllers/rundeck/interceptors/ApiAccessInterceptor.groovy
- rundeckapp/grails-app/controllers/rundeck/interceptors/ApiVersionInterceptor.groovy
- rundeckapp/grails-app/controllers/rundeck/interceptors/AuthorizationInterceptor.groovy
- rundeckapp/src/test/groovy/rundeck/interceptors/ApiAccessInterceptorSpec.groovy
- rundeckapp/src/test/groovy/rundeck/interceptors/ApiVersionInterceptorSpec.groovy
- rundeckapp/src/test/groovy/rundeck/interceptors/AuthorizationInterceptorSpec.groovy
Fix an issue (seen in CI) where API requests before server fully starts prevent all API requests in the session, when using username/password API login.
* Handle exception caused by missing API response marshaller configuration before server has completed startup by responding with 503 (Service Unavailable)
* Fix issue where "error/fiveHundred" response caused by exception would block API access for the session when using username/password login
* Additional change was necessary, due to order of Interceptors: ApiVersionInterceptor should not return false immediately, but adds a request attribute, so that the SetUserInterceptor executes cleanly and sets up appropriate session data about …
> RUN-695: fix issue with API access before server fully starts

- rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Bugfix:
nested groups are not displayed by default.
the check of parameter `rundeck.gui.realJobTree` must return true by default to have the same behavior than Rundeck 3.x
with the grails 5 migration that behavior was changed.
> RUN-705: nested groups are not displayed by default

- rundeckapp/grails-app/controllers/rundeck/interceptors/AuthorizationInterceptor.groovy
- rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
- rundeckapp/src/test/groovy/rundeck/interceptors/AuthorizationInterceptorSpec.groovy
- rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
- test/api/unauthorized-test-xml.sh
- test/testdeck/src/commands/TestCommand.ts
- test/testdeck/src/util/RundeckAPI.ts
Some more updates to API responses and testdeck wait for server startup
* `request.apiVersionStatusNotReady` state should be processed before unauthorized response
*  reason: otherwise the 503 service unavailable response is not sent correctly just 403
* SetUserInterceptor: clause checking auth token should only be applied if a token is in the request
* reason: request state without auth and without a token still falls into that clause
* for api requests which are unauthenticated and have no token, use the `request.invalidApiAuthentication` to indicate invalid auth state via the AuthorizationInterceptor
* AuthorizationInterceptor: default response format was changed to json, xml will be used if Accept header is present
* update …
> RUN-715: CI updates 2

- rundeckapp/grails-app/assets/javascripts/storageBrowseKO.js
- rundeckapp/grails-app/controllers/rundeck/controllers/StorageController.groovy
- rundeckapp/grails-app/views/menu/storage.gsp
- rundeckapp/src/test/groovy/rundeck/controllers/StorageControllerSpec.groovy
- Fixes RUN-707. It's an security enhancement by obsolete file upload feature for import storage key. 
- The uploading file feature is replaced by read the file content in the client-side through FileReader API so there is no file uploaded to the server. 
- We considered obsolete the file upload feature completely. But it will change the user experience significantly. To avoid confusing user we choose the way with minimum impact to the user experience.
There is no noticeable UI change.
> RUN-707: Use-Client-Side-FileReader-API-Load-Content-From-File

- rundeck-authz/rundeck-authz-core/src/main/java/org/rundeck/core/auth/app/RundeckAccess.java
- rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ExecutionControllerSpec.groovy
Change auth required for execution mode toggle, to allow `app_admin` as well as `ops_admin` and `admin`.
> RUN-698: execution mode change should allow app_admin authorization

- .circleci/config.yml
Use Circle Env var to set gradle cache name
> Update gradle caching to use dynamic version

- rundeckapp/grails-spa/packages/ui/src/components/job/schedule/ScheduleEditor.vue
This is a bug fix for (https://github.com/rundeckpro/rundeckpro/issues/2271) and RUN-716
1. The root cause of the bug:
When updating the crontab with the formatted string, a parameter useCrontabString must also be provided to indicate the crontab string should be used to set the schedule. But this parameter is missing so the server-side program always gets a NULL value.
```
// ScheduledExecution.groovy
// Line #816
if(params.crontabString && 'true'==params.useCrontabString){
//parse the crontabString
crontabString = params.crontabString
parseCrontabString(crontabString)
return
}
```
Adding a hidden field of useCrontabString can solve the problem with minimum impact.
2. Another hidden bug …
> RUN-716: Fix the crontab update issue

- rundeckapp/grails-spa/packages/ui/src/components/job/schedule/ScheduleEditor.vue
This is a bugfix. The simple schedule editing form used a wrong form input parameter name for `minute` so the change won't be updated on the server-side
Correct wrong form input field name from `minutes` to `minute`
> RUN-749: Correct the parameter name of minute

- rundeckapp/grails-spa/packages/ui/src/components/job/schedule/ScheduleEditor.vue
- rundeckapp/grails-spa/packages/ui/src/pages/job/editor/i18n.js
Restores a user affordance that provides information about what crontab section is selected.
> RUN-767: restore crontab section hint information in editor

- rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/WorkflowControllerSpec.groovy
Issue:
https://github.com/rundeckpro/rundeckpro/issues/2267
When the property keepgoingonsuccess is not sent by the front-end this is set as false.
> RUN-708: Cannot uncheck the "Keep going on success" option for error handler

- core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionLogger.java
Typo fix
Log level debug is equal to 4 according to the [CONSTANTS.DEBUG_LEVEL](https://github.com/rundeck/rundeck/blob/8ea3bc0f019c0ad9fddeac3550639465d139d3f8/core/src/main/java/com/dtolabs/rundeck/core/Constants.java#L39).
> Update Javadoc in ExecutionLogger.java

- rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
Fix: https://github.com/rundeckpro/rundeckpro/issues/2273
Used to use systemLoadAverage but this always return a negative value in windows.
Now changed this to work with getSystemCpuLoad() which works perfectly on windows and linux.
> RUN-786: Fix: CPU usage showing negative value

- rundeckapp/grails-app/assets/stylesheets/github-markdown.css
- rundeckapp/grails-spa/packages/ui-trellis/src/components/first-run/FirstRun.vue
this is a fix for markdown table. visibility in dark mode. [link to issue](https://github.com/rundeck/rundeck/issues/7380)
> RUN-500: Improve dark-mode markdown table visibility

- rundeckapp/grails-app/assets/javascripts/_package-manager/package.json
> Fixes: ERR_PACKAGE_PATH_NOT_EXPORTED

- build.yaml
- cve-suppress.xml
- test/docker/dockers/rundeck/data/blocklist.yaml
- testbuild.groovy
This is an enhancement to use the new [Rundeck-published ansible-plugin](https://github.com/rundeck-plugins/ansible-plugin/pull/310)
Simply points at the new paths, and uses 3.2.0, under which we will publish the changes
N/a
* The release that contains this code should have release notes or otherwise inform the user that they will need to update to the new migrated ansible plugin.
> RUN-671: Ansible plugin moved to `rundeck-plugins` GitHub Org

- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/grails-app/init/rundeckapp/init/servlet/JettyServletContainerCustomizer.groovy
fixes #7605
This PR fixes redirecting to http if config property `server.useForwardHeaders` or sys config `rundeck.jetty.connector.forwarded` is true
The useForwardHeaders attribute on JettyServletWebServerFactory was not being configured as apparently part of the code had been removed
Looks like this code was removed a long time ago so I was trying to figure out why it seems to be working in 3.4.x versions
> RUN-794: Putting back config attribute useForwardHeaders to avoid https redirecting back to HTTP

- rundeckapp/grails-app/views/common/_mainbar.gsp
Enhancement for name label in mainbar. 
Label design was discussed with Miguel.
> RUN-831 Improve Name Label Size in Mainbar

- rundeckapp/grails-spa/packages/ui-trellis/src/components/widgets/project-select/ProjectSelect.vue
Bugfix: Titles were breaking in project picker if they exceeded the amount of space allotted in the project picker. 
Hide the overflow and cap the end of the line with an ellipses
> RUN-830: Add Ellipses to Long Titles in Project Picker

- rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
- rundeckapp/grails-spa/packages/ui/src/components/job/schedule/ScheduleEditor.vue
- rundeckapp/grails-spa/packages/ui/src/pages/job/editor/SchedulesEditorSection.vue
fix: missing check for heuristic about whether crontab string should be shown by default on Job edit page
> RUN-766: fix schedule crontab string should be shown in job editor

- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Follow up to #7641 to add tests for timeout config
> RUN-832: Add tests for loadOptionsRemoteValues timeout config

- rundeckapp/grails-app/views/menu/_projectExportForm.gsp
A described here: https://github.com/rundeckpro/rundeckpro/issues/2478 there was an error while we try to export a project to other instance of rundeck when the checkbox "preserve uuid" was selected. Technically, the problem was the checkbox used in the form, which was not getting the given value.
**Solution**
What we made was change the current html tag to a built-in GSP component named "g:checkbox", and bind the component to the actual param that will travel to the controller.
**Exhibits**
After the fix, we are able to see the export process result.
**QA Framework tests**
https://github.com/rundeckpro/rundeck-tester/pull/146
> RUN-845: Export to instance not working when preserving UUID

- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Handling special chars when loading remote URL option.
Using clean URL when assembling the URI object and use parsed credentials (URL object) when assembling the basic auth header
Fix: https://github.com/rundeckpro/rundeckpro/issues/2188
> RUN-688: Handling special characters in user:password

- rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ProjectController2Spec.groovy
Fix: https://github.com/rundeckpro/rundeckpro/issues/2129
It was an implementation issue, this cli endpoint wasn't calling the `frameworkService.handleProjectSchedulingEnabledChange` method.
Added private method `checkScheduleChanges(project, propertiesBeforeChange, propertiesAfterChange)` in the ProjectController, so it can be called from a method that makes changes on project properties.
> RUN-843: Fix: Project Scheduling not working properly

- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
Fix: https://github.com/rundeckpro/rundeckpro/issues/2338
ExecutionController was setting default view value in the url using a query parameter instead of a fragment reference (what the `/execution/show` page expects)
> RUN-799: Fix: GUI always displays "nodes" view ignoring set default value

- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/DelegateStorageTree.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/StorageTreeCreator.groovy
- rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/tree/DelegateStorageTreeSpec.groovy
- rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/tree/StorageTreeCreatorSpec.groovy
add delegate storage tree that functions the same on startup, but creates a new storage tree on a config refresh event if a storage prop is changed
> RUN-620: Fix Requirement for Restart When Key Storage Prop is Updated

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- rundeckapp/grails-app/conf/application.groovy
- rundeckapp/grails-app/conf/application.yml
- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/grails-app/services/rundeck/services/actuator/RundeckReadinessHealthIndicatorService.groovy
Enhancement
Configure Spring Boot Actuator Health Indicator out-of-box feature to expose liveness and readiness endpoints. Manually configure DataSourceHealthIndictor to fit into the Rundeck application.
A fully in-house developed solution could be an option but it cost too much effort unnecessarily when we already have a standard Spring Boot out-of-box framework.
How to test it in a local environment:
1. The default configuration has already been set in `application.yml` file under the rundeckapp/grails-app/conf/ folder.
2. By default, the Health indicator endpoints are disabled. There are a few ways to turn it on:
- Use …
> RUN-740: Expose spring actuator health check endpoints

- rundeckapp/grails-spa/packages/ui/src/components/server-identity/main.js
Fix: https://github.com/rundeckpro/rundeckpro/issues/2501
ServerIdentity component was looping over an HtmlCollection affecting the collection size during iterations.
Solution:
create an array from the collection and iterate through its elements.
> RUN-866: RUN-829: Fix: Cluster manager hostname disappears

- core/src/main/java/org/rundeck/app/grails/events/AppEvents.java
- rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
Enhancement: updates grails project config change event
* event includes `changedKeys` set of changed/removed/added key names
> RUN-796: internal project config change event includes changed keys info

- grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/XFOSecurityHeaderProvider.groovy
- grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/XXSSPSecurityHeaderProvider.groovy
Change config access to remove warnings
> RUN-833: avoid logging warnings by removing dot notation config value access

- grails-execution-mode-timer/build.gradle
Fix #7700
* remove asset-pipeline config from execution-mode-timer plugin
> RUN-877: remove asset-pipeline config from plugin

- grails-securityheaders/src/main/groovy/grails/securityheaders/SecurityheadersGrailsPlugin.groovy
- grails-securityheaders/src/main/groovy/org/rundeck/grails/plugins/securityheaders/XXSSPSecurityHeaderProvider.groovy
Fix RUN-874
* set `X-XSS-Protection: 0` by default
ref: https://owasp.org/www-project-secure-headers/#x-xss-protection
> ⚠️ Warning: The X-XSS-Protection header has been deprecated by modern browsers and its use can introduce additional security issues on the client side. As such, it is recommended to set the header as X-XSS-Protection: 0 in order to disable the XSS Auditor, and not allow it to take the default behavior of the browser handling the response. Please use Content-Security-Policy instead.
> RUN-874: Fix: XXSSP header is deprecated

- rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
Fix: https://github.com/rundeck/rundeck/issues/7670
Case Tested in: https://github.com/rundeckpro/rundeck-tester/pull/149
Solution:
Generate report items using the report's ctxProject value instead of the received params.project.
> Fix: 404 page when clicking on referenced execution from a different parent

- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Bugfix
Fix: https://github.com/rundeckpro/rundeckpro/issues/2469
**Description**
When a job was created with some defined options and is exported in a YAML or XML job, removing the option field or enforcing to an empty array (options:[]) doesn't delete the old options.
**Solution** 
Clear the job options and use the new options given on the file.
> RUN-842: Remove options when importing Job Definitions

- rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/autocomplete.scss
Fix: https://github.com/rundeckpro/rundeckpro/issues/2430
Problem
A CSS property was being changed to block when it should remain on none, that class was  "autocomplete-suggestions"
Solution
Add a the CSS property display none to the class autocomplete-suggestions
> RUN-873:Fix: bug ansible plugins dont show properly

- build.yaml
Fixes https://github.com/rundeckpro/rundeckpro/issues/2264
Updating [multiline-regex-datacapture-filter](https://github.com/rundeck-plugins/multiline-regex-datacapture-filter) log filter plugin version to the new release 1.1.0 which contains a new feature to capture multiple key-value pairs for each matched line. See PR https://github.com/rundeck-plugins/multiline-regex-datacapture-filter/pull/6
> RUN-660: Update version plugin to the new release version 1.1.0

- core/src/main/java/com/dtolabs/rundeck/core/execution/impl/local/LocalFileCopier.java
- rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
- rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
- test/api/blocklist-plugin-count-test.sh
Fix: if `local` file copier is configured for a project, GUI fails with an error message
* fix npe when a provider definition is not found
* fix `local` file copier cannot be selected as default project config for file copier
> RUN-887: Fix local file copier config error

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- rundeckapp/grails-app/assets/javascripts/menu/storage.js
- rundeckapp/grails-app/assets/javascripts/storageBrowseKO.js
- rundeckapp/grails-app/controllers/rundeck/controllers/StorageController.groovy
- rundeckapp/grails-app/views/framework/_storageBrowser.gsp
- rundeckapp/grails-app/views/menu/storage.gsp
- rundeckapp/src/test/groovy/rundeck/controllers/StorageControllerSpec.groovy
enhancement: add configuration to disable "Public Key" GUI download option
add a new flag to disable the public key GUI download option: 
````
rundeck.gui.keystorage.downloadenabled=true
````
> RUN-758: add configuration to disable "Public Key" GUI download option

- rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_tooltip-and-popovers.scss
As described in https://github.com/rundeckpro/rundeckpro/issues/2521 there was a popup blocking the user to toggle the button to disable or enable the action within the webhook.
We changed the property of the 'margin-top' from the class 'tooltip', so the popup was on correctly placed.
Pre-fix:
- Webhooks (unable to toggle)
- Job's Schedules (unable to edit the options)
Post-fix:
- Webhooks
- Job's Schedule
*NOTE: Also the 'v-tooltip' project has been migrated (as seen here: [Migration from v-tooltip 2 | Floating Vue](https://floating-vue.starpad.dev/migration/migration-from-v2.html#breaking-changes) ) and now uses 'floating-ui; instead of 'popper'.
> RUN-886: GUI bug pagerduty webhook actions toggle switch

- rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/grails-app/utils/rundeck/codecs/JobsXMLCodec.groovy
- rundeckapp/src/integration-test/groovy/rundeck/codecs/JobsYAMLCodecIntegrationSpec.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/components/JobYAMLFormat.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/components/JobXMLFormatSpec.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/components/JobYAMLFormatSpec.groovy
- rundeckapp/src/test/groovy/rundeck/JobsXMLCodecTests.groovy
- rundeckapp/src/test/groovy/rundeck/JobsYAMLCodecTests.groovy
- rundeckapp/src/test/groovy/rundeck/ScheduledExecutionSpec.groovy
- rundeckapp/src/test/groovy/rundeck/codecs/JobsXMLCodecSpec.groovy
- rundeckapp/src/test/groovy/rundeck/codecs/JobsYAMLCodecSpec.groovy
Rundeck never supported export/import of multiple notifications of the same type in the same trigger (same code since 2014).
Fix: https://github.com/rundeckpro/rundeckpro/issues/2207
Fix: https://github.com/rundeck/rundeck/issues/7496
Fix: https://github.com/rundeck/rundeck/issues/7642
It now supports import/export multiple notifications in the same trigger:
* Compatibility with previous versions is kept. 
* xml webhook element now has all its attributes inside `<webhook format='xml' httpMethod='post' urls='http://asdfasdfas.com' />`
* In yaml, use list of objects when having more than one notification of some type in a trigger.
* **If there are not 2 or more notifications of the same type in the same trigger in the job, IT WILL BE EXPORTED USING PREVIOUS VERSIONS OF YAML/XML FORMAT** …
> RUN-617: Fix/2207 import job with many same type notif

- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/JasyptEncryptionEnforcerUpdaterConfig.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/RundeckBootstrapStorageTreeUpdater.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/StorageTreeCreator.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/TreeCreator.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/TreeUpdater.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/Updater.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/UpdaterConfig.groovy
- rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/tree/JasyptEncryptionEnforcerUpdaterConfigSpec.groovy
- rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/tree/TreeUpdaterSpec.groovy
this feature will automatically re-store any key storage resource that is not encrypted,
when the jasypt-encryption converter plugin is in use. 
If the jasypt-encryption plugin is not configured, this feature will not do anything.
If it is in use, and the enabled flag is set, each resource that is not already encrypted will be restored to encrypt it.
configuration:
enabled (default false):
rundeck.feature.storageRewrite.enabled=true
base path (default "keys"):
rundeck.storage.rewrite.basePath=keys
> RUN-944: Add bootstrap storage tree rewrite feature

- rundeckapp/grails-app/views/menu/_sysConfigNavMenu.gsp
Fix: https://github.com/rundeck/rundeck/issues/7740
Added scroll bar to main menu and set to have max size of 85vh.
> RUN-941: Fix: Can't access some menu items in main menu

- build.yaml
Depends on: https://github.com/rundeck-plugins/openssh-node-execution/pull/28
> RUN-946: bump openssh plugin version to 2.0.2

- rundeckapp/grails-spa/packages/ui-trellis/src/components/execution-log/logBuilder.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/stores/ExecutionOutput.ts
- rundeckapp/grails-spa/packages/ui/src/pages/execution-show/nodeView.ts
Fix: https://github.com/rundeckpro/rundeckpro/issues/2166
Problem:
When selecting logoutput view, a listener was set to the log entry set. So when loading the nodes view first and then changing to logout view, the entry set was already loaded so there was no change to trigger the listener call.  
Fix:
Use the same logic for showing the log entries, no matter the content and only use a function `getEntriesFiltered` with the necessary filter to get the required entries.
> RUN-524: Fix: Output freezes when switching from Nodes tab to Log Output tab

- rundeckapp/grails-app/views/menu/jobs.gsp
- rundeckapp/grails-spa/packages/ui/src/components/activity/activityList.vue
Bugfix: Position of tooltip was not directly underneath the item
Bugfix: Search Icon in dashboard was not fixed to the search input
Fix position of the tooltip viewport in reference to the table row of the activity item
Fix position of search icon
> RUN-922: Adjust Tooltip position for activity list & Fix position of search icon

- rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ApiControllerSpec.groovy
"Process Automation" menu does not work if the user does not have `read` access
The `/server/info` endpoint was changed to accept request without any authorization and returns only basic info. All other info is included if the user has `read` access
> RUN-945 return basic rundeck server info without any authorization.

- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/tree/JasyptEncryptionEnforcerUpdaterConfig.groovy
- rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/tree/JasyptEncryptionEnforcerUpdaterConfigSpec.groovy
This is a bugfix. In some cases, the user updated a key in v4.2.1 could result in the key being saved as plain text but the metadata still marked it as encrypted so if upgraded to newer versions the key auto-conversion process ignored this key. This issue leads to keys saved as plain text in storage. 
To fix this issue, we add an extra check in the storage key auto-conversion process to catch this edge case. The logic is to compare the key's length with the Rundeck-content-size meta info. If those two have the same value, it means the key is plain text so we can encrypt it.
There is no other guaranteed ways to determine if the key is plain text …
> RUN-1015 Use length check to find unencrypted storage keys 

- rundeckapp/grails-app/views/user/loggedout.gsp
- rundeckapp/grails-app/views/user/login.gsp
Partially fix: https://github.com/rundeckpro/rundeckpro/issues/1868
This PR only fix property rundeck.gui.instanceNameLabelColor.  
Problem:
When using rundeck.gui.instanceNameLabelColor didn't change the color of the instance name on the login page nor on the logout page. A CSS class was missing on the HTML.
Solution:
Change the CSS class to match other views where this class worked as expected.  
**Before fix:**
**After fix:**
> instance name color fixed at login and logout

- .circleci/config.yml
- test/ci-test-docker-selenium.sh
- test/docker/dockers/tomcat/Dockerfile
Bugfix
Add the missing public key into the apt trusted list.
https://support.google.com/chrome/thread/4032170/gpg-key-error-debian-repo-for-chrome?hl=en
https://askubuntu.com/questions/13065/how-do-i-fix-the-gpg-error-no-pubkey
> RUN-1058: Add the missing public key into apt trusted list

- core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/ScriptURLNodeStepExecutor.java
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/ScriptURLNodeStepExecutorSpec.groovy
- core/src/test/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/TestScriptURLNodeStepExecutor.java
fix https://github.com/rundeckpro/rundeckpro/issues/2598
This allows to use global variables as token replacement in the url script for remote script step.
It also changes the encoding to apply just to the parameters portion of the url
> RUN-991: Fix: Incorrect "Forward Slash" parsing in File/URL Step

- rundeckapp/grails-app/domain/rundeck/Notification.groovy
- rundeckapp/src/test/groovy/rundeck/NotificationSpec.groovy
Fix: https://github.com/rundeckpro/rundeckpro/issues/2212
Problem
Exporting a job on YAML format using SCM a notification property was showing a string value when a boolean was expected. 
Solution
Change the value set from 'true' to true.
> RUN-1006: Fix Notification Property Value type when SCM Export YAML format.

- core/src/main/java/com/dtolabs/rundeck/core/Constants.java
- core/src/main/java/com/dtolabs/rundeck/plugins/nodes/NodeEnhancerPlugin.java
- rundeckapp/src/main/groovy/org/rundeck/app/services/EnhancedNodeService.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/services/EnhancedNodeServiceSpec.groovy
fix https://github.com/rundeckpro/rundeckpro/issues/2347
With this change it is possible to skip the healthstatus node enhancer when healthchecks are disabled at project level
> RUN-790: Fix bug where Health Status Enhancers affects performance with lots of nodes.

- rundeckapp/src/main/groovy/org/rundeck/app/api/model/SystemInfoModel.groovy
As seen here: https://github.com/rundeckpro/rundeckpro/issues/2587 there was a problem while displaying the max and allocated memory in system report section of Rundeck GUI.
*Solution*
We were storing a long type value in an integer variable, this caused data overflow and this in turn caused some values ​​in the system memory to be negative, which caused the error described. So we changed the data type and fixed the problem.
*Exhibits*
Pre-fix:
Post-fix:
> RUN-1000: System Report 'Allocated Memory' display broken in the GUI

- core/src/main/java/com/dtolabs/rundeck/core/storage/TypedStorageTreeImpl.java
- plugins/copyfile-plugin/src/main/java/com/dtolabs/rundeck/plugin/copyfile/CopyFileNodeStepPlugin.java
I was using the debugger to trace an error I've been stuck on all day. Once I found it, I realized it was a bug. I found the message in the java file TypedStorageTreeImpl.java, but the string is hard coded with what looks to be interpolation, but since it's a java file and you cannot do that in Java, I'm literally getting an error with the interpolation syntax instead of any data. Because of this, it would print ${path} instead of printing the actual path that variables holds. So I fixed it to work with Java syntax instead of the broken Groovy syntax it was using. I also removed a period from the end of another plugin description to fit with the style I have been implementing in the moving cloud repos ticket
> RUN-1045: fixed broken error message that appears when you have not stored a password

- rundeckapp/grails-spa/packages/ui/src/components/activity/savedFilters.vue
Fix [rundeck/rundeckpro#2183](https://github.com/rundeckpro/rundeckpro/issues/2183)
Notification added when filters already exists in the activity page.
Another card was created in order to add the test to the qa framework https://pagerduty.atlassian.net/browse/RUN-1037
> RUN-994: Show proper error message when an existing filter with same name is already present

- rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
- rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
As seen here: https://github.com/rundeckpro/rundeckpro/issues/2617 there was a problem while displaying context variables with date data.
**Solution**
There is a difference between the date format of the classes: Date and Timestamp, which variable "dateStarted" is in Timestamp and "dateEnded" is in Date. It was changing to the same format using the SimpleDateFormat class, but the most comfortable and light solution is to use the class:
**Exhibits**
_Pre-fix:_
_Post-fix_
PD: RUN-1041
> RUN-1041: Fix Date Format differences in Context Variable output

- grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
- grails-webhooks/src/test/groovy/webhooks/WebhookServiceSpec.groovy
As seen here: https://github.com/rundeckpro/rundeckpro/issues/2680, the GUI was not editing any webhooks.
The method 'saveWebhook' of the 'WebhookService', is the responsible for a) saving a new webhook, b) Importing a new webhook and c) editing an existing webhook, so, when this PR: https://github.com/rundeck/rundeck/pull/7737, prevented the import process for webhooks with the same name, also caused the error when we call 'saveWebhook' with the same name for editing.
When the 'importWebhook' is called, it puts an extra attribute inside the 'hook' object to be passed to 'saveWebhook' method, so, what we did was evaluate if that property exists in the hook in order to permit **'saving' for editing and not for importing**.
> BUGFIX RUN-1084: unable to update webhook

- build.gradle
- gradle.properties
- rundeckapp/build.gradle
- testbuild.groovy
This PR updates the following dependencies reported by twistlock scan: 
- **gson** -> `2.8.6` to `2.8.9` (CVE-2022-25647)
- **jetty** -> `9.4.44.v20210927` to `9.4.48.v20220622` (CVE-2022-2048)
Also includes the following additional updates:
- **grails** -> `5.1.7` to `5.1.8`
- **grails gradle plugin** -> `5.1.2` to `5.1.5`
> RUN-983: Package Updates to address new CVEs

- .circleci/config.yml
Fix: nightly circle build fails due to missing argument
supply missing argument
Argument requirement was added, and used in the primary build, but not scheduled nightly build
> RUN-1116: Fix nightly build: tomcat docker test requires tag argument to script

- rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
- rundeckapp/grails-app/domain/rundeck/ReferencedExecution.groovy
- rundeckapp/grails-app/services/rundeck/services/ReportService.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ExecQuery.groovy
- rundeckapp/src/test/groovy/rundeck/ReferencedExecutionSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ReportServiceSpec.groovy
fix https://github.com/rundeckpro/rundeckpro/issues/2404
This PR prevents the use of a huge "in" sentence to retrieve the referenced executions, instead it joins the tables based on the scheduled execution id. Still uses a "in" sentence but a fairly smaller one just for the allowed projects for the user performing the search (this can't be done directly in the query since the project list needs to go trough the authorization context processor first)
> improve query to get referenced executions

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Fix: https://github.com/rundeckpro/rundeckpro/issues/2644
Problem:
When a job option was set from a remote URL the retry param was not taken in count, any retry was made.
There are two ways of setting those configurations, directly on the URL or the config.properties, the ones from the config.properties weren't being used.
Solution:
On the RundeckBaseConfig add the missing params to be accessible.
Implement on the Rundeck side a retry method if something fails when trying to obtain the values from an URL.
A similar solution is already implemented on the code on rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy on the postDataUrl method
> RSE-9-job-remote-option-url-retry-connection-parameter-not-honored

- rundeckapp/grails-spa/packages/ui/src/components/activity/activityList.vue
As seen here: https://github.com/rundeckpro/rundeckpro/issues/2315 , the asynchronous calls from AJAX were causing excessive amount of logs if the user stays in certain section of the rundeck's GUI.
**The solution**
Delaying the calls, doubling the delay from call to call.
> RSE-8 Remove unnecessary GUI messages "ajax - user/login" from Rundeck

- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
fix https://github.com/rundeck/rundeck/issues/7858
now it will generate a map with name and value for the options even if they are just a simple string, this way the sortRemoteOptions method doesn't need to perform any additional validations
> RSE-45: remote options simple json sort

- core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/StringRenderingConstants.java
- rundeckapp/grails-app/assets/javascripts/jobedit.js
- rundeckapp/grails-app/views/execution/_wfitemEdit.gsp
- rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp
Add a new rendering option to support the token script expansion (@ style) in plugin attributes defined with the CODE display type rendering option.
add a new static variable in StringRenderingConstants
It can be used in the following way:
eg:
````
PropertyBuilder.builder()
.string(SCRIPT)
.title("Script")
.description("Script")
.required(true)
.renderingAsTextarea()
.renderingOption(StringRenderingConstants.DISPLAY_TYPE_KEY, StringRenderingConstants.DisplayType.CODE)
.renderingOption(StringRenderingConstants.SCRIPT_TOKEN_AUTOCOMPLETE, StringRenderingConstants.ScriptTokenAutocomplete.ENABLED)
.build()
````
or 
```` …
```
> RUN-1140: Add a new rendering option t support the token script expansion in plugins

- rundeckapp/grails-spa/packages/ui-trellis/theme/scss/pages/login.scss
As seen here: , the login view of rundeck's GUI breaks if the custom logo is too large, preventing the user to see the login button.
We've made the page "scrollable".
After fix:
> RSE-54 Customizing UI with client logo resize login form, push login button to bottom without scroll

- rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
- rundeckapp/grails-app/utils/rundeck/codecs/JobsXMLCodec.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ProjectControllerSpec.groovy
A 'try/catch' block in the importToProject method call, to add a fallback.
Pre fix:
Post fix:
> RSE-60 Failed to Import project, error 500 whitelabel on screen

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- rundeckapp/grails-app/controllers/rundeck/controllers/HelplinkController.groovy
- rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/HelplinkControllerSpec.groovy
As seen here: https://github.com/rundeckpro/rundeckpro/issues/2659, there was an inconsistency when we set the custom url for a 'helpLink' in rundeck's GUI footer.
When we go ahead and change the property ``rundeck.gui.helplink`` in ``rundeck-config.properties`` file, it changes the URL for 'help' but leaves 'Documentation' as a name for that URL, making a confusion. Exhibit:
We were harcoding 'Documentation' as a name for that customizable URL.
We've implemented between both oss and pro repos, a controller to raise a property ``rundeck.gui.helpLinkName`` from the same config file, to map the custom url name.
**OSS PR: https://github.com/rundeckpro/rundeckpro/pull/2721**
> RSE-56 rundeck.gui.helpLink property replace the doc link instead of support link

- core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/PropertyValidator.java
- core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/Validator.java
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/logging/SimpleDataFilterPlugin.groovy
- rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/logging/SimpleDataFilterPluginSpec.groovy
fix: https://github.com/rundeckpro/rundeckpro/issues/2661
The validation was added when you are trying to save a new capture pattern:
Case 1, pattern with no captured group: 
Case 2, valid pattern group with no name:
> fix: RSE-34 validation added to prevent invalid captured pattern

- rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_dropdown.scss
Minor GUI bug found during the 4.6.1 QA.
Pre-fix:
After fix:
> RSE-117 [QA 4.6.1] Minor GUI Bug on WH Dropdown

- rundeckapp/grails-app/assets/javascripts/menu/joboptionsTest.js
Behavior of hasTextfield changed with commit c29630753e6e8b8800b9c24d340473e8a936aaab
text field should not be shown for multivalue options
before: shown in UI in dev mode:
> FAIL: hasTextfield_Test: hasTextfield({"enforced":false,"multivalued":true,"secureInput":false,"hasError":true}): expected: true, was: false
> RUN-1205: fix: dev-mode: failing ui pseudo-test

- examples/README.md
This is an enhancement to notify users about the new location for [Rundeck plugin examples](https://github.com/rundeck/rundeck-plugin-examples) once it is released.
README note in the root folder of example content.
N/a
**Shouldn't be merged until https://github.com/rundeck/rundeck-plugin-examples/pull/1 is merged, and we're ready to open that example plugin repo to the public (currently internal only).**
> RUN-933: Add note about new example plugins repo

- rundeckapp/grails-app/views/menu/home.gsp
As seen here: https://pagerduty.atlassian.net/browse/RSE-140 , in rundeck OSS the MOTD never displays in the project's home page.
Knockout.Js takes certain comments as functions, there was a function that rendered the MOTD piece of code according to an array that was only populated when the 'rdpro-projectdash-detail-info' pro plugin was loaded into the app. That is, after the installation of the license.
we used an observable attribute (updatable by AJAX requests) that renders the piece of code if and only if there is readme/motd; without waiting for a pro plugin.
After the fix (tested in a compiled Rundeck OSS Instance):
NOTE: added spacing between the MOTD and README messages.
> RSE-140 MOTD (Message of the day) not displayed (Rundeck OSS)

- rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
- rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceTests.groovy
**##### Problem**
When you delete a job from the job list page, and you try to see the log output of that job executions, an empty log is shown (it only happens when deleting the job from that page)
**##### Solution**
It was added a way to know if the job was deleted, if it was, Rundeck is going to use the path stored for that job in the execution table.
fix [RSE-50](https://pagerduty.atlassian.net/browse/RSE-50)
fix https://github.com/rundeckpro/rundeckpro/issues/2354
With this fix the user can watch the logs for a specific job even when this was deleted. The previous behavior did not allow to watch those logs even though they were stored in the file system. 
Execution panel with job deleted: 
Activity screen for deleted job: 
Logs from deleted job:
This fix was also tested with a custom …
> RSE-50: fix: allowing user to see logs after the job is deleted

- rundeckapp/grails-spa/packages/ui-trellis/theme/scss/custom/nodes-embed.scss
As seen here: https://github.com/rundeckpro/rundeckpro/issues/2755, when the node name exceeds the maximum visual capacity it overlaps with the next node name horizontally.
Was the display of the list of nodes, which was 'inline-block', that display prevent the component to break into another line or have overflow (hidden).
Changing its display to block, allowing the component to overflow or break in another line.
The modified class, style this components:
- 'Create Job' page
- 'Commands' page
After the fix:
> Fix: Long node names overlapping each other

- rundeckapp/grails-app/views/framework/_editProjectForm.gsp
- rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_dropdown.scss
As seen here: , in the webhook section could be seen a overflow of certain list items.
Was that the css was arranging the link tags within the list but not the span tags inside the links.
We added css to the spans, arranging the spans within the links and so the list items.
Note: by doing this, we have to add css to the arrows inside the list and wrapping icons in span as well.
Dropdown in the Webhooks page (original bug v4.6.1):
Post-fix:
Examples of the same dropdown in other pages:
> Fix: Fix to the text-overflow on the WH's hadler plugin list

- rundeckapp/build.gradle
Bugfix: Address CVE-2022-42889 Commons-text dependency
Remove unnecessary Sass/Less asset pipeline plugins. Sass is built from webpack in UI-trellis
> RUN-1296: CVE-2022-42889: commons-text library

- rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
Bugfix on Log 
Problem: When the SCM fails rundeck by default will retry to reconnect 5 times, On the screenshot below we can see that the retry is being made 6 times and the log shows a weird message saying retry 6/5. 
Solution: Change the evaluation condition to end the cycle when the las retry is done. 
Before fix:
After fix:
> RSE-184: Fix: Log error when SCM tries to reconnect

- rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_progress-bars.scss
**Problem:**
On the activity tab, the percentage on the progress bar moved to the right when the percentage was more than 200% making it impossible to see the percentage.
**Solution:**
Add to the CSS class **.progress-bar** a max-width property to limit the growth of the progress-bar to 100% making the percentage shown on the center whatever the percentage is.
**Before Fix:**
The progress bar grew with the percentage.
**After Fix:**
The percentage is always shown in the center.
The progress bar only grows until 100%.
> RSE-159 Fix: Activity Tab no progress percentage displayed in a Progress-bar

- rundeckapp/build.gradle
On some systems this change can produce a 30-45% speed improvement when running the tests.
> Configure rundeckapp tests to fork every 500 tests for speed improvements.

- rundeckapp/grails-app/assets/javascripts/menu/joboptions.js
**Describe the bug**
When the “Select-all Values by default” is enabled within a Job option: when you change an upstream option, the cascading options don't render as selected, it toggles between select-all and non select all.
Select-all Values by defaul is related to:
1. Click to Edit this Job
2. Go to Workflow -> when adding an option you have this option when delimiting a list by commas or another character:
An additional validation is added when the values selected by default come and these are not considered in a subsequent validation.
Before change:
After change:
> RSE-118: Fix: select-all-function

- rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
**Problem:**
When a Job Definition is exported though CLI in Yaml format the Tags of the related job are not present into the file. With Xml format works as expected.
**Solution:**
Some changes were made in order to get the jobs tags when exporting it into a yaml file using rd-cli.
> rse-104: fix: jobs tags included when exporting yaml file with rd-cli

- rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/logging/SimpleDataFilterPlugin.groovy
- rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/logging/SimpleDataFilterPluginSpec.groovy
As seen [here](https://pagerduty.atlassian.net/jira/software/c/projects/RSE/boards/716?modal=detail&selectedIssue=RSE-169&assignee=6201489c539d790069dd410f), if PDPAOP runs a command with Ansible configured to append Ansi Scape Codes to the output ***and*** we capture the data in key-values, the key value comes with the Ansi Scape Code appended.
1. The ansi color codec for rundeck scapes the values to render the colors in the GUI but didn't remove the values from the values captured.
2. The user may not want in his keys a underscore.
If we filter the output data with the 'invalid characters' method of the key-value plugin, we end up with an unwanted underscore in the 'key' parameter, so we extended plugin's functionality to make possible choosing the replacement for the unwanted values. …
> RSE-169: Fix: Custom Replacement in Key-Value Log Filter Plugin

- core/src/main/java/com/dtolabs/rundeck/plugins/webhook/WebhookData.java
- core/src/main/java/com/dtolabs/rundeck/plugins/webhook/WebhookDataImpl.java
- grails-webhooks/grails-app/controllers/webhooks/WebhookController.groovy
- grails-webhooks/src/test/groovy/webhooks/WebhookControllerSpec.groovy
This PR fixes the bug where Grails eats the inputStream if x-www-form-urlencoded is the content type. The form data is passed to the webhook service in a new formData field in the WebhookData interface.
> RUN-1295: Allow form data in webhooks

- rundeckapp/grails-spa/packages/ui-trellis/theme/scss/runstrap/_dropdown.scss
Minor fix in the dropdown, the 'cell' in dropdown was breaking itself into two lines.
The display of the links inside each cell of the list, which was both icon and text had 'block' as display, that caused the line break.
Appending all the icons within a line with 'inline-block'
Other dropdowns after the fix:
> RSE-203 Fix: Proper Inline Icon Rederization within Dropdowns

- build.yaml
This is an enhancement to target a [new, more secure version of Py WinRM Plugin](https://github.com/rundeck-plugins/py-winrm-plugin/releases/tag/2.1.0).
Simple version bump
n/a
This goes along with Rundeck Pro PR rundeckpro/rundeckpro#2770
> RUN-1290: Target new version of py winrm

- docker/official/Dockerfile
- docker/ubuntu-base/Dockerfile
This is a security bugfix. The ubuntu package libksba8 has a security issue https://ubuntu.com/security/CVE-2022-3515. The issue has been fixed but we need to upgrade the package to its latest version.
Add a step in the ubuntu-base Dockerfile to upgrade the libksba8 package to its latest version.
> RUN-1297: Upgrade-Linux-Package-libksba8-To-Latest-Version

- core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/EngineWorkflowExecutor.java
- core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/engine/StepOperation.java
- core/src/main/java/com/dtolabs/rundeck/core/rules/Rules.java
- core/src/main/java/com/dtolabs/rundeck/core/rules/StateWorkflowSystem.java
- core/src/main/java/com/dtolabs/rundeck/core/rules/WorkflowEngine.java
- core/src/main/java/com/dtolabs/rundeck/core/rules/WorkflowEngineOperationsProcessor.java
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/EngineWorkflowExecutorSpec.groovy
- core/src/test/groovy/com/dtolabs/rundeck/core/rules/WorkflowEngineOperationsProcessorSpec.groovy
- core/src/test/groovy/com/dtolabs/rundeck/core/rules/WorkflowEngineSpec.groovy
- rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
Enhancements to workflow engine
* cleanup state data to remove unnecessary data (shared data + "label" data)
* update events sent from WF engine to include more data
* some WF engine changes:
* process state changes updated to clean up the logic, and keep shared data state separate from WF engine state
* add "gather" behavior to not end workflow before all running operations are truly completed
> RUN-20: WF engine updates

- test/testdeck/src/DockerCompose.ts
- test/testdeck/src/test/api.ts
testing harness in cluster mode does not fully work with token auth due to headers not be correctly sent when targeting individual nodes in the tests.
Update client construction to augment the existing HTTP request policies instead of overwriting them.
> RUN-1327: Fix: cluster test harness token auth fails [testing]

- .gitignore
- rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/SimpleTokenBuilder.java
- rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/DataProvider.java
- rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/TokenDataProvider.java
- rundeck-data-model/src/main/java/org/rundeck/app/data/utils/Utils.java
- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy
- rundeckapp/grails-app/services/rundeck/services/ApiService.groovy
- rundeckapp/grails-app/services/rundeck/services/RundeckAuthTokenManagerService.groovy
- rundeckapp/grails-app/services/rundeck/services/UserService.groovy
- rundeckapp/grails-app/views/user/_token.gsp
- rundeckapp/src/test/groovy/rundeck/controllers/UserControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ApiServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/RundeckAuthTokenManagerServiceSpec.groovy
This PR removes the use of the DataManager in the Rundeck services that are managed by Spring. Spring wiring makes the data providers much easier to use and makes advanced Spring bean management much more convenient.
I've added a DataProvider marker interface to the SPI that should be used by all data providers in the future so that we can easily identify them.
> Rcloud 662

- core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionContext.java
- core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionContextImpl.java
- core/src/main/java/com/dtolabs/rundeck/core/jobs/JobLifecycleComponent.java
- core/src/main/java/com/dtolabs/rundeck/core/jobs/JobLifecycleComponentException.java
- core/src/main/java/com/dtolabs/rundeck/core/jobs/JobLifecycleStatus.java
- core/src/main/java/com/dtolabs/rundeck/core/jobs/JobLifecycleStatusImpl.java
- core/src/main/java/com/dtolabs/rundeck/core/jobs/JobPreExecutionEvent.java
- core/src/main/java/com/dtolabs/rundeck/core/plugins/JobLifecyclePluginException.java
- core/src/main/java/com/dtolabs/rundeck/plugins/jobs/JobPersistEventImpl.java
- core/src/main/java/com/dtolabs/rundeck/plugins/jobs/JobPreExecutionEventImpl.java
- core/src/main/java/com/dtolabs/rundeck/plugins/project/JobLifecyclePlugin.java
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/ExecutionContextImplSpec.groovy
- rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
- rundeckapp/grails-app/services/rundeck/services/JobLifecycleComponentService.groovy
- rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/test/groovy/rundeck/ExecutionService2Spec.groovy
- rundeckapp/src/test/groovy/rundeck/ExecutionServiceParseJobOptsSpec.groovy
- rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/ExecutionServiceTempSpec.groovy
- rundeckapp/src/test/groovy/rundeck/ScheduledExecutionServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/JobLifecycleComponentServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Adds support for `JobLifecycleComponents`, which allow adding additional behavior to the Job lifecycle in the same way as `JobLifecyclePlugins`, but without passing through the plugin layer.
> RUN-1225: Job Lifecycle Components

- core/src/main/java/com/dtolabs/rundeck/core/common/BaseFrameworkExecutionProviders.java
- core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkBase.java
- core/src/main/java/com/dtolabs/rundeck/core/common/IExecutionProviders.java
- core/src/main/java/com/dtolabs/rundeck/core/common/ServiceSupport.java
- core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionServiceImpl.java
- core/src/main/java/com/dtolabs/rundeck/core/execution/service/NodeSpecifiedService.java
- core/src/test/java/com/dtolabs/rundeck/core/execution/impl/common/TestDefaultFileCopierUtil.java
- core/src/test/java/com/dtolabs/rundeck/core/execution/service/TestFileCopierService.java
- core/src/test/java/com/dtolabs/rundeck/core/execution/service/TestNodeExecutorService.java
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/AppExecutionPluginLoader.groovy
enhancement:
change signature of getNodeExecutorForNodeAndProject and getFileCopierForNodeAndProject to pass ExecutionContext instead project name
> RUN-1226: Runner Node Executor enhancement 

- rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
- rundeckapp/grails-spa/packages/ui/src/components/job/resources/NodeFilterResults.vue
The maximum quantity of shown nodes in the rundeck's 'edit job' page was different than the current shown nodes tags within the rendered list of nodes.
The parameter 'max number of nodes' was 'harcoded' in the frontend.
Using the prop [rundeck.gui.matchedNodesMaxCount](https://docs.rundeck.com/docs/administration/configuration/gui-customization.html#rundeck-gui-matchednodesmaxcount) to dynamically tell the GUI the user's desired max nodes to be shown in the GUI.
When a default or other number of nodes are displayed, the exact number of nodes shown is displayed.
'17 nodes shown' displayed (custom value)
101 of 101 nodes shown
> RSE-238 Fix: Dynamic max nodes shown in rundeck GUI

- gradle.properties
An enhancement to address three CVEs involving spring-security: CVE-2022-31690, CVE-2022-22978, and CVE-2022-31692
Bumps the version of our spring-security packages via the gradle.properties file
N/a
Pairs with https://github.com/rundeckpro/rundeckpro/pull/2809
> RUN-1369: Update spring-sec to fixed version

- core/src/main/java/com/dtolabs/rundeck/core/rules/NumericCondition.java
Problem: Rundeck didn't recognize negative numbers on the ruleset and converted any negative number to  0 causing failings when evaluating conditions like **if:option.1>=0** .
Solution: Fix the method in charge of parse values from the ruleset to float numbers to accept negative numbers.
> RSE-259 Fix:Ruleset Plugin fails to evaluate conditions if negative number are used

- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Fix the 404 page if job edit or update URL cannot find the specified ID.
change method to send response
> RUN-1345: fix incorrect 404 page response for job edit/update page

- rundeckapp/grails-app/views/framework/_editProjectForm.gsp
Bugfix: Upon toggling the checkbox in Execution Clean Form tab in Project Settings, the form associated was not showing.
Update jQuery function call and update ID selector
> RUN-1349 | Fix Missing Execution Clean History Form Display

- rundeckapp/grails-app/assets/javascripts/menu/logStorage.js
- rundeckapp/grails-app/assets/javascripts/nodeFiltersKO.js
- rundeckapp/grails-app/assets/javascripts/workflowStepEditorKO.js
function `.success()` was removed, should use `.done()` or `.then()`
reference: https://jquery.com/upgrade-guide/3.0/#ajax
Fix: adding log filters in job editor GUI does not work
broken by jquery upgrade
> RUN-1350: fix: step/global log filters not working after jquery upgrade

- rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
Enable the plugin group in project properties when a new plugin group is defined in the create project form
> RUN-1380: Fix defining plugin groups on project creation

- rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
- rundeckapp/grails-spa/packages/ui/src/pages/project-config/PluginSetConfig.vue
- rundeckapp/grails-spa/packages/ui/src/pages/project-config/ProjectPluginGroups.vue
load plugins config everytime page is loaded for edge cases where there are no events. i.e save, delete a plugin group
> Run 1386-fix plugin groups deleted when not modified

- rundeckapp/grails-spa/packages/ui-trellis/src/components/plugins/pluginConfig.vue
Fix: duplicated fields at notification settings modal
The modal fields for configuring notifications are being displayed repeatedly
The v-else statement behaves differently than when using v-if, causing fields to be rendered repeatedly.
> RUN-1392 Duplicated fields at Notification settings modal

- rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
bug fix.
If I choose the option to change the runner on execution time, when I’m on the job pages to execute the job I don’t have the option to change the runner
in firefox, the code that loads `jobComponentProperties` runs after the VUE component is loaded.
The solution was moving the jobComponentProperties load outside the jquery block.
> RUN-1389: fix error choosing runner on execution runtime

- rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
- rundeckapp/grails-app/domain/rundeck/Project.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
bugfix: Remove Database update for project on an ajax method who's purpose is to retrieve the project list for the picker.  Change the strict character constraint for the description field on project.  Change max length of the description field to match the corresponding text box length
> RCLOUD-728: Fix Project Picker not loading when Projects with special characters exist

- rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
Data attribute in `window._rundeck`object is overriden when loading job page
`jobComponentProperties` should be merged into `data` object instead of override
> RUN-1418: Job activity tab not loading

- rundeckapp/grails-spa/packages/ui/src/pages/project-config/PluginSetConfig.vue
- rundeckapp/grails-spa/packages/ui/src/pages/project-config/ProjectPluginGroups.vue
Plugin groups were able to be saved even if no value was provided. This PR fixes that by confirming the config is set before saving. This PR also updated the emissions to the parent component to only use one method upon loading or when the user saves or deletes.
> RUN-1385: Plugin group null definitions

- rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
- rundeckapp/grails-app/views/menu/jobs.gsp
- rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
Previously if the user don't have permissions to the key configured in the SCM Import Plugin, an internal server error could be seen and the basic job actions couldn't be performed.
1. Since th SCM service use the SESSION user to perform SCM operations, an error occurs when the system search for the keys in the plugin's config
1. In the controller of the menu (who renders job page and its functions) ask if the current user has permission to the key, if not disable the plugin and populate a message to the frontend.
2. Log at ERROR level the incidence.
3. Flash the unauthorized user with a message, letting the user now what happened with the SCM.
a) If an unauthorized user with the SCM import enabled sees the jobs page, an error message will be displayed
b) But if we go ahead and try to …
> RSE-244 Fix: edit/view jobs when SCM Import Plugin is forbidden for user

- rundeckapp/grails-spa/packages/ui-trellis/src/components/version/Copyright.vue
- rundeckapp/grails-spa/packages/ui-trellis/vue.config.js
Defines copyright string with current year at build time
> RUN-1298: generate copyright year at build time

- rundeck-authz/rundeck-authz-core/src/main/java/org/rundeck/core/auth/app/BaseAppRequestMethodAuthorizer.java
- rundeck-authz/rundeck-authz-core/src/main/java/org/rundeck/core/auth/app/RequestMethodAuthorizer.java
- rundeck-authz/rundeck-authz-core/src/main/resources/META-INF/services/org.rundeck.core.auth.app.RequestMethodAuthorizer
- rundeckapp/src/main/groovy/org/rundeck/app/authorization/RdAuthorizeInterceptor.groovy
define ServiceLoader interface for new method interceptor authorization checks
Allows extending authZ checks that can be applied to controller actions with new annotations
> RUN-1397: modular annotation authZ 

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowGraphController.groovy
- rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/WorkflowGraphControllerSpec.groovy
As of version 4.8, a client reported that the job's page of the Rundeck's GUI was too heavy to do changes in the rulesets.
The graphical representation of the rulesets, is delaying the changes in the GUI
1. Add a "v-if" directive to the "canvas" referenced div to prevent the renderization: wrong since the component behave erratic in matters of design.
2. Prevent the graph data population: wrong, the graph renders empty with "START" and "END" only (poor design).
a) Set a controller to retrieve a property that prevent the workflow graph to render (`rundeck.gui.workflowGraph`)
b) Call the controller from the plugin to see if the graph render or not
c) The "main" of the workflow graph plugin, will not write in memory the graph if the property is false (is true by default)
d) if the user …
> RSE-257 Fix: Cannot edit rulesets if the page is too heavy

- rundeckapp/grails-app/views/common/_queryFilterManagerModal.gsp
Fix: save node filter causes js console error (jQuery)
Fix use of promise.
jQuery upgrade
> RUN-1417: Fix use of promise

- rundeckapp/grails-app/services/rundeck/services/PluginService.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/PluginCustomizer.groovy
- rundeckapp/src/test/groovy/rundeck/services/PluginServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/PluginServiceTests.groovy
Some code remains which strips the suffix of a plugin name if it matches the service name, for “.groovy” plugins. This causes some groovy plugins to not be loadable.
Example: “SlackNotification.groovy”, if defined in libext/ even with valid plugin DSL usage, will not be usable.  The code removes “Notification” and lists a plugin named “Slack”, but attempting to load the plugin “Slack” causes an error because it is not found.
* change registration code to use proper "service name:" prefix
* PluginService.listPlugins no longer removes the service name suffix automatically from registered name, which causes groovy plugins to not be loaded correctly
> RUN-1367: Fix: groovy plugins with suffix matching the service should load correctly

- rundeckapp/grails-spa/packages/ui/src/pages/project-config/ProjectPluginGroups.vue
Update the button for adding a new plugin group to say "+ Plugin Config" instead of plugin group
> RUN-1423: Update add plugin button label

- core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionLifecycleComponentException.java
- core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionLifecyclePluginException.java
- core/src/main/java/com/dtolabs/rundeck/core/execution/WorkflowExecutionServiceThread.java
- core/src/main/java/com/dtolabs/rundeck/core/execution/service/FileCopierService.java
- core/src/main/java/com/dtolabs/rundeck/core/execution/service/NodeExecutorService.java
- core/src/main/java/com/dtolabs/rundeck/core/jobs/ExecutionLifecycleComponent.java
- core/src/main/java/com/dtolabs/rundeck/core/jobs/ExecutionLifecycleComponentHandler.java
- core/src/main/java/com/dtolabs/rundeck/core/jobs/IExecutionLifecycleComponentService.java
- core/src/main/java/com/dtolabs/rundeck/plugins/jobs/ExecutionLifecyclePlugin.java
- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/grails-app/services/rundeck/services/ExecutionLifecycleComponentService.groovy
- rundeckapp/grails-app/services/rundeck/services/ExecutionReferenceLifecycleComponentHandler.groovy
- rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
- rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/TestWEServiceThread.groovy
- rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceJobIntegrationSpec.groovy
- rundeckapp/src/main/groovy/rundeck/services/ExecutionLifecycleComponentService.groovy
- rundeckapp/src/main/groovy/rundeck/services/ExecutionReferenceLifecycleComponentHandler.groovy
- rundeckapp/src/main/groovy/rundeck/services/JobLifecycleComponentService.groovy
- rundeckapp/src/test/groovy/rundeck/ExecutionService2Spec.groovy
- rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/ExecutionServiceTempSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ExecutionLifecyclComponentServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/JobLifecycleComponentServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Refactor ExecutionLifecyclePlugin to have a new ExecutionLifecycleComponent similar to JobLifecycleComponent. With this new Component, we can create an ExecutionLifecycle component that cannot be turned off by the final user.
add a new ExecutionLifecycleComponent interface. The current ExecutionLifecyclePlugin interface depends on the first one. 
Now both, the plugins and components are loaded in `ExecutionLifecycleComponentService`
> RUN-1410: Add a new ExecutionLifecicleComponent

- docker/official/remco/templates/jaas-loginmodule.conf
resolve https://github.com/rundeck/rundeck/issues/6251
original PR: https://github.com/rundeck/rundeck/pull/8018
In official docker image, Cannot set ReloadablePropertyFileLoginModule in jaas-loginmodule by environment variables. so i added.
JettyRolePropertyFileLoginModule and JettyAuthPropertyFileLoginModule also cannot be set. but i haven't used that so i didn't change.
**request**
```
rundeck:
jaas:
modules:
- "ReloadablePropertyFileLoginModule"
```
Environmet Variable
```
RUNDECK_JAAS_MODULES_0: "ReloadablePropertyFileLoginModule"
```
**response**
```
rundeck {
org.rundeck.jaas.jetty.ReloadablePropertyFileLoginModule
required
debug="true"
file=".tmp/rundeck/server/config/realm.properties";
};
```
**default**
```
rundeck {
org.eclipse.jetty.jaas.spi.PropertyFileLoginModule 
required …
```
> RUN-1370: Change jaas-loginmodule remco template to be able to use ReloadablePropertyFileLoginModule

- rundeckapp/grails-app/views/user/profile.gsp
The user flash has a wrong spacing when a notification pops up.
Has a 'card' component, wrapping the flash
Removing the wrapper
Pre fix:
Post-fix:
> Fix to user profile flash spacing

- rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/test/groovy/rundeck/ScheduledExecutionServiceSpec.groovy
when a description is set in a job, the changes made to job schedules are not applied or persisted in DB.
By an unknown reason to date, some of the 'ScheduledExcecution" model's attributes, weren't marked as dirty if the description is set. In other words, if the description is set, the scheduled doesn't turn into an 'updated' value and not persisted in grails "save()" method.
- Annotate the 'ScheduleExcecution' model with @DirtyCheck, to track the changes. (not working)
- Validating the pre-saved object, to see if the property is dirty; triggered by other validation. (resource-expensive and not working)
- Passing another param to the save method (failOnError: true) to make a rollback of the save action (since the app works as expected before, this didn't work)
Mark the imported (new) job …
> RSE-280 Fix: Cannot Edit Job Schedules

- rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
- rundeckapp/src/test/groovy/rundeck/ScheduledExecutionSpec.groovy
Ticket: https://pagerduty.atlassian.net/browse/RSE-290
Roles in Active Directory can have spaces as part of their name, this results on the following error after upgrading from 3.3.x to 4.x (`3.3.10 -> 4.4.8` tested) and editing-saving a job.
These are the steps to reproduce the same issue:
1. In a 3.3.X instance (tested on 3.3.10) create a project and a simple job. (WAR/RPM install used)
2. Perform the [upgrade](https://docs.rundeck.com/docs/upgrading/upgrading.html) to 4.X.X version (4.8.0 used)
2. Within the DB schema, change the user_role_list table row of that job to this value (old version because coming from format): `1234ExampleOfRole1,4321ExampleOfRole2`
3. Try to update the job on the UI (just click save without any actual changes) > updates as expected and the list is updated …
> RSE-290: Fix: cannot update jobs after upgrade 3.3 to 4.8 job (error 500)

- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Problem: When trying to update a job by uploading a job definition, it will not remove existing notifications if the new job definition does not have any notifications. This problem was generated by the way the notifications were trying to be deleted, not correctly removing it from the object. 
Solution: Create a method to remove notifications based on the method deleteExistingNotification, to correctly remove notifications from the updated job if the input job doesn't have any notifications.
> RSE-266 Fix: Cannot remove notifications from a job by loading an XML file

- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/src/main/groovy/org/rundeck/web/infosec/ContainerPrincipalRoleSource.groovy
- rundeckapp/src/main/groovy/org/rundeck/web/infosec/ContainerRoleSource.groovy
- rundeckapp/src/main/groovy/org/rundeck/web/infosec/PreauthenticatedAttributeRoleSource.groovy
- rundeckapp/src/test/groovy/org/rundeck/web/infosec/ContainerRoleSourceSpec.groovy
Fixes: https://github.com/rundeckpro/rundeckpro/issues/2180.
The roles are coming in a single comma-separated string. We have 3 authorizing classes for the roles, of which 2 arrive as "admin,user" and another one arrives as "admin", "user". In the first 2 classes, the proper split is not being carried out by the delimiter.
The improvement consists of adding a split to the roles that arrive with commas or better said many roles.
**NGINX config:**
**Before:**
**After:**
> RSE-49: Fix: passing groups via proxy for preauth shows dupe groups in the Rundeck Profile

- rundeckapp/src/main/groovy/org/rundeck/app/components/JobYAMLFormat.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/components/JobYAMLFormatSpec.groovy
Fix to modify the LinkedHashMap mapping and insert a single map to the array. Related to https://github.com/rundeck/rundeck/issues/6711
``` yaml
...
notification:
onfailure:
format: json
method: post
urls: http://rundeck-server:4440/api/36/webhook/TOKEN#webhook
onsuccess:
format: json
method: post
urls: http://rundeck-server:4440/api/36/webhook/TOKEN#webhook
```
When the yaml is identified as coming in Map format (without "-", this symbol reference a list type), each map is inserted into the list:
code reference:
```
iteration {
map.put(key,value)
array.add(map)
}
```
The mapping of the LinkedHashMap is modified to insert a single map to the array.
code reference:
```
iteration {
map.put(key,value)
}
array.add(map)
```
Now list types and map types are accepted
``` yaml
...
notification: …
```
> RSE-133: Fix: Notifications payload format are not imported properly by the API and the UI

- .gitmodules
- packaging/lib/deb/etc/init.d/rundeckd
Ticket: https://pagerduty.atlassian.net/browse/RSE-245
1. Install 4.7.0 DEB package & run “pwd” command on localhost.
2. Check system report for PWD env variable.
Related to https://github.com/rundeck/rundeck/issues/4554
Rundeck version: 4.7.0
Install type: DEB
OS Name/version: Ubuntu 20.04
DB Type/version: H2
This was happening because the `/` is the default directory to run daemons used by the `start-stop-daemon` command. To solve the issue it was necessary to set this directory through the `--chdir` parameter when the `start-stop-daemon` is called in the `rundeckd` daemon.
> RSE-245: Fix: deb install not taking wrong base dir for commands

- rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
- Confirm value is set to something other than null before writing the value to project settings.
- Removed defined config for plugin groups for createProject view. It should never have any defined config, unlike editProject.
> Run 1466: fix create project plugin group null save error

- rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
Confirm that all keys are set before writing to project properties. if the value set is null, do not write to project properties
> RUN-1465: Fix null save error on plugin groups

- rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy
Fix: generated openapi spec 3.0.x has validation errors, due to `required:false` being unnecessary
> Cleanup: remove unnecessary openapi flags

- rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
- rundeckapp/src/main/groovy/rundeck/services/JobLifecycleComponentService.groovy
This PR corrects the way job components errors are handled, so they are considered as execution errors and not option validation errors.
This fixes the issue of executions not running when triggered from the job list page (inline run), where the absence of a runner won't render any error message.
Also small improvements on job component error reporting messages
> RUN-1477: Fix error handling on job component failure

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy
Ticket: https://pagerduty.atlassian.net/browse/RSE-186
The following settings work through Configuration Management but they require a restart:
`rundeck.security.syncOauthUser=true`
Added the property as part of the solution mentioned in enterprise PR
> RSE-186: syncOauthUser properties don't have hot reload

- rundeckapp/grails-app/views/execution/show.gsp
Adds a custom page loaded event for UI
> RUN-1434: fix exec page UI plugins: send event to indicate page loaded has completed

- core/src/main/java/com/dtolabs/rundeck/core/config/FeatureService.java
- core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
- core/src/main/java/com/dtolabs/rundeck/core/config/FeaturesDefinition.java
- rundeckapp/grails-app/services/rundeck/services/feature/FeatureService.groovy
Refactor:
Change FeatureService to use an interface instead of the Features enum
This will allows us to manage a Features set for enterprise
> RUN-1436: Change FeatureService to use an interface instead of the Features enum

- rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCombinedLdapLoginModule.java
- rundeckapp/src/test/java/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModuleTest2.java
Issue:
When using AD with paginated roles, rundeck would only retrieve the first page roles
Solution:
Allow rundeck to iterate over pages to get all the roles associated to the user
To use pagination you need to enable this by setting the property below as "true" in the "jaas-activedirectory.config" file
`rolePagination="true"`
> RSE-255 : Allow Roles pagination when using Active Directory

- rundeckapp/src/main/groovy/rundeck/services/ExecutionLifecycleComponentService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ExecutionLifecyclComponentServiceSpec.groovy
Bug: When a job is imported, the execution life cycle components are not loaded
- split component load from plugin load
- if the configuration is empty, don't call setPluginConfigVal
> RUN-1509: Fix: ExecutionLifecycle component is not loaded when a job is imported

- rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/webhooks/views/WebhooksView.vue
Bugfix: Upon creation of a webhook, the page wouldn't show the correct information, and appear to have had an issue.
Currently the UUID that is used to select the webhook is incorrect, and has been modified to use the correct UUID from the API.
> RUN-1492: Fix: Webhooks not showing proper information After Create

- test/selenium/package.json
- test/testdeck/package.json
backport https://github.com/rundeck/rundeck/pull/8184 to release/4.11.x
> Backport: Update chromedriver 110 

- grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
- rundeckapp/src/test/groovy/rundeck/services/WebhookServiceSpec.groovy
fix: webhook import should fail for existing token
> RUN-1552: fix: webhook import should fail for existing token (4.11.0-rc1)

- rundeckapp/grails-app/domain/rundeck/Execution.groovy
- rundeckapp/grails-app/i18n/messages.properties
- rundeckapp/grails-app/i18n/messages_es_419.properties
- rundeckapp/grails-app/i18n/messages_fr_FR.properties
- rundeckapp/grails-app/i18n/messages_pt_BR.properties
- rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
- rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
- rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/notification/DummyEmailNotificationPlugin.groovy
- rundeckapp/src/test/groovy/rundeck/ExecutionTest.groovy
- rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Problems:
1. Notifications triggered when the average duration exceeded were being sent with the template of the on-start notification, causing confusion to some clients. 
2. On the notifications triggered for the on-restart failure if the subject was left empty the default template the subject of the email didn't expand the variable name.
3. The email template body for average time exceeded and for retry-failure was missing information, a variable name was being shown without being expanded. 
Solution:
Modify the execution status when the average time was exceeded and add the missing messages to messages.properties
> RSE-297: Notifications fixes for Average Duration, OnRestart, etc.

- rundeckapp/grails-app/init/rundeckapp/Application.groovy
- rundeckapp/src/test/groovy/rundeckapp/ApplicationTest.groovy
If application startup throws an error and the -m flag is active, exit with a non zero code and print error.
> Migration only startup exit code fix

- rundeckapp/grails-app/views/common/_mainbar.gsp
Create a link to the execution mode toggle page when the execution mode is set to passive
> RUN-1139: Add link to execution mode toggle page on passive mode display

- rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy
- rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy
Make rundeck plugin registry check for null objects rather than rely on groovy truthy checks which can cause unexpected behavior
> Fix plugin registry loading behavior

- rundeckapp/grails-app/views/execution/_wfAddStep.gsp
- rundeckapp/grails-app/views/execution/show.gsp
- rundeckapp/grails-app/views/framework/nodes.gsp
- rundeckapp/grails-app/views/menu/jobs.gsp
Remove links to JS tests that are inserted in development mode.
> RUN-1356: remove in-page js tests in dev mode

- .circleci/config.yml
- scripts/circle-helpers.sh
- scripts/convert_tl_junit.sh
Convert twistlock scan output to junit xml for display by circleci
> RUN-1554: Convert twistlock output to junit for circleci

- build.yaml
Ticket: https://pagerduty.atlassian.net/browse/RSE-321
Fixed in: https://github.com/rundeck-plugins/py-winrm-plugin/pull/94
Upgrading py-winrm plugin version, fix is present in v2.1.2
> RSE-321: Fix: ERROR while running a dir command in a path with Japanese files (Upgrade plugin version)

- test/selenium/.gitignore
- test/selenium/.npmrc
Fix selenium failures when chrome is updated, by always using latest chromedriver
Set npmrc value to force latest chromedriver
> RUN-1646: Always use chromedriver latest in selenium tests

- rundeckapp/build.gradle
- rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/grails-app/i18n/messages.properties
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
- rundeckapp/src/main/groovy/org/rundeck/app/jobs/options/JobOptionConfigRemoteUrl.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/EditOptsControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Enhancement:  Add JSON Path Option to Remote URL Option Input
This enhancement would allow customers to specify the JSON path where they would pull the value from.
For example, having a JSON payload as the following:
```
{
"key1":"value1",
"key2":
{
"sub-key3":"value3",
"sub-key4":"value4"
}
}
```
Users would like to be able to just show in the Option list the “sub-key” list above by presenting a JSON path of $.key2 for the path to return.
- add a new field in the remote option URL
- if the filter is set, use `JsonPath` to filter the remote URL payload
- return the results
A clear and concise description of any alternative solutions or features …
> RUN-1619: Add JSON Path Option to Remote URL Option Input

- rundeckapp/grails-app/conf/application.yml
It's a security enhancement. 
Add a spring configuration `server.servlet.session.cookie.same-site` to application.yml file. Spring boot will automatically add `SameSite=Strict` header into the HTTP cookie.
https://github.com/rundeck/rundeck/pull/new/RUN-1616-Cookie-Missing-SameSite-Security-Flag
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite#strict
> RUN-1616: Set Cookie SemeSite Flag To Strict

- rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/pluginMeta/RdPluginMeta.java
- rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/PluginMetaDataProvider.java
- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/grails-app/domain/rundeck/PluginMeta.groovy
- rundeckapp/grails-app/services/rundeck/services/JobMetadataService.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormPluginMetaDataProvider.groovy
- rundeckapp/src/test/groovy/rundeck/services/JobMetadataServiceSpec.groovy
Move PluginMeta interaction of the database behind data SPI
A new RdPluginMeta interface was created and all of the references were moved to new entity
Jira ticket https://pagerduty.atlassian.net/browse/RCLOUD-794
> Adding PluginMeta spi

- rundeckapp/grails-app/conf/application.yml
Bugfix. The configuration item SameSite="Strict" was not correctly indented.
> RUN-1663: SameSite configuration incorrect indent

- rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/EditOptsControllerSpec.groovy
bug,  
fix removing remoteUrl json-filter when the value is removed from the option form
> RUN-1664: Job option Json Path Filter can’t be deleted

- rundeckapp/src/main/groovy/org/rundeck/app/jobs/options/JobOptionConfigRemoteUrl.groovy
- rundeckapp/src/test/groovy/rundeck/OptionSpec.groovy
When the remote URL is set with a `json-filter`, when a job is imported an exception is thrown 
check if the `authenticationType` is set before loading the option value.
> RUN-1666: fix import when configRemoteUrl is set

- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
bug:
if the configRemoteUrl auth is not set the setUrl wasn't called wich trigger an error
check configRemoteUrl authenticationType is set
> RUN-1665: Remote URL doesn't work with Json Path Filter

- rundeckapp/grails-app/views/layouts/base.gsp
defered script loading conflicts with expected script loading order
> RUN-1676: 4.12.0-rc2: disable defer for ui plugins

- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
When the execution doesn't report about the failed or successful nodes, when the execution attempt was activated on the "failed nodes" there was an NPE as there was no information on failed nodes.
The plugin adapter doesn't report about failed nodes.
As discussed internally in previous reviews about this, the NPE was handled at the controller level, preventing null values ​​from being read and triggering the retry with the original nodeset
> RSE-328 Fix: NPE Job Retry with No Failed Nodes

- core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/StepPluginAdapter.java
- core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapter.java
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/StepPluginAdapterSpec.groovy
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapterSpec.groovy
refactor to pass configuration values to the runner when plugins use @PluginProperty annotations
> RUN-1691: pass configuration values to the runner when plugins use @PluginProperty annotations

- rundeckapp/grails-app/views/scm/_statusBadge.gsp
> RSE-183 Fix: Misplaced SCM Tooltip on Job Show

- rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Ticket: https://pagerduty.atlassian.net/browse/RSE-335
Cluster member wasn't able to reschedule jobs that are not owned by it because it was reading the `project.disable.schedule` property from cache (which was invalid after the schedule state was changed from other member and before the schedule change message was processed)
Allow `FrameworkService` to return project configuration after reloading it.
> RSE-335: Fix: Enable schedules from project settings don't work as expected in clustermode

- rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
In concordance to [this](https://pagerduty.atlassian.net/browse/RSE-324) and [this](https://nvd.nist.gov/vuln/detail/cve-2022-24785) we updated the deprecated versions for moment.js.
:white_check_mark: Only UI-Trellis is affected.
The list of project/plugins below were affected, mainly because of the dependency of vue-moment (moment.js) which was deprecated:
- rundeckpro-calendars
- rundeckpro-config/vue-spa
- rundeckpro-jobdata
- rundeckpro-node-wizard
- rundeckpro-nodehealthcheck
- rundeckpro-reactions
- rundeckpro-roimetrics
- rundeckpro-security
- rundeckpro-ui-components
- rundeckpro-tour-manager
- rundeckpro-webhooks
- ui-workflow-designer
- ui-trellis
> RSE-324 Fix: Updated vue-moment dependency to latest moment version

- rundeckapp/grails-app/conf/application.yml
Sets SameSite cookie policy to Lax as default to allow correct OAuth2 SSO flows
> RUN-1709: Sets SameSite cookie policy to Lax as default to allow OAuth2 SSO flows

- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageView.vue
Bugfix. Use String literal `Loading...` to replace the malfunction i18n translation. This is a temporary fix, we should implement a i18n solution to fully translate the component.
> RUN-1727: Correct loading indicator text

- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/imp/actions/ImportJobs.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/ScmController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScmControllerSpec.groovy
- test/api/test-scm-plugins-job-action-perform.sh
When you import remote jobs with SCM configured using the API, you get an error in the response but the job WAS imported.
When you consume the `performAction` method to import the remote job, you first check if you're going to delete any jobs, and if you don't delete any jobs, the response is set to `success = false`.
The field `success = true` is added after successfully importing the remote job.
**Before fix:**
**After fix:**
> RSE-271 Fix: Successful remote job import from API but getting error in SCM API response

- rundeckapp/grails-app/assets/javascripts/_package-manager/mix-manifest.json
- rundeckapp/grails-app/assets/javascripts/_package-manager/webpack.mix.js
- rundeckapp/grails-app/views/scheduledExecution/_jobEditCommon.gsp
- rundeckapp/grails-app/views/scheduledExecution/show.gsp
The jQuery autocomplete js file that is copied by webpack should go in the vendor folder. This change fixes git always showing jquery.autocomplete.min.js as needing to be checked in after a complete gradle build.
> Put webpack copied jquery autocomplete asset in the vendor folder.

- rundeckapp/grails-app/views/feed/_jobreportItem.gsp
- rundeckapp/grails-app/views/feed/index.gsp
This is a bugfix.
After 4adf6cdd6624facaf69866f3cee03d63abd32c98 the RSS feed generation stopped working. Missing property "jcExecId". This commit fixes the RSS feed.
> RUN-1703: Fix RSS feed servlet

- rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/execution/ReferencedExecutionDataProvider.java
- rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/job/JobDataProvider.java
- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/grails-app/domain/rundeck/ReferencedExecution.groovy
- rundeckapp/grails-app/views/scheduledExecution/_jobActionButton.gsp
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormJobQueryProvider.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormReferencedExecutionDataProvider.groovy
- rundeckapp/src/test/groovy/rundeck/ReferencedExecutionSpec.groovy
The SPI changes for ReferencedExecution broke a gsp that tried to list the parent job info for a referenced job.
> Fix issue with showing referenced execution data in gsp layer

- rundeck-data-model/build.gradle
- rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/report/dto/SaveReportRequestImpl.java
- rundeckapp/grails-app/domain/rundeck/BaseReport.groovy
- rundeckapp/grails-app/domain/rundeck/ExecReport.groovy
Change logging to info.
Mark deprecated fields in BaseReport and ExecReport
> When SaveReportRequest builder hits a deprecated field it should not print a stack trace.

- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/BaseGitPlugin.groovy
- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
Ticket: https://pagerduty.atlassian.net/browse/RSE-366
After committing a change in a job in the Remote Repo, the SCM import status API call:
`curl --location 'http://hostname:4440/api/15/project/PROJECT_NAME/scm/import/status' --header 'X-Rundeck-Auth-Token: API_TOKEN'`
returns:
`{"actions":[],"integration":"import","message":"","project":"test","synchState":"CLEAN"}`
where it should be:
`{"actions":["import-jobs"],"integration":"import","message":"1 file(s) need to be imported","project":"Pimport","synchState":"IMPORT_NEEDED"}`
This happens sometimes because some other method pulled the changes from the repo without updating the sync status of the jobs.
Check if the local repo was updated from another place. This check is made in the existing `clusterFixJobs` method, which is called …
> RSE-366: Fix: SCM import plugin does not refresh status in API unless GUI is refreshed

- rundeck-data-model/src/main/java/org/rundeck/app/data/model/v1/report/RdExecReport.java
- rundeckapp/grails-app/domain/rundeck/ExecReport.groovy
- rundeckapp/grails-app/migrations/core/BaseReport.groovy
- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/activityList.vue
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormExecReportDataProvider.groovy
- rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
Currently the BaseReport/ExecReport data has a soft reference to the internal ScheduleExecution id. A migration needs to be written to look up the internal ScheduledExecution id and put in a job uuid instead. 
A new column was added to the base_report table to reference the jobUuid, and the proper adjustments were made to save execReports and then list execReports.
Jira ticket here https://pagerduty.atlassian.net/browse/RCLOUD-909
> RCLOUD-909: BaseReport JobUuid adjustments

- docker/ubuntu-base/Dockerfile
> RUN-1741: Reduce ubuntu base dockerfile size

- rundeckapp/grails-app/assets/javascripts/adhocCommandKO.js
- rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
Enhancement. When the user selects a previously executed command the Selected Runner should also be updated.
> RUN-1707 Adhoc Command UI Change To Support Runner Selector

- core/src/main/java/com/dtolabs/rundeck/core/plugins/AbstractDescribableScriptPlugin.java
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapterSpec.groovy
- core/src/test/groovy/com/dtolabs/rundeck/core/plugins/AbstractDescribableScriptPluginSpec.groovy
Since version 4.9.0 plugins that used ${config.*} variables, were no longer resolving configured values, replacing aforementioned values with blank strings. 
[RSE-461](https://pagerduty.atlassian.net/browse/RSE-461)
There were a field to indicate whether the application needed to resolve the config path, being always true. Meaning we were gonna replace ${config.*} values  for blank.
We added the validation to replace that field for whatever we defined in the plugin configuration.
[RSE-461]: https://pagerduty.atlassian.net/browse/RSE-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSE-461 Fix: Job Step plugin that uses ${config.*} variables within are no longer resolving

- rundeckapp/grails-app/migrations/core/Execution.groovy
- rundeckapp/grails-app/migrations/core/ScheduledExecution.groovy
- rundeckapp/grails-app/migrations/core/Workflow.groovy
- rundeckapp/grails-app/migrations/core/WorkflowStep.groovy
Enhancement. By adding additional indexes to improve database performance.
All ID columns by default have been indexed. We need to create an index for the column that references a foreign table.
This is a request from our clients when they found the added index can improve database performance, especially on deletion executions.
> RUN-1735: Add additional DB index to improve performance

- plugins/azure-object-store-plugin/build.gradle
upgrade libraries azure-object-store-plugin
> RUN-1771: upgrade libraries azure-object-store-plugin

- rundeckapp/grails-app/views/layouts/base.gsp
* scripts/styles with `asset:` prefix will be treated as local assets and use asset URL directly
* allows asset plugin to manage caching
> RUN-1782: Support local assets in UI plugins by using asset: prefix

- rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
- rundeckapp/grails-app/views/feed/_jobreportItem.gsp
- rundeckapp/grails-app/views/feed/index.gsp
- rundeckapp/grails-app/views/reports/_baseReport.gsp
Old references to the ctxProject field caused some links to fail to reference the correct project.
> RUN-1791: Fix references to ctxProject.

- rundeckapp/grails-app/migrations/changelog.groovy
- rundeckapp/grails-app/migrations/core/BaseReport.groovy
- rundeckapp/grails-app/migrations/core/BaseReportSpi.groovy
Fix failing migration
Move the migration that uses the column execution_id from the table base_report after it's created, also a precondition was added to check if the column exists.
Jira ticket https://pagerduty.atlassian.net/browse/RUN-1765
> RUN-1765: BaseReport migration

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- docker/official/remco/templates/rundeck-config-features.properties
- rundeckapp/grails-app/controllers/rundeck/interceptors/InternalErrorsInterceptor.groovy
- rundeckapp/src/test/groovy/rundeck/interceptors/InternalErrorsInterceptorSpec.groovy
- rundeckapp/templates/config/rundeck-config.properties.template
Ticket: https://pagerduty.atlassian.net/browse/RSE-326
When there's an internal error, the responses include information about the internal system (stacktraces).
or
Use an Interceptor that matches responses with internal server errors and render a default error page for any of them:
```
rundeck.feature.debug.showTracesOnResponse=false
```
> RSE-326: Fix: Error responses including stacktraces

- rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
Ticket: https://pagerduty.atlassian.net/browse/RSE-331
_Steps to Reproduce_
Steps to reproduce the behavior:
1- Install rundeck 4.8/4.9 on a cluster mode
2- Add the cluster on an rds mariadb database.
3- Add this remote execution policy 
```
rundeck.clusterMode.remoteExecution.policy=RoundRobin
rundeck.clusterMode.remoteExecution.config.activeOnly=true
rundeck.clusterMode.remoteExecution.profiles=P1,P2
rundeck.clusterMode.remoteExecution.profile.P1.policy=Preset
rundeck.clusterMode.remoteExecution.profile.P1.config.uuid=ffffccff-c818-456d-87ce-763c499ec196
rundeck.clusterMode.remoteExecution.profile.P1.config.activeOnly=true
rundeck.clusterMode.remoteExecution.profile.P1.projects=P1-only
rundeck.clusterMode.remoteExecution.profile.P2.policy=Preset …
```
> RSE-331: Fix: "Active Connection is required" errors when using s3 log storage

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/grails-app/utils/rundeck/codecs/JobsXMLCodec.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/components/JobXMLFormat.groovy
- rundeckapp/src/test/groovy/rundeck/JobsXMLCodecTests.groovy
Problem: When a job was exported on XML on Rundeck versions previous to 4.12 values separator was always a "," After fixing this issue a new issue appears when importing a job from a previous version where values and enforced values didn't match for not using the same value delimiter.
Solution: add a new property where the user can override the valueListDelimiter on the XML.
The new property is rundeck.jobsImport.xmlValueListDelimiter =,  this property needs to be added on the rundeck-config.properties
> RSE-462 Fix: unable to upload xml jobs on 4.12 being exported from 4.5

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/grails-app/init/rundeckapp/init/servlet/JettyServletContainerCustomizer.groovy
- rundeckapp/grails-app/init/rundeckapp/init/servlet/JettyServletHstsCustomizer.groovy
- rundeckapp/src/test/groovy/rundeckapp/init/servlet/JettyServletHstsCustomizerSpec.groovy
Problem:
HSTS headers were not being applied to the assets path because the doFilterInternal method from the RundeckSecurityHeadersFilter class was unable to apply the headers to those paths since they were outside of its scope.
Solution:
Delegate the HSTS to the embedded Jetty server by adding a SecureRequestCustomizer
> RSE-430 Fix: HTTP Strict Transport Security (HSTS) Header Not Used

- rundeckapp/grails-app/init/rundeckapp/init/servlet/BanConfigCustomizer.groovy
- rundeckapp/grails-app/init/rundeckapp/init/servlet/BanHttpMethodCustomizer.groovy
- rundeckapp/grails-app/init/rundeckapp/init/servlet/JettyServletContainerCustomizer.groovy
- rundeckapp/src/test/groovy/rundeckapp/init/servlet/BanConfigCustomizerTest.groovy
Issue:
it was a problem when it was sent a trace http method to the root path because the app response with a cookie JSESSIONID and this addressed to a security concern.
Fix:
I was added a customizer to jetty to avoid trace http method requests and the response it's a 405 - Method not allowed and without any cookie associated to.
> RSE-421: fix: Added a customizer to avoid trace method on root path

- core/src/main/java/com/dtolabs/rundeck/core/plugins/AbstractDescribableScriptPlugin.java
- core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/StringRenderingConstants.java
- core/src/test/groovy/com/dtolabs/rundeck/core/plugins/BaseScriptPluginSpec.groovy
Script plugins, where a key storage selector is used for a field, have the option to retrieve values from the key storage and use the raw password.
add a way to skip exceptions for key storage conversion failure and use the original value
> RUN-1830: Script plugins, skip exceptions for key storage conversion

- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Problem:
Jobs with a "step-first" workflow strategy couldn't be imported. This workflow strategy should be taken for Rundeck as a sequential since they are marked as a synonym.
Solution:
Evaluate if the job to be imported has a "step-first" workflow strategy and replace it with a sequential workflow strategy.
>  RSE-569 Fix: Error importing job definition from 4.5

- test/selenium/.npmrc
Reverting https://github.com/rundeck/rundeck/pull/8400
* related bugs supposedly are fixed https://github.com/giggio/node-chromedriver/issues/418#issuecomment-1641077838
> use latest chromedriver

- test/selenium/.npmrc
> backport: use latest chromedriver

- rundeckapp/grails-spa/build.gradle
turn off build caching for the grails-spa project
> disable gradle build caching from grails-spa build

- rundeckapp/grails-spa/packages/ui-trellis/package.json
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/utils/AceEditor.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/utils/AceEditorVue.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/custom/process-flow.scss
- rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/runstrap/_code.scss
- rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/runstrap/_input-groups.scss
- rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/runstrap/_variables.scss
* Updates the Ace text editor used via Vue to adapt to dark mode
* Updates some styles for dark mode
* border for list items
* color/bg for `<code>` 
Before:
After:
> RUN-1859: Dark mode updates

- rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java
- rundeckapp/src/test/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModuleTest.groovy
- rundeckapp/src/test/java/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModuleTest2.java
Depends and continue: https://github.com/rundeck/rundeck/commit/be518d9c4863dfcff5922e1d460e358e9466cb65
This flag is created with the intention of controlling if we want to obtain all the user's groups and those that come by default. Due to the large number of groups a user can have (example: 500k groups), it may reduce performance when logging in.
LDAP: error code 4 - Sizelimit Exceeded when you activated the nestedGroups option and you had a large number of groups.
**New**: `allGroups` flag to enable/disable if getting all groups or default. Flag is **false** by default.
Flag: `allGroups` in `false`:
Flag: `allGroups` in `true`:
> RSE-406::Flag to enable/disable search for more than 1000 users

- rundeckapp/grails-app/views/execution/_wfstateNodeModelDisplay.gsp
- rundeckapp/grails-app/views/execution/show.gsp
**Issue:** When running a job with too many nodes (like 700) to dispatch it, rundeck would get stuck when trying to show the log output page.
**Solution:** Remove non working functionality that tried to attach the runner id associated to the node (also removes the "runned id" column)
> RSE-693: Fix stuck log output

- rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
- rundeckapp/src/test/groovy/com/dtolabs/rundeck/execution/WorkflowExecutionListenerTest.java
- rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
- rundeckapp/src/test/resources/META-INF/services/com.dtolabs.rundeck.core.execution.workflow.WorkflowExecutionListener
Add a new plugin to log node usage.
A new implementation of WorkflowExecutionListener was created to handle the log creation when an execution ends, and this changes load the new implementation in the multiListener.
Additional context
Jira ticket https://pagerduty.atlassian.net/browse/RCLOUD-922
[Document](https://docs.google.com/document/d/1Se4PHnTGx1rf0PQQYbYfrewLIhmmHmpl84Wn30Astlo/edit#heading=h.zesn33r7rii)
> RCLOUD-924: Load additional WorkflowExecutionlistener

- scripts/circle-helpers.sh
replace / char in branch name to set correct docker tag
Fix: twistlock checks try to pull incorrect docker image if branch name contains `/` char
> RUN-1821: fix: docker tag used for twistlock check

- rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/runstrap/_media.scss
fix style for notification toasts, remove an extraneous border style.
before:
after:
> RUN-1873: remove unstylish border from notifications

- rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/webhooks/views/WebhooksView.vue
When there is more than one webhook (it doesn't matter what type) and you click on any saved webhook except the bottom one, clicking "Regenerate" then "Save" immediately loads the bottom webhook, so the regenerated string is not visible for long enough to copy it.
[RSE-521](https://pagerduty.atlassian.net/browse/RSE-521)
For some reason, after saving the webhook config, the selection was going to the last one in the list by default. So instead of doing that, we are sending now the selected webhook so the generated code can be copied.
[RSE-521]: https://pagerduty.atlassian.net/browse/RSE-521?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> RSE-521:Fix: When clicking "Save" button at webhook can't copy the genereated string

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
- rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
As a solution to Runner authorization issues, we expanded the capability to map "required" roles to allow connections.
When the property ```rundeck.security.requiredRole``` is set, the interceptor 'SetUserInterceptor.groovy' acts as a filter and check if the role received in request matches with the role named in the property; when the runner attempts to connect to rundeck's server, only one role ("_runner") is extracted from the connection token, that caused [this issue](https://pagerduty.atlassian.net/browse/RSE-712)
Adding other property to add comma separated roles in order to map other roles as well.
STR Previous Behavior (4.15):
1. Enable the runner management and add the property ```rundeck.security.requiredRole=yourRole```
2. Create a project
3. Create a runner and assign it to …
> RSE-712 Fix: Map Different Required Authorizing Roles

- rundeckapp/grails-app/services/rundeck/services/WorkflowService.groovy
Ticket: https://pagerduty.atlassian.net/browse/RSE-445
The execution state is not synchronized among cluster members when using shared file system log storage because the `<exec_id>.state.json` is generated on execution completion if not using any log storage plugin.
Keep the `<exec_id>.state.json` files updated on every workflow status change. Also reading the status from the file without using a cache on cluster mode
Create some kind of "file watcher" on the `WorkflowStateFileLoader` to keep the cache updated on every external change of the file. This was discarded for the extra complexity that implies for a little benefit
> RSE-445: Fix: execution state in clustermode with nfs logstorage not in sync

- grails-execution-mode-timer/grails-app/services/com/rundeck/plugin/UpdateModeProjectService.groovy
- grails-execution-mode-timer/src/test/groovy/com/rundeck/plugin/EditProjectControllerSpec.groovy
- grails-execution-mode-timer/src/test/groovy/com/rundeck/plugin/UpdateModeProjectServiceSpec.groovy
- rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
- rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionJobIntegrationSpec.groovy
- rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
Problem: Some jobs do not trigger after disabling/enabling the schedule at the project level on the cluster this also happened with Disable Execution Later/Disable Scheduled Later.
Solution: The query that queries the messaging table was modified to sort the retrieved records by ID, avoiding a race condition that caused scheduled jobs not to execute. Also, the project config is now obtained directly from DB and not from the cache avoiding inconsistencies.
A missing notification was added to the cluster communication to notify the "Disable Execution Later" / "Disable Scheduled Later" events.
> Rse 702 schedule cluster

- rundeckapp/src/main/groovy/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java
Keep the value true to fetch all groups in LDAP. If there is an error, just change it to false.
> RSE-724: Keep "allGroups" in true by default.

- rundeckapp/grails-app/views/layouts/base.gsp
- rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/runstrap/_view.scss
* wrap section-content to allow before/after ui-sockets
> RUN-1853: UI main layout updates

- rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
- rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
- rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionJobIntegrationSpec.groovy
- rundeckapp/src/main/groovy/rundeck/services/ScheduledExecutionDeletedException.java
- rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
**Issue:** whenever an scheduled job was deleted on a cluster member different than the owner, the job would still be running on quartz but throwing exception each time that it tried to run
`[2023-07-31T11:34:00,029] ERROR quartzjobs.ExecutionJob [quartzScheduler_Worker-5] - Unable to start Job execution: No row with the given identifier exists: [rundeck.ScheduledExecution#13]
org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [rundeck.ScheduledExecution#13]
at org.hibernate.boot.internal.StandardEntityNotFoundDelegate.handleEntityNotFound(StandardEntityNotFoundDelegate.java:28) ~[hibernate-core-5.4.24.Final.jar!/:5.4.24.Final]
at org.hibernate.event.internal.DefaultLoadEventListener.load(DefaultLoadEventListener.java:216) …
> RSE-721: fixes job deletion of an scheduled job

- rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/webhooks/views/WebhooksView.vue
The fix for #8453 caused a new issue when creating a new webhook showing `undefined` in the webhook URL
It checks if it is creating a new webhook. If so, it will keep the previous behavior to select the new item created. If not, it will keep the current selection
> Fix RUN-1883: selecting correct webhook when it's saving a new one

- core/src/main/java/com/dtolabs/rundeck/core/resources/ScriptResourceModelSource.java
- core/src/test/groovy/com/dtolabs/rundeck/core/resources/ScriptResourceModelSourceSpec.groovy
remove script file resource model validation to be executed in a remote runner
> RUN-1897: enable execution of  script file resource model in a remote runner

- core/src/main/java/com/dtolabs/rundeck/core/execution/ExecutionServiceImpl.java
- core/src/main/java/com/dtolabs/rundeck/core/logging/LoggingManagerImpl.java
- core/src/main/java/com/dtolabs/rundeck/core/logging/PluginFilteredStreamingLogWriter.java
- core/src/main/java/com/dtolabs/rundeck/core/logging/PluginLoggingManager.java
- core/src/main/java/com/dtolabs/rundeck/plugins/logging/LogFilterPlugin.java
- core/src/test/groovy/com/dtolabs/rundeck/core/logging/PluginFilteredStreamingLogWriterSpec.groovy
allows log filter plugins to know the result status of the step or workflow they are applied to
add status result to the LogFilterPlugin `complete` method
RUN-1840
> RUN-1840: propagate status result to log filter complete method

- rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
- rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
The API calls to metrics endpoint returned a 500 when user requested it.
When rundeck server query the database for metrics, the results came in 'INTERVAL' datatype and the mapping was set to a "TIMESTAMP" object.
Creating different criterias that will be iterated until the result is extracted.
:heavy_check_mark: H2
:heavy_check_mark: Postgres
:heavy_check_mark: Mysql
:heavy_check_mark: Microsoft SQL Server
:heavy_check_mark: Oracle
1. Start the server and set it to use PostgreSql as a database backend
2. Import a project that has more than 1k of execution records, _can be used [this](https://github.com/rundeckpro/rundeck-tester/tree/master/qa-framework-test-runner/environments/loadEnvironment/projectImport/EDLProject) QAF project_
3. Create an user token allowed to use the API
4. Make …
> RSE-699 Fix: Metrics Call Fails in PSQL

- core/src/main/java/com/dtolabs/rundeck/core/logging/PluginFilteredStreamingLogWriter.java
- core/src/main/java/com/dtolabs/rundeck/core/logging/PluginLoggingContext.java
- core/src/test/groovy/com/dtolabs/rundeck/core/logging/PluginFilteredStreamingLogWriterSpec.groovy
Extends the PluginLoggingContext to include the full Execution Context
> RUN-1902: Add execution context for log filter plugins

- rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
Force UTC timezone for test that requires the timezone to be UTC to work correctly
> Fix flaky test

- rundeckapp/grails-app/views/scheduledExecution/_tabsEdit.gsp
- rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/en_US.js
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/containers/tabs/Tabs.vue
These changes are necessary to fix the following bugs:
- upon downloading a runner, the section would be rendered empty due to an extra tab being rendered (this.$slots.default isn't reacting on the change of content, therefore it tries to render a tab for 'editing the runner', which shouldn't happen);
- upon editing a job, the node tab wasn't rendering all strings;
will make a second PR on pro
- on tabs: changed the template to use a computed property, to ensure that the tabs will match the slots passed;
- add missing strings;
> RUN-1917 add strings, adjust _tabsEdit and fix render of tabs

- rundeckapp/grails-app/views/execution/_wfAddStep.gsp
If a step plugin has extended description content, the first line is not shown in the list of plugins when adding a new step to a workflow.
before:
after:
RUN-1923
> RUN-1923: fix: short description not shown for node/workflow steps in workflow step create picker

- rundeckapp/grails-app/views/framework/_pluginConfigPropertyFormField.gsp
Enhancement to make NodeExecutor configuration use the Runner Key Storage Selector component.
And fix some Vue3 migration issues.
> RUN-1905: Inject storage filter and fieldId to Vue

- build.yaml
upgrade ansible plugin
- add key storage support for resource model
- implement ProxySecretBundleCreator to share keys with the runner
- project and framework mapping were missing for the new property ANSIBLE_BINARIES_DIR_PATH
> RUN-1912: update ansible plugin to 3.2.7

- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Adds additional validation data to the validation map response when validating a job, instead of just logging the errors
> RUN-1922: include all validation data in validateJobDefinition map

- rundeckapp/grails-app/views/scheduledExecution/_tabsEdit.gsp
Bugfix, there is no default value for Nodes tab name, so it displays as an empty string
Restored old behavior where value was loaded using gsp
Old behavior:
New behavior:
> RUN-1917: Add default tab name for Nodes

- rundeckapp/grails-app/utils/rundeck/codecs/JobsXMLCodec.groovy
- rundeckapp/src/test/groovy/rundeck/JobsXMLCodecTests.groovy
If a import was attempted with a empty notification plugin, configured in a job an error could be seen: 
Removing the validation from the xml codec, which was the functionality that was preventing the import.
> RSE-534 Fix: Cannot Import Jobs with Blank Notification's Config

- build.yaml
Problem: A in the sshj-plugin has modified how private keys are used by the SSHClient, as a consequence of this change, private keys stored in the filesystem have become inaccessible to Rundeck, resulting in failed node authentication.
Solution
Changes were made directly on the sshj plugin PR: https://github.com/rundeck-plugins/sshj-plugin/pull/20
The auth method was adapted to take in count the location of the key. If the private key is stored in Rundeck (AKA key storage), the current behavior will remain the same to avoid generating a temporary key. If the private key is located at a filesystem path, it will be loaded into the SSHClient, allowing it to authenticate again.
> RSE-765 Fix: File System keys unreachable in Rundeck

- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageView.vue
This is an enhancement to CyberArk key storage provider plugin. The change refactored the code to make it support different CyberArk working modes. Currently, legacy mode and CCP mode have been implemented. 
The legacy mode keeps the existing business logic.
The CCP mode limits the user's ability to browse the key storage. Only direct key access by the path is allowed.
At the UI side, in CCP mode a warning message will prompt the user to manually type in the path of the key into the form field.
> RUN-1864: CyberArk CCP Mode

- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageEdit.vue
When an error is returned from promise trying to save a new key, it is not shown on the page
Change the code to catch result and error message from promise
> RUN-1947 key storage view does not show error when saving fails

- .circleci/config.yml
Circle ci is failing on openAPI validation due to mismatch on the node version. 
Add install node to openAPI job.
before:
after:
> Update circle-ci to install node before openAPI validation

- rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/runstrap/_tables.scss
Fix table header on dark theme
Vue 3 is loading a chunk of the css out of order, added an extra selector to ensure that the rules will prevail even though they are coming earlier in the cascade.
Adjusting way vue 3 loads the css, but that's more time consuming
> RUN-1942 table

- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/widgets/rundeck-info/RundeckInfo.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/widgets/rundeck-info/RundeckInfoWidget.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/Releases.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/System.ts
> RUN-1940: info widget should appear before loading finishes

- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/execution-log/LogNodeChunk.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/execution-log/logViewer.vue
Bug introduced with vue 3 migration, where logs weren't showing at runtime
Removed mobx observer and use vue computed properties instead. Also, fix small issue with saving configs (as settings has nested objects);
Will make a PR on pro to fix the error with 'addUiMessages'
> RUN-1962 Fix logViewer regression

- rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ConfigurationServiceSpec.groovy
Fix: execution mode state is not retained after config refresh
Don't rely on config value, which may have been reloaded from disk.  The execution mode should persist in memory instead.
> RUN-1975: fix: execution mode is not retained after config refresh

- grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
- rundeckapp/src/test/groovy/rundeck/services/WebhookServiceSpec.groovy
The authConfigJson property is lost when updating a webhook
It checks if the webhook uses authorization header and is a update method, if so the webhook keeps the authConfigJson prop
> RUN-1973 Fix webhook update to keep auth config

- core/src/main/java/com/dtolabs/rundeck/core/resources/LocalResourceModelSource.java
enhancement: 
There are some plugins like Local Node or Node Wizard that cannot be executed in a remote node. For this case, the best approach would be to disable the runner selector to avoid getting errors trying to run these plugins in a remote runner.
> RUN-1974: Disable resource model runner selector for only local plugins

- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/execution-log/logViewer.vue
With vue 3 migration, Logviewer isn't rendering the progress bar with full width.
added 'align-self: stretch' to force the flex div to occupy full width.
before:
after:
> RUN-2005: fix log viewer progress bar

- grails-rundeck-data-shared/src/main/groovy/rundeck/data/job/RdOption.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/ScheduledExecutionToJobConverter.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/data/job/converters/ScheduledExecutionToJobConverterSpec.groovy
Fixed conversion exception thrown when attempting to convert ScheduledExecution with an option that contained configuration data.
> The ScheduleExecution to JobData converter was broken when attempting to convert job options

- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/execution-log/logViewer.vue
Bug: when scrolling log output, the lines flicker and jump around.
Remove css transition that affects log line dom elements
version 4.17.0
> RUN-2015: Fix: flickering execution log view

- core/src/main/java/com/dtolabs/rundeck/core/data/SharedDataContextUtils.java
- core/src/main/java/com/dtolabs/rundeck/core/dispatcher/DataContextUtils.java
- core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/CustomFieldsAdapter.java
- core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/StepPluginAdapter.java
- core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapter.java
- core/src/test/groovy/com/dtolabs/rundeck/core/dispatcher/DataContextUtilsSpec.groovy
- core/src/test/groovy/com/dtolabs/rundeck/core/dispatcher/SharedDataContextUtilsSpec.groovy
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/CustomFieldsAdapterSpec.groovy
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/StepPluginAdapterSpec.groovy
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapterSpec.groovy
- rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/DynamicFormPluginProp.vue
- rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
Fix variable expansion in Workflow Step, Node Step and Notification plugins that use the DYNAMIC_FORM rendering option
Variable expansion within a DYNAMIC_FORM plugin property value cannot be done directly since the expanded variable can break the JSON formatting
> RUN-1732: fix variable expansion for DYNAMIC_FORM property values

- rundeck-authz/rundeck-authz-api/src/main/java/com/dtolabs/rundeck/core/authorization/RuleEvaluator.java
- rundeck-authz/rundeck-authz-api/src/test/groovy/com/dtolabs/rundeck/core/authorization/RuleEvaluatorSpec.groovy
- rundeckapp/grails-app/services/rundeck/services/UserService.groovy
- rundeckapp/src/test/groovy/rundeck/services/UserServiceSpec.groovy
Bug fix, avoid NPE during authorization checks if a UserGroupSourcePlugin result has a null entry.
Skip null values
> RUN-2024: avoid NPE if UserGroupSourcePlugin returns a null entry

- core/src/main/java/com/dtolabs/rundeck/plugins/logging/ExecutionFileStoragePlugin.java
- rundeckapp/grails-app/domain/rundeck/Execution.groovy
- rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
- rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
- rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
- rundeckapp/src/integration-test/groovy/rundeck/ExecutionIntegrationSpec.groovy
- rundeckapp/src/test/groovy/rundeck/ExecutionSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
Ticket: https://pagerduty.atlassian.net/browse/RSE-438
Not exporting logs if they are not present in the file system even if they are in the configured remote log storage
_**STR**_
1. Have an instance with a configured remote log storage
2. Create a Project with a job and run it a couple of times
3. remove some log files from the server file system (`<RDECK_HOME>/var/logs/rundeck/<PROJECT_NAME>/job/<JOB_UUID>/logs`)
4. Export the project and import it from another instance that has the same log storage configured.
_**Actual Behavior**_
* Error message shows up: some executions (the ones removed in step **3**) couldn't be loaded
_**Expected behavior**_
* No error should be displayed and execution logs should be loaded afterwards from remote log storage when accessed
* When exporting an …
> RSE-812: Fix: not importing logs from s3logstore

- rundeckapp/grails-app/domain/rundeck/Execution.groovy
- rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
- rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
- rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
- rundeckapp/src/test/groovy/rundeck/ExecutionTest.groovy
- rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
- remove AVERAGE_DURATION_EXCEEDED execution status added in https://github.com/rundeck/rundeck/pull/8156
- that AVERAGE_DURATION_EXCEEDED status produces an issue checking if the execution finishing using the API 
- add the fix to send the right subject in the email AVERAGE_DURATION_EXCEEDED notification 
> RUN-2031: remove AVERAGE_DURATION_EXCEEDED execution status

- rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ProjectController2Spec.groovy
When an individual project config is updated the config property is validating isolated and it is not considering the others current settings. It cause validation error for required properties
Now all the current settings is loaded before validation
> RUN-2019: project config plugin validation issue from API request

- rundeckapp/build.gradle
Beware: This version of H2 database breaks upgrading from previous versions: https://github.com/h2database/h2database/pull/3834#issuecomment-1630341920
> RUN-1828: Upgrade h2 database due to CVE-2022-45868

- core/src/main/java/com/dtolabs/rundeck/core/resources/ScriptPluginResourceModelSourceFactory.java
- core/src/test/groovy/com/dtolabs/rundeck/core/resources/ScriptPluginResourceModelSourceFactorySpec.groovy
BUG: 
Getting this error using Script Resource Model
`Reason: runtimeException class java.lang.String cannot be cast to class java.lang.Boolean (java.lang.String and java.lang.Boolean are in module java.base of loader 'bootstrap')`
Change how the parameter is cast to a boolean
This affects script plugins using a runner
> Change how the disableContentConversion parameter is cast to boolean

- scripts/circleci/helper-functions.sh
Other PR got issue with npm command related to permissions to install packages in the global node modules in circleci
Remove the npm command and execute redocli package using npx command for open api tests
> Run redocli command using npx command for open api tests

- rundeckapp/grails-spa/build.gradle
- scripts/circleci/build-functions.sh
Avoid parallel execution of runNpmBuild tasks to prevent npm build errors, while still allowing gradle parallel builds
> Avoid parallel execution of runNpmBuild tasks

- rundeckapp/grails-app/views/framework/_jobOptionsKO.gsp
- rundeckapp/grails-app/views/scheduledExecution/_optView.gsp
- rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/pages/jobs.scss
Job option description is affected by an overflow due to long texts without spaces. This behaviour occurs on Job page and Edit Job page.
Adding css style on these pages to avoid the overflow from its DOM element.
> RSE-886: Fix: Job option description too long

- rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
- rundeckapp/grails-app/migrations/changelog.groovy
- rundeckapp/grails-app/migrations/core/Storage.groovy
Ticket: https://pagerduty.atlassian.net/browse/RSE-744
In 3.3.x it was possible to add a resource yaml node resource with more than 4000 lines and since 3.4.0, when db changes were moved to be managed with liquibase, servers with mysql started showing the following error message in the nodes page after saving a node source like so:
And the service log showing a stacktrace with this caused-by message:
`Caused by: org.rundeck.storage.api.StorageException: Failed to save content at path projects/P/etc/project.properties: validation error: Data too long for column 'data' at row 1`
This happens because after migrating to liquibase, the type for data was set to blob while in previous versions was longblob. A fragment of the Storage table changeset:
```
column( name: "data", type: …
```
> RSE-892: Fix: Node wizard and resourceyaml sources cannot store +4K lines of node entries 

- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/notifications/NotificationsEditor.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/pluginPropEdit.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/utils/ExtendedDescription.vue
Bugfix for RUN-2059
By default, the markdown view component uses a light theme (defined by the prop mode) that overrides the CSS from the project. While the component has a built-in dark theme as well, the simplest solution is not to apply any of them and let the project's CSS style them, as the built-in dark theme is also very different from the project's style.
Before:
After:
> RUN-2059: prevent markdown-view from applying its default theme

- .gitmodules
Switches the packaging branch to the legacy release branch for after the merging of https://github.com/rundeck/packaging/pull/43
> Switch 4.17.x to legacy packaging branch

- rundeckapp/grails-app/migrations/changelog.groovy
- rundeckapp/grails-app/migrations/core/Storage.groovy
Fixes error introduced in: https://github.com/rundeck/rundeck/pull/8690
Rundeck-tester pipeline: https://app.circleci.com/pipelines/github/rundeckpro/rundeck-tester/7233/workflows/f71d0902-f77a-4265-a0a3-965f8ea18cbf
There was the following column definition in changeset  `core/Storage.groovy::3.4.0-2`:
`column(name: "data", type: 'blob')`
And after the merged PR, for `mariadb` and `mysql` dbms:
`column(name: "data", type: 'longblob')`
This resulted in a different checksum for the changeset that creates the table:
```
Liquibase.exception.ValidationFailedException: Validation Failed:
1 changesets check sum
core/Storage.groovy::3.4.0-23::rundeckuser (generated) was: 8:9e0a3ed272a5f3ba2cd4767e8715aca5 but is now: 8:1b5259deaa6f5ffbeca82ae99143c53e
```
Use a different property to hold the …
> Fix liquidbase checksum error

- .circleci/config.yml
Add generated packages as build artifacts so they can be downloaded from circleci.
> CircleCI: Store generated rpm and deb as build artifacts

- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/NodeCard.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/NodeDefaultFilterDropdown.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/NodeFilterInput.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/types/nodeTypes.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/nodes/main.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/en_US.js
Follow up of two tickets, #8558 and #8688 , adding the possibility to save filters as default.
How to test:
- on nodes page, type the filter to search nodes and save it as a new filter (by clicking on the arrow on the right side of the word 'nodes');
- upon saving, you'll see under 'filters' tab in the node summary, ie:
- then click on the small arrow on the right side of the name and mark it as 'default filter'
** Important: at this point there's no visual feedback that it worked, but you can see that it's the new default filter by either looking at localstorage OR by refreshing the page OR by clicking again the same menu on the right side of the filter where you've clicked before**
> RUN-2069: Update default node filter indicator

- grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
- rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/WebhookDataProvider.java
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormTokenDataProvider.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormWebhookDataProvider.groovy
- rundeckapp/src/test/groovy/rundeck/services/WebhookServiceSpec.groovy
Enhancement for threaded write to the database
When using the gorm approach as a secondary write there was an issue with the session. By defining the writes as transactional the session will be respected
> RCLOUD-1066: Transactional write to database for AuthToken and Webhook

- scripts/circleci/build-functions.sh
when running on circleci functional-test was always using snapshot instead of the image generated by the branch
> fix test image reference for functional test module

- functional-test/src/test/groovy/org/rundeck/tests/functional/api/jobs/JobImportSpec.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
Fix: if the Job import API is called with JSON job data, but incorrect API version, it returns an unexpected error
Return 400 error with "api.error.api-version.unsupported" error code
> RUN-2084: job import with JSON format with unsupported version should return expected error

- rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/ExecutionOutput.ts
Even showing whale logs message the browser is crashing when trying open output logs
Maxline parameter was not sent to server to prevent download the log output
> RSE-919: Fix whale logs crashing browser

- docker/ubuntu-base/Dockerfile
install a fixed version of Goland for Remco for CVE issue
In this way, we can control the Goland version instead depending on the version used by Remco
> RUN-2107: Use a fixed version of go for remco in Docker Image

- docker/ubuntu-base/Dockerfile
[Backport rundeck/rundeck#8498](https://github.com/rundeck/rundeck/pull/8498)
> [Backport rundeck/rundeck#8498] RUN-2107: Use a fixed version of go for remco in Docker Image

- core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapter.java
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapterSpec.groovy
- plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/ScriptNodeStepPlugin.groovy
Script inline plugin should use `@` to define data reference to be replace by data.
The script input should not be handled by NodeStepPluginAdapter, so it will skip this for script plugin types and let the plugins to handle it
> RUN-2114:  Fix replacing data references in script as it uses different tokens to define them

- rundeckapp/grails-app/services/rundeck/services/ScmService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
A exception is thrown in cluster when SCM try to get jobs plugin metadata (of no jobs).
No jobs to extract metadata from, so GORM complains with the wrong identifier exception.
Handling exception, and eventually the cluster will rearrange the metadata.
> RSE-755 Fix: SCM Disabled in Cluster while Job Plugins Metadata Retrieval

- .circleci/config.yml
Remove tomcat tests as is not longer supported since 5.0
> Remove tomcat tests from circleci workflow

- .circleci/config.yml
- scripts/circleci/build-functions.sh
- scripts/circleci/helper-functions.sh
- scripts/circleci/local-overrides.sh
- scripts/circleci/setup.sh
- scripts/circleci/testdeck-functions.sh
Changes docker images management to not use ecr anymore and rely only on the images already published to dockerhub.
>  CircleCI: Removes dependency on ECR for docker image management

- core/src/main/java/com/dtolabs/rundeck/core/logging/StorageFile.java
- core/src/test/groovy/com/dtolabs/rundeck/core/logging/StorageFileTest.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
- rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
- rundeckapp/grails-app/services/rundeck/services/logging/MultiFileStorageRequestImpl.groovy
- rundeckapp/src/test/groovy/rundeck/services/logging/StorageFileImplTest.groovy
Ticket: https://pagerduty.atlassian.net/browse/RSE-926
When the server is under high load, some log storage requests can fail and if they reach the maximum store attempts, the following error is thrown:
`Exception in thread "LogFileStorageTask695" java.lang.IllegalArgumentException: Active Connection is required`
And even if clicking on re-queue buttons through GUI, the maximum of attempts is reached and the storage requests that initially failed keeps failing over and over 
Customers receive lots of messages like this due to [an internal issue with the grails-data-mapping library](https://github.com/grails/grails-data-mapping/issues/1234), which handles the DomainObject.withNewSession calls (which are used for managing the requests). 
Besides this, when the user clicks on a `requeue` …
> RSE-926: Fix: Active Connection Required, StackOverflow false upload error (s3) on LogFileStorage Service

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/pages/jobs/JobCreatePage.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/tests/jobs/JobsSpec.groovy
- rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
There is a wrong “Default Value“ field appearing in the job option section of job definition UI, when user write something in the “Storage“ input value and the remove it:
The “Default Value“ input must not be rendered if the secure option is selected.
In file “rundeckpro/rundeck/rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp“, aprox line: 270 there is an event handler that yields the behavior of the bug:
```groovy
<wdgt:eventHandler for="defaultStoragePath_${storagePathKey}" state="empty" inline="true" oneway="true" frequency="2" >
<wdgt:action targetSelector=".opt_keystorage_disabled" visible="true"/> <-------- THIS LINE
<wdgt:action targetSelector=".opt_keystorage_enabled" visible="false"/>
</wdgt:eventHandler>
```
One hypothesis is that this line, was mistakenly leaved …
> RSE-941: Unexpected Default Value Field for Options

- core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapter.java
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/NodeStepPluginAdapterSpec.groovy
- plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/CommandNodeStepPlugin.groovy
The replacement of tokens is occurring before the plugin is executed considering each word of an option as a separate argument
The fix make the replacement only in the command plugin so it can consider each word of an option as the same argument
> RSE-937: Fix replace token for command plugin

- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/utils/AceEditorVue.vue
AceEditorVue was only adding a change listener in case the initial content wasn't the same as the backupContent (an empty string). This works fine for scenarios where the editor already starts populated, but for readme and message of the day, where there's no content until the first save, this was a problem as the lack of listeners would prevent the content from being properly updated and saved.
Moved the call for adding the event listener from modelValue watcher to the mounted hook.  
How to test:
* Create a project
* Navigate to Project Settings, either "Edit README" or "Edit Message of the Day" pages
* Attempt to save a message
> RUN-2134: Attach change event listener on mount instead of watch

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/pages/jobs/JobEditPage.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/pages/jobs/JobUploadPage.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/tests/jobs/JobsSpec.groovy
- rundeckapp/grails-app/assets/javascripts/optionEditKO.js
- rundeckapp/grails-app/i18n/messages.properties
- rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/grails-app/views/scheduledExecution/_optEdit.gsp
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
- When users has a secure option with default value, they cannot get the storage path to override the default value
- They cannot see in the GUI the default value, nor modify it
1. As of 3.4.x users cannot input default values for secure options because the field is hidden.
2. By execution parameter, the option's value has predominance over other values.
*: To stop and prevent security issues since the default value prints as a plain text string in a exported YAML or XML definition.
> RSE-954 Fix: Wrong Value Used as Secure Option

- rundeckapp/grails-app/services/rundeck/services/ConfigurationService.groovy
- rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
- rundeckapp/grails-app/services/rundeck/services/JobSchedulerService.groovy
- rundeckapp/src/test/groovy/rundeck/services/QuartzJobScheduleManagerServiceSpec.groovy
Ticket: https://pagerduty.atlassian.net/browse/RSE-952
**Problem:**
When the cluster member that is running an execution is shutdown, the execution is not being retried on any other cluster member (it is retried in the killed one, getting stuck in running state indefinitely) whereas in 4.8, the execution is retried on another cluster member.
**Expected Outcome:**
The running execution in the stopped cluster member gets retried on any other cluster member.
**Proposed Solution:**
Detect the application shutdown subscribing to `rdpro.shutdown` signal annotation to then force the `ConfigurationService` to toggle the execution mode in the current server so that it's not possible to choose it on any further reschedule operation during the shutdown process.
In order to make this work we must …
> RSE-952: Fix: Cluster not retrying execution on another node when owner shutdown

- core/src/main/java/com/dtolabs/rundeck/core/storage/StorageTreeFactory.java
Plugin group settings isn't loaded for storage plugins
Changed property resolver on storage tree factory to get framework property using the correct property prefix
> RUN-36: Fix loading storage plugins to load plugin group settings

- rundeck-data-model/src/main/java/org/rundeck/app/data/providers/v1/storage/StorageDataProvider.java
- rundeckapp/grails-app/services/rundeck/services/DbStorageService.groovy
- rundeckapp/grails-app/services/rundeck/services/data/StorageDataService.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormProjectDataProvider.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/storage/GormStorageDataProvider.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/providers/GormStorageDataProviderSpec.groovy
Enhancement. 
As we moved away from the gorm implementation, a way to fetch project and storage withouth the id is needed. 
There is also a need to create transactions when writing to the database
For project `name` is a unique value, for storage is a combination of `namespace`, `dir` and `name`. So every use of `id` was changed for the entire entity so we have flexiblity for fetching.
`withTransaction` blocks where added when writing to the database
> RCLOUD-1118: Project and Storage usage of unique value for fetch

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/LogViewerOutput.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/pages/JobCreatePage.groovy
- rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/execution-show/main.js
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/execution-log/LogNodeChunk.vue
Fix regression, where navigating to a job output with `#outputL[Number]` wouldn't highlight the correct line.
Added a check on LogNodeChunk to emit a line-select event on mounted, that will cause the line to be highlighted. 
Also added a test.
> RUN-2155: job output highlight

- grails-webhooks/grails-app/services/webhooks/WebhookService.groovy
- rundeckapp/src/test/groovy/rundeck/services/WebhookServiceSpec.groovy
bug:
don't create a new webhook when already exists in the project
> RUN-2156: don't create a new webhook when already exists in the project

- rundeckapp/grails-app/controllers/rundeck/controllers/ControllerBase.groovy
- rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
- rundeckapp/src/main/groovy/org/rundeck/web/WebUtil.groovy
support `rundeck.feature.legacyXml.defaultEnabled` setting
Modifies the legacyXml flag to enable defaultEnabled config
> RUN-2165: legacyXml feature flag should support defaultEnabled

- rundeckapp/grails-app/controllers/rundeck/controllers/WorkflowController.groovy
- rundeckapp/grails-app/domain/rundeck/PluginStep.groovy
- rundeckapp/src/test/groovy/rundeck/PluginStepTests.groovy
After refactoring built-in plugins, the jobs definitions was changed make them incompatible on previous versions
Keep the job definitions as before the refactoring so that the jobs definitions will looks like the same as before refactoring
> RUN-2179: Keep job definitions created in 5.x working in previous versions

- rundeckapp/grails-app/domain/rundeck/PluginStep.groovy
- rundeckapp/src/test/groovy/rundeck/PluginStepTests.groovy
Plugin config data was not being exported
Include config data when exporting old built-in plugins 
> Fix: Plugin config data was not being exported

- core/src/main/java/com/dtolabs/rundeck/core/config/Features.java
- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- rundeckapp/grails-app/controllers/rundeck/controllers/ProjectController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ProjectController2Spec.groovy
RSE-903: Rdcli is not working properly updating projects on severals rundeck versions
add flag to endpoint /{project}/config/{keypath} to enable/disable the plugin validation
add a system config flag api.project.config.enablePluginValidation to enable/disable the plugin validation in the endpoint /{project}/config/{keypath}
> RSE-903: Rdcli is not working properly updating projects on severals rundeck versions

- functional-test/src/test/groovy/org/rundeck/util/container/RdClient.groovy
- functional-test/src/test/groovy/org/rundeck/util/container/SeleniumBase.groovy
A connection pool is added to control the stream when turning clusters on and off.
Also, option `--disable-blink-features=AutomationControlled` is added
> RSE-934: Migrate API to New testdeck

- core/build.gradle
- core/src/main/java/com/dtolabs/rundeck/net/api/RundeckApi.java
- core/src/main/java/com/dtolabs/rundeck/net/api/RundeckClient.java
- rundeckapp/build.gradle
- rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
Related to 
https://pagerduty.atlassian.net/browse/RSE-401
Problem: A dependency on the rd-api-client external repository was introduced on this PR, https://github.com/rundeck/rundeck/pull/8504
Solution: Revert changes that removed the RundeckApi and create a new RundeckClient to allow to export projects to other instances via API without depending on the rd-api-client
> RSE-979 Fix: Remove dependency from rd-api-client

- .gitignore
- rundeckapp/grails-app/assets/javascripts/menu/joboptions.js
I messed up this one: [https://github.com/rundeck/rundeck/pull/8657](https://github.com/rundeck/rundeck/pull/8657)
So here we go again.
------
Is this a bugfix, or an enhancement? Please describe.
Bugfix: https://github.com/rundeck/rundeck/issues/8587
cleanup if(remote()) function in jobOptions.
It now only showes the values loaded remote to not mixup values from previous remote calls
Describe alternatives you've considered
fix doublication check, but this would not fix the behavior that there are values from an old call.
Additional context
I dont wanted to push the 3000 files from the **/bin folders.
> RUN-2126: Bug/fix behavior when remotevalues reload

- .circleci/config.yml
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/pages/BasePage.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/pages/jobs/JobCreatePage.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/tests/execution/CommandSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/tests/jobs/JobsSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/tests/project/NodesSpec.groovy
The flaky tests of:
`go to edit nodes`
`job workflow undo redo`
`job option simple redo`
`job option revert all`
`job option undo redo`
The old testdeck configuration for selenium is removed
> Fix flaky tests

- core/src/main/java/com/dtolabs/rundeck/core/utils/SSHAgentProcess.java
- plugins/jsch-plugin/src/main/java/org/rundeck/plugins/jsch/net/ExtSSHExec.java
- plugins/jsch-plugin/src/main/java/org/rundeck/plugins/jsch/net/ExtScp.java
- plugins/jsch-plugin/src/main/java/org/rundeck/plugins/jsch/net/SSHTaskBuilder.java
- plugins/jsch-plugin/src/test/java/org/rundeck/plugins/jsch/net/TestSSHTaskBuilder.java
Fixes #8925 
Restore class removed from rundeck-core library
> RUN-2211: Fix: restore class to java core library

- functional-test/src/test/groovy/org/rundeck/tests/functional/api/export_import/JobsImportSpec.groovy
After merging this PR: https://github.com/rundeck/rundeck/pull/8924
a test started to fail because it was using a method that was moved to `JobUtils`
> RSE-1024: Fixed test that was using a method that was moved to jobUtils

- functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/LogViewerOutputSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/pages/JobShowPage.groovy
- functional-test/src/test/resources/projects-import/long-job-output-project/rundeck-longOutput/jobs/job-f44481c4-159d-4176-869b-e4a9bd898fe5.xml
1. Replaced time-expensive selenium based project and job creation for a preset project
2. Added more log lines without sleep in-between to force the user's window re-location
3. Switched the test goal to assert if the last log line is displayed and rendered to the view.
> Selenium Testdeck's "auto scroll on log viewer page..." Flaky Test Fix

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/tests/project/NodesSpec.groovy
- Instead of going directly from login page to a project path, we validate the home and then navigate to project home before loading a specific path.
> Testdeck Fix: go edit nodes flaky tests

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- rundeckapp/grails-app/controllers/rundeck/interceptors/ZZ_TimerInterceptor.groovy
- rundeckapp/src/test/groovy/rundeck/interceptors/ZZ_TimerInterceptorSpec.groovy
Add ability to configure path prefixes for web requests that should be excluded from web request log
Set`rundeck.web.logging.ignorePrefixes` with a comma separated list of prefixes for web paths that should not be logged by the web request logger.
> RCLOUD-1182:  Configure web request logging

- scripts/convert_tl_junit.sh
Adds the vulnerability status to the twistlock test report
> Improve circleci message reporting for twistlock

- rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/project-nodes-config/ProjectNodePage.vue
The node wizard functionality was broken in https://github.com/rundeck/rundeck/pull/8898. An additional vue app was being created that was messing with the ability to determine if any sources were writeable, this fixes that
> Fix Node Wizard in Vue UI

- .circleci/config.yml
Backport of https://github.com/rundeck/rundeck/pull/8977. Changes introduced since made the solution required different.
> Update remote docker to use default version for release/4.17.x branch.

- functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginActionsSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginInputsSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginJobActionInputSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginJobActionsPerformSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginJobDiffSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginJobStatusSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginSetupSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginStatusSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/scm/ScmStatusBadgeSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/api/scm/GitScmApiClient.groovy
- functional-test/src/test/groovy/org/rundeck/util/api/scm/gitea/GiteaApiRemoteRepo.groovy
- functional-test/src/test/groovy/org/rundeck/util/api/scm/httpbody/IntegrationStatusResponse.groovy
- functional-test/src/test/groovy/org/rundeck/util/api/scm/httpbody/ScmActionInputFieldsResponse.groovy
- functional-test/src/test/groovy/org/rundeck/util/api/scm/httpbody/ScmJobStatusResponse.groovy
- functional-test/src/test/groovy/org/rundeck/util/api/scm/httpbody/ScmPluginInputFieldsResponse.groovy
- functional-test/src/test/groovy/org/rundeck/util/api/scm/httpbody/ScmPluginsListResponse.groovy
- functional-test/src/test/groovy/org/rundeck/util/api/scm/httpbody/ScmProjectConfigResponse.groovy
- functional-test/src/test/groovy/org/rundeck/util/common/scm/ScmActionId.groovy
- functional-test/src/test/groovy/org/rundeck/util/common/scm/ScmIntegration.groovy
- functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
- functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobShowPage.groovy
- functional-test/src/test/groovy/org/rundeck/util/gui/pages/scm/ConfigureScmPage.groovy
- functional-test/src/test/groovy/org/rundeck/util/gui/pages/scm/PerformScmActionPage.groovy
- functional-test/src/test/groovy/org/rundeck/util/gui/scm/ScmStatusBadge.groovy
- functional-test/src/test/resources/projects-import/scm/PScmStatusBadgeTest.rdproject/rundeck-PScmStatusBadgeTest/files/etc/project.properties
- functional-test/src/test/resources/projects-import/scm/PScmStatusBadgeTest.rdproject/rundeck-PScmStatusBadgeTest/files/etc/scm-export.properties
- functional-test/src/test/resources/projects-import/scm/PScmStatusBadgeTest.rdproject/rundeck-PScmStatusBadgeTest/files/etc/scm-import.properties
- functional-test/src/test/resources/projects-import/scm/PScmStatusBadgeTest.rdproject/rundeck-PScmStatusBadgeTest/jobs/job-08879a4b-3d0d-427c-9b69-226296ce30af.xml
- functional-test/src/test/resources/projects-import/scm/PScmStatusBadgeTest.rdproject/rundeck-PScmStatusBadgeTest/jobs/job-1ccd6bc5-63ae-4853-8f00-5fdaad031a24.xml
- functional-test/src/test/resources/projects-import/scm/PScmStatusBadgeTest.rdproject/rundeck-PScmStatusBadgeTest/jobs/job-740791d7-8734-4d8a-a77d-465aa2ccfe63.xml
Ticket: https://pagerduty.atlassian.net/browse/RSE-980
Depends On: https://github.com/rundeck/rundeck/pull/8877
The following tests were added to validate the scm status badge shown next to the job name on the job detail page `(/project/<project_name>/job/show/<job_uuid>`) when having scm import or export plugins enabled:
`"job scm import status badge for a newly created job"`: Having only scm import enabled, when clicking on a newly created job, the following status badge is shown:
`"job scm import status badge after import job changes"`: When exporting changes of an edited job, after enabling only the scm import plugin, the status badge must be the following
`"job scm export status badge when job created and after commit"`: the status badge must be the following when having only scm …
> RSE-980: Tests: Job Scm Status Badge Selenium Tests

- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/NodeCard.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/services/nodeServices.ts
On the vue conversion for nodes, the wrong endpoint was used to fetch the execution mode (`/system/executions/status`, which would fetch the system execution status instead of the project's). The issue is that the former endpoint requires permissions, that do not apply to the nodes page.
Swapped the endpoint to fetch the project metadata instead and leverage it to determine the execution status. 
Considered reusing getProjectMeta which lives in JobBrowse.ts, but decided against it as the type return and error handling are different.
Will add unit tests for this in a later moment, so that can tackle all components in the …
> RSE-1051: Replace api call for fetching execution modes for nodes

- rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/nodeUi.ts
Part of RSE-981 fix, to address the issue on the UI that was preventing the nodes from loading.
The issue happened when nodes have the attribute 'editUrl'. This attribute needs a string replacement - when the code was in knockout, it was considering that the value in that attribute was a method and calling it before returning it. With the code outside of knockout, update it to first check if it's a method, otherwise to just return its value.
> RSE-981: Fix for nodes not showing 

- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/activityList.vue
"undefined%" message appears in the progress bar instead of percentage. Fixed it to make it shows the percentage in number. 
> RUN-2032: Percentage in number showing in progress bar instead of undefined%

- functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecutionSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/common/jobs/JobUtils.groovy
- functional-test/src/test/groovy/org/rundeck/util/common/projects/ProjectUtils.groovy
- functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
- functional-test/src/test/groovy/org/rundeck/util/gui/pages/BasePage.groovy
- functional-test/src/test/resources/test-files/api-test-executions-running-scheduled.xml
- rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
- rundeckapp/grails-app/controllers/rundeck/interceptors/ApiProjectSelectInterceptor.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/interceptors/ApiProjectSelectInterceptorSpec.groovy
This PR addresses a bug related to the Schedule Forecast page.
**Describe the problem**
When selecting more than two projects (but not all) on the Schedule Forecast page and clicking the "search" button, the loading icon remains stuck, and a warning icon appears. This issue stems from the API call to `http://rundeck/api/v/{params.project}/executions/running` where `params.project` is not correctly processed for multiple selected projects.
The solution involves two main changes:
1. **Interceptor Exclusion**: Modify the `ApiProjectSelectInterceptor` to include an exclusion for the `apiExecutionsRunningv14()` method, allowing it to bypass pre-validation checks that incorrectly handle …
> RSE-873: Scheduled forecast GUI errors

- scripts/circleci/helper-functions.sh
Use build image instead of branch image to ensure it is for current build
> Wiz Scan Build Image Instead of Branch Image

- rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
Fix an error in which providing a wrong runner token would bleed NPEs in the service log instead of failing with a comprehensive error message.
> Fix npe error when wrong runner token is presented

- functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginJobDiffSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/common/jobs/JobUtils.groovy
Problem:
Sometimes the method  callGetJobStatus to get the SCM status of a job via API get the value before is completely updated in Resulting on a NPE 
Solution:
Create a new method that calls the callGetJobStatus inside a cicle assuring that the SCM status is not empty before checking results.
> Fix failing test on circleCi "test_check_diff_after_actions"

- rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/editor/SchedulesEditorSection.vue
Fix a minor bug in the job editor Schedules UI: timezone data used by the GUI is included in the json data sent to the server.
Remove the timeZones from the json
> RUN-2248: Fix: don't include UI timezone data in schedules json

- docker/ubuntu-base/Dockerfile
Update remco for CVE-2023-44487
> RUN-2239: Update golang and remco

- rundeckapp/grails-app/domain/rundeck/Execution.groovy
`4.17.0` added new columns at the execution table, however the domain object incorrectly is set as non-nullable (gorm's default), preventing the correct update of executions from previous versions that have a null value on those columns.
> RSE-985: Fix inconsistent Execution class constraints.

- core/build.gradle
- rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
- rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/logstorage/GormLogFileStorageRequestProvider.groovy
- rundeckapp/src/test/groovy/rundeck/services/LogFileStorageServiceSpec.groovy
Cleanup of unused methods
Cleanup of some unused methods in the LogFileStorageRequestProvider, along with the removal of the `cleanupDuplicates` method, as duplicates are not possible due to the constraint:
`addUniqueConstraint(columnNames: "execution_id", constraintName: "UC_LOG_FILE_STORAGE_REQUESTEXECUTION_ID_COL", tableName: "log_file_storage_request") `
> RCLOUD-1184: cleanup LogFileStorageRequestProvider

- functional-test/src/test/groovy/org/rundeck/util/gui/scm/ScmStatusBadge.groovy
- rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/tests/JobScmStatus.spec.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/browse/tree/JobScmStatus.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/job/head/scm/scm-status-badge.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/en_US.js
Fix: SCM status spinner is always shown for jobs in the next UI job list screen 
> RUN-2260: Fix: spinner always shown in nextUi jobs list

- docker/official/lib/entry.sh
- docker/official/lib/includes/100_defaults.sh
The docker official image is ignoring the value set at the `JVM_MAX_RAM_PERCENTAGE` environment variable when setting the value for the `-XX:MaxRAMPercentage` argument, but instead is incorrectly used the value of the deprecated `JVM_MAX_RAM_FRACTION` env variable.
This could potentially mislead administrators into think the rundeck container is using less memory than what is using in reality, as the final value for `MaxRAMPercentage` will be 75% regardless of the value of `JVM_MAX_RAM_PERCENTAGE`
> RUN-2270: Fix docker image ignoring value of JVM_MAX_RAM_PERCENTAGE

- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormUserDataProvider.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/providers/GormUserDataProviderSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScmServiceSpec.groovy
Bugfix for session not handled properly when context is Scm 
Use hibernate capabilities to attach a User query in the thread again
I didn't consider any other option
Usage of `findByLogin` does not require further writes so no problem with return value not being attached to the context
> Fix hibernate user session on scm context

- core/build.gradle
- grails-rundeck-data-shared/src/main/groovy/rundeck/data/execution/RdExecution.groovy
- grails-rundeck-data-shared/src/main/groovy/rundeck/data/execution/reference/ExecutionReferenceImpl.groovy
- grails-rundeck-data-shared/src/main/groovy/rundeck/data/job/reference/JobReferenceImpl.groovy
- grails-rundeck-data-shared/src/main/groovy/rundeck/data/job/reference/JobRevReferenceImpl.groovy
- grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/ExecutionDataUtil.groovy
- grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/JobDataUtil.groovy
- grails-rundeck-data-shared/src/main/groovy/rundeck/data/validation/shared/SharedExecutionConstraints.groovy
- grails-rundeck-data-shared/src/main/groovy/rundeck/events/RdExecutionCompleteEvent.groovy
- grails-rundeck-data-shared/src/test/groovy/rundeck/data/util/ExecutionDataUtilSpec.groovy
- rundeckapp/grails-app/domain/rundeck/Execution.groovy
- rundeckapp/grails-app/services/rundeck/services/ExecutionEventsService.groovy
- rundeckapp/grails-app/services/rundeck/services/FileUploadService.groovy
- rundeckapp/grails-app/services/rundeck/services/LogFileStorageService.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/ExecutionToRdExecutionConverter.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/data/job/converters/ExecutionToRdExecutionConverterSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ExecutionEventsServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/FileUploadServiceSpec.groovy
Add models for creating job and execution reference objects.
Support new execution completion event that doesn't require an Execution domain class.
> RCLOUD-1110: Add models for creating job and execution reference objects.

- rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
- rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
When a execution is running the 'date_completed' data needed to make metrics calculations, is null.
If 'date_completed' is null, we exclude the calculation of that particular execution from the metrics.
> RSE-776 Fix: Server Error while Metrics Request

- build.yaml
Fix merged to the plugin on this PR https://github.com/rundeck-plugins/openssh-node-execution/pull/35
However plugin needs to be updated on rundeck.
> OpenSSH CopyFile not working on Docker

- .circleci/config.yml
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ScheduledJobSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/webhook/WebhooksSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/container/SeleniumBase.groovy
This reduces machine resource class for the functional tests from large to medium and increases the implicit wait time for selenium
> RPL-6: reduce machine resources to its default (medium)

- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/grails-app/controllers/rundeck/interceptors/SetUserInterceptor.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormUserDataProvider.groovy
- rundeckapp/src/main/groovy/org/rundeck/security/RundeckJaasAuthenticationSuccessEventListener.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/providers/GormUserDataProviderSpec.groovy
- rundeckapp/src/test/groovy/org/rundeck/security/RundeckJaasAuthenticationSuccessEventListenerTest.groovy
- rundeckapp/src/test/groovy/rundeck/interceptors/SetUserInterceptorSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/UserServiceSpec.groovy
Problem:
When accessing Rundeck for the first time if the users had configured the rundeck.security.syncLdapUser=true property users were duplicated on the RDUSER table.
Solution:
On the SetUserInterceptor remove code that was causing a duplicated register, this part of the code wasn't necessary since the user is already being created on the RundeckJaasAuthenticationSuccessEventListener.groovy.
The use of the method getUserByLoginOrCreate was replaced by findOrCreateUser since both methods had the same logic
> RSE-774 Fix: Users logged from LDAP are duplicate

- rundeckapp/grails-spa/packages/ui-trellis/tsconfig.build.json
Unblocks PR #9048 - adding tests inside the library folder failed the pipeline as the build command wasn't recognizing jest due to the configs in tsconfig.build.json
Updated tsconfig.build.json to properly consider the node_modules/@types folder and added types property to globally include jest.
Pipeline passing with both this PR and PR 9048 changes: https://app.circleci.com/pipelines/github/rundeck/rundeck?branch=fix-jest
Refs: 
https://www.typescriptlang.org/tsconfig#typeRoots
https://www.typescriptlang.org/tsconfig#types
https://stackoverflow.com/a/39827904 
Considered to completely remove typeRoots.
> RUN-2309: Update tsconfig.build.json to properly recognize jest

- core/src/main/java/com/dtolabs/rundeck/core/logging/internal/DefaultLogEvent.java
- rundeckapp/src/test/groovy/com/dtolabs/rundeck/app/internal/logging/FSStreamingLogWriterSpec.groovy
Fix: log event metadata may be incorrect.  If e.g. "key value data" log filter is used, and "log output" is checked, the metadata used to log the output in JSON format can become copied to other log output lines.  This surfaces as an exception in the server log:
```
ERROR controllers.ExecutionController - Failed converting data type class java.lang.String(application/json) with plugins: [json-data-view, log-data-table-view]
```
Fix: metadata should not merge with previous lines
> RUN-2314: fix log event metadata may be incorrect

- rundeckapp/grails-app/i18n/messages.properties
- rundeckapp/grails-app/i18n/messages_zh_cn.properties
- rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/en_US.js
Changes "Secure" to "Plain Text with Password Input"
> RUN-2266: Change label and description of secureExposed option type

- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/home/HomeActionsMenu.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/home/HomeBrowserItem.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/home/tests/HomeActionsMenu.spec.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/home/tests/HomeBrowserItem.spec.ts
Bugfix: remove extra backslash added when concatenating URLs in the UI:Next: for menu/home
Just remove extra backslash
> RUN-2265: Ui:Next: remove duplicated backslash on nextUi for menu/home

- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormUserDataProvider.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/providers/GormUserDataProviderSpec.groovy
Related to:
https://pagerduty.atlassian.net/browse/RSE-864
Problem:
After solving the issue where users were duplicated when authenticating with LDAP, an error was thrown on user/profile page when authenticating with AD.
Solution:
Evaluate case sensitiveness on the validateUserExists method, this change avoid an error 500 that was generated on the user/profile page. It was only generated when authenticating from AD 
Extra info on :
https://pagerduty.atlassian.net/browse/RSE-961
> RSE-961 Login counting multiple times in user classes

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/LogViewerOutputSpec.groovy
- functional-test/src/test/resources/projects-import/long-job-output-project/rundeck-longOutput/jobs/job-1f0306cd-e123-44f3-8977-9e52edad8ce7.xml
- functional-test/src/test/resources/projects-import/long-job-output-project/rundeck-longOutput/jobs/job-1f0306cd-e123-44f3-8977-9e52edad8ce8.xml
- rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy
- rundeckapp/grails-app/views/execution/show.gsp
- rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/execution-show/main.js
Add the new configuration `rundeck.logviewer.maxLogSize` to define the max log output size. If the log output is bigger than the configured value, the whale log warning is shown. If no value is provided the default value is same as currently: 3145728 bytes
> RUN-2192: Make max log size configurable (whale log limit)

- plugins/script-node-step-plugin/build.gradle
- plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/CommandNodeStepPlugin.groovy
- plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/ScriptFileNodeStepExecutor.groovy
- plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/ScriptURLNodeStepExecutor.groovy
- plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/Util.groovy
- plugins/script-node-step-plugin/src/test/groovy/org/rundeck/plugin/scriptnodestep/UtilSpec.groovy
Avoid "ambiguous method overloading" error result.
TODO:
> RUN-2326: Fix handling step failures with null message (e.g. cancellation)

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/LogViewerOutputSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/gui/pages/execution/ExecutionShowPage.groovy
It fixes the test, getting the current execution id from the UI
> testdeck: fix execution maxLogSize test

- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/readme-motd/EditProjectFile.spec.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/readme-motd/EditProjectFile.vue
This is an enhancement. I have added unit tests for the EditProjectFile.vue component to ensure its functionality and behavior are as expected
I have written a series of unit tests using Jest and Vue Test Utils. These tests cover various scenarios including:
- Rendering the correct title based on the filename.
- Rendering file content when the getFileText method returns successfully.
- Handling failure when the getFileText method fails.
- Handling failure when a user edits the file and fails to save it.
- Handling success when a user edits the file and saves it.
- Displaying admin-specific messages and configuration links when the user is an admin.
- Displaying non-admin specific …
> RUN-2307 unit tests for edit project file

- functional-test/src/test/groovy/org/rundeck/util/gui/pages/webhooks/WebhooksPage.groovy
https://pagerduty.atlassian.net/browse/RPL-8
WebhooksPage updated
> RPL-8: QAF Migration - WebhooksPage updated

- core/build.gradle
- grails-rundeck-data-shared/src/main/groovy/rundeck/data/execution/RdExecution.groovy
- grails-rundeck-data-shared/src/main/groovy/rundeck/data/report/SaveReportRequestImpl.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
- rundeckapp/grails-app/domain/rundeck/ExecReport.groovy
- rundeckapp/grails-app/domain/rundeck/Execution.groovy
- rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionsCleanUp.groovy
- rundeckapp/grails-app/migrations/core/BaseReportSpi.groovy
- rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
- rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
- rundeckapp/grails-app/services/rundeck/services/ReportService.groovy
- rundeckapp/src/integration-test/groovy/ReportServiceTests.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormExecReportDataProvider.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormReferencedExecutionDataProvider.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/data/providers/GormExecReportDataProviderSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
Refactor of GormExecReportDataProvider
Update the GormExecReportDataProvider to remove usage of Execution and ReferencedExecution Domains
There are non-destructive migrations in this PR, but deploying them could take a long time depending on the size of the tables, as we recently experienced.
> RCLOUD-1221: Remove Execution usages of GormExecReportDataProvider

- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormUserDataProvider.groovy
Related to https://github.com/rundeckpro/rundeckpro/pull/3681
improve method findUserByLoginCaseSensitivity to avoid undesired logins
> RUN-2369 Login as local user doesn't evaluate case sensitive feature

- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormUserDataProvider.groovy
On bug bash found that rundeck.feature.caseInsensitiveUsername.enabled can be enabled/disabled on the rundeck-config.properties but not from the GUI on System configuration page.
> RUN-2453: Feature rundeck.feature.caseInsensitiveUsername.enabled doesn't show on System configuration page

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- docker/official/remco/templates/rundeck-config.properties
- rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
- rundeckapp/grails-app/services/rundeck/controllers/MenuService.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/MenuServiceSpec.groovy
Fixes the `rundeck.startup.detectFirstRun` config flag to work, enables setting it via remco.
> RUN-2450: fix config for detectFirstrun

- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/logstorage/GormLogFileStorageRequestProvider.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/data/providers/logstorage/GormLogFileStorageRequestProviderSpec.groovy
the log file storage request may already be deleted, causing NPE when deleting by execution UUID
> RUN-2354: fix: npe during cleanup incomplete executions

- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/grails-app/init/rundeckapp/init/servlet/BanHttpMethodCustomizer.groovy
- rundeckapp/grails-app/init/rundeckapp/init/servlet/JettyServletContainerCustomizer.groovy
- rundeckapp/grails-app/init/rundeckapp/init/servlet/RundeckHostHeaderCustomizer.groovy
When performing a request to Rundeck with no Host header, the internal IP is revealed on the response
This PR add a customizer that is enabled by the config `rundeck.feature.setServerUrlOnNoHostHeader.enabled` that will force the serverUrl and serverPort in the response if there is no Host header on request
> RSE-1052: fix IP disclosure when request doesnt have Host header

- docker/ubuntu-base/Dockerfile
This is a small enhancement to enable building `rundeck` Docker images for an `arm64` architecture.
This change enables building `arm64` images locally as described in [README.md](https://github.com/rundeck/rundeck/blob/main/README.md). It is a prerequisite for official CI builds of arm64 images (as requested in https://github.com/rundeck/rundeck/issues/6433).
Adds the appropriate build of https://github.com/krallin/tini into the `ubuntu-base` image based on the Docker build's target architecture.
This seems like a practical first step?
Before this enhancement, attempting to build and run the project from an Apple Silicon …
> [RUN-2508] Enables building arm64 Docker images locally

- grails-rundeck-data-shared/src/main/groovy/rundeck/data/job/RdWorkflowStep.groovy
- grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/ExecReportUtil.groovy
- grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/WorkflowStepUtil.groovy
- grails-rundeck-data-shared/src/test/groovy/rundeck/data/util/ExecReportUtilSpec.groovy
- grails-rundeck-data-shared/src/test/groovy/rundeck/data/util/WorkflowStepUtilSpec.groovy
- rundeckapp/grails-app/domain/rundeck/CommandExec.groovy
- rundeckapp/grails-app/domain/rundeck/Execution.groovy
- rundeckapp/grails-app/domain/rundeck/JobExec.groovy
- rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
- rundeckapp/grails-app/services/rundeck/services/NotificationService.groovy
- rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
- rundeckapp/grails-app/views/execution/show.gsp
- rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/WorkflowToRdWorkflowConverter.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormExecReportDataProvider.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/data/providers/GormExecReportDataProviderSpec.groovy
- rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
> RCLOUD-1221: ExecReport adjustments

- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/widgets/project-select/ProjectSelect.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/widgets/project-select/ProjectSelectButton.vue
- rundeckapp/src/test/groovy/rundeck/controllers/MenuControllerSpec.groovy
This PR is part of the changes necessary for the vue conversion of the schedule forecast page (RUN-2193, RUN-2194 and RUN-2195).
Update the project select dropdown to allow multiple selections. 
ProjectSelect accepts now a mode prop, whose value will determine its behavior. If "single", projectSelect will render links that upon click will take the user to the project page, if "multi", ProjectSelect will emit an array with the names of the selected projects.
Also, ProjectSelectButton can render a label in accordance to the number of projects selected.
Adapt vue-multiselect, which was asked to change in prol of reusing the projectSelect. …
> RUN-2193, RUN-2194, RUN-2195: :nextUI: convert forecast page

- .gitmodules
Update release/5.3.x branch to point at correct branch in packaging repo
> RUN-2308: Use release/5.3.x branch of packaging repo

- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/readme-motd/EditProjectFile.spec.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/readme-motd/EditProjectFile.vue
This is an enhancement of the testing suite for the `EditProjectFile.vue` component.
I've refactored the tests for `EditProjectFile.vue` to improve readability and maintainability. The changes include better organization of test cases, clearer descriptions, and removal of unnecessary global mocks.
An alternative would have been to leave the tests as they were, but this would have made the test suite harder to maintain and understand in the long run.
> RUN-2353-Refactor editProject test to improve readability and maintainability

- rundeckapp/grails-spa/packages/ui-trellis/package-lock.json
- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/readme-motd/EditProjectFile.spec.ts
Upon merging storybook's PR, outdated package-locks got merged which broke the pipeline. This PR updates package-lock for ui-trellis and also add a ts-ignore on a test file that has typescript errors (rundeck core does not fail upon tests having typescript errors, while rundeckpro does. Will make a ticket to further address this issue).
> Fix pipeline

- rundeckapp/build.gradle
During the upgrade to Grails 6.1.2 (PR https://github.com/rundeck/rundeck/pull/9068) the `org.apache.tomcat:tomcat-jdbc` runtime dependency was removed by a developer thinking it was unused.
It turns out that the `tomcat-jdbc` pool was detected and configured by Spring's auto-configuration. The removal of this dependency changed the primary DataSource used by the job scheduler from `tomcat-jdbc` to `HikariCP` (which has a different default configuration).
This PR restores the `tomcat-jdbc` pool and upgrades the minor version.
Restores the `tomcat-jdbc` pool as the primary `DataSource` used by the application.
We considered rolling forward with …
> RUN-2554: Restores Tomcat JDBC pool.

- rundeckapp/build.gradle
- rundeckapp/grails-spa/packages/ui-trellis/vue.config.app.js
- rundeckapp/grails-spa/packages/ui-trellis/vue.config.library.js
Bugfix - fixes assets' URLs in CSS files.
TLDR; webpack 5 changed how it bundles things and resolve URLs, preferring to use asset modules/asset management in prol of loaders, while vue-cli still leverages them, which makes it hard to adjust things.
Therefore the best solution was to follow the advice of one of the maintainers of leaving the publicPath as auto and change other things instead (github.com/webpack/webpack/discussions/17290)
Some other relevant links:
https://github.com/webpack/webpack/issues/15499
https://github.com/webpack-contrib/css-loader/issues/256
How to test:
run project with:
docker run -d -P -p 4441:4440 -e RUNDECK_SERVER_ADDRESS=0.0.0.0 -e …
> RUN-2540: Webpack fix for assets urls inside css files

- core/src/main/java/org/rundeck/app/components/project/ProjectComponent.java
- rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
- rundeckapp/grails-app/services/rundeck/services/ProjectService.groovy
- rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ProjectServiceSpec.groovy
Enhancement
- Add a mechanism to disable project component 
- Add a mechanism to call a method in project components after the project is created (using API or GUI)
- new methods for `projectComponent` interface to check if the component is enabled and after-project-creation mechanisms
- call after-project-creation method of `projectComponent` after the project is created (using API or the GUI)
> RUN-2159: new methods for projectComponent interface

- rundeckapp/grails-app/controllers/rundeck/controllers/MenuController.groovy
- rundeckapp/grails-app/services/rundeck/services/JobSchedulesService.groovy
- rundeckapp/grails-app/services/rundeck/services/RdJobService.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/OrchestratorUpdater.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/ScheduledExecutionFromRdJobUpdater.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/job/converters/WorkflowUpdater.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormJobDataProvider.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/data/providers/GormJobDataProviderSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/NotificationServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/RdJobServiceSpec.groovy
Enhancement. The business logic for saving a JobData was inside the provider that nees to be changed. 
An existing service is used to collect all the saving logic
> RCLOUD-1131: Refactor job service and provider

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/login/BasicLoginSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/gui/pages/login/LoginPage.groovy
- rundeckapp/grails-app/taglib/rundeck/UtilityTagLib.groovy
**Problem:** 
The “Docs” link on the front page when starting OSS gives a 404 error. It directs to:
“https://docs.rundeck.com/5.3.0/manual/02-getting-help.html?utm_source=rundeckapp&utm_medium=5.3.0-20240520 Linux java 11.0.22&utm_campaign=helplink&utm_content=menu%2Fwelcome”
instead of:
"https://docs.rundeck.com/docs/5.3.0/introduction/getting-help.html”
Solution:
Modify the link in the UtilityTagLib to redirect to the correct URL. Additionally, a functional test was added to validate that the URL is always correct.
> RUN-2544 Fix: Main docs link goes to 404

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobsSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ScheduledJobSpec.groovy
scheduled job: sometimes fails on PRO due to not waiting enough for the executions to run
Select all json list options by default: it was not waiting for the options to be shown
- It increases the waiting time for scheduled execution to run
- It waits for the final options to be shown
> Add stability for tests

- functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionSpec.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/UserController.groovy
Fix component errors return 500 on API job run action
Fix disabled job and project return 500 on API job run 
Fix failed user profile update returns 500 on API update
All of these API calls now return a 400 with a descriptive message.
> RCLOUD-1344: Fix API calls returning 500 where 400 is more appropriate

- packaging/test/docker/installcommon/redhatubi8.Dockerfile
- packaging/test/docker/installcommon/rockylinux8.Dockerfile
- packaging/test/docker/rpminstall/Dockerfile
- packaging/test/test-docker-install-rpm.sh
Resolves an issue with the packaging tests in the CI pipeline.
This PR switches the image used to test the Rundeck RPM distribution from [the now deprecated] CentOS to [Red Hat's Universal Base Images](https://developers.redhat.com/articles/ubi-faq).
> [RUN-2636] Red Hat image for RPM packaging test

- rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/en_US.js
bugfix: when updating webpack to version 5, had to remove the locale strings imports from uiv, as due to the way they were exported from the package, it wasn't possible to import them anymore. 
Manually added these strings to project's locale file.
To reproduce:
1. Project > Activity > Search… modal
2. Time dropdown choose Other…
3. check Start After or any other filter
4. Click the calendar icon to show the date/time picker
5. See the AM/PM button label text is uiv.timePicker.pm
After:
> RUN-2478: bring in uiv translations

- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/tests/dateTimePicker.spec.ts
In accordance to circle ci, the test `emits update:modelValue when time changes` is flaky because of dates
froze the dates to fix this and make all these tests sturdier + concatenated 2 tests that were asserting similar things.
To mock the global Date object.
> RUN-2672: Fix flaky unit test for `emits update:modelValue when time changes`

- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/src/main/groovy/rundeck/services/audit/AuditEventsService.groovy
- rundeckapp/src/test/groovy/rundeck/services/audit/AuditEventsServiceSpec.groovy
Add JMX metrics to track user logins both successful and failed and user logouts.
New metrics:
userLogin.success
userLogin.failure
userLogout.success
> RCLOUD-1371: Add JMX metrics for to track user login and logout

- core/src/main/java/com/dtolabs/rundeck/plugins/storage/StoragePlugin.java
Enables users of the StoragePlugins to verify if the storage plugin has been configured and initialized properly, thus can be used.
> RDC-2479 : Add isConfigured check to the StoragePlugin

- rundeckapp/grails-app/controllers/rundeck/interceptors/AuthorizationInterceptor.groovy
- rundeckapp/src/test/groovy/rundeck/interceptors/AuthorizationInterceptorSpec.groovy
Add JMX metrics to track api authorizations
New metrics:
apiAuthorization.success
apiAuthorization.failure
> RCLOUD-1389: add metric

- rundeckapp/grails-app/conf/spring/resources.groovy
- rundeckapp/grails-app/controllers/rundeck/interceptors/AA_TimerInterceptor.groovy
- rundeckapp/grails-app/controllers/rundeck/interceptors/ApiVersionInterceptor.groovy
- rundeckapp/grails-app/controllers/rundeck/interceptors/FormTokenInterceptor.groovy
- rundeckapp/grails-app/controllers/rundeck/interceptors/RequestIdInterceptor.groovy
- rundeckapp/src/main/groovy/org/rundeck/web/DefaultRequestIdProvider.groovy
- rundeckapp/src/main/groovy/org/rundeck/web/RequestIdProvider.groovy
This is the first in a series of small changes aimed to improve the ability to operate Rundeck. It adds a randomly generated "request id" to each HTTP request and sets this value in the logger's context.
This change adds a `requestId` value to the logger's MDC. The `requestId` used can be customized by implementing your own `RequestIdProvider` and replacing the `requestIdProvider` bean.
Not exactly an alternative but this PR stops short of updating the default log4j2 configuration for the next release. This will happen in a subsequent release after we have exercised this change for some time.
Here are a few sample log …
> [RCLOUD-1380] Initial request id support

- core/src/main/java/org/rundeck/app/web/RequestIdProvider.java
- rundeckapp/grails-app/controllers/rundeck/interceptors/AA_TimerInterceptor.groovy
- rundeckapp/grails-app/controllers/rundeck/interceptors/ApiVersionInterceptor.groovy
- rundeckapp/grails-app/controllers/rundeck/interceptors/RequestIdInterceptor.groovy
- rundeckapp/src/main/groovy/org/rundeck/web/DefaultRequestIdProvider.groovy
- rundeckapp/src/main/groovy/org/rundeck/web/RequestIdProvider.groovy
Resolves an issue where https://github.com/rundeck/rundeck/pull/9210 was not actually very extendable because the `RequestIdProvider` interface was not in an appropriate module.
> [RCLOUD-1380] Moves requestId interface to core module.

- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/NodeFilterInput.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/NodeRemoteEdit.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/NodeTable.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/resources/types/nodeTypes.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/NodeFilterLocalstore.ts
This PR fixes some typescript checks issue when including NodeTable and NodeFilterInput components in a enterprise componente vue
> RUN-2499: Fix typescript issues to use NodeTable and NodeFilterInput components in another enterprise component

- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Problem:
Jobs scheduled at Project level continue to run when disabled by a Not Owner cluster member
Solution:
Add a condition to validate if scheduled executions are scheduled at project level.
STR:
1. Steps to reproduce the behavior:
2. Create a simple job (no schedule at job level)
3. Add as Project Schedule to this job (example, run every minute).
4. Disable the job schedule from the Jobs tab (Actions > Disable Schedule)
5. Wait to check that the job does not run and it has the NEVER next to it (expected)
6. Enable back the job schedule from the Jobs tab (Actions > Enable Schedule)
7. Log in to the other cluster member (not owner)
8. Disable the job schedule from the Jobs tab (Actions > Disable Schedule
9. Wait to check that the job still runs even if it has the NEVER next to it (NOT …
> RUN-2603 Jobs scheduled at Project level continue to run when disabled by a Not Owner cluster member

- functional-test/src/test/groovy/org/rundeck/util/container/SeleniumBase.groovy
When doing the test cleanup, it was always triggering a new chrome windows, with this it will use the current chrome instance (if there is one) to take the screenshot if the test has failed. If there is no chrome instance running then there is no point in taking the screenshot since it would be either that it's not a selenium test or for some reason the selenium test couldn't create a new chrome instance, hence it doesn't make any sense to capture a screenshot of a blank page
> Prevents chrome windows to open unnecessarily

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/BasicJobsSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobCreatePage.groovy
- functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobShowPage.groovy
- rundeckapp/grails-app/assets/javascripts/jobedit.js
- rundeckapp/grails-app/views/scheduledExecution/_edit.gsp
- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/details/DetailsEditor.vue
With the vue conversion of the job creation/edit details tab, the mechanism to update the UI upon selecting a group was changed and it broke the old UI. 
Tweaked a bit the check for the new UI to ensure it will use the correct mechanism (new UI, emit an event, old UI, manipulate the DOM).
**How to test**
Without the nextUi enabled:
Edit or create a new job - on the details tab, click to select a group and select one. Input should update the data.
> RUN-537: Fix for group selection on old UI

- functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
- functional-test/src/test/groovy/org/rundeck/util/container/RdClient.groovy
- functional-test/src/test/groovy/org/rundeck/util/container/RdContainer.groovy
Improvement to the functional tests harness:
- Made Rundeck HTTP client timeouts in the RdContainer configurable
- Added handling for the unsuccessfully created job executions in the RdContainer that resulted in an infinite loop
Jira ticket: https://pagerduty.atlassian.net/browse/RUN-2703?atlOrigin=eyJpIjoiOGE5ZjhiYTM3MjllNGRlZDg1M2NjZGE4M2U1ZGViZmMiLCJwIjoiaiJ9
> RUN-2703 : improve functional test harness

- rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/nodeUi.spec.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/nodeUi.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/tests/nodeUi.spec.ts
This update serves as both a bugfix and an enhancement. This is a bugfix related to the incorrect handling of `ui.attributes` while the enhancement includes the addition of tests to ensure the component behaves as expected.
I have modified the `glyphiconBadges` function to correctly parse and validate the badge names provided in the `attributes["ui:badges"]` string.
Additionally, I have added comprehensive tests to verify the function's behavior:
- Parsing well-formed input strings.
- Parsing input strings that do not end with numbers
- Filtering out invalid badge names.
- Handling empty input strings.
- Returning an empty array when no valid badges are provided.
- Handling null or …
> fixed and added test for glyphiconBadges

- rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ReportsControllerSpec.groovy
Fix: executions created before version 4.17.0 are missing a uuid value.  The Activity list fails to display these executions.
If the uuid is not set in the report, look up the execution by the ID.
> RUN-2606: Look up execution by id if uuid not in report

- rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionsCleanUp.groovy
- rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
- rundeckapp/grails-app/services/rundeck/services/ReportService.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/DBExecReportSupport.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormExecReportDataProvider.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/data/providers/GormExecReportDataProviderSpec.groovy
- rundeckapp/src/test/groovy/rundeck/ExecutionServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ReportServiceSpec.groovy
Fix: executions without UUID cannot be deleted
Support deleting by DB ID.
> RUN-2606: fix report delete by execution ID

- functional-test/src/test/groovy/org/rundeck/util/gui/pages/scm/ConfigureScmPage.groovy
**Issue:** Whenever changing from enable/disable, if the "toggleButton" was not found it was just ignoring it and just letting the process to continue, this way if the button is not found the test would fail after leaving no clue on what really happen
**Fix:** Now it waits for the toggleButton to exist and then clicking it. This way if the button for some reason does not show, it will be easier to identify the failure
> Testdeck improvement scm

- .circleci/config.yml
- functional-test/build.gradle
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/JobTabsSpec.groovy
- scripts/circleci/build-functions.sh
This is an enhancement to increase the speed of the CI pipeline. This change splits the functional tests and executes them across multiple machines in parallel.
This solution splits test execution across a set of machines by:
* Using the `circleci` CLI to enumerate test source code files and split them across the set of running machines.
* Using Gradle to convert the paths of source code files into paths of compiled classes.
* Providing a custom [JUnit include function](https://docs.gradle.org/7.6.2/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:include(groovy.lang.Closure)) that matches against the set of compiled classes.
**Describe alternatives you've …
> RUN-2730: Increase CI speed by splitting functional tests

- .circleci/config.yml
This is an enhancement to increase the speed of the CI pipeline and reduce points of failure. It removes the installation of node and aws cli from functional tests workflow
Instead of using the "install-build-dependencies" it just calls the function to install the basic stuff to run the workflow (dependencies_build_setup)
> RUN-2730: Remove unrequired dependency installation for functional tests

- rundeckapp/grails-app/init/rundeckapp/BootStrap.groovy
- rundeckapp/grails-app/init/rundeckapp/cli/CommandLineSetup.groovy
When Rundeck is started in migration mode there's no need to emit the bootstrap event which might have side effects.
This PR prevents the bootstrap event when Rundeck is started with the `-m` command line flag.
> RCLOUD-1425: Prevent bootstrap event when starting Rundeck with -m

- functional-test/readme.md
- functional-test/src/test/groovy/org/rundeck/util/container/RdContainer.groovy
- functional-test/src/test/resources/docker/compose/oss/docker-compose-blocklist.yml
- functional-test/src/test/resources/docker/compose/oss/docker-compose.yml
- functional-test/src/test/resources/docker/ldap/docker-compose.yml
Add an environment parameter to allow specifying the target cpu architecture to use on functional tests.
- On an ARM machine (for example an M chip Macbook), build a rundeck image from scratch. Make sure it was build as an `arm64` image.
- Set the evironment variable `TEST_TARGET_PLATFORM=linux/arm64`
- Running the functional tests locally with the image built should work correctly.
> Allow setting a custom cpu architecture when running functional tests

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/JobTakeoverQueryBuilder.groovy
- grails-rundeck-data-shared/src/test/groovy/rundeck/data/util/JobTakeoverQueryBuilderSpec.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceIntegrationSpec.groovy
Add a raw sql version of the query that returns jobs that should be taken over by the takeover api. The criteria query is extremely inefficient when there are lots of scheduled jobs and executions in the db and can take a very long time to complete.
This query can be turned on by using the flag: `rundeck.feature.enhancedJobTakeoverQuery.enabled=true`
This feature should be considered experimental.
> RCLOUD-1427: Enhance query that returns job data for schedule takeover

- functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/ExecuteScriptSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/RunCommandSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/workflowSteps/FileUrlScriptStepSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/common/jobs/JobUtils.groovy
- functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
Improves execution status check handling to get the execution output log when a test check fails.
> Print output log if waiting for execution fails in functional tests

- functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/appadmin/KeyStorageSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/common/WaitingTime.groovy
- functional-test/src/test/groovy/org/rundeck/util/common/jobs/JobUtils.groovy
- functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
- functional-test/src/test/groovy/org/rundeck/util/gui/pages/jobs/JobReferenceStep.groovy
- functional-test/src/test/groovy/org/rundeck/util/gui/pages/scm/PerformScmActionPage.groovy
RUN-2771: Fix shortened waiting times causing ROI and K8S tests to fail.
- Switch all waiting times to java.time.Duration for a more flexible api.
- Changes `runJobAndWait()` to wait longer
> RUN-2771: Fix shortened waiting times causing ROI and K8S tests to fail.

- grails-rundeck-data-shared/src/main/groovy/rundeck/data/util/JobTakeoverQueryBuilder.groovy
- grails-rundeck-data-shared/src/test/groovy/rundeck/data/util/JobTakeoverQueryBuilderSpec.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
Swap out Spring's JdbcTemplate for Groovy Sql because it properly supports named parameters.
> RCLOUD-1427: Use JdbcTemplate instead of Groovy Sql

- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/InputSwitch/Docs.mdx
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/InputSwitch/InputSwitch.stories.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/InputSwitch/inputswitch.scss
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/Message/message.scss
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/TabView/tabview.scss
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/primeVue/Tag/Tag.stories.ts
Small CSS fixes for message and tabs components (RUN-2661 and RUN-2663); and style the switch component.
To see run locally `npm run storybook`
PS: these changes will be validated by designers afterwards.
List of fixes:
- message component colors were wrong for variants info and warning;
- tabs's grey board wasn't gray-300 color;
> RUN-2661, RUN-2663: CSS fixes and switch component started

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- rundeckapp/grails-app/conf/application.yml
This is a small enhancement that defaults to applying a 120s timeout for sending job notifications. 
If necessary, this timeout can be adjusted by setting `rundeck.notification.threadTimeOut` to a millisecond value.
Enables a timeout for processing and sending all notifications related to job execution to reduce the likelihood of "stuck" executions when a notification destination is not responding in a timely manner.
Note: for _reasons_, the default value must be set in two different locations for everything to work properly in both OSS and Pro.
> RUN-2705: Notification timeouts enabled by default.

- docker/official/remco/templates/jaas-loginmodule.conf
Some LDAP servers don't support pagination in the search queries so that pagination must be disabled to fix `error code 12 - Unavailable Critical Extension` in the LDAP search.
This PR addresses the issue described in #8273 by allowing the user to set the `RUNDECK_JAAS_LDAP_ROLEPAGINATION=false` in the docker based setup if needed.
> RUN-2741: Add LDAP rolePagination config option for docker

- docker/official/remco/templates/jaas-loginmodule.conf
Recreate https://github.com/rundeck/rundeck/pull/8822
* enable rolePagination config via docker 
> Some LDAP servers don't support pagination in the search queries so that rolePagination must be disabled to fix “error code 12 - Unavailable Critical Extension” in the LDAP search.
> RUN-2741: Add LDAP rolePagination config option

- rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy
- rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionJobIntegrationSpec.groovy
- rundeckapp/src/test/groovy/rundeck/ScheduledExecutionSpec.groovy
- rundeckapp/src/test/groovy/rundeck/ScheduledExecutionTest.groovy
- rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/LocalJobSchedulesManagerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/RdJobServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
Changes the quartz schedule key to prevent scenarios in which certain combination of job deletions and import can cause multiple triggering of the same schedule.
Changes the quartz schedule key from using the DB id, project name and group, to the job UUID.
** Bonus Fix **
Also fixes a minor bug in which attempting to delete a job with two or more running executions results in a 500 error instead of the correct error message.
> RUN-2572: avoid multi executions for same schedule

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/appadmin/AccessControlSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/appadmin/KeyStorageSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/BasicJobsSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/gui/pages/BasePage.groovy
Jira ticket: https://pagerduty.atlassian.net/browse/RUN-2822
Context: Modifications were made to the waitForModal method in the RunnerResourceModelSpec class to enhance its flexibility and eliminate redundant usage.
Changes Made:
Refactoring of waitForModal Method:
The original waitForModal method took an expected parameter and waited for the modal to contain exactly that number of elements before proceeding. If the condition wasn’t met within a specified timeout, a TimeoutException was thrown.
The method was modified to include a second optional parameter, modalFieldCssSelector, which allows specifying a custom CSS selector to identify the modal. This enhances the method's flexibility by enabling it to work with different modals on the same page.
Removal of Redundant waitForModal Calls: …
> Fix logic on method waitForModal

- functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/container/RdClient.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/support/ExecutionQuery.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/providers/GormReferencedExecutionDataProvider.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionController2Spec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ReportServiceSpec.groovy
This PR fixes two issues related to referenced executions:
1- The activity tab at job page wasn't showing referenced executions as previous versions did.
2- The api endpoint api/jjob/{id}/executions to return the same result as activity tab at job page, including referenced executions
For the first issue listed above, it fixes the gorm data provider to collect execution uuid (instead of the job uuid).
For the second case, the criteria to build query to list executions should check also the referenced executions table. For the api calls, it is included by default but can be used the parameter includeJobRef as false if it is not desired to get the referenced executions
> RUN-2376 api/job/id/executions to return referenced executions

- functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecutionSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobExecutionSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/project/ExecutionModeSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/util/WaitUtilsSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/common/ResourceAcceptanceTimeoutException.groovy
- functional-test/src/test/groovy/org/rundeck/util/common/WaitBehaviour.groovy
- functional-test/src/test/groovy/org/rundeck/util/common/WaitUtils.groovy
- functional-test/src/test/groovy/org/rundeck/util/common/execution/ExecutionUtils.groovy
- functional-test/src/test/groovy/org/rundeck/util/common/jobs/JobUtils.groovy
- functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
Jira: https://pagerduty.atlassian.net/browse/RUN-2833
- Introduction of conditional sleep functionality
- deprecation of unconditional sleep functions
- conversion of selected functional tests from unconditional to conditional sleeps
See the test suite execution timing
> RUN-2833 : Introduce wait and poll functions and rewrite a few functional tests to use them

- core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtils.java
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtilsSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/workflowSteps/StepExecutionContextSpec.groovy
- functional-test/src/test/resources/projects-import/step-execution-context/rundeck-TestStepExecContext/jobs/job-1266c6ed-5cb7-4736-9e64-7f902f1090fa.xml
- functional-test/src/test/resources/projects-import/step-execution-context/rundeck-TestStepExecContext/jobs/job-aeb9ce8c-c78b-4414-9948-26bfd134303c.xml
Fix: script steps that fail do not correctly export the "exec.exitCode" context variable
Fix the error where the script cleanup step exitCode was overriding the script's exit code.
> RUN-2689: fix: exitCode from script steps is not correct in context variable data

- rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/NavBar.ts
Bug introduced by RUN-2242 changes, where items in the submenus won't be displayed if they don't have enabled property. 
Fix adds enabled property to navbar items in case they don't have one.
> RUN-2857: navbar fix for "more" items

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/execution/CommandOnMultipleNodesSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/gui/pages/project/ProjectEditPage.groovy
https://app.circleci.com/pipelines/github/rundeck/rundeck?branch=RUN-2854-commandPage
Whenever virtual scroll is used, even though the element might be visible for the user, the dom might not be reflecting the latest state.
Note: the 3 failed builds are unrelated flakes.
Force the navigation to the line, to ensure that all elements are present.
> RUN-2854: rundeck: T Selenium > execution succeeds on all nodes matching the ANY filter

- functional-test/src/test/groovy/org/rundeck/util/gui/pages/project/ProjectEditPage.groovy
https://app.circleci.com/pipelines/github/rundeck/rundeck?branch=RUN-2847-ace
Sometimes the test fails as the setting that needs to be disabled isn't set in the project config.
Add a try-catch, so that if setting isn't available, it will be added anyway at the end of the config.
> RUN-2847: Flaky - rundeck: T Selenium > disable schedules at project level

- plugins/object-store-plugin/build.gradle
- plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/ObjectStorePlugin.groovy
- plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/directorysource/ObjectStoreDirectAccessDirectorySource.groovy
- plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/directorysource/ObjectStoreMemoryDirectorySource.groovy
- plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/stream/CloseAfterCopyStream.groovy
- plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/stream/LazyAccessObjectStoreInputStream.groovy
- plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreTree.groovy
- plugins/object-store-plugin/src/main/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreUtils.groovy
- plugins/object-store-plugin/src/test/groovy/org/rundeck/plugin/objectstore/directorysource/ObjectStoreDirectAccessDirectorySourceTest.groovy
- plugins/object-store-plugin/src/test/groovy/org/rundeck/plugin/objectstore/directorysource/ObjectStoreMemoryDirectorySourceTest.groovy
- plugins/object-store-plugin/src/test/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreTreeWithDirectAccessDirSourceTest.groovy
- plugins/object-store-plugin/src/test/groovy/org/rundeck/plugin/objectstore/tree/ObjectStoreTreeWithMemoryDirSourceTest.groovy
- plugins/object-store-plugin/src/test/groovy/org/rundeck/plugin/objectstore/tree/TimeoutTest.groovy
- plugins/object-store-plugin/src/test/groovy/testhelpers/MinioContainer.groovy
- plugins/object-store-plugin/src/test/groovy/testhelpers/MinioTestUtils.groovy
- Update of the no-longer supported `io.minio:minio:7` dependency with the latest `io.minio:minio:8`.
- v7 is dependent on [okhttp:3.14.9](https://github.com/minio/minio-java/blob/7.1.4/build.gradle#L56) that is affected by [CVE-2021-0341](https://nvd.nist.gov/vuln/detail/CVE-2021-0341) as described [here](https://github.com/square/okhttp/issues/6724).
- Refactor code to work with the interface changes introduced in v8.
**Dependency Scan Results**
**Validation with S3**
***Sample Config***
`./rundeck_config/oss/rundeck-config.properties`
```
rundeck.storage.provider.1.type=object
rundeck.storage.provider.1.path=keys/objs
rundeck.storage.provider.1.config.bucket=p-run-2864-test
rundeck.storage.provider.1.config.objectStoreUrl=https\://s3.amazonaws.com …
```
> RUN-2864 : Update `object-store-plugin` dependencies to prevent CVE-2021-0341

- rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/i18n.ts
With the vue conversion, the js files for languages other than en_US fell behind and didn't have all the keys added over time.
add a fallback setting to createI18n, more here: https://vue-i18n.intlify.dev/guide/essentials/fallback.html
> RUN-2885: add fallback behaviour for i18n in Vue

- rundeckapp/grails-app/controllers/rundeck/interceptors/AuditInterceptor.groovy
- rundeckapp/grails-app/controllers/rundeck/interceptors/ProjectSelectInterceptor.groovy
- rundeckapp/grails-app/i18n/messages.properties
- rundeckapp/src/test/groovy/rundeck/interceptors/AuditInterceptorSpec.groovy
- rundeckapp/src/test/groovy/rundeck/interceptors/ProjectSelectInterceptorSpec.groovy
When Rundeck for some reason loses the connection with database, it causes to print a lot of errors to the log file, making its size to increase very fast
If a request to an error page reaches the interceptor, it should skip the interceptor validations and let the request to proceed. Then it avoid the request to be stuck in a loop that is the cause of the issue
Firstly, I tried to wrap part of the before method in a try-catch block to return an error status and error message to interrupt the request
> RUN-2419 skip interceptor if request to an error page

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/project/ExecutionModeSpec.groovy
The test should should test for all executions to finish, otherwise it's possible it will proceed when the running execution has not yet completed, because it only verifies if *any* execution has finished.
this change aligns with the following test case "disable schedules at project level UI" which uses "verifyForAll"
Fix a flaky test
> RUN-2898: fix: flaky test, timing might cause failure

- rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/i18n.ts
RUN-2885's PR enabled the i18n to fallback to English in case the key wasn't available, but didn't notice that English wasn't permanently enabled when another language was selected, which prevented the fallback from working.
Adds English to the dictionary of available languages.
Another alternative would be to merge English first in the dictionary of the selected locale and then the remainder of the chosen locale (that then would overwrite the keys that were translated), but this isn't recommended as there's a better approach with the fallback.
Before:
After:
> RUN-2885: add english to the dictionary of available languages so that fallback behaviour works correctly (follow-up)

- rundeckapp/src/main/groovy/org/rundeck/app/components/RundeckJobDefinitionManager.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/components/RundeckJobDefinitionManagerSpec.groovy
Fix: if a job definition component reports an invalid configuration, it fails to invalidate the job definition
> RUN-2897: fix: invalid job components are not reported

- .circleci/config.yml
Looks like we're not the only ones experiencing flakiness with the install of node per https://github.com/CircleCI-Public/node-orb/pull/229 . This PR adds caching of the node install files via this change of the Orb. 
None. This is a simple enough change. Let's see if it works.
> RUN-2889: Cache Node Installs

- core/src/main/java/com/dtolabs/rundeck/core/utils/ResourceAcceptanceTimeoutException.java
- core/src/main/java/com/dtolabs/rundeck/core/utils/WaitUtils.java
- core/src/test/groovy/com/dtolabs/utils/WaitUtilsSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ScheduledJobSpec.groovy
- rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
- rundeckapp/src/integration-test/groovy/rundeck/quartzjobs/ExecutionJobIntegrationSpec.groovy
- rundeckapp/src/main/groovy/rundeck/services/MissingScheduledExecutionException.java
- rundeckapp/src/main/groovy/rundeck/services/ScheduledExecutionDeletedException.java
- rundeckapp/src/test/groovy/rundeck/quartzjobs/ExecutionJobSpec.groovy
This is a bugfix (mitigation) for the race condition between the quartz scheduler thread that gets ScheduledExecution ID from the memory store and the web server thread that puts the ID into the memory store AND creates the ScheduledExecution object in the DB. The issue occurs when the quartz thread processes the associated job and attempts to fetch the newly (almost) created ScheduledExecution object from the DB **BEFORE** the DB transaction is committed.
The problem is mitigated by retrying the DB fetch operation multiple times (with a timeout) giving the web server thread additional time to commit.
The proper alternative would be to wait for …
> RUN-2853: Fix race condition between the quartz scheduler and the web server thread that creates ScheduledExecution

- .circleci/config.yml
- rundeckapp/grails-app/views/common/_navBarProjectSettingsData.gsp
This should fix #9414. That was looking like a simple copy/paste error as the export/import rights are managed just above the delete action.
Switched from authExport to authDelete in the link enabled attribute
> RUN-2937: Fix the project export right managing both export and delete action

- .circleci/config.yml
- build.gradle
- scripts/circleci/build-functions.sh
- scripts/circleci/dependencies-functions.sh
- testbuild.groovy
This PR provides some improvements on the build and pipeline:
* Removes dependency on a local groovy sdk, using gradle directly to run groovy scripts.
* Improve encapsulation of some dependency installation functions.
* Remove unnecessary node and awscli installation from many jobs.
* Explicitely set all circleci job images to latest ubuntu 22.
> RUN-2929: Remove build dependency on local Groovy SDK

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/execution/CommandOnMultipleNodesSpec.groovy
Flaky test fix
There is a race condition between the output log lines produced by the system and the tests verifying the log line count. The wait and retry logic introduced gives the system more time to produce the expected number of log lines.
> RUN-2932: Introduce wait and retry to the flaky functional CommandOnMultipleNodesSpec tests

- rundeckapp/grails-app/views/common/_navBarProjectSettingsData.gsp
- rundeckapp/grails-app/views/execution/show.gsp
- rundeckapp/grails-app/views/framework/_legacyEditProjectFile.gsp
- rundeckapp/grails-app/views/framework/adhoc.gsp
- rundeckapp/grails-app/views/framework/editProjectFile.gsp
- rundeckapp/grails-app/views/menu/_projectConfigNavMenu.gsp
- rundeckapp/grails-app/views/menu/_projectExportForm.gsp
- rundeckapp/grails-app/views/menu/jobs.gsp
- rundeckapp/grails-app/views/menu/jobs.next.gsp
- rundeckapp/grails-app/views/menu/projectHome.gsp
- rundeckapp/grails-app/views/reports/_activityLinks.gsp
- rundeckapp/grails-app/views/reports/index.gsp
- rundeckapp/grails-app/views/scheduledExecution/show.gsp
- rundeckapp/grails-app/views/user/list.gsp
This should fix #9416. A resourceAllowedTest call was missing an ` any:true`  parameter so that either ` admin`  or ` app_admin` were enough to allow full access for a set of projects.
Added ` any: true` when both AuthConstants.ADMIN and AuthConstants.APP_ADMIN were required to a few cases similar to the one in _navBarProjectSettingsData.gsp.
I also found a similar case in _projectExportForm.gsp and aligned it with _projectImportForm.gsp
There's some discrepancies in presentation throughout the code for call to auth.resourceAllowedTest and auth:resourceAllowed, I restricted my changes only close to the cases at hand.
> RUN-2938: Fix an exclusive test on ADMIN and APP_ADMIN when it should be one or the other

- rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/project-dashboard/components/activitySummary.spec.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/app/pages/project-dashboard/components/activitySummary.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/en_US.js
- Fix: if userCount or failedCount was 0 it should not show the related text. The Vue "v-if" was used incorrectly.
- Fix i18n
- Add unit tests for activitySummary.vue
> RUN-2949: UI: Project Dashboard: Fix: activity summary should not be shown for 0 counts

- .circleci/config.yml
- scripts/circleci/packaging-functions.sh
Add retry loop for signing test which is flaky
> RUN-2787: Add retry for packaging signing test

- core/src/main/java/com/dtolabs/rundeck/core/common/PluginControlService.java
- core/src/main/java/com/dtolabs/rundeck/core/common/PluginControlServiceImpl.java
- rundeckapp/src/test/groovy/rundeck/services/FrameworkServiceSpec.groovy
This is a small cleanup PR that removes unused code from `PluginControlService` before new code is added in subsequent PRs.
Deleted unused methods.
N/A
N/A
> RUN-2930: Removes unused code from PluginControlService

- functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecutionSpec.groovy
Try to fix a flaky test increasing waiting time to check period to avoid hibernate exception when trying to access an object that could be removed
Checking log from circleci, we can see this error when get the executions from api request:
`[docker-java-stream-2080914965] INFO org.rundeck.util.container.RdContainer - STDOUT: org.hibernate.ObjectNotFoundException: No row with the given identifier exists: [rundeck.Workflow#22]
[docker-java-stream-2080914965] INFO org.rundeck.util.container.RdContainer - STDOUT:       at org.hibernate.boot.internal.StandardEntityNotFoundDelegate.handleEntityNotFound(StandardEntityNotFoundDeleg …
> RUN-2860 Increase waiting time for check period

- core/src/main/java/com/dtolabs/rundeck/core/common/PluginControlServiceImpl.java
- core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginRegistry.java
- core/src/test/groovy/com/dtolabs/rundeck/core/common/PluginControlServiceImplSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/integration/BlocklistSpec.groovy
- rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
- rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistry.groovy
- rundeckapp/src/test/groovy/rundeck/services/PluginServiceTests.groovy
This is an enhancement to [the plugin blocklist](https://docs.rundeck.com/docs/administration/security/blocklist.html) when blocking specific plugins by provider name. In the current state, when plugins for certain types of providers (e.g. WorkflowNodeStep) were blocked, they would still show up in various UIs and APIs. With this change, a blocked plugin will be more cleanly removed from these UIs and APIs.
**Context**
The `PluginBlocklist` / `RundeckPluginBlocklist` manages the list of blocked plugins and plugin containers (files). A few services are aware of this blocklist but the PluginRegistry is the primary one. Flows that obtain plugin information from the `PluginService` and / or the `PluginRegistry` properly filter out …
> RPL-82: Alternate Plugin Blocklist Enhancement

- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/activity/activityList.vue
Fix spacing for date in now running section to match history section.
> RUN-2974: UI: fix: spacing in date started section for now running executions

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/BulkJobActionsSpec.groovy
- rundeckapp/grails-app/assets/javascripts/menu/jobs.next.js
- rundeckapp/grails-app/views/menu/jobs.next.gsp
- rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
- rundeckapp/grails-spa/packages/ui-trellis/src/library/theme/scss/runstrap/_checkbox-radio.scss
Fixes the problem where the execution modal would be broken if the UI currently uses the nextUi flag enabled, as it would fail to load the UI for overriding nodes for the job.
The problem consisted of 2 separate matters:
- with the nextUi enabled, the UI loads a different gsp page than the default one, which was missing 2 imports for correctly loading the UI for overriding nodes and an embedJson called pageParams;
- besides that, the UI for the execution modal was allowing users to override the nodes as long as the initial filter wasn't a dynamic one (ie `name: ${options.name}`), but wasn't initiating the required scripts for this functionality if the job was set to not allow node changes (filter overrides). 
**Describe the …
> RUN-2810: Fix execution modal when nextUi mode is enabled

- rundeckapp/grails-app/controllers/rundeck/controllers/PluginController.groovy
- rundeckapp/grails-app/services/rundeck/services/PluginApiService.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/plugins/ApiPluginListProvider.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/PluginControllerSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/PluginApiServiceSpec.groovy
The enhancement to extend the responses of the `*/plugin/list API` to include `isHighlighted` and `highlightedOrder` properties.
**QA**
***Sample Response:***
```
GET http://localhost:4440/api/50/plugin/list
Accept:*/*
X-Rundeck-Auth-token:<...>
```
```
[
{
"iconUrl": "http://localhost:4440/plugin/icon/WorkflowStep/WinRMCheck",
"title": "WinRM Check Step",
"builtin": false,
"id": "59ed572534b2",
"providerMetadata": null,
"service": "WorkflowStep",
"highlightedOrder": 0,
"artifactName": "py-winrm-plugin",
"pluginVersion": "2.1.3",
"description": "Check the connection with a remote node using winrm-python",
"isHighlighted": false,
"name": "WinRMCheck",
"author": "© 2022, Pagerduty, Inc."
},
{
"iconUrl": "http://localhost:4440/plugin/icon/WorkflowNodeStep/script-inline",
"title": "Script", …
```
> RUN-2725 : Expose additional plugin properties in `*/plugin/list` API responses

- rundeckapp/grails-app/views/user/login.gsp
The code change will remove a template invocation in login.gsp, the login page. As far as we know it is only used for a rundeckpro functionality that is being removed.
There is a related commit for this same issue on rundeckpro.
See original changes that introduced this on the UI on RCLOUD-561 and RCLOUD-596.
> RCLOUD-1413 Removes unused template invocation in login page.

- docker/official/remco/templates/jaas-loginmodule.conf
Fixes #8255 
Enable "JettyRolePropertyFileLoginModule" in the docker template.
Enable support for the JettyRolePropertyFileLoginModule.
To test:
You can use the this docker-zoo branch: https://github.com/rundeck/docker-zoo/pull/43
1. specify the image: `rundeck/ci:RUN-3011`
2. Login as admin/admin or build/build
3. observe the user profile displays groups as defined in the realm.properties here: https://github.com/rundeck/docker-zoo/pull/43/files#diff-b0f66ddc03aa3bd7f06998d3e6bfd143422909a8a929b1344f0fe0466634aa3d
> RUN-3011: Fix: JettyRolePropertyFileLoginModule supported in docker

- functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecutionSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/export_import/JobsExportSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobImportSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/plugin/PluginSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/ConfigSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/ProjectSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/project/ProjectsSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/container/RdClient.groovy
- rundeckapp/grails-app/controllers/rundeck/controllers/FrameworkController.groovy
- rundeckapp/grails-app/controllers/rundeckapp/UrlMappings.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/ApiVersions.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/tag/TagForNodes.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/app/api/tag/TagsForNodesResponse.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/FrameworkControllerSpec.groovy
Adds a new GET project/{project}/nodes/tags API endpoint to get a summary of tags in a project
- Docs PR: https://github.com/rundeck/docs/pull/1599
**Testing**
***Project with nodes and tags***
```
GET http://localhost:4440/api/50/project/P1/nodes/tags
HTTP/1.1 200 OK
Content-Type: application/json;charset=utf-8
Transfer-Encoding: chunked
{
"tags": [
{
"nodeCount": 3,
"name": "stub"
},
{
"nodeCount": 3,
"name": "stub2"
}
]
}
```
***Project with no tags***
```
GET http://localhost:4440/api/50/project/Hackweek/nodes/tags
HTTP/1.1 200 OK
Content-Type: application/json;charset=utf-8
Transfer-Encoding: chunked
{
"tags": []
}
```
> RUN-2952 : Add GET project/{project}/nodes/tags

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/jobs/ExpandedJobGroupsSpec.groovy
Temporarily excludes a functional test from pro CI until we can properly diagnose the issue with it.
> RUN-3034: Temporarily excludes failing test from pro CI.

- plugins/git-plugin/src/main/groovy/org/rundeck/plugin/scm/git/GitImportPlugin.groovy
- plugins/git-plugin/src/test/groovy/org/rundeck/plugin/scm/git/GitImportPluginSpec.groovy
When importing changes using scm import plugin after enabling it via API, it returns success but no changes is imported. It happens because the tracked job ids list is empty when plugin gets the tracked items
If the tracked job ids list is empty, the plugin will try to get the job id from the job state map
> RUN-2916: Fix import action of scm import plugin when importing right after enabling the plugin

- rundeckapp/grails-app/views/scheduledExecution/_execOptionsForm.gsp
This is a bugfix for https://pagerduty.atlassian.net/browse/RUN-3049
When having "Editable Filter" false at job level, rundeck would ignore the selected nodes and it would run the steps against all of the nodes matching the node filter
Rollback change https://github.com/rundeck/rundeck/pull/9459
"Editable Filter" should not prevent users select/unselect the nodes matches by the node filter, it should only prevent the user from changing the node filter
> RUN-3049: fixes the nodes targeted with having editable filter false

- rundeckapp/grails-spa/packages/ui-trellis/src/app/components/job/workflow/WorkflowSteps.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/app/utilities/locales/en_US.js
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/ChoosePluginModal.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/tests/ChoosePluginModal.spec.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/Plugins.ts
Follow-up of RUN-2725, consuming the exposed parameters in the /plugins/list to properly categorize the step plugins as highlighted/non-highlighted 
Update ChoosePluginModal to be able to handle sorting of the plugins by isHighlighted parameter and then by highlightedOrder, and finally by name.
Also, update the divider's title to match the number of non-highlighted plugins that matches the search query. 
To see the changes, enable the alphaUi flag in the system config's UI (rundeck.feature.alphaUi.enabled)and the nextUi flag in the theme selector (bottom right corner).
After this PR:
> RUN-2989: Add promoted/highlighted steps in the vue converted pieces for workflow

- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceJobIntegrationSpec.groovy
**Jira Ticket**: https://pagerduty.atlassian.net/browse/RPL-27
Improve the ServiceNow plugin to prevent excessive delays when loading the list of groups from ServiceNow. Avoid unnecessary API calls to Snow when the information is not required. 
**Customer Impact:**
Significantly reduces the time it takes to load the list of groups from ServiceNow, enhancing productivity and eliminating unnecessary delays.
Improves user satisfaction by providing a smoother and faster integration between Rundeck and ServiceNow.
**Release Notes:**
**Kind of Change**
**Development Checklist**
Specific Considerations:
GUI Changes:
</details>
Start a Rundeck instance.
Configure the ServiceNow plugin at the project level.
Create a job.
Add a notification to create an incident in ServiceNow.
Previously, loading …
> RPL-27 Performance issues using service now plugin

- core/src/main/java/com/dtolabs/rundeck/core/config/RundeckConfigBase.java
- rundeckapp/grails-app/domain/rundeck/Execution.groovy
- rundeckapp/grails-app/jobs/rundeck/quartzjobs/ExecutionJob.groovy
- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
This PR contains a few required pieces for implementing an improved execution takeover for rundeckpro running in cluster mode. More detail to come soon.
* Adds a new takeover function that commits claimed executions before scheduling them to run on the server.
* The `rundeck.scheduledExecutionService.startup.rescheduleMode` configuration property actually works now.
> RCLOUD-1557: Reclaim and schedule in smaller transactions

- rundeck-authz/rundeck-authz-core/src/main/java/org/rundeck/core/auth/AuthResources.java
This is a bugfix for [RPL-81](https://pagerduty.atlassian.net/browse/RPL-81): Remove "Params" from resource-level Runner ACL
This PR removes `username` and `roles` params from resource-level runner ACL when creating rules at system level as neither of these are applicable to Runners.
Replace the list containing the params that don't apply with an empty list in the `AuthResource` map used by `AclManagerController`. 
Runners / Enterprise related change
[RPL-81]: https://pagerduty.atlassian.net/browse/RPL-81?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> remove params from resource-level runner acl at system level

- rundeckapp/grails-spa/README.md
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/widgets/project-select/ProjectSelectButton.vue
- A bug fix for the code injection vulnerability via the project display name label
- Minor Storybook docs update
A maliciously crafted project display name can be used to abuse the implicit Vue component attribute Inheritance and pass in executable code
The fix disables the Vue component attribute inheritance explicitly 
- Before the change: 
- After the change:
> RUN-2964: Code Injection Vulnerability via Project Name Label

- plugins/script-node-step-plugin/src/main/groovy/org/rundeck/plugin/scriptnodestep/Util.groovy
- plugins/script-node-step-plugin/src/test/groovy/org/rundeck/plugin/scriptnodestep/UtilSpec.groovy
RUN-3021
fixes #9483 
Since 5.0.0 conversion to internal plugins, "result.resultCode" value was not included in error handler context data for Script or Command steps.
* include failure data in thrown exception
> RUN-3021: fix: result data set not included in error handler context

- functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginSetupSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/scm/ScmPluginStatusSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/api/responses/common/RundeckResponse.groovy
- functional-test/src/test/groovy/org/rundeck/util/api/scm/GitScmApiClient.groovy
- functional-test/src/test/groovy/org/rundeck/util/api/scm/gitea/GiteaApiRemoteRepo.groovy
- functional-test/src/test/resources/docker/compose/oss/gitea/start.sh
Jira tickets:
- https://pagerduty.atlassian.net/browse/RUN-3093
- https://pagerduty.atlassian.net/browse/RUN-3103
- https://pagerduty.atlassian.net/browse/RUN-3104
Multiple SCM functional tests have been flaky for a long time and underwent various fix attempts. However, by looking at them holistically, I'm starting to be further convinced that the problem is not in the tests themselves. 
My theory is that (sometimes):
1. the `gitea` container is not fully up or configured when the tests are executed by circleci
2. the overly optimistic `GitScmApiClient` (that ignores unsuccessful API responses), masks point 1 above by "swallowing" errors during the tests setup.
This PR might not fix the flaky tests since it does not address point 1 above directly.
It mostly deals with point 2 and is …
> Improve stability of SCM tests

- docker/official/Dockerfile
- docker/official/README.md
- docker/official/lib/includes/110_sideload_plugins.sh
This is a small enhancement to allow for "sideloading" external plugins  when using Rundeck in complex containerized environments.
In certain containerized runtimes like Kubernetes, it can be desirable to mount any dynamic portions of each container's filesystem on a separate volume. In these scenarios, [the volume](https://kubernetes.io/docs/concepts/storage/ephemeral-volumes/) is typically empty at the time the container is created, making it difficult to get external plugins into the container.
This solution introduces a `plugins-to-sideload/` directory to Rundeck home. External plugins can be placed here [either by extending the Rundeck image or mounting an external directory]. …
> RCLOUD-1588: Ability to sideload plugins into Docker image.

- functional-test/src/test/groovy/org/rundeck/util/api/scm/gitea/GiteaApiRemoteRepo.groovy
A race conditions is suspected between the code that creates a repository for the admin user in test setup() and the `gitea` docker-compose script that creates the admin user: resources/docker/compose/oss/gitea/start.sh
It manifest in the repo create API call failing with:
`Failed to create repository: 401 {"message":"user does not exist [uid: 0, name: rundeckgitea]","url":"http://localhost:3000/api/swagger"}`
Ex: https://app.circleci.com/pipelines/github/rundeck/rundeck/17101/workflows/0ccc94ab-8a59-47f9-8e5a-a28788526b18/jobs/195705/tests
This PR introduces wait-and-retry logic for the repo creation.
> RUN-3104 : Add wait and retry to gitea repo creation call

- .circleci/config.yml
- README.md
- docker/build.gradle
- docker/ubuntu-base/Dockerfile
- scripts/circleci/build-functions.sh
This pull request introduces a new circleci workflow that executes functional tests against the Rundeck instance running on JRE 17. 
The tests are executed: 
- on the `main` branch nightly
- on any branch with the name matching the `release/5.` pattern on a build
Jira: https://pagerduty.atlassian.net/browse/RUN-2217?atlOrigin=eyJpIjoiYTJlZTJhMjg2MmIxNGUwMmFhODI4MDViNDY3YjMxNTMiLCJwIjoiaiJ9
Reviewer Note:
- Sample successful run with JRE 17: https://app.circleci.com/pipelines/github/rundeck/rundeck/17094/workflows/26028159-c625-4b1a-9195-636b1101ca4e
> RUN-2217: Update CI pipeline to include tests using java 17

- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/pluginConfig.vue
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/plugins/tests/ChoosePluginModal.spec.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/library/services/plugins.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/Plugins.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/RootStore.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/test/Plugins.spec.ts
- rundeckapp/grails-spa/packages/ui-trellis/src/library/stores/test/mocks/mockPluginData.ts
* Enables caching API response for plugin details in the GUI.
* Improves browser behavior on some pages
> RUN-3135: cache some API response in GUI

- core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/WorkflowExecutionListenerStepMetrics.java
- core/src/test/groovy/com/dtolabs/rundeck/core/execution/workflow/WorkflowExecutionListenerStepMetricsSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecutionOutputSpec.groovy
- functional-test/src/test/groovy/org/rundeck/tests/functional/api/job/JobErrorHandler.groovy
- functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
- functional-test/src/test/resources/projects-import/error-handler-project/error-handler-project/files/etc/project.properties
- functional-test/src/test/resources/projects-import/error-handler-project/error-handler-project/jobs/job-f9b34a63-ff95-41f4-9646-87d90b35fc3X.xml
- functional-test/src/test/resources/projects-import/error-handler-project/error-handler-project/jobs/job-f9b34a63-ff95-41f4-9646-87d90b35fc3d.xml
**Bug Fix**
When using an error handler with the "continue on failure" option, if the job didn't exist or was deleted, and if the referenced job was of type workflow step, a null pointer exception was thrown.
**Solution**
To resolve this issue, the code was modified to validate that the variable is not null before attempting to access any data from the result. This change prevents the null pointer exception from occurring and addresses the reported bug.
Additionally, two functional tests were added. These tests verify that error handlers function correctly for both scenarios: when the referenced job is a workflow step and when it is a node step.
To test it manually use the job provided on the functional tests, on both cases the referenced job doesn't exist and since it has an error …
> RUN-3130 Fix Error handler failing when is used on a Job Reference with a workflow step

- rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy
- rundeckapp/src/integration-test/groovy/rundeck/services/ScheduledExecutionServiceIntegrationSpec.groovy
This is a follow up to add additional resilience to the takeover mechanism implemented in https://github.com/rundeck/rundeck/pull/9522.
This change surrounds the "claim job" and "schedule job" portions of the new takeover method with retries.
In the current implementation of the `reclaimAndScheduleJobByJob` function, the individual operations must be retried individually because they are committed individually. For example, if the "claim job" portion of the takeover succeeds, retrying the entire takeover would miss this job in the "find jobs to takeover" stage.
An alternate approach to this problem would be to implement a takeover with an …
> RCLOUD-1560: Adds resilience to new takeover method.

- rundeckapp/grails-app/views/execution/show.gsp
Fix: 404 error in js console loading css file that does not exist linked in execution show page
RUN-3218
> RUN-3218: remove link to css file that does not exist linked in execution show page

- functional-test/src/test/groovy/org/rundeck/util/container/BaseContainer.groovy
- rundeckapp/grails-spa/packages/ui-trellis/src/library/components/storage/KeyStorageView.vue
This is an enhancement to better allow testing of key storage in selenium tests.
I've added a data-testid attribute to the key directory button for better discoverability in test suites and added the key deletion request to the selenium BaseContainer class.
I could have defined the key deletion request directly in a test but making it available for wider use seems wise, especially since there are similar functions in this class already.
N/A
> Add project key deletion request to function test's BaseContainer

- rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy
- rundeckapp/src/test/groovy/rundeck/controllers/ScheduledExecutionControllerSpec.groovy
* fix: option remote JSON filtered via json path should allow array result.
e.g., JSON returns:
```json
[
{"key":"value1"},
{"key":"value2"}
]
```
Using json path: `$[*].key` returns an array `["value1","value2"]`. This array would be accepted without the jsonpath query, but fails when it is the result of a jsonpath query.
Remove incorrect rejection of array results from json path query.
> RUN-2144: Fix: option remote json using jsonpath should allow array result

- rundeckapp/grails-app/services/rundeck/services/ApiService.groovy
- rundeckapp/grails-app/services/rundeck/services/UserService.groovy
- rundeckapp/src/test/groovy/rundeck/services/ApiServiceSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/UserServiceSpec.groovy
Enhancement - add method to apiService to allow deleting API tokens when deleting a user. 
New method + tests. The method doesn't check if the user id is valid as the controller won't reach the method in such scenarios.
Considered to expire the tokens and then use the existing method to remove expired tokens, but discarded as this could delete other tokens that weren't requested to be removed as a side-effect (due to being expired).
> RUN-3212: Add method to delete api tokens by user

- functional-test/src/test/groovy/org/rundeck/util/gui/common/navigation/NavProjectSettings.groovy
- rundeckapp/grails-spa/packages/ui-trellis/src/library/services/plugins.ts
After some refactoring made on frontend and vue code, the request to retrieve plugin details is not including project name on query parameters when it is performed on project context. It makes plugins that have any property with dynamic defaults not be processed and the property is empty when loaded
This PR fix the behavior so that project name is included to the plugin details request.
> RUN-3205 Add project name to params to get plugin details

- gradle/wrapper/gradle-wrapper.properties
This is an enhancement.
Updated the grade-wrapper.properties file to use Gradle 7.6.2, replacing the older 7.6.1 version
This update is related to CVE-2023-35947
> RUN-2678: Chore(gradle):Upgrade to 7.6.2

- core/src/main/java/com/dtolabs/rundeck/core/plugins/configuration/PluginAdapterImpl.java
- core/src/test/groovy/com/dtolabs/rundeck/core/plugins/configuration/PluginAdapterUtilitySpec.groovy
- rundeckapp/src/test/groovy/com/dtolabs/rundeck/server/plugins/RundeckPluginRegistrySpec.groovy
If an Option type PluginProperty is configured with a blank string value, it causes an exception.
> RUN-3422: fix: blank string value for "Options" property type causes Exception

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/activity/ActivitySpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/gui/pages/activity/ActivityPage.groovy
- rundeckapp/grails-app/views/reports/index.gsp
Fix a bug: using `?max=100` URL params on the activity page causes a 500 error
> RUN-3397: fix max param for activity page

- functional-test/src/test/groovy/org/rundeck/tests/functional/api/execution/ExecutionSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/common/execution/ExecutionUtils.groovy
Flaky test fix
Change utility code used by a test
Because a Closure proxied as a Supplier cannot throw exceptions, an UndeclaredThrowableException happens when a JSON parse failure occurs.
The test is meant to accept that failure and skip the result, but instead fails.
Use a Closure directly to correctly see the thrown exception
> RUN-3452: fix: flaky test when a JSON parse error occurs

- rundeckapp/grails-app/controllers/rundeck/interceptors/PostApiTokenInterceptor.groovy
- rundeckapp/src/test/groovy/rundeck/interceptors/PostApiTokenInterceptorSpec.groovy
This PR addresses [RUN-3335](https://jira.atlassian.com/browse/RUN-3335): **Restart API call should be disabled if user has AppAdmin**.
- Disables the "Restart" API call for users who have the AppAdmin role.
- Adds validation in the API endpoint to check user roles before allowing the restart action.
- Updates related tests to reflect the change in access permissions.
Previously, users with the AppAdmin role were able to perform restart actions via the API, which is not intended behavior. This change ensures that only authorized roles have access to the restart functionality, improving security and compliance with permission requirements.
- Unit tests updated and passing.
- Manual verification: confirmed that users with AppAdmin cannot trigger the restart API, while other authorized roles …
> RUN-3335 Restart api call should be disabled if user have AppAdmin

- functional-test/src/test/groovy/org/rundeck/tests/functional/selenium/scm/ScmStatusBadgeSpec.groovy
- functional-test/src/test/groovy/org/rundeck/util/gui/scm/ScmStatusBadge.groovy
The scm test is failing due to the following exception
`org.eclipse.jgit.api.errors.JGitInternalException: Exception caught during execution of merge command. org.eclipse.jgit.errors.LockFailedException: Cannot lock /home/rundeck/projects/PScmStatusBadgeTest/ScmImport/.git/index. Ensure that no other process has an open file handle on the lock file /home/rundeck/projects/PScmStatusBadgeTest/ScmImport/.git/index.lock, then you may delete the lock file and retry.`
With this fix whenever it fails to get the scm status, it will refresh the page and try again.
> RUN-3491: add single retry with page refresh to scm test

- setversion.sh
Change how setversion.sh works, so that we can automate how we handle snapshot updates.
Add the possibility of passing the flag `--bump-minor`, which removes the need of passing arguments (still supports the existing logic though, so both ways can be used).
> RUN-3508: Update setversion.sh

- grails-repository/grails-app/controllers/repository/ArtifactController.groovy
- grails-repository/src/test/groovy/repository/ArtifactControllerSpec.groovy
This PR is a bugfix. It addresses the missing authorization check when accessing plugin details in Rundeck.
An authorization check has been added to the endpoint that displays plugin details. Now, before showing plugin information, the system verifies that the user has the necessary permissions, improving access control and security.
> RUN-3353 add missing authorisation check for plugin details

- .circleci/config.yml
Some PRs fall behind main for a period of time.  If Snyk is scanning those branches it may be reporting on findings that are already fixed in Main.  This prevents the scan from running anywhere but the Main branch.
> Only run SNYK Scan on Main

- rundeckapp/build.gradle
CVE-2025-48976 is a Denial of Service (DoS) vulnerability in Apache Commons FileUpload versions 1.0 through 1.5. The vulnerability is caused by allocation of resources for multipart headers with insufficient limits, which allows attackers to cause a DoS attack.
Key Details:
Severity: DoS vulnerability (CWE-770: Allocation of Resources Without Limits or Throttling)
Affected versions: 1.0 to 1.5 (excluding 1.6)
Fixed in: Version 1.6 and 2.0.0-M4+
> RUN:3564: Update File Commons Version

- .circleci/config.yml
- build.gradle
- grails-persistlocale/build.gradle
- rundeckapp/build.gradle
Add constraint for commons-io to ensure everywhere is using the proper version.
Note: This also includes a fix to CirclCI to run scans locally only (don't send back to console) so we can try to verify if fixes address the intended CVE.
> RUN-2901: CVE-2024-47554

- build.gradle
- gradle.properties
- grails-persistlocale/build.gradle
- grails-rundeck-data-shared/build.gradle
- grails-webhooks/build.gradle
- rundeckapp/build.gradle
**Summary**
Identified and fixed the commons-fileupload vulnerability issue comprehensively across the Rundeck workspace. Here's what was done:
**Root Cause**
The vulnerability was coming from transitive dependencies through the Grails framework, specifically through org.grails:grails-web-fileupload:6.1.2 which was pulling in the vulnerable commons-fileupload:1.5.
**Changes Made**
build.gradle - Added constraint to force commons-fileupload:1.6.0 for all transitive dependencies build.gradle - Added the same constraint (this was specifically mentioned in your Snyk finding) build.gradle - Added constraint since it uses grails-web-boot build.gradle - Added constraint since it uses grails-web-boot build.gradle (root) - Added global force resolution strategy to ensure all subprojects use the …
> RUN-3564: Additional Fixes for CVE-2025-48976

- rundeckapp/grails-app/services/rundeck/services/scm/ScmLoaderService.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/data/job/metadata/JobScmMetadataComponent.groovy
- rundeckapp/src/test/groovy/rundeck/services/scm/ScmLoaderServiceSpec.groovy
bugfix: if SCM is disabled/broken for a project, it can cause repeated error logs stating "SCM disabled or project removed"
fix behavior where where Exception is thrown in order to cause the loader task to finish
[A change in 5.12.0](https://github.com/rundeck/rundeck/pull/9639) caused the behavior to change, where a RuntimeException was intentionally used to stop the scheduled task
> RUN-3684: Fix: repeated exceptions after SCM is disabled

- rundeckapp/grails-app/views/framework/_pluginConfigPropertiesInputs.gsp
This is an enhancement to translating plugin group names
In order to help with translations, I added the possibility of translating group names in plugins
```properties
property.[primary|secondary].[group].groupName
```
For translate primary groups, you need to put in your plugin:
```properties
property.primary.My\ Amazing\ Group.groupName=Any example here
```
For the secondary, just change the `primary` word
```properties
property.secondary.My\ Wonderful\ Group.groupName=Any example here
```
> RUN-3748: Add possibility to translate group name of plugins

- rundeckapp/grails-app/domain/rundeck/Option.groovy
- rundeckapp/src/main/groovy/org/rundeck/app/components/JobYAMLFormat.groovy
- rundeckapp/src/test/groovy/org/rundeck/app/components/JobYAMLFormatSpec.groovy
- rundeckapp/src/test/groovy/rundeck/services/ScheduledExecutionServiceSpec.groovy
This PR fixes an issue with YAML exported job delimiter handling where the valuesListDelimiter property wasn't being properly applied when creating Option objects from maps containing array values.
Fixed Option.fromMap to properly join array values using the specified delimiter
Modified YAML formatting to preserve delimiter values when trimming spaces
Added comprehensive test coverage for the delimiter functionality
> RUN-3106:  Yaml exported job delimiter issue

- rundeckapp/grails-app/migrations/changelog.groovy
- rundeckapp/grails-app/migrations/core/ExecutionIndexes.groovy
Customer is experiencing deadlock issues when using oracle database. It can be affected by cleaning execution job that affect the performance in the database causing the deadlocks
It adds a new index in the execution database for retry_execution_id that improves the performance when rundeck triggers the clean execution job and, as a side effect, this reduces deadlock cases in the database.
In a local test using postgresql, without the index, the cleaning process took 8 seconds to delete +/- 550  execution. After adding the index, it was reduced to 2 seconds.
> RUN-2921: Add index for retry_execution_id in the execution table

- core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkBase.java
- core/src/main/java/com/dtolabs/rundeck/core/common/FrameworkFactory.java
- core/src/main/java/com/dtolabs/rundeck/core/common/ProjectNodeSupport.java
- core/src/test/groovy/com/dtolabs/rundeck/core/common/FrameworkBaseSpec.groovy
- core/src/test/groovy/com/dtolabs/rundeck/core/common/ProjectNodeSupportSpec.groovy
- rundeckapp/grails-app/services/rundeck/services/FrameworkService.groovy
- rundeckapp/grails-app/services/rundeck/services/NodeService.groovy
- rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy
- rundeckapp/src/main/groovy/com/dtolabs/rundeck/server/projects/RundeckProjectConfig.java
- rundeckapp/src/test/groovy/rundeck/services/ProjectManagerServiceSpec.groovy
- restore reverted change to avoid loading full framework config for project configs
- this change inadvertently broke the behavior of framework globals, since they were implicitly always included in the project config
- fix framework globals by loading them explicitly
- get framework globals directly 
> RUN-3720: project config load refactor 
